call javaapi#namespace('com.sun.corba.se.impl.dynamicany')

call javaapi#class('DynAnyBasicImpl', 'DynAnyImpl', [
  \ javaapi#method(0,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'to_any(', ')', 'Any'),
  \ javaapi#method(0,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,'destroy(', ')', 'void'),
  \ javaapi#method(0,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,'component_count(', ')', 'int'),
  \ javaapi#method(0,'next(', ')', 'boolean'),
  \ javaapi#method(0,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,'rewind(', ')', 'void'),
  \ javaapi#method(0,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynAnyCollectionImpl', 'DynAnyConstructedImpl', [
  \ javaapi#method(0,'get_elements(', ')', 'Any[]'),
  \ javaapi#method(0,'set_elements(', 'Any[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'get_elements_as_dyn_any(', ')', 'DynAny[]'),
  \ javaapi#method(0,'set_elements_as_dyn_any(', 'DynAny[]) throws TypeMismatch, InvalidValue', 'void'),
  \ ])

call javaapi#class('DynAnyComplexImpl', 'DynAnyConstructedImpl', [
  \ javaapi#method(0,'current_member_name(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'current_member_kind(', ') throws TypeMismatch, InvalidValue', 'TCKind'),
  \ javaapi#method(0,'set_members(', 'NameValuePair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'set_members_as_dyn_any(', 'NameDynAnyPair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ ])

call javaapi#class('DynAnyConstructedImpl', 'DynAnyImpl', [
  \ javaapi#method(0,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,'component_count(', ')', 'int'),
  \ javaapi#method(0,'next(', ')', 'boolean'),
  \ javaapi#method(0,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,'rewind(', ')', 'void'),
  \ javaapi#method(0,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'to_any(', ')', 'Any'),
  \ javaapi#method(0,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,'destroy(', ')', 'void'),
  \ javaapi#method(0,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ ])

call javaapi#class('DynAnyFactoryImpl', 'LocalObject', [
  \ javaapi#method(0,'DynAnyFactoryImpl(', 'ORB)', 'public'),
  \ javaapi#method(0,'create_dyn_any(', 'Any) throws InconsistentTypeCode', 'DynAny'),
  \ javaapi#method(0,'create_dyn_any_from_type_code(', 'TypeCode) throws InconsistentTypeCode', 'DynAny'),
  \ javaapi#method(0,'_ids(', ')', 'String[]'),
  \ ])

call javaapi#class('DynAnyImpl', 'LocalObject', [
  \ javaapi#method(0,'type(', ')', 'TypeCode'),
  \ javaapi#method(0,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'to_any(', ')', 'Any'),
  \ javaapi#method(0,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,'destroy(', ')', 'void'),
  \ javaapi#method(0,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,'_ids(', ')', 'String[]'),
  \ ])

call javaapi#class('DynAnyUtil', '', [
  \ javaapi#method(0,'DynAnyUtil(', ')', 'public'),
  \ ])

call javaapi#class('DynArrayImpl', 'DynAnyCollectionImpl', [
  \ javaapi#method(0,'set_elements_as_dyn_any(', 'DynAny[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'get_elements_as_dyn_any(', ')', 'DynAny[]'),
  \ javaapi#method(0,'set_elements(', 'Any[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'get_elements(', ')', 'Any[]'),
  \ javaapi#method(0,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,'destroy(', ')', 'void'),
  \ javaapi#method(0,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,'to_any(', ')', 'Any'),
  \ javaapi#method(0,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'rewind(', ')', 'void'),
  \ javaapi#method(0,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,'next(', ')', 'boolean'),
  \ javaapi#method(0,'component_count(', ')', 'int'),
  \ javaapi#method(0,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynEnumImpl', 'DynAnyBasicImpl', [
  \ javaapi#method(0,'component_count(', ')', 'int'),
  \ javaapi#method(0,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,'get_as_string(', ')', 'String'),
  \ javaapi#method(0,'set_as_string(', 'String) throws InvalidValue', 'void'),
  \ javaapi#method(0,'get_as_ulong(', ')', 'int'),
  \ javaapi#method(0,'set_as_ulong(', 'int) throws InvalidValue', 'void'),
  \ ])

call javaapi#class('DynFixedImpl', 'DynAnyBasicImpl', [
  \ javaapi#method(0,'get_value(', ')', 'String'),
  \ javaapi#method(0,'set_value(', 'String) throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ ])

call javaapi#class('DynSequenceImpl', 'DynAnyCollectionImpl', [
  \ javaapi#method(0,'get_length(', ')', 'int'),
  \ javaapi#method(0,'set_length(', 'int) throws InvalidValue', 'void'),
  \ javaapi#method(0,'set_elements_as_dyn_any(', 'DynAny[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'get_elements_as_dyn_any(', ')', 'DynAny[]'),
  \ javaapi#method(0,'set_elements(', 'Any[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'get_elements(', ')', 'Any[]'),
  \ javaapi#method(0,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,'destroy(', ')', 'void'),
  \ javaapi#method(0,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,'to_any(', ')', 'Any'),
  \ javaapi#method(0,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'rewind(', ')', 'void'),
  \ javaapi#method(0,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,'next(', ')', 'boolean'),
  \ javaapi#method(0,'component_count(', ')', 'int'),
  \ javaapi#method(0,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynStructImpl', 'DynAnyComplexImpl', [
  \ javaapi#method(0,'get_members(', ')', 'NameValuePair[]'),
  \ javaapi#method(0,'get_members_as_dyn_any(', ')', 'NameDynAnyPair[]'),
  \ javaapi#method(0,'set_members_as_dyn_any(', 'NameDynAnyPair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'set_members(', 'NameValuePair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'current_member_kind(', ') throws TypeMismatch, InvalidValue', 'TCKind'),
  \ javaapi#method(0,'current_member_name(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,'destroy(', ')', 'void'),
  \ javaapi#method(0,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,'to_any(', ')', 'Any'),
  \ javaapi#method(0,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'rewind(', ')', 'void'),
  \ javaapi#method(0,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,'next(', ')', 'boolean'),
  \ javaapi#method(0,'component_count(', ')', 'int'),
  \ javaapi#method(0,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynUnionImpl', 'DynAnyConstructedImpl', [
  \ javaapi#method(0,'get_discriminator(', ')', 'DynAny'),
  \ javaapi#method(0,'set_discriminator(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'set_to_default_member(', ') throws TypeMismatch', 'void'),
  \ javaapi#method(0,'set_to_no_active_member(', ') throws TypeMismatch', 'void'),
  \ javaapi#method(0,'has_no_active_member(', ')', 'boolean'),
  \ javaapi#method(0,'discriminator_kind(', ')', 'TCKind'),
  \ javaapi#method(0,'member(', ') throws InvalidValue', 'DynAny'),
  \ javaapi#method(0,'member_name(', ') throws InvalidValue', 'String'),
  \ javaapi#method(0,'member_kind(', ') throws InvalidValue', 'TCKind'),
  \ javaapi#method(0,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,'destroy(', ')', 'void'),
  \ javaapi#method(0,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,'to_any(', ')', 'Any'),
  \ javaapi#method(0,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'rewind(', ')', 'void'),
  \ javaapi#method(0,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,'next(', ')', 'boolean'),
  \ javaapi#method(0,'component_count(', ')', 'int'),
  \ javaapi#method(0,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynValueBoxImpl', 'DynValueCommonImpl', [
  \ javaapi#method(0,'get_boxed_value(', ') throws InvalidValue', 'Any'),
  \ javaapi#method(0,'set_boxed_value(', 'Any) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'get_boxed_value_as_dyn_any(', ') throws InvalidValue', 'DynAny'),
  \ javaapi#method(0,'set_boxed_value_as_dyn_any(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'set_members_as_dyn_any(', 'NameDynAnyPair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'set_members(', 'NameValuePair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'get_members_as_dyn_any(', ') throws InvalidValue', 'NameDynAnyPair[]'),
  \ javaapi#method(0,'get_members(', ') throws InvalidValue', 'NameValuePair[]'),
  \ javaapi#method(0,'set_to_value(', ')', 'void'),
  \ javaapi#method(0,'set_to_null(', ')', 'void'),
  \ javaapi#method(0,'is_null(', ')', 'boolean'),
  \ javaapi#method(0,'current_member_kind(', ') throws TypeMismatch, InvalidValue', 'TCKind'),
  \ javaapi#method(0,'current_member_name(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,'destroy(', ')', 'void'),
  \ javaapi#method(0,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,'to_any(', ')', 'Any'),
  \ javaapi#method(0,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'rewind(', ')', 'void'),
  \ javaapi#method(0,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,'next(', ')', 'boolean'),
  \ javaapi#method(0,'component_count(', ')', 'int'),
  \ javaapi#method(0,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynValueCommonImpl', 'DynAnyComplexImpl', [
  \ javaapi#method(0,'is_null(', ')', 'boolean'),
  \ javaapi#method(0,'set_to_null(', ')', 'void'),
  \ javaapi#method(0,'set_to_value(', ')', 'void'),
  \ javaapi#method(0,'get_members(', ') throws InvalidValue', 'NameValuePair[]'),
  \ javaapi#method(0,'get_members_as_dyn_any(', ') throws InvalidValue', 'NameDynAnyPair[]'),
  \ javaapi#method(0,'set_members(', 'NameValuePair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'set_members_as_dyn_any(', 'NameDynAnyPair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ ])

call javaapi#class('DynValueImpl', 'DynValueCommonImpl', [
  \ javaapi#method(0,'set_members_as_dyn_any(', 'NameDynAnyPair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'set_members(', 'NameValuePair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'get_members_as_dyn_any(', ') throws InvalidValue', 'NameDynAnyPair[]'),
  \ javaapi#method(0,'get_members(', ') throws InvalidValue', 'NameValuePair[]'),
  \ javaapi#method(0,'set_to_value(', ')', 'void'),
  \ javaapi#method(0,'set_to_null(', ')', 'void'),
  \ javaapi#method(0,'is_null(', ')', 'boolean'),
  \ javaapi#method(0,'current_member_kind(', ') throws TypeMismatch, InvalidValue', 'TCKind'),
  \ javaapi#method(0,'current_member_name(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,'destroy(', ')', 'void'),
  \ javaapi#method(0,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,'to_any(', ')', 'Any'),
  \ javaapi#method(0,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,'rewind(', ')', 'void'),
  \ javaapi#method(0,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,'next(', ')', 'boolean'),
  \ javaapi#method(0,'component_count(', ')', 'int'),
  \ javaapi#method(0,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,'type(', ')', 'TypeCode'),
  \ ])

