call javaapi#namespace('com.sun.xml.internal.messaging.saaj.soap.name')

call javaapi#class('NameImpl', 'Name', [
  \ javaapi#field(1,1,'XML_NAMESPACE_PREFIX', 'String'),
  \ javaapi#field(1,1,'XML_SCHEMA_NAMESPACE_PREFIX', 'String'),
  \ javaapi#field(1,1,'SOAP_ENVELOPE_PREFIX', 'String'),
  \ javaapi#field(1,1,'XML_NAMESPACE', 'String'),
  \ javaapi#field(1,1,'SOAP11_NAMESPACE', 'String'),
  \ javaapi#field(1,1,'SOAP12_NAMESPACE', 'String'),
  \ javaapi#field(1,1,'XML_SCHEMA_NAMESPACE', 'String'),
  \ javaapi#field(0,0,'uri', 'String'),
  \ javaapi#field(0,0,'localName', 'String'),
  \ javaapi#field(0,0,'prefix', 'String'),
  \ javaapi#field(1,0,'log', 'Logger'),
  \ javaapi#field(1,1,'XMLNS_URI', 'String'),
  \ javaapi#method(0,0,'NameImpl(', 'String)', ''),
  \ javaapi#method(0,0,'NameImpl(', 'String, String, String)', ''),
  \ javaapi#method(1,1,'convertToName(', 'QName)', 'Name'),
  \ javaapi#method(1,1,'convertToQName(', 'Name)', 'QName'),
  \ javaapi#method(1,1,'createFromUnqualifiedName(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createFromTagName(', 'String)', 'Name'),
  \ javaapi#method(1,1,'createFromQualifiedName(', 'String, String)', 'Name'),
  \ javaapi#method(1,0,'createFromTagAndUri(', 'String, String)', 'Name'),
  \ javaapi#method(1,0,'getPrefixSeparatorIndex(', 'String)', 'int'),
  \ javaapi#method(1,1,'getPrefixFromQualifiedName(', 'String)', 'String'),
  \ javaapi#method(1,1,'getLocalNameFromQualifiedName(', 'String)', 'String'),
  \ javaapi#method(1,1,'getPrefixFromTagName(', 'String)', 'String'),
  \ javaapi#method(1,1,'getLocalNameFromTagName(', 'String)', 'String'),
  \ javaapi#method(1,1,'isQualified(', 'String)', 'boolean'),
  \ javaapi#method(1,1,'create(', 'String, String, String)', 'NameImpl'),
  \ javaapi#method(1,1,'createQName(', 'String, String)', 'String'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'getLocalName(', ')', 'String'),
  \ javaapi#method(0,1,'getPrefix(', ')', 'String'),
  \ javaapi#method(0,1,'getURI(', ')', 'String'),
  \ javaapi#method(0,1,'getQualifiedName(', ')', 'String'),
  \ javaapi#method(1,1,'createEnvelope1_1Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createEnvelope1_2Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createHeader1_1Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createHeader1_2Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createBody1_1Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createBody1_2Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createFault1_1Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createNotUnderstood1_2Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createUpgrade1_2Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createSupportedEnvelope1_2Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createFault1_2Name(', 'String, String)', 'NameImpl'),
  \ javaapi#method(1,1,'createCodeSubcode1_2Name(', 'String, String)', 'NameImpl'),
  \ javaapi#method(1,1,'createDetail1_1Name(', ')', 'NameImpl'),
  \ javaapi#method(1,1,'createDetail1_1Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createFaultElement1_1Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createFaultElement1_1Name(', 'String, String)', 'NameImpl'),
  \ javaapi#method(1,1,'createSOAP11Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createSOAP12Name(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'createSOAP12Name(', 'String, String)', 'NameImpl'),
  \ javaapi#method(1,1,'createXmlName(', 'String)', 'NameImpl'),
  \ javaapi#method(1,1,'copyElementName(', 'Element)', 'Name'),
  \ ])

