call javaapi#namespace('com.sun.org.apache.xerces.internal.impl.xs.opti')

call javaapi#class('AttrImpl', 'NodeImpl', [
  \ javaapi#method(0,1,'AttrImpl(', ')', ''),
  \ javaapi#method(0,1,'AttrImpl(', 'Element, String, String, String, String, String)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getSpecified(', ')', 'boolean'),
  \ javaapi#method(0,1,'getValue(', ')', 'String'),
  \ javaapi#method(0,1,'getNodeValue(', ')', 'String'),
  \ javaapi#method(0,1,'getOwnerElement(', ')', 'Element'),
  \ javaapi#method(0,1,'getOwnerDocument(', ')', 'Document'),
  \ javaapi#method(0,1,'setValue(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'isId(', ')', 'boolean'),
  \ javaapi#method(0,1,'getSchemaTypeInfo(', ')', 'TypeInfo'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('DefaultDocument', 'NodeImpl', [
  \ javaapi#method(0,1,'DefaultDocument(', ')', ''),
  \ javaapi#method(0,1,'getDoctype(', ')', 'DocumentType'),
  \ javaapi#method(0,1,'getImplementation(', ')', 'DOMImplementation'),
  \ javaapi#method(0,1,'getDocumentElement(', ')', 'Element'),
  \ javaapi#method(0,1,'getElementsByTagName(', 'String)', 'NodeList'),
  \ javaapi#method(0,1,'getElementsByTagNameNS(', 'String, String)', 'NodeList'),
  \ javaapi#method(0,1,'getElementById(', 'String)', 'Element'),
  \ javaapi#method(0,1,'importNode(', 'Node, boolean) throws DOMException', 'Node'),
  \ javaapi#method(0,1,'createElement(', 'String) throws DOMException', 'Element'),
  \ javaapi#method(0,1,'createDocumentFragment(', ')', 'DocumentFragment'),
  \ javaapi#method(0,1,'createTextNode(', 'String)', 'Text'),
  \ javaapi#method(0,1,'createComment(', 'String)', 'Comment'),
  \ javaapi#method(0,1,'createCDATASection(', 'String) throws DOMException', 'CDATASection'),
  \ javaapi#method(0,1,'createProcessingInstruction(', 'String, String) throws DOMException', 'ProcessingInstruction'),
  \ javaapi#method(0,1,'createAttribute(', 'String) throws DOMException', 'Attr'),
  \ javaapi#method(0,1,'createEntityReference(', 'String) throws DOMException', 'EntityReference'),
  \ javaapi#method(0,1,'createElementNS(', 'String, String) throws DOMException', 'Element'),
  \ javaapi#method(0,1,'createAttributeNS(', 'String, String) throws DOMException', 'Attr'),
  \ javaapi#method(0,1,'getInputEncoding(', ')', 'String'),
  \ javaapi#method(0,1,'getXmlEncoding(', ')', 'String'),
  \ javaapi#method(0,1,'getXmlStandalone(', ')', 'boolean'),
  \ javaapi#method(0,1,'setXmlStandalone(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getXmlVersion(', ')', 'String'),
  \ javaapi#method(0,1,'setXmlVersion(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'getStrictErrorChecking(', ')', 'boolean'),
  \ javaapi#method(0,1,'setStrictErrorChecking(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getDocumentURI(', ')', 'String'),
  \ javaapi#method(0,1,'setDocumentURI(', 'String)', 'void'),
  \ javaapi#method(0,1,'adoptNode(', 'Node) throws DOMException', 'Node'),
  \ javaapi#method(0,1,'normalizeDocument(', ')', 'void'),
  \ javaapi#method(0,1,'getDomConfig(', ')', 'DOMConfiguration'),
  \ javaapi#method(0,1,'renameNode(', 'Node, String, String) throws DOMException', 'Node'),
  \ ])

call javaapi#class('DefaultElement', 'NodeImpl', [
  \ javaapi#method(0,1,'DefaultElement(', ')', ''),
  \ javaapi#method(0,1,'DefaultElement(', 'String, String, String, String, short)', ''),
  \ javaapi#method(0,1,'getTagName(', ')', 'String'),
  \ javaapi#method(0,1,'getAttribute(', 'String)', 'String'),
  \ javaapi#method(0,1,'getAttributeNode(', 'String)', 'Attr'),
  \ javaapi#method(0,1,'getElementsByTagName(', 'String)', 'NodeList'),
  \ javaapi#method(0,1,'getAttributeNS(', 'String, String)', 'String'),
  \ javaapi#method(0,1,'getAttributeNodeNS(', 'String, String)', 'Attr'),
  \ javaapi#method(0,1,'getElementsByTagNameNS(', 'String, String)', 'NodeList'),
  \ javaapi#method(0,1,'hasAttribute(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'hasAttributeNS(', 'String, String)', 'boolean'),
  \ javaapi#method(0,1,'getSchemaTypeInfo(', ')', 'TypeInfo'),
  \ javaapi#method(0,1,'setAttribute(', 'String, String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'removeAttribute(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'removeAttributeNode(', 'Attr) throws DOMException', 'Attr'),
  \ javaapi#method(0,1,'setAttributeNode(', 'Attr) throws DOMException', 'Attr'),
  \ javaapi#method(0,1,'setAttributeNS(', 'String, String, String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'removeAttributeNS(', 'String, String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'setAttributeNodeNS(', 'Attr) throws DOMException', 'Attr'),
  \ javaapi#method(0,1,'setIdAttributeNode(', 'Attr, boolean) throws DOMException', 'void'),
  \ javaapi#method(0,1,'setIdAttribute(', 'String, boolean) throws DOMException', 'void'),
  \ javaapi#method(0,1,'setIdAttributeNS(', 'String, String, boolean) throws DOMException', 'void'),
  \ ])

call javaapi#class('DefaultNode', 'Node', [
  \ javaapi#method(0,1,'DefaultNode(', ')', ''),
  \ javaapi#method(0,1,'getNodeName(', ')', 'String'),
  \ javaapi#method(0,1,'getNodeValue(', ') throws DOMException', 'String'),
  \ javaapi#method(0,1,'getNodeType(', ')', 'short'),
  \ javaapi#method(0,1,'getParentNode(', ')', 'Node'),
  \ javaapi#method(0,1,'getChildNodes(', ')', 'NodeList'),
  \ javaapi#method(0,1,'getFirstChild(', ')', 'Node'),
  \ javaapi#method(0,1,'getLastChild(', ')', 'Node'),
  \ javaapi#method(0,1,'getPreviousSibling(', ')', 'Node'),
  \ javaapi#method(0,1,'getNextSibling(', ')', 'Node'),
  \ javaapi#method(0,1,'getAttributes(', ')', 'NamedNodeMap'),
  \ javaapi#method(0,1,'getOwnerDocument(', ')', 'Document'),
  \ javaapi#method(0,1,'hasChildNodes(', ')', 'boolean'),
  \ javaapi#method(0,1,'cloneNode(', 'boolean)', 'Node'),
  \ javaapi#method(0,1,'normalize(', ')', 'void'),
  \ javaapi#method(0,1,'isSupported(', 'String, String)', 'boolean'),
  \ javaapi#method(0,1,'getNamespaceURI(', ')', 'String'),
  \ javaapi#method(0,1,'getPrefix(', ')', 'String'),
  \ javaapi#method(0,1,'getLocalName(', ')', 'String'),
  \ javaapi#method(0,1,'getBaseURI(', ')', 'String'),
  \ javaapi#method(0,1,'hasAttributes(', ')', 'boolean'),
  \ javaapi#method(0,1,'setNodeValue(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'insertBefore(', 'Node, Node) throws DOMException', 'Node'),
  \ javaapi#method(0,1,'replaceChild(', 'Node, Node) throws DOMException', 'Node'),
  \ javaapi#method(0,1,'removeChild(', 'Node) throws DOMException', 'Node'),
  \ javaapi#method(0,1,'appendChild(', 'Node) throws DOMException', 'Node'),
  \ javaapi#method(0,1,'setPrefix(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'compareDocumentPosition(', 'Node)', 'short'),
  \ javaapi#method(0,1,'getTextContent(', ') throws DOMException', 'String'),
  \ javaapi#method(0,1,'setTextContent(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'isSameNode(', 'Node)', 'boolean'),
  \ javaapi#method(0,1,'lookupPrefix(', 'String)', 'String'),
  \ javaapi#method(0,1,'isDefaultNamespace(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'lookupNamespaceURI(', 'String)', 'String'),
  \ javaapi#method(0,1,'isEqualNode(', 'Node)', 'boolean'),
  \ javaapi#method(0,1,'getFeature(', 'String, String)', 'Object'),
  \ javaapi#method(0,1,'setUserData(', 'String, Object, UserDataHandler)', 'Object'),
  \ javaapi#method(0,1,'getUserData(', 'String)', 'Object'),
  \ ])

call javaapi#class('DefaultText', 'NodeImpl', [
  \ javaapi#method(0,1,'DefaultText(', ')', ''),
  \ javaapi#method(0,1,'getData(', ') throws DOMException', 'String'),
  \ javaapi#method(0,1,'setData(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'getLength(', ')', 'int'),
  \ javaapi#method(0,1,'substringData(', 'int, int) throws DOMException', 'String'),
  \ javaapi#method(0,1,'appendData(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'insertData(', 'int, String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'deleteData(', 'int, int) throws DOMException', 'void'),
  \ javaapi#method(0,1,'replaceData(', 'int, int, String) throws DOMException', 'void'),
  \ javaapi#method(0,1,'splitText(', 'int) throws DOMException', 'Text'),
  \ javaapi#method(0,1,'isElementContentWhitespace(', ')', 'boolean'),
  \ javaapi#method(0,1,'getWholeText(', ')', 'String'),
  \ javaapi#method(0,1,'replaceWholeText(', 'String) throws DOMException', 'Text'),
  \ ])

call javaapi#class('DefaultXMLDocumentHandler', 'XMLDTDContentModelHandler', [
  \ javaapi#method(0,1,'DefaultXMLDocumentHandler(', ')', ''),
  \ javaapi#method(0,1,'startDocument(', 'XMLLocator, String, NamespaceContext, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'xmlDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'doctypeDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'comment(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'processingInstruction(', 'String, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startPrefixMapping(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'emptyElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startGeneralEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'textDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endGeneralEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'characters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'ignorableWhitespace(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endElement(', 'QName, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endPrefixMapping(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDocument(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startDTD(', 'XMLLocator, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startParameterEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endParameterEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startExternalSubset(', 'XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endExternalSubset(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'elementDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startAttlist(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'attributeDecl(', 'String, String, String, String[], String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endAttlist(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'internalEntityDecl(', 'String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'externalEntityDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'unparsedEntityDecl(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'notationDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startConditional(', 'short, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'ignoredCharacters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endConditional(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDTD(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startContentModel(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'any(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'empty(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startGroup(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'pcdata(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'element(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'separator(', 'short, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'occurrence(', 'short, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endGroup(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endContentModel(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'setDocumentSource(', 'XMLDocumentSource)', 'void'),
  \ javaapi#method(0,1,'getDocumentSource(', ')', 'XMLDocumentSource'),
  \ javaapi#method(0,1,'setDTDSource(', 'XMLDTDSource)', 'void'),
  \ javaapi#method(0,1,'getDTDSource(', ')', 'XMLDTDSource'),
  \ javaapi#method(0,1,'setDTDContentModelSource(', 'XMLDTDContentModelSource)', 'void'),
  \ javaapi#method(0,1,'getDTDContentModelSource(', ')', 'XMLDTDContentModelSource'),
  \ ])

call javaapi#class('ElementImpl', 'DefaultElement', [
  \ javaapi#method(0,1,'ElementImpl(', 'int, int, int)', ''),
  \ javaapi#method(0,1,'ElementImpl(', 'int, int)', ''),
  \ javaapi#method(0,1,'ElementImpl(', 'String, String, String, String, int, int, int)', ''),
  \ javaapi#method(0,1,'ElementImpl(', 'String, String, String, String, int, int)', ''),
  \ javaapi#method(0,1,'getOwnerDocument(', ')', 'Document'),
  \ javaapi#method(0,1,'getParentNode(', ')', 'Node'),
  \ javaapi#method(0,1,'hasChildNodes(', ')', 'boolean'),
  \ javaapi#method(0,1,'getFirstChild(', ')', 'Node'),
  \ javaapi#method(0,1,'getLastChild(', ')', 'Node'),
  \ javaapi#method(0,1,'getPreviousSibling(', ')', 'Node'),
  \ javaapi#method(0,1,'getNextSibling(', ')', 'Node'),
  \ javaapi#method(0,1,'getAttributes(', ')', 'NamedNodeMap'),
  \ javaapi#method(0,1,'hasAttributes(', ')', 'boolean'),
  \ javaapi#method(0,1,'getTagName(', ')', 'String'),
  \ javaapi#method(0,1,'getAttribute(', 'String)', 'String'),
  \ javaapi#method(0,1,'getAttributeNode(', 'String)', 'Attr'),
  \ javaapi#method(0,1,'getAttributeNS(', 'String, String)', 'String'),
  \ javaapi#method(0,1,'getAttributeNodeNS(', 'String, String)', 'Attr'),
  \ javaapi#method(0,1,'hasAttribute(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'hasAttributeNS(', 'String, String)', 'boolean'),
  \ javaapi#method(0,1,'setAttribute(', 'String, String)', 'void'),
  \ javaapi#method(0,1,'getLineNumber(', ')', 'int'),
  \ javaapi#method(0,1,'getColumnNumber(', ')', 'int'),
  \ javaapi#method(0,1,'getCharacterOffset(', ')', 'int'),
  \ javaapi#method(0,1,'getAnnotation(', ')', 'String'),
  \ javaapi#method(0,1,'getSyntheticAnnotation(', ')', 'String'),
  \ ])

call javaapi#class('NamedNodeMapImpl', 'NamedNodeMap', [
  \ javaapi#method(0,1,'NamedNodeMapImpl(', 'Attr[])', ''),
  \ javaapi#method(0,1,'getNamedItem(', 'String)', 'Node'),
  \ javaapi#method(0,1,'item(', 'int)', 'Node'),
  \ javaapi#method(0,1,'getLength(', ')', 'int'),
  \ javaapi#method(0,1,'getNamedItemNS(', 'String, String)', 'Node'),
  \ javaapi#method(0,1,'setNamedItemNS(', 'Node) throws DOMException', 'Node'),
  \ javaapi#method(0,1,'setNamedItem(', 'Node) throws DOMException', 'Node'),
  \ javaapi#method(0,1,'removeNamedItem(', 'String) throws DOMException', 'Node'),
  \ javaapi#method(0,1,'removeNamedItemNS(', 'String, String) throws DOMException', 'Node'),
  \ ])

call javaapi#class('NodeImpl', 'DefaultNode', [
  \ javaapi#method(0,1,'NodeImpl(', ')', ''),
  \ javaapi#method(0,1,'NodeImpl(', 'String, String, String, String, short)', ''),
  \ javaapi#method(0,1,'getNodeName(', ')', 'String'),
  \ javaapi#method(0,1,'getNamespaceURI(', ')', 'String'),
  \ javaapi#method(0,1,'getPrefix(', ')', 'String'),
  \ javaapi#method(0,1,'getLocalName(', ')', 'String'),
  \ javaapi#method(0,1,'getNodeType(', ')', 'short'),
  \ javaapi#method(0,1,'setReadOnly(', 'boolean, boolean)', 'void'),
  \ javaapi#method(0,1,'getReadOnly(', ')', 'boolean'),
  \ ])

call javaapi#class('SchemaDOM', 'DefaultDocument', [
  \ javaapi#method(0,1,'SchemaDOM(', ')', ''),
  \ javaapi#method(0,1,'startElement(', 'QName, XMLAttributes, int, int, int)', 'ElementImpl'),
  \ javaapi#method(0,1,'emptyElement(', 'QName, XMLAttributes, int, int, int)', 'ElementImpl'),
  \ javaapi#method(0,1,'startElement(', 'QName, XMLAttributes, int, int)', 'ElementImpl'),
  \ javaapi#method(0,1,'emptyElement(', 'QName, XMLAttributes, int, int)', 'ElementImpl'),
  \ javaapi#method(0,1,'endElement(', ')', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'printDOM(', ')', 'void'),
  \ javaapi#method(1,1,'traverse(', 'Node, int)', 'void'),
  \ javaapi#method(1,1,'indent(', 'int)', 'void'),
  \ javaapi#method(0,1,'getDocumentElement(', ')', 'Element'),
  \ javaapi#method(0,1,'getImplementation(', ')', 'DOMImplementation'),
  \ ])

call javaapi#class('SchemaDOMImplementation', 'DOMImplementation', [
  \ javaapi#method(1,1,'getDOMImplementation(', ')', 'DOMImplementation'),
  \ javaapi#method(0,1,'createDocument(', 'String, String, DocumentType) throws DOMException', 'Document'),
  \ javaapi#method(0,1,'createDocumentType(', 'String, String, String) throws DOMException', 'DocumentType'),
  \ javaapi#method(0,1,'getFeature(', 'String, String)', 'Object'),
  \ javaapi#method(0,1,'hasFeature(', 'String, String)', 'boolean'),
  \ ])

call javaapi#class('SchemaDOMParser', 'DefaultXMLDocumentHandler', [
  \ javaapi#field(1,1,'ERROR_REPORTER', 'String'),
  \ javaapi#field(1,1,'GENERATE_SYNTHETIC_ANNOTATION', 'String'),
  \ javaapi#field(0,0,'fLocator', 'XMLLocator'),
  \ javaapi#field(0,0,'fNamespaceContext', 'NamespaceContext'),
  \ javaapi#method(0,1,'SchemaDOMParser(', 'XMLParserConfiguration)', ''),
  \ javaapi#method(0,1,'startDocument(', 'XMLLocator, String, NamespaceContext, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDocument(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'comment(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'processingInstruction(', 'String, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'characters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'emptyElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endElement(', 'QName, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'ignorableWhitespace(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'getDocument(', ')', 'Document'),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean)', 'void'),
  \ javaapi#method(0,1,'getFeature(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object)', 'void'),
  \ javaapi#method(0,1,'getProperty(', 'String)', 'Object'),
  \ javaapi#method(0,1,'setEntityResolver(', 'XMLEntityResolver)', 'void'),
  \ javaapi#method(0,1,'parse(', 'XMLInputSource) throws IOException', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'resetNodePool(', ')', 'void'),
  \ ])

call javaapi#class('SchemaParsingConfig', 'BasicParserConfiguration', [
  \ javaapi#field(1,0,'XML11_DATATYPE_VALIDATOR_FACTORY', 'String'),
  \ javaapi#field(1,0,'WARN_ON_DUPLICATE_ATTDEF', 'String'),
  \ javaapi#field(1,0,'WARN_ON_UNDECLARED_ELEMDEF', 'String'),
  \ javaapi#field(1,0,'ALLOW_JAVA_ENCODINGS', 'String'),
  \ javaapi#field(1,0,'CONTINUE_AFTER_FATAL_ERROR', 'String'),
  \ javaapi#field(1,0,'LOAD_EXTERNAL_DTD', 'String'),
  \ javaapi#field(1,0,'NOTIFY_BUILTIN_REFS', 'String'),
  \ javaapi#field(1,0,'NOTIFY_CHAR_REFS', 'String'),
  \ javaapi#field(1,0,'NORMALIZE_DATA', 'String'),
  \ javaapi#field(1,0,'SCHEMA_ELEMENT_DEFAULT', 'String'),
  \ javaapi#field(1,0,'GENERATE_SYNTHETIC_ANNOTATIONS', 'String'),
  \ javaapi#field(1,0,'ERROR_REPORTER', 'String'),
  \ javaapi#field(1,0,'ENTITY_MANAGER', 'String'),
  \ javaapi#field(1,0,'DOCUMENT_SCANNER', 'String'),
  \ javaapi#field(1,0,'DTD_SCANNER', 'String'),
  \ javaapi#field(1,0,'XMLGRAMMAR_POOL', 'String'),
  \ javaapi#field(1,0,'DTD_VALIDATOR', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_BINDER', 'String'),
  \ javaapi#field(1,0,'DATATYPE_VALIDATOR_FACTORY', 'String'),
  \ javaapi#field(1,0,'VALIDATION_MANAGER', 'String'),
  \ javaapi#field(1,0,'SCHEMA_VALIDATOR', 'String'),
  \ javaapi#field(1,0,'LOCALE', 'String'),
  \ javaapi#field(0,0,'fDatatypeValidatorFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fNamespaceScanner', 'XMLNSDocumentScannerImpl'),
  \ javaapi#field(0,0,'fDTDScanner', 'XMLDTDScannerImpl'),
  \ javaapi#field(0,0,'fXML11DatatypeFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fXML11NSDocScanner', 'XML11NSDocumentScannerImpl'),
  \ javaapi#field(0,0,'fXML11DTDScanner', 'XML11DTDScannerImpl'),
  \ javaapi#field(0,0,'fCurrentDVFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fCurrentScanner', 'XMLDocumentScanner'),
  \ javaapi#field(0,0,'fCurrentDTDScanner', 'XMLDTDScanner'),
  \ javaapi#field(0,0,'fGrammarPool', 'XMLGrammarPool'),
  \ javaapi#field(0,0,'fVersionDetector', 'XMLVersionDetector'),
  \ javaapi#field(0,0,'fErrorReporter', 'XMLErrorReporter'),
  \ javaapi#field(0,0,'fEntityManager', 'XMLEntityManager'),
  \ javaapi#field(0,0,'fInputSource', 'XMLInputSource'),
  \ javaapi#field(0,0,'fValidationManager', 'ValidationManager'),
  \ javaapi#field(0,0,'fLocator', 'XMLLocator'),
  \ javaapi#field(0,0,'fParseInProgress', 'boolean'),
  \ javaapi#field(0,0,'fConfigUpdated', 'boolean'),
  \ javaapi#method(0,1,'SchemaParsingConfig(', ')', ''),
  \ javaapi#method(0,1,'SchemaParsingConfig(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'SchemaParsingConfig(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'SchemaParsingConfig(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,1,'getFeatureState(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'getPropertyState(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'setLocale(', 'Locale) throws XNIException', 'void'),
  \ javaapi#method(0,1,'setInputSource(', 'XMLInputSource) throws XMLConfigurationException, IOException', 'void'),
  \ javaapi#method(0,1,'parse(', 'boolean) throws XNIException, IOException', 'boolean'),
  \ javaapi#method(0,1,'cleanup(', ')', 'void'),
  \ javaapi#method(0,1,'parse(', 'XMLInputSource) throws XNIException, IOException', 'void'),
  \ javaapi#method(0,1,'reset(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'configurePipeline(', ')', 'void'),
  \ javaapi#method(0,0,'configureXML11Pipeline(', ')', 'void'),
  \ javaapi#method(0,0,'checkFeature(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,0,'checkProperty(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,0,'resetXML10(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'resetXML11(', ') throws XNIException', 'void'),
  \ javaapi#method(0,1,'resetNodePool(', ')', 'void'),
  \ ])

call javaapi#class('TextImpl', 'DefaultText', [
  \ javaapi#method(0,1,'TextImpl(', 'StringBuffer, SchemaDOM, int, int)', ''),
  \ javaapi#method(0,1,'getParentNode(', ')', 'Node'),
  \ javaapi#method(0,1,'getPreviousSibling(', ')', 'Node'),
  \ javaapi#method(0,1,'getNextSibling(', ')', 'Node'),
  \ javaapi#method(0,1,'getData(', ') throws DOMException', 'String'),
  \ javaapi#method(0,1,'getLength(', ')', 'int'),
  \ javaapi#method(0,1,'substringData(', 'int, int) throws DOMException', 'String'),
  \ ])

