call javaapi#namespace('com.sun.xml.internal.stream.buffer')

call javaapi#class('AbstractCreator', 'AbstractCreatorProcessor', [
  \ javaapi#field(0,0,'_buffer', 'MutableXMLStreamBuffer'),
  \ javaapi#method(0,1,'AbstractCreator(', ')', ''),
  \ javaapi#method(0,1,'setXMLStreamBuffer(', 'MutableXMLStreamBuffer)', 'void'),
  \ javaapi#method(0,1,'getXMLStreamBuffer(', ')', 'MutableXMLStreamBuffer'),
  \ javaapi#method(0,0,'createBuffer(', ')', 'void'),
  \ javaapi#method(0,0,'increaseTreeCount(', ')', 'void'),
  \ javaapi#method(0,0,'setBuffer(', 'MutableXMLStreamBuffer)', 'void'),
  \ javaapi#method(0,0,'setHasInternedStrings(', 'boolean)', 'void'),
  \ javaapi#method(0,0,'storeStructure(', 'int)', 'void'),
  \ javaapi#method(0,0,'resizeStructure(', ')', 'void'),
  \ javaapi#method(0,0,'storeStructureString(', 'String)', 'void'),
  \ javaapi#method(0,0,'resizeStructureStrings(', ')', 'void'),
  \ javaapi#method(0,0,'storeContentString(', 'String)', 'void'),
  \ javaapi#method(0,0,'storeContentCharacters(', 'int, char[], int, int)', 'void'),
  \ javaapi#method(0,0,'resizeContentCharacters(', ')', 'void'),
  \ javaapi#method(0,0,'storeContentCharactersCopy(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,0,'peekAtContentObject(', ')', 'Object'),
  \ javaapi#method(0,0,'storeContentObject(', 'Object)', 'void'),
  \ javaapi#method(0,0,'resizeContentObjects(', ')', 'void'),
  \ ])

call javaapi#class('AbstractCreatorProcessor', '', [
  \ javaapi#field(1,0,'FLAG_DOCUMENT_FRAGMENT', 'int'),
  \ javaapi#field(1,0,'FLAG_PREFIX', 'int'),
  \ javaapi#field(1,0,'FLAG_URI', 'int'),
  \ javaapi#field(1,0,'FLAG_QUALIFIED_NAME', 'int'),
  \ javaapi#field(1,0,'CONTENT_TYPE_CHAR_ARRAY', 'int'),
  \ javaapi#field(1,0,'CONTENT_TYPE_CHAR_ARRAY_COPY', 'int'),
  \ javaapi#field(1,0,'CONTENT_TYPE_STRING', 'int'),
  \ javaapi#field(1,0,'CONTENT_TYPE_OBJECT', 'int'),
  \ javaapi#field(1,0,'CHAR_ARRAY_LENGTH_SMALL', 'int'),
  \ javaapi#field(1,0,'CHAR_ARRAY_LENGTH_MEDIUM', 'int'),
  \ javaapi#field(1,0,'CHAR_ARRAY_LENGTH_SMALL_SIZE', 'int'),
  \ javaapi#field(1,0,'CHAR_ARRAY_LENGTH_MEDIUM_SIZE', 'int'),
  \ javaapi#field(1,0,'VALUE_TYPE_STRING', 'int'),
  \ javaapi#field(1,0,'VALUE_TYPE_OBJECT', 'int'),
  \ javaapi#field(1,0,'TYPE_MASK', 'int'),
  \ javaapi#field(1,0,'T_DOCUMENT', 'int'),
  \ javaapi#field(1,0,'T_ELEMENT', 'int'),
  \ javaapi#field(1,0,'T_ATTRIBUTE', 'int'),
  \ javaapi#field(1,0,'T_NAMESPACE_ATTRIBUTE', 'int'),
  \ javaapi#field(1,0,'T_TEXT', 'int'),
  \ javaapi#field(1,0,'T_COMMENT', 'int'),
  \ javaapi#field(1,0,'T_PROCESSING_INSTRUCTION', 'int'),
  \ javaapi#field(1,0,'T_UNEXPANDED_ENTITY_REFERENCE', 'int'),
  \ javaapi#field(1,0,'T_END', 'int'),
  \ javaapi#field(1,0,'T_DOCUMENT_FRAGMENT', 'int'),
  \ javaapi#field(1,0,'T_ELEMENT_U_LN_QN', 'int'),
  \ javaapi#field(1,0,'T_ELEMENT_P_U_LN', 'int'),
  \ javaapi#field(1,0,'T_ELEMENT_U_LN', 'int'),
  \ javaapi#field(1,0,'T_ELEMENT_LN', 'int'),
  \ javaapi#field(1,0,'T_NAMESPACE_ATTRIBUTE_P', 'int'),
  \ javaapi#field(1,0,'T_NAMESPACE_ATTRIBUTE_P_U', 'int'),
  \ javaapi#field(1,0,'T_NAMESPACE_ATTRIBUTE_U', 'int'),
  \ javaapi#field(1,0,'T_ATTRIBUTE_U_LN_QN', 'int'),
  \ javaapi#field(1,0,'T_ATTRIBUTE_P_U_LN', 'int'),
  \ javaapi#field(1,0,'T_ATTRIBUTE_U_LN', 'int'),
  \ javaapi#field(1,0,'T_ATTRIBUTE_LN', 'int'),
  \ javaapi#field(1,0,'T_ATTRIBUTE_U_LN_QN_OBJECT', 'int'),
  \ javaapi#field(1,0,'T_ATTRIBUTE_P_U_LN_OBJECT', 'int'),
  \ javaapi#field(1,0,'T_ATTRIBUTE_U_LN_OBJECT', 'int'),
  \ javaapi#field(1,0,'T_ATTRIBUTE_LN_OBJECT', 'int'),
  \ javaapi#field(1,0,'T_TEXT_AS_CHAR_ARRAY', 'int'),
  \ javaapi#field(1,0,'T_TEXT_AS_CHAR_ARRAY_SMALL', 'int'),
  \ javaapi#field(1,0,'T_TEXT_AS_CHAR_ARRAY_MEDIUM', 'int'),
  \ javaapi#field(1,0,'T_TEXT_AS_CHAR_ARRAY_COPY', 'int'),
  \ javaapi#field(1,0,'T_TEXT_AS_STRING', 'int'),
  \ javaapi#field(1,0,'T_TEXT_AS_OBJECT', 'int'),
  \ javaapi#field(1,0,'T_COMMENT_AS_CHAR_ARRAY', 'int'),
  \ javaapi#field(1,0,'T_COMMENT_AS_CHAR_ARRAY_SMALL', 'int'),
  \ javaapi#field(1,0,'T_COMMENT_AS_CHAR_ARRAY_MEDIUM', 'int'),
  \ javaapi#field(1,0,'T_COMMENT_AS_CHAR_ARRAY_COPY', 'int'),
  \ javaapi#field(1,0,'T_COMMENT_AS_STRING', 'int'),
  \ javaapi#field(1,0,'T_END_OF_BUFFER', 'int'),
  \ javaapi#field(0,0,'_currentStructureFragment', 'FragmentedArray<byte[]>'),
  \ javaapi#field(0,0,'_structure', 'byte[]'),
  \ javaapi#field(0,0,'_structurePtr', 'int'),
  \ javaapi#field(0,0,'_currentStructureStringFragment', 'String[]>'),
  \ javaapi#field(0,0,'_structureStrings', 'String[]'),
  \ javaapi#field(0,0,'_structureStringsPtr', 'int'),
  \ javaapi#field(0,0,'_currentContentCharactersBufferFragment', 'FragmentedArray<char[]>'),
  \ javaapi#field(0,0,'_contentCharactersBuffer', 'char[]'),
  \ javaapi#field(0,0,'_contentCharactersBufferPtr', 'int'),
  \ javaapi#field(0,0,'_currentContentObjectFragment', 'Object[]>'),
  \ javaapi#field(0,0,'_contentObjects', 'Object[]'),
  \ javaapi#field(0,0,'_contentObjectsPtr', 'int'),
  \ javaapi#method(0,1,'AbstractCreatorProcessor(', ')', ''),
  \ ])

call javaapi#class('AbstractProcessor', 'AbstractCreatorProcessor', [
  \ javaapi#field(1,0,'STATE_ILLEGAL', 'int'),
  \ javaapi#field(1,0,'STATE_DOCUMENT', 'int'),
  \ javaapi#field(1,0,'STATE_DOCUMENT_FRAGMENT', 'int'),
  \ javaapi#field(1,0,'STATE_ELEMENT_U_LN_QN', 'int'),
  \ javaapi#field(1,0,'STATE_ELEMENT_P_U_LN', 'int'),
  \ javaapi#field(1,0,'STATE_ELEMENT_U_LN', 'int'),
  \ javaapi#field(1,0,'STATE_ELEMENT_LN', 'int'),
  \ javaapi#field(1,0,'STATE_TEXT_AS_CHAR_ARRAY_SMALL', 'int'),
  \ javaapi#field(1,0,'STATE_TEXT_AS_CHAR_ARRAY_MEDIUM', 'int'),
  \ javaapi#field(1,0,'STATE_TEXT_AS_CHAR_ARRAY_COPY', 'int'),
  \ javaapi#field(1,0,'STATE_TEXT_AS_STRING', 'int'),
  \ javaapi#field(1,0,'STATE_TEXT_AS_OBJECT', 'int'),
  \ javaapi#field(1,0,'STATE_COMMENT_AS_CHAR_ARRAY_SMALL', 'int'),
  \ javaapi#field(1,0,'STATE_COMMENT_AS_CHAR_ARRAY_MEDIUM', 'int'),
  \ javaapi#field(1,0,'STATE_COMMENT_AS_CHAR_ARRAY_COPY', 'int'),
  \ javaapi#field(1,0,'STATE_COMMENT_AS_STRING', 'int'),
  \ javaapi#field(1,0,'STATE_PROCESSING_INSTRUCTION', 'int'),
  \ javaapi#field(1,0,'STATE_END', 'int'),
  \ javaapi#field(1,0,'STATE_NAMESPACE_ATTRIBUTE', 'int'),
  \ javaapi#field(1,0,'STATE_NAMESPACE_ATTRIBUTE_P', 'int'),
  \ javaapi#field(1,0,'STATE_NAMESPACE_ATTRIBUTE_P_U', 'int'),
  \ javaapi#field(1,0,'STATE_NAMESPACE_ATTRIBUTE_U', 'int'),
  \ javaapi#field(1,0,'STATE_ATTRIBUTE_U_LN_QN', 'int'),
  \ javaapi#field(1,0,'STATE_ATTRIBUTE_P_U_LN', 'int'),
  \ javaapi#field(1,0,'STATE_ATTRIBUTE_U_LN', 'int'),
  \ javaapi#field(1,0,'STATE_ATTRIBUTE_LN', 'int'),
  \ javaapi#field(1,0,'STATE_ATTRIBUTE_U_LN_QN_OBJECT', 'int'),
  \ javaapi#field(1,0,'STATE_ATTRIBUTE_P_U_LN_OBJECT', 'int'),
  \ javaapi#field(1,0,'STATE_ATTRIBUTE_U_LN_OBJECT', 'int'),
  \ javaapi#field(1,0,'STATE_ATTRIBUTE_LN_OBJECT', 'int'),
  \ javaapi#field(0,0,'_buffer', 'XMLStreamBuffer'),
  \ javaapi#field(0,0,'_fragmentMode', 'boolean'),
  \ javaapi#field(0,0,'_stringInterningFeature', 'boolean'),
  \ javaapi#field(0,0,'_treeCount', 'int'),
  \ javaapi#field(0,0,'_qNameBuffer', 'StringBuilder'),
  \ javaapi#method(0,1,'AbstractProcessor(', ')', ''),
  \ javaapi#method(0,0,'setBuffer(', 'XMLStreamBuffer)', 'void'),
  \ javaapi#method(0,0,'setBuffer(', 'XMLStreamBuffer, boolean)', 'void'),
  \ javaapi#method(0,0,'peekStructure(', ')', 'int'),
  \ javaapi#method(0,0,'readStructure(', ')', 'int'),
  \ javaapi#method(0,0,'readEiiState(', ')', 'int'),
  \ javaapi#method(1,0,'getEIIState(', 'int)', 'int'),
  \ javaapi#method(1,0,'getNIIState(', 'int)', 'int'),
  \ javaapi#method(1,0,'getAIIState(', 'int)', 'int'),
  \ javaapi#method(0,0,'readStructure16(', ')', 'int'),
  \ javaapi#method(0,0,'readStructureString(', ')', 'String'),
  \ javaapi#method(0,0,'readContentString(', ')', 'String'),
  \ javaapi#method(0,0,'readContentCharactersCopy(', ')', 'char[]'),
  \ javaapi#method(0,0,'readContentCharactersBuffer(', 'int)', 'int'),
  \ javaapi#method(0,0,'readContentObject(', ')', 'Object'),
  \ javaapi#method(0,0,'getQName(', 'String, String)', 'String'),
  \ javaapi#method(0,0,'getPrefixFromQName(', 'String)', 'String'),
  \ ])

call javaapi#class('AttributesHolder', 'Attributes', [
  \ javaapi#field(1,0,'DEFAULT_CAPACITY', 'int'),
  \ javaapi#field(1,0,'ITEM_SIZE', 'int'),
  \ javaapi#field(1,0,'PREFIX', 'int'),
  \ javaapi#field(1,0,'URI', 'int'),
  \ javaapi#field(1,0,'LOCAL_NAME', 'int'),
  \ javaapi#field(1,0,'QNAME', 'int'),
  \ javaapi#field(1,0,'TYPE', 'int'),
  \ javaapi#field(1,0,'VALUE', 'int'),
  \ javaapi#field(0,0,'_attributeCount', 'int'),
  \ javaapi#field(0,0,'_strings', 'String[]'),
  \ javaapi#method(0,1,'AttributesHolder(', ')', ''),
  \ javaapi#method(0,1,'getLength(', ')', 'int'),
  \ javaapi#method(0,1,'getPrefix(', 'int)', 'String'),
  \ javaapi#method(0,1,'getLocalName(', 'int)', 'String'),
  \ javaapi#method(0,1,'getQName(', 'int)', 'String'),
  \ javaapi#method(0,1,'getType(', 'int)', 'String'),
  \ javaapi#method(0,1,'getURI(', 'int)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'int)', 'String'),
  \ javaapi#method(0,1,'getIndex(', 'String)', 'int'),
  \ javaapi#method(0,1,'getType(', 'String)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'String)', 'String'),
  \ javaapi#method(0,1,'getIndex(', 'String, String)', 'int'),
  \ javaapi#method(0,1,'getType(', 'String, String)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'String, String)', 'String'),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ javaapi#method(0,1,'addAttributeWithQName(', 'String, String, String, String, String)', 'void'),
  \ javaapi#method(0,1,'addAttributeWithPrefix(', 'String, String, String, String, String)', 'void'),
  \ ])

call javaapi#class('FragmentedArray<T>', '', [
  \ javaapi#field(0,0,'_item', 'T'),
  \ javaapi#field(0,0,'_next', 'FragmentedArray<T>'),
  \ javaapi#field(0,0,'_previous', 'FragmentedArray<T>'),
  \ ])

call javaapi#class('MutableXMLStreamBuffer', 'XMLStreamBuffer', [
  \ javaapi#field(1,1,'DEFAULT_ARRAY_SIZE', 'int'),
  \ javaapi#method(0,1,'MutableXMLStreamBuffer(', ')', ''),
  \ javaapi#method(0,1,'setSystemId(', 'String)', 'void'),
  \ javaapi#method(0,1,'MutableXMLStreamBuffer(', 'int)', ''),
  \ javaapi#method(0,1,'createFromXMLStreamReader(', 'XMLStreamReader) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'createFromXMLStreamWriter(', ')', 'XMLStreamWriter'),
  \ javaapi#method(0,1,'createFromSAXBufferCreator(', ')', 'SAXBufferCreator'),
  \ javaapi#method(0,1,'createFromXMLReader(', 'XMLReader, InputStream) throws SAXException, IOException', 'void'),
  \ javaapi#method(0,1,'createFromXMLReader(', 'XMLReader, InputStream, String) throws SAXException, IOException', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,0,'setHasInternedStrings(', 'boolean)', 'void'),
  \ ])

call javaapi#class('XMLStreamBuffer', '', [
  \ javaapi#field(0,0,'_inscopeNamespaces', 'String>'),
  \ javaapi#field(0,0,'_hasInternedStrings', 'boolean'),
  \ javaapi#field(0,0,'_structure', 'FragmentedArray<byte[]>'),
  \ javaapi#field(0,0,'_structurePtr', 'int'),
  \ javaapi#field(0,0,'_structureStrings', 'String[]>'),
  \ javaapi#field(0,0,'_structureStringsPtr', 'int'),
  \ javaapi#field(0,0,'_contentCharactersBuffer', 'FragmentedArray<char[]>'),
  \ javaapi#field(0,0,'_contentCharactersBufferPtr', 'int'),
  \ javaapi#field(0,0,'_contentObjects', 'Object[]>'),
  \ javaapi#field(0,0,'_contentObjectsPtr', 'int'),
  \ javaapi#field(0,0,'treeCount', 'int'),
  \ javaapi#field(0,0,'systemId', 'String'),
  \ javaapi#method(0,1,'XMLStreamBuffer(', ')', ''),
  \ javaapi#method(0,1,'isCreated(', ')', 'boolean'),
  \ javaapi#method(0,1,'isFragment(', ')', 'boolean'),
  \ javaapi#method(0,1,'isElementFragment(', ')', 'boolean'),
  \ javaapi#method(0,1,'isForest(', ')', 'boolean'),
  \ javaapi#method(0,1,'getSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getInscopeNamespaces(', ')', 'String>'),
  \ javaapi#method(0,1,'hasInternedStrings(', ')', 'boolean'),
  \ javaapi#method(0,1,'readAsXMLStreamReader(', ') throws XMLStreamException', 'StreamReaderBufferProcessor'),
  \ javaapi#method(0,1,'writeToXMLStreamWriter(', 'XMLStreamWriter, boolean) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeToXMLStreamWriter(', 'XMLStreamWriter) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'readAsXMLReader(', ')', 'SAXBufferProcessor'),
  \ javaapi#method(0,1,'readAsXMLReader(', 'boolean)', 'SAXBufferProcessor'),
  \ javaapi#method(0,1,'writeTo(', 'ContentHandler, boolean) throws SAXException', 'void'),
  \ javaapi#method(0,1,'writeTo(', 'ContentHandler) throws SAXException', 'void'),
  \ javaapi#method(0,1,'writeTo(', 'ContentHandler, ErrorHandler, boolean) throws SAXException', 'void'),
  \ javaapi#method(0,1,'writeTo(', 'ContentHandler, ErrorHandler) throws SAXException', 'void'),
  \ javaapi#method(0,1,'writeTo(', 'Node) throws XMLStreamBufferException', 'Node'),
  \ javaapi#method(1,1,'createNewBufferFromXMLStreamReader(', 'XMLStreamReader) throws XMLStreamException', 'XMLStreamBuffer'),
  \ javaapi#method(1,1,'createNewBufferFromXMLReader(', 'XMLReader, InputStream) throws SAXException, IOException', 'XMLStreamBuffer'),
  \ javaapi#method(1,1,'createNewBufferFromXMLReader(', 'XMLReader, InputStream, String) throws SAXException, IOException', 'XMLStreamBuffer'),
  \ javaapi#method(0,0,'getStructure(', ')', 'FragmentedArray<byte[]>'),
  \ javaapi#method(0,0,'getStructurePtr(', ')', 'int'),
  \ javaapi#method(0,0,'getStructureStrings(', ')', 'String[]>'),
  \ javaapi#method(0,0,'getStructureStringsPtr(', ')', 'int'),
  \ javaapi#method(0,0,'getContentCharactersBuffer(', ')', 'FragmentedArray<char[]>'),
  \ javaapi#method(0,0,'getContentCharactersBufferPtr(', ')', 'int'),
  \ javaapi#method(0,0,'getContentObjects(', ')', 'Object[]>'),
  \ javaapi#method(0,0,'getContentObjectsPtr(', ')', 'int'),
  \ ])

call javaapi#class('XMLStreamBufferException', 'Exception', [
  \ javaapi#method(0,1,'XMLStreamBufferException(', 'String)', ''),
  \ javaapi#method(0,1,'XMLStreamBufferException(', 'String, Exception)', ''),
  \ javaapi#method(0,1,'XMLStreamBufferException(', 'Exception)', ''),
  \ ])

call javaapi#class('XMLStreamBufferMark', 'XMLStreamBuffer', [
  \ javaapi#method(0,1,'XMLStreamBufferMark(', 'Map<String, String>, AbstractCreatorProcessor)', ''),
  \ ])

call javaapi#class('XMLStreamBufferResult', 'SAXResult', [
  \ javaapi#field(0,0,'_buffer', 'MutableXMLStreamBuffer'),
  \ javaapi#field(0,0,'_bufferCreator', 'SAXBufferCreator'),
  \ javaapi#method(0,1,'XMLStreamBufferResult(', ')', ''),
  \ javaapi#method(0,1,'XMLStreamBufferResult(', 'MutableXMLStreamBuffer)', ''),
  \ javaapi#method(0,1,'getXMLStreamBuffer(', ')', 'MutableXMLStreamBuffer'),
  \ javaapi#method(0,1,'setXMLStreamBuffer(', 'MutableXMLStreamBuffer)', 'void'),
  \ javaapi#method(0,1,'getHandler(', ')', 'ContentHandler'),
  \ javaapi#method(0,1,'getLexicalHandler(', ')', 'LexicalHandler'),
  \ ])

call javaapi#class('XMLStreamBufferSource', 'SAXSource', [
  \ javaapi#field(0,0,'_buffer', 'XMLStreamBuffer'),
  \ javaapi#field(0,0,'_bufferProcessor', 'SAXBufferProcessor'),
  \ javaapi#method(0,1,'XMLStreamBufferSource(', 'XMLStreamBuffer)', ''),
  \ javaapi#method(0,1,'getXMLStreamBuffer(', ')', 'XMLStreamBuffer'),
  \ javaapi#method(0,1,'setXMLStreamBuffer(', 'XMLStreamBuffer)', 'void'),
  \ javaapi#method(0,1,'getXMLReader(', ')', 'XMLReader'),
  \ ])

