call javaapi#namespace('com.sun.xml.internal.fastinfoset.stax.factory')

call javaapi#class('StAXEventFactory', 'XMLEventFactory', [
  \ javaapi#method(0,'StAXEventFactory(', ')', 'public'),
  \ javaapi#method(0,'setLocation(', 'Location)', 'void'),
  \ javaapi#method(0,'createAttribute(', 'String, String, String, String)', 'Attribute'),
  \ javaapi#method(0,'createAttribute(', 'String, String)', 'Attribute'),
  \ javaapi#method(0,'createAttribute(', 'QName, String)', 'Attribute'),
  \ javaapi#method(0,'createNamespace(', 'String)', 'Namespace'),
  \ javaapi#method(0,'createNamespace(', 'String, String)', 'Namespace'),
  \ javaapi#method(0,'createStartElement(', 'QName, Iterator, Iterator)', 'StartElement'),
  \ javaapi#method(0,'createStartElement(', 'String, String, String)', 'StartElement'),
  \ javaapi#method(0,'createStartElement(', 'String, String, String, Iterator, Iterator)', 'StartElement'),
  \ javaapi#method(0,'createStartElement(', 'String, String, String, Iterator, Iterator, NamespaceContext)', 'StartElement'),
  \ javaapi#method(0,'createEndElement(', 'QName, Iterator)', 'EndElement'),
  \ javaapi#method(0,'createEndElement(', 'String, String, String)', 'EndElement'),
  \ javaapi#method(0,'createEndElement(', 'String, String, String, Iterator)', 'EndElement'),
  \ javaapi#method(0,'createCharacters(', 'String)', 'Characters'),
  \ javaapi#method(0,'createCData(', 'String)', 'Characters'),
  \ javaapi#method(0,'createSpace(', 'String)', 'Characters'),
  \ javaapi#method(0,'createIgnorableSpace(', 'String)', 'Characters'),
  \ javaapi#method(0,'createStartDocument(', ')', 'StartDocument'),
  \ javaapi#method(0,'createStartDocument(', 'String)', 'StartDocument'),
  \ javaapi#method(0,'createStartDocument(', 'String, String)', 'StartDocument'),
  \ javaapi#method(0,'createStartDocument(', 'String, String, boolean)', 'StartDocument'),
  \ javaapi#method(0,'createEndDocument(', ')', 'EndDocument'),
  \ javaapi#method(0,'createEntityReference(', 'String, EntityDeclaration)', 'EntityReference'),
  \ javaapi#method(0,'createComment(', 'String)', 'Comment'),
  \ javaapi#method(0,'createDTD(', 'String)', 'DTD'),
  \ javaapi#method(0,'createProcessingInstruction(', 'String, String)', 'ProcessingInstruction'),
  \ ])

call javaapi#class('StAXInputFactory', 'XMLInputFactory', [
  \ javaapi#method(0,'StAXInputFactory(', ')', 'public'),
  \ javaapi#method(1,'newInstance(', ')', 'XMLInputFactory'),
  \ javaapi#method(0,'createXMLStreamReader(', 'Reader) throws XMLStreamException', 'XMLStreamReader'),
  \ javaapi#method(0,'createXMLStreamReader(', 'InputStream) throws XMLStreamException', 'XMLStreamReader'),
  \ javaapi#method(0,'createXMLStreamReader(', 'String, Reader) throws XMLStreamException', 'XMLStreamReader'),
  \ javaapi#method(0,'createXMLStreamReader(', 'Source) throws XMLStreamException', 'XMLStreamReader'),
  \ javaapi#method(0,'createXMLStreamReader(', 'String, InputStream) throws XMLStreamException', 'XMLStreamReader'),
  \ javaapi#method(0,'createXMLStreamReader(', 'InputStream, String) throws XMLStreamException', 'XMLStreamReader'),
  \ javaapi#method(0,'createXMLEventReader(', 'InputStream) throws XMLStreamException', 'XMLEventReader'),
  \ javaapi#method(0,'createXMLEventReader(', 'Reader) throws XMLStreamException', 'XMLEventReader'),
  \ javaapi#method(0,'createXMLEventReader(', 'Source) throws XMLStreamException', 'XMLEventReader'),
  \ javaapi#method(0,'createXMLEventReader(', 'String, InputStream) throws XMLStreamException', 'XMLEventReader'),
  \ javaapi#method(0,'createXMLEventReader(', 'InputStream, String) throws XMLStreamException', 'XMLEventReader'),
  \ javaapi#method(0,'createXMLEventReader(', 'String, Reader) throws XMLStreamException', 'XMLEventReader'),
  \ javaapi#method(0,'createXMLEventReader(', 'XMLStreamReader) throws XMLStreamException', 'XMLEventReader'),
  \ javaapi#method(0,'getEventAllocator(', ')', 'XMLEventAllocator'),
  \ javaapi#method(0,'getXMLReporter(', ')', 'XMLReporter'),
  \ javaapi#method(0,'getXMLResolver(', ')', 'XMLResolver'),
  \ javaapi#method(0,'setXMLReporter(', 'XMLReporter)', 'void'),
  \ javaapi#method(0,'setXMLResolver(', 'XMLResolver)', 'void'),
  \ javaapi#method(0,'createFilteredReader(', 'XMLEventReader, EventFilter) throws XMLStreamException', 'XMLEventReader'),
  \ javaapi#method(0,'createFilteredReader(', 'XMLStreamReader, StreamFilter) throws XMLStreamException', 'XMLStreamReader'),
  \ javaapi#method(0,'getProperty(', 'String) throws IllegalArgumentException', 'Object'),
  \ javaapi#method(0,'isPropertySupported(', 'String)', 'boolean'),
  \ javaapi#method(0,'setEventAllocator(', 'XMLEventAllocator)', 'void'),
  \ javaapi#method(0,'setProperty(', 'String, Object) throws IllegalArgumentException', 'void'),
  \ ])

call javaapi#class('StAXOutputFactory', 'XMLOutputFactory', [
  \ javaapi#method(0,'StAXOutputFactory(', ')', 'public'),
  \ javaapi#method(0,'createXMLEventWriter(', 'Result) throws XMLStreamException', 'XMLEventWriter'),
  \ javaapi#method(0,'createXMLEventWriter(', 'Writer) throws XMLStreamException', 'XMLEventWriter'),
  \ javaapi#method(0,'createXMLEventWriter(', 'OutputStream) throws XMLStreamException', 'XMLEventWriter'),
  \ javaapi#method(0,'createXMLEventWriter(', 'OutputStream, String) throws XMLStreamException', 'XMLEventWriter'),
  \ javaapi#method(0,'createXMLStreamWriter(', 'Result) throws XMLStreamException', 'XMLStreamWriter'),
  \ javaapi#method(0,'createXMLStreamWriter(', 'Writer) throws XMLStreamException', 'XMLStreamWriter'),
  \ javaapi#method(0,'createXMLStreamWriter(', 'OutputStream) throws XMLStreamException', 'XMLStreamWriter'),
  \ javaapi#method(0,'createXMLStreamWriter(', 'OutputStream, String) throws XMLStreamException', 'XMLStreamWriter'),
  \ javaapi#method(0,'getProperty(', 'String) throws IllegalArgumentException', 'Object'),
  \ javaapi#method(0,'isPropertySupported(', 'String)', 'boolean'),
  \ javaapi#method(0,'setProperty(', 'String, Object) throws IllegalArgumentException', 'void'),
  \ ])

