call javaapi#namespace('com.sun.org.apache.xml.internal.security.signature')

call javaapi#class('InvalidDigestValueException', 'XMLSignatureException', [
  \ javaapi#method(0,1,'InvalidDigestValueException(', ')', ''),
  \ javaapi#method(0,1,'InvalidDigestValueException(', 'String)', ''),
  \ javaapi#method(0,1,'InvalidDigestValueException(', 'String, Object[])', ''),
  \ javaapi#method(0,1,'InvalidDigestValueException(', 'String, Exception)', ''),
  \ javaapi#method(0,1,'InvalidDigestValueException(', 'String, Object[], Exception)', ''),
  \ ])

call javaapi#class('InvalidSignatureValueException', 'XMLSignatureException', [
  \ javaapi#method(0,1,'InvalidSignatureValueException(', ')', ''),
  \ javaapi#method(0,1,'InvalidSignatureValueException(', 'String)', ''),
  \ javaapi#method(0,1,'InvalidSignatureValueException(', 'String, Object[])', ''),
  \ javaapi#method(0,1,'InvalidSignatureValueException(', 'String, Exception)', ''),
  \ javaapi#method(0,1,'InvalidSignatureValueException(', 'String, Object[], Exception)', ''),
  \ ])

call javaapi#class('Manifest', 'SignatureElementProxy', [
  \ javaapi#method(0,1,'Manifest(', 'Document)', ''),
  \ javaapi#method(0,1,'Manifest(', 'Element, String) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'addDocument(', 'String, String, Transforms, String, String, String) throws XMLSignatureException', 'void'),
  \ javaapi#method(0,1,'generateDigestValues(', ') throws XMLSignatureException, ReferenceNotInitializedException', 'void'),
  \ javaapi#method(0,1,'getLength(', ')', 'int'),
  \ javaapi#method(0,1,'item(', 'int) throws XMLSecurityException', 'Reference'),
  \ javaapi#method(0,1,'setId(', 'String)', 'void'),
  \ javaapi#method(0,1,'getId(', ')', 'String'),
  \ javaapi#method(0,1,'verifyReferences(', ') throws MissingResourceFailureException, XMLSecurityException', 'boolean'),
  \ javaapi#method(0,1,'verifyReferences(', 'boolean) throws MissingResourceFailureException, XMLSecurityException', 'boolean'),
  \ javaapi#method(0,1,'getVerificationResult(', 'int) throws XMLSecurityException', 'boolean'),
  \ javaapi#method(0,1,'addResourceResolver(', 'ResourceResolver)', 'void'),
  \ javaapi#method(0,1,'addResourceResolver(', 'ResourceResolverSpi)', 'void'),
  \ javaapi#method(0,1,'setResolverProperty(', 'String, String)', 'void'),
  \ javaapi#method(0,1,'getResolverProperty(', 'String)', 'String'),
  \ javaapi#method(0,1,'getSignedContentItem(', 'int) throws XMLSignatureException', 'byte[]'),
  \ javaapi#method(0,1,'getReferencedContentBeforeTransformsItem(', 'int) throws XMLSecurityException', 'XMLSignatureInput'),
  \ javaapi#method(0,1,'getReferencedContentAfterTransformsItem(', 'int) throws XMLSecurityException', 'XMLSignatureInput'),
  \ javaapi#method(0,1,'getSignedContentLength(', ')', 'int'),
  \ javaapi#method(0,1,'getBaseLocalName(', ')', 'String'),
  \ ])

call javaapi#class('MissingResourceFailureException', 'XMLSignatureException', [
  \ javaapi#method(0,1,'MissingResourceFailureException(', 'String, Reference)', ''),
  \ javaapi#method(0,1,'MissingResourceFailureException(', 'String, Object[], Reference)', ''),
  \ javaapi#method(0,1,'MissingResourceFailureException(', 'String, Exception, Reference)', ''),
  \ javaapi#method(0,1,'MissingResourceFailureException(', 'String, Object[], Exception, Reference)', ''),
  \ javaapi#method(0,1,'setReference(', 'Reference)', 'void'),
  \ javaapi#method(0,1,'getReference(', ')', 'Reference'),
  \ ])

call javaapi#interface('NodeFilter', '', [
  \ javaapi#method(0,1,'isNodeInclude(', 'Node)', 'int'),
  \ javaapi#method(0,1,'isNodeIncludeDO(', 'Node, int)', 'int'),
  \ ])

call javaapi#class('ObjectContainer', 'SignatureElementProxy', [
  \ javaapi#method(0,1,'ObjectContainer(', 'Document)', ''),
  \ javaapi#method(0,1,'ObjectContainer(', 'Element, String) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'setId(', 'String)', 'void'),
  \ javaapi#method(0,1,'getId(', ')', 'String'),
  \ javaapi#method(0,1,'setMimeType(', 'String)', 'void'),
  \ javaapi#method(0,1,'getMimeType(', ')', 'String'),
  \ javaapi#method(0,1,'setEncoding(', 'String)', 'void'),
  \ javaapi#method(0,1,'getEncoding(', ')', 'String'),
  \ javaapi#method(0,1,'appendChild(', 'Node)', 'Node'),
  \ javaapi#method(0,1,'getBaseLocalName(', ')', 'String'),
  \ ])

call javaapi#class('Reference', 'SignatureElementProxy', [
  \ javaapi#field(1,1,'CacheSignedNodes', 'boolean'),
  \ javaapi#field(1,1,'OBJECT_URI', 'String'),
  \ javaapi#field(1,1,'MANIFEST_URI', 'String'),
  \ javaapi#method(0,0,'Reference(', 'Document, String, String, Manifest, Transforms, String) throws XMLSignatureException', ''),
  \ javaapi#method(0,0,'Reference(', 'Element, String, Manifest) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'getMessageDigestAlgorithm(', ') throws XMLSignatureException', 'MessageDigestAlgorithm'),
  \ javaapi#method(0,1,'setURI(', 'String)', 'void'),
  \ javaapi#method(0,1,'getURI(', ')', 'String'),
  \ javaapi#method(0,1,'setId(', 'String)', 'void'),
  \ javaapi#method(0,1,'getId(', ')', 'String'),
  \ javaapi#method(0,1,'setType(', 'String)', 'void'),
  \ javaapi#method(0,1,'getType(', ')', 'String'),
  \ javaapi#method(0,1,'typeIsReferenceToObject(', ')', 'boolean'),
  \ javaapi#method(0,1,'typeIsReferenceToManifest(', ')', 'boolean'),
  \ javaapi#method(0,1,'generateDigestValue(', ') throws XMLSignatureException, ReferenceNotInitializedException', 'void'),
  \ javaapi#method(0,1,'getContentsBeforeTransformation(', ') throws ReferenceNotInitializedException', 'XMLSignatureInput'),
  \ javaapi#method(0,1,'getTransformsInput(', ') throws ReferenceNotInitializedException', 'XMLSignatureInput'),
  \ javaapi#method(0,1,'getContentsAfterTransformation(', ') throws XMLSignatureException', 'XMLSignatureInput'),
  \ javaapi#method(0,1,'getNodesetBeforeFirstCanonicalization(', ') throws XMLSignatureException', 'XMLSignatureInput'),
  \ javaapi#method(0,1,'getHTMLRepresentation(', ') throws XMLSignatureException', 'String'),
  \ javaapi#method(0,1,'getTransformsOutput(', ')', 'XMLSignatureInput'),
  \ javaapi#method(0,0,'dereferenceURIandPerformTransforms(', 'OutputStream) throws XMLSignatureException', 'XMLSignatureInput'),
  \ javaapi#method(0,1,'getTransforms(', ') throws XMLSignatureException, InvalidTransformException, TransformationException, XMLSecurityException', 'Transforms'),
  \ javaapi#method(0,1,'getReferencedBytes(', ') throws ReferenceNotInitializedException, XMLSignatureException', 'byte[]'),
  \ javaapi#method(0,1,'getDigestValue(', ') throws Base64DecodingException, XMLSecurityException', 'byte[]'),
  \ javaapi#method(0,1,'verify(', ') throws ReferenceNotInitializedException, XMLSecurityException', 'boolean'),
  \ javaapi#method(0,1,'getBaseLocalName(', ')', 'String'),
  \ ])

call javaapi#class('ReferenceNotInitializedException', 'XMLSignatureException', [
  \ javaapi#method(0,1,'ReferenceNotInitializedException(', ')', ''),
  \ javaapi#method(0,1,'ReferenceNotInitializedException(', 'String)', ''),
  \ javaapi#method(0,1,'ReferenceNotInitializedException(', 'String, Object[])', ''),
  \ javaapi#method(0,1,'ReferenceNotInitializedException(', 'String, Exception)', ''),
  \ javaapi#method(0,1,'ReferenceNotInitializedException(', 'String, Object[], Exception)', ''),
  \ ])

call javaapi#class('SignatureProperties', 'SignatureElementProxy', [
  \ javaapi#method(0,1,'SignatureProperties(', 'Document)', ''),
  \ javaapi#method(0,1,'SignatureProperties(', 'Element, String) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'getLength(', ')', 'int'),
  \ javaapi#method(0,1,'item(', 'int) throws XMLSignatureException', 'SignatureProperty'),
  \ javaapi#method(0,1,'setId(', 'String)', 'void'),
  \ javaapi#method(0,1,'getId(', ')', 'String'),
  \ javaapi#method(0,1,'addSignatureProperty(', 'SignatureProperty)', 'void'),
  \ javaapi#method(0,1,'getBaseLocalName(', ')', 'String'),
  \ ])

call javaapi#class('SignatureProperty', 'SignatureElementProxy', [
  \ javaapi#method(0,1,'SignatureProperty(', 'Document, String)', ''),
  \ javaapi#method(0,1,'SignatureProperty(', 'Document, String, String)', ''),
  \ javaapi#method(0,1,'SignatureProperty(', 'Element, String) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'setId(', 'String)', 'void'),
  \ javaapi#method(0,1,'getId(', ')', 'String'),
  \ javaapi#method(0,1,'setTarget(', 'String)', 'void'),
  \ javaapi#method(0,1,'getTarget(', ')', 'String'),
  \ javaapi#method(0,1,'appendChild(', 'Node)', 'Node'),
  \ javaapi#method(0,1,'getBaseLocalName(', ')', 'String'),
  \ ])

call javaapi#class('SignedInfo', 'Manifest', [
  \ javaapi#method(0,1,'SignedInfo(', 'Document) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'SignedInfo(', 'Document, String, String) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'SignedInfo(', 'Document, String, int, String) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'SignedInfo(', 'Document, Element, Element) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'SignedInfo(', 'Element, String) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'verify(', ') throws MissingResourceFailureException, XMLSecurityException', 'boolean'),
  \ javaapi#method(0,1,'verify(', 'boolean) throws MissingResourceFailureException, XMLSecurityException', 'boolean'),
  \ javaapi#method(0,1,'getCanonicalizedOctetStream(', ') throws CanonicalizationException, InvalidCanonicalizerException, XMLSecurityException', 'byte[]'),
  \ javaapi#method(0,1,'signInOctectStream(', 'OutputStream) throws CanonicalizationException, InvalidCanonicalizerException, XMLSecurityException', 'void'),
  \ javaapi#method(0,1,'getCanonicalizationMethodURI(', ')', 'String'),
  \ javaapi#method(0,1,'getSignatureMethodURI(', ')', 'String'),
  \ javaapi#method(0,1,'getSignatureMethodElement(', ')', 'Element'),
  \ javaapi#method(0,1,'createSecretKey(', 'byte[])', 'SecretKey'),
  \ javaapi#method(0,0,'getSignatureAlgorithm(', ')', 'SignatureAlgorithm'),
  \ javaapi#method(0,1,'getBaseLocalName(', ')', 'String'),
  \ javaapi#method(0,1,'getInclusiveNamespaces(', ')', 'String'),
  \ ])

call javaapi#class('XMLSignature', 'SignatureElementProxy', [
  \ javaapi#field(1,1,'ALGO_ID_MAC_HMAC_SHA1', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_SIGNATURE_DSA', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_SIGNATURE_RSA', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_SIGNATURE_RSA_SHA1', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_SIGNATURE_NOT_RECOMMENDED_RSA_MD5', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_SIGNATURE_RSA_RIPEMD160', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_SIGNATURE_RSA_SHA256', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_SIGNATURE_RSA_SHA384', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_SIGNATURE_RSA_SHA512', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_MAC_HMAC_NOT_RECOMMENDED_MD5', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_MAC_HMAC_RIPEMD160', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_MAC_HMAC_SHA256', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_MAC_HMAC_SHA384', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_MAC_HMAC_SHA512', 'String'),
  \ javaapi#field(1,1,'ALGO_ID_SIGNATURE_ECDSA_SHA1', 'String'),
  \ javaapi#method(0,1,'XMLSignature(', 'Document, String, String) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'XMLSignature(', 'Document, String, String, int) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'XMLSignature(', 'Document, String, String, String) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'XMLSignature(', 'Document, String, String, int, String) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'XMLSignature(', 'Document, String, Element, Element) throws XMLSecurityException', ''),
  \ javaapi#method(0,1,'XMLSignature(', 'Element, String) throws XMLSignatureException, XMLSecurityException', ''),
  \ javaapi#method(0,1,'setId(', 'String)', 'void'),
  \ javaapi#method(0,1,'getId(', ')', 'String'),
  \ javaapi#method(0,1,'getSignedInfo(', ')', 'SignedInfo'),
  \ javaapi#method(0,1,'getSignatureValue(', ') throws XMLSignatureException', 'byte[]'),
  \ javaapi#method(0,1,'getKeyInfo(', ')', 'KeyInfo'),
  \ javaapi#method(0,1,'appendObject(', 'ObjectContainer) throws XMLSignatureException', 'void'),
  \ javaapi#method(0,1,'getObjectItem(', 'int)', 'ObjectContainer'),
  \ javaapi#method(0,1,'getObjectLength(', ')', 'int'),
  \ javaapi#method(0,1,'sign(', 'Key) throws XMLSignatureException', 'void'),
  \ javaapi#method(0,1,'addResourceResolver(', 'ResourceResolver)', 'void'),
  \ javaapi#method(0,1,'addResourceResolver(', 'ResourceResolverSpi)', 'void'),
  \ javaapi#method(0,1,'checkSignatureValue(', 'X509Certificate) throws XMLSignatureException', 'boolean'),
  \ javaapi#method(0,1,'checkSignatureValue(', 'Key) throws XMLSignatureException', 'boolean'),
  \ javaapi#method(0,1,'addDocument(', 'String, Transforms, String, String, String) throws XMLSignatureException', 'void'),
  \ javaapi#method(0,1,'addDocument(', 'String, Transforms, String) throws XMLSignatureException', 'void'),
  \ javaapi#method(0,1,'addDocument(', 'String, Transforms) throws XMLSignatureException', 'void'),
  \ javaapi#method(0,1,'addDocument(', 'String) throws XMLSignatureException', 'void'),
  \ javaapi#method(0,1,'addKeyInfo(', 'X509Certificate) throws XMLSecurityException', 'void'),
  \ javaapi#method(0,1,'addKeyInfo(', 'PublicKey)', 'void'),
  \ javaapi#method(0,1,'createSecretKey(', 'byte[])', 'SecretKey'),
  \ javaapi#method(0,1,'setFollowNestedManifests(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getBaseLocalName(', ')', 'String'),
  \ ])

call javaapi#class('XMLSignatureException', 'XMLSecurityException', [
  \ javaapi#method(0,1,'XMLSignatureException(', ')', ''),
  \ javaapi#method(0,1,'XMLSignatureException(', 'String)', ''),
  \ javaapi#method(0,1,'XMLSignatureException(', 'String, Object[])', ''),
  \ javaapi#method(0,1,'XMLSignatureException(', 'String, Exception)', ''),
  \ javaapi#method(0,1,'XMLSignatureException(', 'String, Object[], Exception)', ''),
  \ ])

call javaapi#class('XMLSignatureInput', 'Cloneable', [
  \ javaapi#method(0,1,'isNeedsToBeExpanded(', ')', 'boolean'),
  \ javaapi#method(0,1,'setNeedsToBeExpanded(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'XMLSignatureInput(', 'byte[])', ''),
  \ javaapi#method(0,1,'XMLSignatureInput(', 'InputStream)', ''),
  \ javaapi#method(0,1,'XMLSignatureInput(', 'String)', ''),
  \ javaapi#method(0,1,'XMLSignatureInput(', 'String, String) throws UnsupportedEncodingException', ''),
  \ javaapi#method(0,1,'XMLSignatureInput(', 'Node)', ''),
  \ javaapi#method(0,1,'XMLSignatureInput(', 'Set)', ''),
  \ javaapi#method(0,1,'getNodeSet(', ') throws CanonicalizationException, ParserConfigurationException, IOException, SAXException', 'Set'),
  \ javaapi#method(0,1,'getNodeSet(', 'boolean) throws ParserConfigurationException, IOException, SAXException, CanonicalizationException', 'Set'),
  \ javaapi#method(0,1,'getOctetStream(', ') throws IOException', 'InputStream'),
  \ javaapi#method(0,1,'getOctetStreamReal(', ')', 'InputStream'),
  \ javaapi#method(0,1,'getBytes(', ') throws IOException, CanonicalizationException', 'byte[]'),
  \ javaapi#method(0,1,'isNodeSet(', ')', 'boolean'),
  \ javaapi#method(0,1,'isElement(', ')', 'boolean'),
  \ javaapi#method(0,1,'isOctetStream(', ')', 'boolean'),
  \ javaapi#method(0,1,'isOutputStreamSet(', ')', 'boolean'),
  \ javaapi#method(0,1,'isByteArray(', ')', 'boolean'),
  \ javaapi#method(0,1,'isInitialized(', ')', 'boolean'),
  \ javaapi#method(0,1,'getMIMEType(', ')', 'String'),
  \ javaapi#method(0,1,'setMIMEType(', 'String)', 'void'),
  \ javaapi#method(0,1,'getSourceURI(', ')', 'String'),
  \ javaapi#method(0,1,'setSourceURI(', 'String)', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'getHTMLRepresentation(', ') throws XMLSignatureException', 'String'),
  \ javaapi#method(0,1,'getHTMLRepresentation(', 'Set) throws XMLSignatureException', 'String'),
  \ javaapi#method(0,1,'getExcludeNode(', ')', 'Node'),
  \ javaapi#method(0,1,'setExcludeNode(', 'Node)', 'void'),
  \ javaapi#method(0,1,'getSubNode(', ')', 'Node'),
  \ javaapi#method(0,1,'isExcludeComments(', ')', 'boolean'),
  \ javaapi#method(0,1,'setExcludeComments(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'updateOutputStream(', 'OutputStream) throws CanonicalizationException, IOException', 'void'),
  \ javaapi#method(0,1,'updateOutputStream(', 'OutputStream, boolean) throws CanonicalizationException, IOException', 'void'),
  \ javaapi#method(0,1,'setOutputStream(', 'OutputStream)', 'void'),
  \ javaapi#method(0,0,'getResetableInputStream(', ') throws IOException', 'InputStream'),
  \ javaapi#method(0,1,'addNodeFilter(', 'NodeFilter)', 'void'),
  \ javaapi#method(0,1,'getNodeFilters(', ')', 'List'),
  \ javaapi#method(0,1,'setNodeSet(', 'boolean)', 'void'),
  \ ])

call javaapi#class('XMLSignatureInputDebugger', '', [
  \ javaapi#method(0,1,'XMLSignatureInputDebugger(', 'XMLSignatureInput)', ''),
  \ javaapi#method(0,1,'XMLSignatureInputDebugger(', 'XMLSignatureInput, Set)', ''),
  \ javaapi#method(0,1,'getHTMLRepresentation(', ') throws XMLSignatureException', 'String'),
  \ ])

