call javaapi#namespace('com.sun.xml.internal.ws.model.wsdl')

call javaapi#class('AbstractExtensibleImpl', 'AbstractObjectImpl', [
  \ javaapi#field(0,0,'extensions', 'WSDLExtension>'),
  \ javaapi#field(0,0,'notUnderstoodExtensions', 'UnknownWSDLExtension>'),
  \ javaapi#method(0,0,'AbstractExtensibleImpl(', 'XMLStreamReader)', ''),
  \ javaapi#method(0,0,'AbstractExtensibleImpl(', 'String, int)', ''),
  \ javaapi#method(0,1,'getExtensions(', ')', 'WSDLExtension>'),
  \ javaapi#method(0,1,'getExtensions(', 'Class<T>)', 'Iterable<T>'),
  \ javaapi#method(0,1,'getExtension(', 'Class<T>)', 'T'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ ])

call javaapi#class('AbstractFeaturedObjectImpl', 'AbstractExtensibleImpl', [
  \ javaapi#field(0,0,'features', 'WebServiceFeatureList'),
  \ javaapi#method(0,0,'AbstractFeaturedObjectImpl(', 'XMLStreamReader)', ''),
  \ javaapi#method(0,0,'AbstractFeaturedObjectImpl(', 'String, int)', ''),
  \ javaapi#method(0,1,'addFeature(', 'WebServiceFeature)', 'void'),
  \ javaapi#method(0,1,'getFeatures(', ')', 'WebServiceFeatureList'),
  \ javaapi#method(0,1,'getFeature(', 'String)', 'WebServiceFeature'),
  \ javaapi#method(0,1,'getFeature(', 'Class<F>)', 'F'),
  \ javaapi#method(0,1,'getFeatures(', ')', 'WSFeatureList'),
  \ ])

call javaapi#class('AbstractObjectImpl', 'WSDLObject', [
  \ javaapi#method(0,1,'getLocation(', ')', 'Locator'),
  \ ])

call javaapi#class('WSDLBoundFaultImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,1,'WSDLBoundFaultImpl(', 'XMLStreamReader, String, WSDLBoundOperationImpl)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getQName(', ')', 'QName'),
  \ javaapi#method(0,1,'getFault(', ')', 'WSDLFault'),
  \ javaapi#method(0,1,'getBoundOperation(', ')', 'WSDLBoundOperation'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ ])

call javaapi#class('WSDLBoundOperationImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,1,'WSDLBoundOperationImpl(', 'XMLStreamReader, WSDLBoundPortTypeImpl, QName)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'QName'),
  \ javaapi#method(0,1,'getSOAPAction(', ')', 'String'),
  \ javaapi#method(0,1,'setSoapAction(', 'String)', 'void'),
  \ javaapi#method(0,1,'getPart(', 'String, Mode)', 'WSDLPartImpl'),
  \ javaapi#method(0,1,'addPart(', 'WSDLPartImpl, Mode)', 'void'),
  \ javaapi#method(0,1,'getInputParts(', ')', 'ParameterBinding>'),
  \ javaapi#method(0,1,'getOutputParts(', ')', 'ParameterBinding>'),
  \ javaapi#method(0,1,'getFaultParts(', ')', 'ParameterBinding>'),
  \ javaapi#method(0,1,'getInParts(', ')', 'WSDLPart>'),
  \ javaapi#method(0,1,'getOutParts(', ')', 'WSDLPart>'),
  \ javaapi#method(0,1,'getFaults(', ')', 'WSDLBoundFaultImpl>'),
  \ javaapi#method(0,1,'addFault(', 'WSDLBoundFaultImpl)', 'void'),
  \ javaapi#method(0,1,'getInputMimeTypes(', ')', 'String>'),
  \ javaapi#method(0,1,'getOutputMimeTypes(', ')', 'String>'),
  \ javaapi#method(0,1,'getFaultMimeTypes(', ')', 'String>'),
  \ javaapi#method(0,1,'getInputBinding(', 'String)', 'ParameterBinding'),
  \ javaapi#method(0,1,'getOutputBinding(', 'String)', 'ParameterBinding'),
  \ javaapi#method(0,1,'getFaultBinding(', 'String)', 'ParameterBinding'),
  \ javaapi#method(0,1,'getMimeTypeForInputPart(', 'String)', 'String'),
  \ javaapi#method(0,1,'getMimeTypeForOutputPart(', 'String)', 'String'),
  \ javaapi#method(0,1,'getMimeTypeForFaultPart(', 'String)', 'String'),
  \ javaapi#method(0,1,'getOperation(', ')', 'WSDLOperationImpl'),
  \ javaapi#method(0,1,'getBoundPortType(', ')', 'WSDLBoundPortType'),
  \ javaapi#method(0,1,'setInputExplicitBodyParts(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'setOutputExplicitBodyParts(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'setFaultExplicitBodyParts(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'setStyle(', 'Style)', 'void'),
  \ javaapi#method(0,1,'getReqPayloadName(', ')', 'QName'),
  \ javaapi#method(0,1,'getResPayloadName(', ')', 'QName'),
  \ javaapi#method(0,1,'getRequestNamespace(', ')', 'String'),
  \ javaapi#method(0,1,'setRequestNamespace(', 'String)', 'void'),
  \ javaapi#method(0,1,'getResponseNamespace(', ')', 'String'),
  \ javaapi#method(0,1,'setResponseNamespace(', 'String)', 'void'),
  \ javaapi#method(0,1,'setAnonymous(', 'ANONYMOUS)', 'void'),
  \ javaapi#method(0,1,'getAnonymous(', ')', 'ANONYMOUS'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,1,'getFaults(', ')', 'Iterable'),
  \ javaapi#method(0,1,'getPart(', 'String, Mode)', 'WSDLPart'),
  \ javaapi#method(0,1,'getOperation(', ')', 'WSDLOperation'),
  \ ])

call javaapi#class('WSDLBoundPortTypeImpl', 'AbstractFeaturedObjectImpl', [
  \ javaapi#method(0,1,'WSDLBoundPortTypeImpl(', 'XMLStreamReader, WSDLModelImpl, QName, QName)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'QName'),
  \ javaapi#method(0,1,'getOwner(', ')', 'WSDLModelImpl'),
  \ javaapi#method(0,1,'get(', 'QName)', 'WSDLBoundOperationImpl'),
  \ javaapi#method(0,1,'put(', 'QName, WSDLBoundOperationImpl)', 'void'),
  \ javaapi#method(0,1,'getPortTypeName(', ')', 'QName'),
  \ javaapi#method(0,1,'getPortType(', ')', 'WSDLPortTypeImpl'),
  \ javaapi#method(0,1,'getBindingOperations(', ')', 'WSDLBoundOperationImpl>'),
  \ javaapi#method(0,1,'getBindingId(', ')', 'BindingID'),
  \ javaapi#method(0,1,'setBindingId(', 'BindingID)', 'void'),
  \ javaapi#method(0,1,'setStyle(', 'Style)', 'void'),
  \ javaapi#method(0,1,'getStyle(', ')', 'Style'),
  \ javaapi#method(0,1,'isRpcLit(', ')', 'boolean'),
  \ javaapi#method(0,1,'isDoclit(', ')', 'boolean'),
  \ javaapi#method(0,1,'getBinding(', 'QName, String, Mode)', 'ParameterBinding'),
  \ javaapi#method(0,1,'getMimeType(', 'QName, String, Mode)', 'String'),
  \ javaapi#method(0,1,'getOperation(', 'String, String)', 'WSDLBoundOperationImpl'),
  \ javaapi#method(0,1,'enableMTOM(', ')', 'void'),
  \ javaapi#method(0,1,'isMTOMEnabled(', ')', 'boolean'),
  \ javaapi#method(0,1,'getSOAPVersion(', ')', 'SOAPVersion'),
  \ javaapi#method(0,1,'getFeature(', 'Class)', 'WebServiceFeature'),
  \ javaapi#method(0,1,'getFeatures(', ')', 'WebServiceFeatureList'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,1,'getOperation(', 'String, String)', 'WSDLBoundOperation'),
  \ javaapi#method(0,1,'getPortType(', ')', 'WSDLPortType'),
  \ javaapi#method(0,1,'get(', 'QName)', 'WSDLBoundOperation'),
  \ javaapi#method(0,1,'getOwner(', ')', 'WSDLModel'),
  \ ])

call javaapi#class('WSDLFaultImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,1,'WSDLFaultImpl(', 'XMLStreamReader, String, QName, WSDLOperationImpl)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getMessage(', ')', 'WSDLMessageImpl'),
  \ javaapi#method(0,1,'getOperation(', ')', 'WSDLOperation'),
  \ javaapi#method(0,1,'getQName(', ')', 'QName'),
  \ javaapi#method(0,1,'getAction(', ')', 'String'),
  \ javaapi#method(0,1,'setAction(', 'String)', 'void'),
  \ javaapi#method(0,1,'isDefaultAction(', ')', 'boolean'),
  \ javaapi#method(0,1,'setDefaultAction(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,1,'getMessage(', ')', 'WSDLMessage'),
  \ ])

call javaapi#class('WSDLInputImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,1,'WSDLInputImpl(', 'XMLStreamReader, String, QName, WSDLOperationImpl)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getMessage(', ')', 'WSDLMessage'),
  \ javaapi#method(0,1,'getAction(', ')', 'String'),
  \ javaapi#method(0,1,'getOperation(', ')', 'WSDLOperation'),
  \ javaapi#method(0,1,'getQName(', ')', 'QName'),
  \ javaapi#method(0,1,'setAction(', 'String)', 'void'),
  \ javaapi#method(0,1,'isDefaultAction(', ')', 'boolean'),
  \ javaapi#method(0,1,'setDefaultAction(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ ])

call javaapi#class('WSDLMessageImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,1,'WSDLMessageImpl(', 'XMLStreamReader, QName)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'QName'),
  \ javaapi#method(0,1,'add(', 'WSDLPartImpl)', 'void'),
  \ javaapi#method(0,1,'parts(', ')', 'WSDLPartImpl>'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ ])

call javaapi#class('WSDLModelImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,1,'WSDLModelImpl(', 'String)', ''),
  \ javaapi#method(0,1,'WSDLModelImpl(', ')', ''),
  \ javaapi#method(0,1,'addMessage(', 'WSDLMessageImpl)', 'void'),
  \ javaapi#method(0,1,'getMessage(', 'QName)', 'WSDLMessageImpl'),
  \ javaapi#method(0,1,'addPortType(', 'WSDLPortTypeImpl)', 'void'),
  \ javaapi#method(0,1,'getPortType(', 'QName)', 'WSDLPortTypeImpl'),
  \ javaapi#method(0,1,'addBinding(', 'WSDLBoundPortTypeImpl)', 'void'),
  \ javaapi#method(0,1,'getBinding(', 'QName)', 'WSDLBoundPortTypeImpl'),
  \ javaapi#method(0,1,'addService(', 'WSDLServiceImpl)', 'void'),
  \ javaapi#method(0,1,'getService(', 'QName)', 'WSDLServiceImpl'),
  \ javaapi#method(0,1,'getMessages(', ')', 'WSDLMessageImpl>'),
  \ javaapi#method(0,1,'getPortTypes(', ')', 'WSDLPortTypeImpl>'),
  \ javaapi#method(0,1,'getBindings(', ')', 'WSDLBoundPortType>'),
  \ javaapi#method(0,1,'getServices(', ')', 'WSDLServiceImpl>'),
  \ javaapi#method(0,1,'getFirstServiceName(', ')', 'QName'),
  \ javaapi#method(0,1,'getFirstPortName(', ')', 'QName'),
  \ javaapi#method(0,1,'getMatchingPort(', 'QName, QName)', 'WSDLPortImpl'),
  \ javaapi#method(0,1,'getBinding(', 'QName, QName)', 'WSDLBoundPortTypeImpl'),
  \ javaapi#method(0,1,'getPolicyMap(', ')', 'PolicyMap'),
  \ javaapi#method(0,1,'setPolicyMap(', 'PolicyMap)', 'void'),
  \ javaapi#method(0,1,'freeze(', ')', 'void'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,1,'getService(', 'QName)', 'WSDLService'),
  \ javaapi#method(0,1,'getBinding(', 'QName, QName)', 'WSDLBoundPortType'),
  \ javaapi#method(0,1,'getBinding(', 'QName)', 'WSDLBoundPortType'),
  \ javaapi#method(0,1,'getPortType(', 'QName)', 'WSDLPortType'),
  \ ])

call javaapi#class('WSDLOperationImpl', 'AbstractExtensibleImpl', [
  \ javaapi#field(0,0,'messages', 'WSDLMessageImpl>'),
  \ javaapi#method(0,1,'WSDLOperationImpl(', 'XMLStreamReader, WSDLPortTypeImpl, QName)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'QName'),
  \ javaapi#method(0,1,'getParameterOrder(', ')', 'String'),
  \ javaapi#method(0,1,'setParameterOrder(', 'String)', 'void'),
  \ javaapi#method(0,1,'getInput(', ')', 'WSDLInputImpl'),
  \ javaapi#method(0,1,'setInput(', 'WSDLInputImpl)', 'void'),
  \ javaapi#method(0,1,'getOutput(', ')', 'WSDLOutputImpl'),
  \ javaapi#method(0,1,'isOneWay(', ')', 'boolean'),
  \ javaapi#method(0,1,'setOutput(', 'WSDLOutputImpl)', 'void'),
  \ javaapi#method(0,1,'getFaults(', ')', 'WSDLFaultImpl>'),
  \ javaapi#method(0,1,'getFault(', 'QName)', 'WSDLFault'),
  \ javaapi#method(0,1,'getPortTypeName(', ')', 'QName'),
  \ javaapi#method(0,1,'addFault(', 'WSDLFaultImpl)', 'void'),
  \ javaapi#method(0,1,'freez(', 'WSDLModelImpl)', 'void'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,1,'getOutput(', ')', 'WSDLOutput'),
  \ javaapi#method(0,1,'getInput(', ')', 'WSDLInput'),
  \ ])

call javaapi#class('WSDLOutputImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,1,'WSDLOutputImpl(', 'XMLStreamReader, String, QName, WSDLOperationImpl)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getMessage(', ')', 'WSDLMessage'),
  \ javaapi#method(0,1,'getAction(', ')', 'String'),
  \ javaapi#method(0,1,'isDefaultAction(', ')', 'boolean'),
  \ javaapi#method(0,1,'setDefaultAction(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getOperation(', ')', 'WSDLOperation'),
  \ javaapi#method(0,1,'getQName(', ')', 'QName'),
  \ javaapi#method(0,1,'setAction(', 'String)', 'void'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ ])

call javaapi#class('WSDLPartDescriptorImpl', 'AbstractObjectImpl', [
  \ javaapi#method(0,1,'WSDLPartDescriptorImpl(', 'XMLStreamReader, QName, WSDLDescriptorKind)', ''),
  \ javaapi#method(0,1,'name(', ')', 'QName'),
  \ javaapi#method(0,1,'type(', ')', 'WSDLDescriptorKind'),
  \ ])

call javaapi#class('WSDLPartImpl', 'AbstractObjectImpl', [
  \ javaapi#method(0,1,'WSDLPartImpl(', 'XMLStreamReader, String, int, WSDLPartDescriptor)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getBinding(', ')', 'ParameterBinding'),
  \ javaapi#method(0,1,'setBinding(', 'ParameterBinding)', 'void'),
  \ javaapi#method(0,1,'getIndex(', ')', 'int'),
  \ javaapi#method(0,1,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,1,'getDescriptor(', ')', 'WSDLPartDescriptor'),
  \ ])

call javaapi#class('WSDLPortImpl', 'AbstractFeaturedObjectImpl', [
  \ javaapi#method(0,1,'WSDLPortImpl(', 'XMLStreamReader, WSDLServiceImpl, QName, QName)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'QName'),
  \ javaapi#method(0,1,'getBindingName(', ')', 'QName'),
  \ javaapi#method(0,1,'getAddress(', ')', 'EndpointAddress'),
  \ javaapi#method(0,1,'getOwner(', ')', 'WSDLServiceImpl'),
  \ javaapi#method(0,1,'setAddress(', 'EndpointAddress)', 'void'),
  \ javaapi#method(0,1,'setEPR(', 'WSEndpointReference)', 'void'),
  \ javaapi#method(0,1,'getEPR(', ')', 'WSEndpointReference'),
  \ javaapi#method(0,1,'getBinding(', ')', 'WSDLBoundPortTypeImpl'),
  \ javaapi#method(0,1,'getSOAPVersion(', ')', 'SOAPVersion'),
  \ javaapi#method(0,1,'getFeature(', 'Class)', 'WebServiceFeature'),
  \ javaapi#method(0,1,'getFeatures(', ')', 'WebServiceFeatureList'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,1,'getOwner(', ')', 'WSDLService'),
  \ javaapi#method(0,1,'getBinding(', ')', 'WSDLBoundPortType'),
  \ ])

call javaapi#class('WSDLPortTypeImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,1,'WSDLPortTypeImpl(', 'XMLStreamReader, WSDLModelImpl, QName)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'QName'),
  \ javaapi#method(0,1,'get(', 'String)', 'WSDLOperationImpl'),
  \ javaapi#method(0,1,'getOperations(', ')', 'WSDLOperationImpl>'),
  \ javaapi#method(0,1,'put(', 'String, WSDLOperationImpl)', 'void'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,1,'get(', 'String)', 'WSDLOperation'),
  \ ])

call javaapi#class('WSDLProperties', 'PropertySet', [
  \ javaapi#method(0,1,'WSDLProperties(', 'WSDLPort)', ''),
  \ javaapi#method(0,1,'getWSDLService(', ')', 'QName'),
  \ javaapi#method(0,1,'getWSDLPort(', ')', 'QName'),
  \ javaapi#method(0,1,'getWSDLPortType(', ')', 'QName'),
  \ javaapi#method(0,0,'getPropertyMap(', ')', 'PropertyMap'),
  \ ])

call javaapi#class('WSDLServiceImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,1,'WSDLServiceImpl(', 'XMLStreamReader, WSDLModelImpl, QName)', ''),
  \ javaapi#method(0,1,'getParent(', ')', 'WSDLModelImpl'),
  \ javaapi#method(0,1,'getName(', ')', 'QName'),
  \ javaapi#method(0,1,'get(', 'QName)', 'WSDLPortImpl'),
  \ javaapi#method(0,1,'getFirstPort(', ')', 'WSDLPort'),
  \ javaapi#method(0,1,'getPorts(', ')', 'WSDLPortImpl>'),
  \ javaapi#method(0,1,'getMatchingPort(', 'QName)', 'WSDLPortImpl'),
  \ javaapi#method(0,1,'put(', 'QName, WSDLPortImpl)', 'void'),
  \ javaapi#method(0,1,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,1,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,1,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,1,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,1,'get(', 'QName)', 'WSDLPort'),
  \ javaapi#method(0,1,'getParent(', ')', 'WSDLModel'),
  \ ])

