call javaapi#namespace('com.sun.xml.internal.org.jvnet.fastinfoset.sax.helpers')

call javaapi#class('EncodingAlgorithmAttributesImpl', 'EncodingAlgorithmAttributes', [
  \ javaapi#method(0,1,'EncodingAlgorithmAttributesImpl(', ')', ''),
  \ javaapi#method(0,1,'EncodingAlgorithmAttributesImpl(', 'Attributes)', ''),
  \ javaapi#method(0,1,'EncodingAlgorithmAttributesImpl(', 'Map, Attributes)', ''),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ javaapi#method(0,1,'addAttribute(', 'String, String, String, String, String)', 'void'),
  \ javaapi#method(0,1,'addAttribute(', 'String, String, String, String, String, boolean, String)', 'void'),
  \ javaapi#method(0,1,'addAttributeWithBuiltInAlgorithmData(', 'String, String, String, int, Object)', 'void'),
  \ javaapi#method(0,1,'addAttributeWithAlgorithmData(', 'String, String, String, String, int, Object)', 'void'),
  \ javaapi#method(0,1,'replaceWithAttributeAlgorithmData(', 'int, String, int, Object)', 'void'),
  \ javaapi#method(0,1,'setAttributes(', 'Attributes)', 'void'),
  \ javaapi#method(0,1,'setAttributes(', 'EncodingAlgorithmAttributes)', 'void'),
  \ javaapi#method(0,1,'getLength(', ')', 'int'),
  \ javaapi#method(0,1,'getLocalName(', 'int)', 'String'),
  \ javaapi#method(0,1,'getQName(', 'int)', 'String'),
  \ javaapi#method(0,1,'getType(', 'int)', 'String'),
  \ javaapi#method(0,1,'getURI(', 'int)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'int)', 'String'),
  \ javaapi#method(0,1,'getIndex(', 'String)', 'int'),
  \ javaapi#method(0,1,'getType(', 'String)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'String)', 'String'),
  \ javaapi#method(0,1,'getIndex(', 'String, String)', 'int'),
  \ javaapi#method(0,1,'getType(', 'String, String)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'String, String)', 'String'),
  \ javaapi#method(0,1,'getAlgorithmURI(', 'int)', 'String'),
  \ javaapi#method(0,1,'getAlgorithmIndex(', 'int)', 'int'),
  \ javaapi#method(0,1,'getAlgorithmData(', 'int)', 'Object'),
  \ javaapi#method(0,1,'getAlpababet(', 'int)', 'String'),
  \ javaapi#method(0,1,'getToIndex(', 'int)', 'boolean'),
  \ ])

call javaapi#class('FastInfosetDefaultHandler', 'DefaultHandler', [
  \ javaapi#method(0,1,'FastInfosetDefaultHandler(', ')', ''),
  \ javaapi#method(0,1,'comment(', 'char[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,1,'startCDATA(', ') throws SAXException', 'void'),
  \ javaapi#method(0,1,'endCDATA(', ') throws SAXException', 'void'),
  \ javaapi#method(0,1,'startDTD(', 'String, String, String) throws SAXException', 'void'),
  \ javaapi#method(0,1,'endDTD(', ') throws SAXException', 'void'),
  \ javaapi#method(0,1,'startEntity(', 'String) throws SAXException', 'void'),
  \ javaapi#method(0,1,'endEntity(', 'String) throws SAXException', 'void'),
  \ javaapi#method(0,1,'octets(', 'String, int, byte[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,1,'object(', 'String, int, Object) throws SAXException', 'void'),
  \ javaapi#method(0,1,'booleans(', 'boolean[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,1,'bytes(', 'byte[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,1,'shorts(', 'short[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,1,'ints(', 'int[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,1,'longs(', 'long[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,1,'floats(', 'float[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,1,'doubles(', 'double[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,1,'uuids(', 'long[], int, int) throws SAXException', 'void'),
  \ ])

