call javaapi#namespace('com.sun.xml.internal.stream.dtd.nonvalidating')

call javaapi#class('DTDGrammar', '', [
  \ javaapi#field(1,1,'TOP_LEVEL_SCOPE', 'int'),
  \ javaapi#field(0,0,'fDTDSource', 'XMLDTDSource'),
  \ javaapi#field(0,0,'fDTDContentModelSource', 'XMLDTDContentModelSource'),
  \ javaapi#field(0,0,'fCurrentElementIndex', 'int'),
  \ javaapi#field(0,0,'fCurrentAttributeIndex', 'int'),
  \ javaapi#field(0,0,'fReadingExternalDTD', 'boolean'),
  \ javaapi#field(0,0,'fAttributeDecl', 'XMLAttributeDecl'),
  \ javaapi#method(0,1,'DTDGrammar(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'getAttributeDeclIndex(', 'int, String)', 'int'),
  \ javaapi#method(0,1,'startDTD(', 'XMLLocator, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'elementDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'attributeDecl(', 'String, String, String, String[], String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'getSymbolTable(', ')', 'SymbolTable'),
  \ javaapi#method(0,1,'getFirstElementDeclIndex(', ')', 'int'),
  \ javaapi#method(0,1,'getNextElementDeclIndex(', 'int)', 'int'),
  \ javaapi#method(0,1,'getElementDeclIndex(', 'String)', 'int'),
  \ javaapi#method(0,1,'getElementDeclIndex(', 'QName)', 'int'),
  \ javaapi#method(0,1,'getContentSpecType(', 'int)', 'short'),
  \ javaapi#method(0,1,'getElementDecl(', 'int, XMLElementDecl)', 'boolean'),
  \ javaapi#method(0,1,'getFirstAttributeDeclIndex(', 'int)', 'int'),
  \ javaapi#method(0,1,'getNextAttributeDeclIndex(', 'int)', 'int'),
  \ javaapi#method(0,1,'getAttributeDecl(', 'int, XMLAttributeDecl)', 'boolean'),
  \ javaapi#method(0,1,'isCDATAAttribute(', 'QName, QName)', 'boolean'),
  \ javaapi#method(0,1,'printElements(', ')', 'void'),
  \ javaapi#method(0,1,'printAttributes(', 'int)', 'void'),
  \ javaapi#method(0,0,'createElementDecl(', ')', 'int'),
  \ javaapi#method(0,0,'setElementDecl(', 'int, XMLElementDecl)', 'void'),
  \ javaapi#method(0,0,'setFirstAttributeDeclIndex(', 'int, int)', 'void'),
  \ javaapi#method(0,0,'createAttributeDecl(', ')', 'int'),
  \ javaapi#method(0,0,'setAttributeDecl(', 'int, int, XMLAttributeDecl)', 'void'),
  \ javaapi#method(0,1,'notationDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'getNotationDecls(', ')', 'List'),
  \ javaapi#method(0,1,'endDTD(', 'Augmentations) throws XNIException', 'void'),
  \ ])

call javaapi#class('XMLAttributeDecl', '', [
  \ javaapi#field(0,1,'name', 'QName'),
  \ javaapi#field(0,1,'simpleType', 'XMLSimpleType'),
  \ javaapi#field(0,1,'optional', 'boolean'),
  \ javaapi#method(0,1,'XMLAttributeDecl(', ')', ''),
  \ javaapi#method(0,1,'setValues(', 'QName, XMLSimpleType, boolean)', 'void'),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ ])

call javaapi#class('XMLElementDecl', '', [
  \ javaapi#field(1,1,'TYPE_ANY', 'short'),
  \ javaapi#field(1,1,'TYPE_EMPTY', 'short'),
  \ javaapi#field(1,1,'TYPE_MIXED', 'short'),
  \ javaapi#field(1,1,'TYPE_CHILDREN', 'short'),
  \ javaapi#field(1,1,'TYPE_SIMPLE', 'short'),
  \ javaapi#field(0,1,'name', 'QName'),
  \ javaapi#field(0,1,'scope', 'int'),
  \ javaapi#field(0,1,'type', 'short'),
  \ javaapi#field(0,1,'simpleType', 'XMLSimpleType'),
  \ javaapi#method(0,1,'XMLElementDecl(', ')', ''),
  \ javaapi#method(0,1,'setValues(', 'QName, int, short, XMLSimpleType)', 'void'),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ ])

call javaapi#class('XMLNotationDecl', '', [
  \ javaapi#field(0,1,'name', 'String'),
  \ javaapi#field(0,1,'publicId', 'String'),
  \ javaapi#field(0,1,'systemId', 'String'),
  \ javaapi#field(0,1,'baseSystemId', 'String'),
  \ javaapi#method(0,1,'XMLNotationDecl(', ')', ''),
  \ javaapi#method(0,1,'setValues(', 'String, String, String, String)', 'void'),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ ])

call javaapi#class('XMLSimpleType', '', [
  \ javaapi#field(1,1,'TYPE_CDATA', 'short'),
  \ javaapi#field(1,1,'TYPE_ENTITY', 'short'),
  \ javaapi#field(1,1,'TYPE_ENUMERATION', 'short'),
  \ javaapi#field(1,1,'TYPE_ID', 'short'),
  \ javaapi#field(1,1,'TYPE_IDREF', 'short'),
  \ javaapi#field(1,1,'TYPE_NMTOKEN', 'short'),
  \ javaapi#field(1,1,'TYPE_NOTATION', 'short'),
  \ javaapi#field(1,1,'TYPE_NAMED', 'short'),
  \ javaapi#field(1,1,'DEFAULT_TYPE_DEFAULT', 'short'),
  \ javaapi#field(1,1,'DEFAULT_TYPE_FIXED', 'short'),
  \ javaapi#field(1,1,'DEFAULT_TYPE_IMPLIED', 'short'),
  \ javaapi#field(1,1,'DEFAULT_TYPE_REQUIRED', 'short'),
  \ javaapi#field(0,1,'type', 'short'),
  \ javaapi#field(0,1,'name', 'String'),
  \ javaapi#field(0,1,'enumeration', 'String'),
  \ javaapi#field(0,1,'list', 'boolean'),
  \ javaapi#field(0,1,'defaultType', 'short'),
  \ javaapi#field(0,1,'defaultValue', 'String'),
  \ javaapi#field(0,1,'nonNormalizedDefaultValue', 'String'),
  \ javaapi#method(0,1,'XMLSimpleType(', ')', ''),
  \ javaapi#method(0,1,'setValues(', 'short, String, String[], boolean, short, String, String)', 'void'),
  \ javaapi#method(0,1,'setValues(', 'XMLSimpleType)', 'void'),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ ])

