call javaapi#namespace('com.sun.xml.internal.org.jvnet.fastinfoset.sax.helpers')

call javaapi#class('EncodingAlgorithmAttributesImpl', 'EncodingAlgorithmAttributes', [
  \ javaapi#method(0,'EncodingAlgorithmAttributesImpl(', ')', 'public'),
  \ javaapi#method(0,'EncodingAlgorithmAttributesImpl(', 'Attributes)', 'public'),
  \ javaapi#method(0,'EncodingAlgorithmAttributesImpl(', 'Map, Attributes)', 'public'),
  \ javaapi#method(0,'clear(', ')', 'void'),
  \ javaapi#method(0,'addAttribute(', 'String, String, String, String, String)', 'void'),
  \ javaapi#method(0,'addAttribute(', 'String, String, String, String, String, boolean, String)', 'void'),
  \ javaapi#method(0,'addAttributeWithBuiltInAlgorithmData(', 'String, String, String, int, Object)', 'void'),
  \ javaapi#method(0,'addAttributeWithAlgorithmData(', 'String, String, String, String, int, Object)', 'void'),
  \ javaapi#method(0,'replaceWithAttributeAlgorithmData(', 'int, String, int, Object)', 'void'),
  \ javaapi#method(0,'setAttributes(', 'Attributes)', 'void'),
  \ javaapi#method(0,'setAttributes(', 'EncodingAlgorithmAttributes)', 'void'),
  \ javaapi#method(0,'getLength(', ')', 'int'),
  \ javaapi#method(0,'getLocalName(', 'int)', 'String'),
  \ javaapi#method(0,'getQName(', 'int)', 'String'),
  \ javaapi#method(0,'getType(', 'int)', 'String'),
  \ javaapi#method(0,'getURI(', 'int)', 'String'),
  \ javaapi#method(0,'getValue(', 'int)', 'String'),
  \ javaapi#method(0,'getIndex(', 'String)', 'int'),
  \ javaapi#method(0,'getType(', 'String)', 'String'),
  \ javaapi#method(0,'getValue(', 'String)', 'String'),
  \ javaapi#method(0,'getIndex(', 'String, String)', 'int'),
  \ javaapi#method(0,'getType(', 'String, String)', 'String'),
  \ javaapi#method(0,'getValue(', 'String, String)', 'String'),
  \ javaapi#method(0,'getAlgorithmURI(', 'int)', 'String'),
  \ javaapi#method(0,'getAlgorithmIndex(', 'int)', 'int'),
  \ javaapi#method(0,'getAlgorithmData(', 'int)', 'Object'),
  \ javaapi#method(0,'getAlpababet(', 'int)', 'String'),
  \ javaapi#method(0,'getToIndex(', 'int)', 'boolean'),
  \ ])

call javaapi#class('FastInfosetDefaultHandler', 'DefaultHandler', [
  \ javaapi#method(0,'FastInfosetDefaultHandler(', ')', 'public'),
  \ javaapi#method(0,'comment(', 'char[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,'startCDATA(', ') throws SAXException', 'void'),
  \ javaapi#method(0,'endCDATA(', ') throws SAXException', 'void'),
  \ javaapi#method(0,'startDTD(', 'String, String, String) throws SAXException', 'void'),
  \ javaapi#method(0,'endDTD(', ') throws SAXException', 'void'),
  \ javaapi#method(0,'startEntity(', 'String) throws SAXException', 'void'),
  \ javaapi#method(0,'endEntity(', 'String) throws SAXException', 'void'),
  \ javaapi#method(0,'octets(', 'String, int, byte[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,'object(', 'String, int, Object) throws SAXException', 'void'),
  \ javaapi#method(0,'booleans(', 'boolean[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,'bytes(', 'byte[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,'shorts(', 'short[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,'ints(', 'int[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,'longs(', 'long[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,'floats(', 'float[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,'doubles(', 'double[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,'uuids(', 'long[], int, int) throws SAXException', 'void'),
  \ ])

