call javaapi#namespace('com.sun.org.apache.xerces.internal.impl.xs.opti')

call javaapi#class('AttrImpl', 'NodeImpl', [
  \ javaapi#method(0,'AttrImpl(', ')', 'public'),
  \ javaapi#method(0,'AttrImpl(', 'Element, String, String, String, String, String)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'String'),
  \ javaapi#method(0,'getSpecified(', ')', 'boolean'),
  \ javaapi#method(0,'getValue(', ')', 'String'),
  \ javaapi#method(0,'getNodeValue(', ')', 'String'),
  \ javaapi#method(0,'getOwnerElement(', ')', 'Element'),
  \ javaapi#method(0,'getOwnerDocument(', ')', 'Document'),
  \ javaapi#method(0,'setValue(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,'isId(', ')', 'boolean'),
  \ javaapi#method(0,'getSchemaTypeInfo(', ')', 'TypeInfo'),
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ ])

call javaapi#class('DefaultDocument', 'NodeImpl', [
  \ javaapi#method(0,'DefaultDocument(', ')', 'public'),
  \ javaapi#method(0,'getDoctype(', ')', 'DocumentType'),
  \ javaapi#method(0,'getImplementation(', ')', 'DOMImplementation'),
  \ javaapi#method(0,'getDocumentElement(', ')', 'Element'),
  \ javaapi#method(0,'getElementsByTagName(', 'String)', 'NodeList'),
  \ javaapi#method(0,'getElementsByTagNameNS(', 'String, String)', 'NodeList'),
  \ javaapi#method(0,'getElementById(', 'String)', 'Element'),
  \ javaapi#method(0,'importNode(', 'Node, boolean) throws DOMException', 'Node'),
  \ javaapi#method(0,'createElement(', 'String) throws DOMException', 'Element'),
  \ javaapi#method(0,'createDocumentFragment(', ')', 'DocumentFragment'),
  \ javaapi#method(0,'createTextNode(', 'String)', 'Text'),
  \ javaapi#method(0,'createComment(', 'String)', 'Comment'),
  \ javaapi#method(0,'createCDATASection(', 'String) throws DOMException', 'CDATASection'),
  \ javaapi#method(0,'createProcessingInstruction(', 'String, String) throws DOMException', 'ProcessingInstruction'),
  \ javaapi#method(0,'createAttribute(', 'String) throws DOMException', 'Attr'),
  \ javaapi#method(0,'createEntityReference(', 'String) throws DOMException', 'EntityReference'),
  \ javaapi#method(0,'createElementNS(', 'String, String) throws DOMException', 'Element'),
  \ javaapi#method(0,'createAttributeNS(', 'String, String) throws DOMException', 'Attr'),
  \ javaapi#method(0,'getInputEncoding(', ')', 'String'),
  \ javaapi#method(0,'getXmlEncoding(', ')', 'String'),
  \ javaapi#method(0,'getXmlStandalone(', ')', 'boolean'),
  \ javaapi#method(0,'setXmlStandalone(', 'boolean)', 'void'),
  \ javaapi#method(0,'getXmlVersion(', ')', 'String'),
  \ javaapi#method(0,'setXmlVersion(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,'getStrictErrorChecking(', ')', 'boolean'),
  \ javaapi#method(0,'setStrictErrorChecking(', 'boolean)', 'void'),
  \ javaapi#method(0,'getDocumentURI(', ')', 'String'),
  \ javaapi#method(0,'setDocumentURI(', 'String)', 'void'),
  \ javaapi#method(0,'adoptNode(', 'Node) throws DOMException', 'Node'),
  \ javaapi#method(0,'normalizeDocument(', ')', 'void'),
  \ javaapi#method(0,'getDomConfig(', ')', 'DOMConfiguration'),
  \ javaapi#method(0,'renameNode(', 'Node, String, String) throws DOMException', 'Node'),
  \ ])

call javaapi#class('DefaultElement', 'NodeImpl', [
  \ javaapi#method(0,'DefaultElement(', ')', 'public'),
  \ javaapi#method(0,'DefaultElement(', 'String, String, String, String, short)', 'public'),
  \ javaapi#method(0,'getTagName(', ')', 'String'),
  \ javaapi#method(0,'getAttribute(', 'String)', 'String'),
  \ javaapi#method(0,'getAttributeNode(', 'String)', 'Attr'),
  \ javaapi#method(0,'getElementsByTagName(', 'String)', 'NodeList'),
  \ javaapi#method(0,'getAttributeNS(', 'String, String)', 'String'),
  \ javaapi#method(0,'getAttributeNodeNS(', 'String, String)', 'Attr'),
  \ javaapi#method(0,'getElementsByTagNameNS(', 'String, String)', 'NodeList'),
  \ javaapi#method(0,'hasAttribute(', 'String)', 'boolean'),
  \ javaapi#method(0,'hasAttributeNS(', 'String, String)', 'boolean'),
  \ javaapi#method(0,'getSchemaTypeInfo(', ')', 'TypeInfo'),
  \ javaapi#method(0,'setAttribute(', 'String, String) throws DOMException', 'void'),
  \ javaapi#method(0,'removeAttribute(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,'removeAttributeNode(', 'Attr) throws DOMException', 'Attr'),
  \ javaapi#method(0,'setAttributeNode(', 'Attr) throws DOMException', 'Attr'),
  \ javaapi#method(0,'setAttributeNS(', 'String, String, String) throws DOMException', 'void'),
  \ javaapi#method(0,'removeAttributeNS(', 'String, String) throws DOMException', 'void'),
  \ javaapi#method(0,'setAttributeNodeNS(', 'Attr) throws DOMException', 'Attr'),
  \ javaapi#method(0,'setIdAttributeNode(', 'Attr, boolean) throws DOMException', 'void'),
  \ javaapi#method(0,'setIdAttribute(', 'String, boolean) throws DOMException', 'void'),
  \ javaapi#method(0,'setIdAttributeNS(', 'String, String, boolean) throws DOMException', 'void'),
  \ ])

call javaapi#class('DefaultNode', 'Node', [
  \ javaapi#method(0,'DefaultNode(', ')', 'public'),
  \ javaapi#method(0,'getNodeName(', ')', 'String'),
  \ javaapi#method(0,'getNodeValue(', ') throws DOMException', 'String'),
  \ javaapi#method(0,'getNodeType(', ')', 'short'),
  \ javaapi#method(0,'getParentNode(', ')', 'Node'),
  \ javaapi#method(0,'getChildNodes(', ')', 'NodeList'),
  \ javaapi#method(0,'getFirstChild(', ')', 'Node'),
  \ javaapi#method(0,'getLastChild(', ')', 'Node'),
  \ javaapi#method(0,'getPreviousSibling(', ')', 'Node'),
  \ javaapi#method(0,'getNextSibling(', ')', 'Node'),
  \ javaapi#method(0,'getAttributes(', ')', 'NamedNodeMap'),
  \ javaapi#method(0,'getOwnerDocument(', ')', 'Document'),
  \ javaapi#method(0,'hasChildNodes(', ')', 'boolean'),
  \ javaapi#method(0,'cloneNode(', 'boolean)', 'Node'),
  \ javaapi#method(0,'normalize(', ')', 'void'),
  \ javaapi#method(0,'isSupported(', 'String, String)', 'boolean'),
  \ javaapi#method(0,'getNamespaceURI(', ')', 'String'),
  \ javaapi#method(0,'getPrefix(', ')', 'String'),
  \ javaapi#method(0,'getLocalName(', ')', 'String'),
  \ javaapi#method(0,'getBaseURI(', ')', 'String'),
  \ javaapi#method(0,'hasAttributes(', ')', 'boolean'),
  \ javaapi#method(0,'setNodeValue(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,'insertBefore(', 'Node, Node) throws DOMException', 'Node'),
  \ javaapi#method(0,'replaceChild(', 'Node, Node) throws DOMException', 'Node'),
  \ javaapi#method(0,'removeChild(', 'Node) throws DOMException', 'Node'),
  \ javaapi#method(0,'appendChild(', 'Node) throws DOMException', 'Node'),
  \ javaapi#method(0,'setPrefix(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,'compareDocumentPosition(', 'Node)', 'short'),
  \ javaapi#method(0,'getTextContent(', ') throws DOMException', 'String'),
  \ javaapi#method(0,'setTextContent(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,'isSameNode(', 'Node)', 'boolean'),
  \ javaapi#method(0,'lookupPrefix(', 'String)', 'String'),
  \ javaapi#method(0,'isDefaultNamespace(', 'String)', 'boolean'),
  \ javaapi#method(0,'lookupNamespaceURI(', 'String)', 'String'),
  \ javaapi#method(0,'isEqualNode(', 'Node)', 'boolean'),
  \ javaapi#method(0,'getFeature(', 'String, String)', 'Object'),
  \ javaapi#method(0,'setUserData(', 'String, Object, UserDataHandler)', 'Object'),
  \ javaapi#method(0,'getUserData(', 'String)', 'Object'),
  \ ])

call javaapi#class('DefaultText', 'NodeImpl', [
  \ javaapi#method(0,'DefaultText(', ')', 'public'),
  \ javaapi#method(0,'getData(', ') throws DOMException', 'String'),
  \ javaapi#method(0,'setData(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,'getLength(', ')', 'int'),
  \ javaapi#method(0,'substringData(', 'int, int) throws DOMException', 'String'),
  \ javaapi#method(0,'appendData(', 'String) throws DOMException', 'void'),
  \ javaapi#method(0,'insertData(', 'int, String) throws DOMException', 'void'),
  \ javaapi#method(0,'deleteData(', 'int, int) throws DOMException', 'void'),
  \ javaapi#method(0,'replaceData(', 'int, int, String) throws DOMException', 'void'),
  \ javaapi#method(0,'splitText(', 'int) throws DOMException', 'Text'),
  \ javaapi#method(0,'isElementContentWhitespace(', ')', 'boolean'),
  \ javaapi#method(0,'getWholeText(', ')', 'String'),
  \ javaapi#method(0,'replaceWholeText(', 'String) throws DOMException', 'Text'),
  \ ])

call javaapi#class('DefaultXMLDocumentHandler', 'XMLDTDContentModelHandler', [
  \ javaapi#method(0,'DefaultXMLDocumentHandler(', ')', 'public'),
  \ javaapi#method(0,'startDocument(', 'XMLLocator, String, NamespaceContext, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'xmlDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'doctypeDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'comment(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'processingInstruction(', 'String, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startPrefixMapping(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'emptyElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startGeneralEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'textDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endGeneralEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'characters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'ignorableWhitespace(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endElement(', 'QName, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endPrefixMapping(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endDocument(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startDTD(', 'XMLLocator, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startParameterEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endParameterEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startExternalSubset(', 'XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endExternalSubset(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'elementDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startAttlist(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'attributeDecl(', 'String, String, String, String[], String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endAttlist(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'internalEntityDecl(', 'String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'externalEntityDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'unparsedEntityDecl(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'notationDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startConditional(', 'short, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'ignoredCharacters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endConditional(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endDTD(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startContentModel(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'any(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'empty(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startGroup(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'pcdata(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'element(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'separator(', 'short, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'occurrence(', 'short, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endGroup(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endContentModel(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'setDocumentSource(', 'XMLDocumentSource)', 'void'),
  \ javaapi#method(0,'getDocumentSource(', ')', 'XMLDocumentSource'),
  \ javaapi#method(0,'setDTDSource(', 'XMLDTDSource)', 'void'),
  \ javaapi#method(0,'getDTDSource(', ')', 'XMLDTDSource'),
  \ javaapi#method(0,'setDTDContentModelSource(', 'XMLDTDContentModelSource)', 'void'),
  \ javaapi#method(0,'getDTDContentModelSource(', ')', 'XMLDTDContentModelSource'),
  \ ])

call javaapi#class('ElementImpl', 'DefaultElement', [
  \ javaapi#method(0,'ElementImpl(', 'int, int, int)', 'public'),
  \ javaapi#method(0,'ElementImpl(', 'int, int)', 'public'),
  \ javaapi#method(0,'ElementImpl(', 'String, String, String, String, int, int, int)', 'public'),
  \ javaapi#method(0,'ElementImpl(', 'String, String, String, String, int, int)', 'public'),
  \ javaapi#method(0,'getOwnerDocument(', ')', 'Document'),
  \ javaapi#method(0,'getParentNode(', ')', 'Node'),
  \ javaapi#method(0,'hasChildNodes(', ')', 'boolean'),
  \ javaapi#method(0,'getFirstChild(', ')', 'Node'),
  \ javaapi#method(0,'getLastChild(', ')', 'Node'),
  \ javaapi#method(0,'getPreviousSibling(', ')', 'Node'),
  \ javaapi#method(0,'getNextSibling(', ')', 'Node'),
  \ javaapi#method(0,'getAttributes(', ')', 'NamedNodeMap'),
  \ javaapi#method(0,'hasAttributes(', ')', 'boolean'),
  \ javaapi#method(0,'getTagName(', ')', 'String'),
  \ javaapi#method(0,'getAttribute(', 'String)', 'String'),
  \ javaapi#method(0,'getAttributeNode(', 'String)', 'Attr'),
  \ javaapi#method(0,'getAttributeNS(', 'String, String)', 'String'),
  \ javaapi#method(0,'getAttributeNodeNS(', 'String, String)', 'Attr'),
  \ javaapi#method(0,'hasAttribute(', 'String)', 'boolean'),
  \ javaapi#method(0,'hasAttributeNS(', 'String, String)', 'boolean'),
  \ javaapi#method(0,'setAttribute(', 'String, String)', 'void'),
  \ javaapi#method(0,'getLineNumber(', ')', 'int'),
  \ javaapi#method(0,'getColumnNumber(', ')', 'int'),
  \ javaapi#method(0,'getCharacterOffset(', ')', 'int'),
  \ javaapi#method(0,'getAnnotation(', ')', 'String'),
  \ javaapi#method(0,'getSyntheticAnnotation(', ')', 'String'),
  \ ])

call javaapi#class('NamedNodeMapImpl', 'NamedNodeMap', [
  \ javaapi#method(0,'NamedNodeMapImpl(', 'Attr[])', 'public'),
  \ javaapi#method(0,'getNamedItem(', 'String)', 'Node'),
  \ javaapi#method(0,'item(', 'int)', 'Node'),
  \ javaapi#method(0,'getLength(', ')', 'int'),
  \ javaapi#method(0,'getNamedItemNS(', 'String, String)', 'Node'),
  \ javaapi#method(0,'setNamedItemNS(', 'Node) throws DOMException', 'Node'),
  \ javaapi#method(0,'setNamedItem(', 'Node) throws DOMException', 'Node'),
  \ javaapi#method(0,'removeNamedItem(', 'String) throws DOMException', 'Node'),
  \ javaapi#method(0,'removeNamedItemNS(', 'String, String) throws DOMException', 'Node'),
  \ ])

call javaapi#class('NodeImpl', 'DefaultNode', [
  \ javaapi#method(0,'NodeImpl(', ')', 'public'),
  \ javaapi#method(0,'NodeImpl(', 'String, String, String, String, short)', 'public'),
  \ javaapi#method(0,'getNodeName(', ')', 'String'),
  \ javaapi#method(0,'getNamespaceURI(', ')', 'String'),
  \ javaapi#method(0,'getPrefix(', ')', 'String'),
  \ javaapi#method(0,'getLocalName(', ')', 'String'),
  \ javaapi#method(0,'getNodeType(', ')', 'short'),
  \ javaapi#method(0,'setReadOnly(', 'boolean, boolean)', 'void'),
  \ javaapi#method(0,'getReadOnly(', ')', 'boolean'),
  \ ])

call javaapi#class('SchemaDOM', 'DefaultDocument', [
  \ javaapi#method(0,'SchemaDOM(', ')', 'public'),
  \ javaapi#method(0,'startElement(', 'QName, XMLAttributes, int, int, int)', 'ElementImpl'),
  \ javaapi#method(0,'emptyElement(', 'QName, XMLAttributes, int, int, int)', 'ElementImpl'),
  \ javaapi#method(0,'startElement(', 'QName, XMLAttributes, int, int)', 'ElementImpl'),
  \ javaapi#method(0,'emptyElement(', 'QName, XMLAttributes, int, int)', 'ElementImpl'),
  \ javaapi#method(0,'endElement(', ')', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'printDOM(', ')', 'void'),
  \ javaapi#method(1,'traverse(', 'Node, int)', 'void'),
  \ javaapi#method(1,'indent(', 'int)', 'void'),
  \ javaapi#method(0,'getDocumentElement(', ')', 'Element'),
  \ javaapi#method(0,'getImplementation(', ')', 'DOMImplementation'),
  \ ])

call javaapi#class('SchemaDOMImplementation', 'DOMImplementation', [
  \ javaapi#method(1,'getDOMImplementation(', ')', 'DOMImplementation'),
  \ javaapi#method(0,'createDocument(', 'String, String, DocumentType) throws DOMException', 'Document'),
  \ javaapi#method(0,'createDocumentType(', 'String, String, String) throws DOMException', 'DocumentType'),
  \ javaapi#method(0,'getFeature(', 'String, String)', 'Object'),
  \ javaapi#method(0,'hasFeature(', 'String, String)', 'boolean'),
  \ ])

call javaapi#class('BooleanStack', '', [
  \ javaapi#method(0,'BooleanStack(', ')', 'public'),
  \ javaapi#method(0,'size(', ')', 'int'),
  \ javaapi#method(0,'push(', 'boolean)', 'void'),
  \ javaapi#method(0,'pop(', ')', 'boolean'),
  \ javaapi#method(0,'clear(', ')', 'void'),
  \ ])

call javaapi#class('SchemaDOMParser', 'DefaultXMLDocumentHandler', [
  \ javaapi#field(1,'ERROR_REPORTER', 'String'),
  \ javaapi#field(1,'GENERATE_SYNTHETIC_ANNOTATION', 'String'),
  \ javaapi#method(0,'SchemaDOMParser(', 'XMLParserConfiguration)', 'public'),
  \ javaapi#method(0,'startDocument(', 'XMLLocator, String, NamespaceContext, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endDocument(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'comment(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'processingInstruction(', 'String, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'characters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'emptyElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endElement(', 'QName, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'ignorableWhitespace(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'startCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'endCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,'getDocument(', ')', 'Document'),
  \ javaapi#method(0,'setFeature(', 'String, boolean)', 'void'),
  \ javaapi#method(0,'getFeature(', 'String)', 'boolean'),
  \ javaapi#method(0,'setProperty(', 'String, Object)', 'void'),
  \ javaapi#method(0,'getProperty(', 'String)', 'Object'),
  \ javaapi#method(0,'setEntityResolver(', 'XMLEntityResolver)', 'void'),
  \ javaapi#method(0,'parse(', 'XMLInputSource) throws IOException', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'resetNodePool(', ')', 'void'),
  \ ])

call javaapi#class('SchemaParsingConfig', 'BasicParserConfiguration', [
  \ javaapi#method(0,'SchemaParsingConfig(', ')', 'public'),
  \ javaapi#method(0,'SchemaParsingConfig(', 'SymbolTable)', 'public'),
  \ javaapi#method(0,'SchemaParsingConfig(', 'SymbolTable, XMLGrammarPool)', 'public'),
  \ javaapi#method(0,'SchemaParsingConfig(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', 'public'),
  \ javaapi#method(0,'getFeatureState(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,'setFeature(', 'String, boolean) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,'getPropertyState(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,'setProperty(', 'String, Object) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,'setLocale(', 'Locale) throws XNIException', 'void'),
  \ javaapi#method(0,'setInputSource(', 'XMLInputSource) throws XMLConfigurationException, IOException', 'void'),
  \ javaapi#method(0,'parse(', 'boolean) throws XNIException, IOException', 'boolean'),
  \ javaapi#method(0,'cleanup(', ')', 'void'),
  \ javaapi#method(0,'parse(', 'XMLInputSource) throws XNIException, IOException', 'void'),
  \ javaapi#method(0,'reset(', ') throws XNIException', 'void'),
  \ javaapi#method(0,'resetNodePool(', ')', 'void'),
  \ ])

call javaapi#class('TextImpl', 'DefaultText', [
  \ javaapi#method(0,'TextImpl(', 'StringBuffer, SchemaDOM, int, int)', 'public'),
  \ javaapi#method(0,'getParentNode(', ')', 'Node'),
  \ javaapi#method(0,'getPreviousSibling(', ')', 'Node'),
  \ javaapi#method(0,'getNextSibling(', ')', 'Node'),
  \ javaapi#method(0,'getData(', ') throws DOMException', 'String'),
  \ javaapi#method(0,'getLength(', ')', 'int'),
  \ javaapi#method(0,'substringData(', 'int, int) throws DOMException', 'String'),
  \ ])

