call javaapi#namespace('com.sun.corba.se.impl.encoding')

call javaapi#class('BufferManagerFactory', '', [
  \ javaapi#field(1,1,'GROW', 'int'),
  \ javaapi#field(1,1,'COLLECT', 'int'),
  \ javaapi#field(1,1,'STREAM', 'int'),
  \ javaapi#method(0,1,'BufferManagerFactory(', ')', ''),
  \ javaapi#method(1,1,'newBufferManagerRead(', 'GIOPVersion, byte, ORB)', 'BufferManagerRead'),
  \ javaapi#method(1,1,'newBufferManagerRead(', 'int, byte, ORB)', 'BufferManagerRead'),
  \ javaapi#method(1,1,'newBufferManagerWrite(', 'int, byte, ORB)', 'BufferManagerWrite'),
  \ javaapi#method(1,1,'newBufferManagerWrite(', 'GIOPVersion, byte, ORB)', 'BufferManagerWrite'),
  \ javaapi#method(1,1,'defaultBufferManagerRead(', 'ORB)', 'BufferManagerRead'),
  \ ])

call javaapi#interface('BufferManagerRead', '', [
  \ javaapi#method(0,1,'processFragment(', 'ByteBuffer, FragmentMessage)', 'void'),
  \ javaapi#method(0,1,'underflow(', 'ByteBufferWithInfo)', 'ByteBufferWithInfo'),
  \ javaapi#method(0,1,'init(', 'Message)', 'void'),
  \ javaapi#method(0,1,'getMarkAndResetHandler(', ')', 'MarkAndResetHandler'),
  \ javaapi#method(0,1,'cancelProcessing(', 'int)', 'void'),
  \ javaapi#method(0,1,'close(', 'ByteBufferWithInfo)', 'void'),
  \ ])

call javaapi#class('BufferManagerReadGrow', 'MarkAndResetHandler', [
  \ javaapi#method(0,1,'processFragment(', 'ByteBuffer, FragmentMessage)', 'void'),
  \ javaapi#method(0,1,'init(', 'Message)', 'void'),
  \ javaapi#method(0,1,'underflow(', 'ByteBufferWithInfo)', 'ByteBufferWithInfo'),
  \ javaapi#method(0,1,'cancelProcessing(', 'int)', 'void'),
  \ javaapi#method(0,1,'getMarkAndResetHandler(', ')', 'MarkAndResetHandler'),
  \ javaapi#method(0,1,'mark(', 'RestorableInputStream)', 'void'),
  \ javaapi#method(0,1,'fragmentationOccured(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'close(', 'ByteBufferWithInfo)', 'void'),
  \ ])

call javaapi#class('BufferManagerReadStream', 'MarkAndResetHandler', [
  \ javaapi#method(0,1,'cancelProcessing(', 'int)', 'void'),
  \ javaapi#method(0,1,'processFragment(', 'ByteBuffer, FragmentMessage)', 'void'),
  \ javaapi#method(0,1,'underflow(', 'ByteBufferWithInfo)', 'ByteBufferWithInfo'),
  \ javaapi#method(0,1,'init(', 'Message)', 'void'),
  \ javaapi#method(0,1,'close(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,0,'getByteBufferPool(', ')', 'ByteBufferPool'),
  \ javaapi#method(0,1,'mark(', 'RestorableInputStream)', 'void'),
  \ javaapi#method(0,1,'fragmentationOccured(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'getMarkAndResetHandler(', ')', 'MarkAndResetHandler'),
  \ ])

call javaapi#class('BufferManagerWrite', '', [
  \ javaapi#field(0,0,'orb', 'ORB'),
  \ javaapi#field(0,0,'wrapper', 'ORBUtilSystemException'),
  \ javaapi#field(0,0,'outputObject', 'Object'),
  \ javaapi#field(0,0,'sentFullMessage', 'boolean'),
  \ javaapi#method(0,1,'sentFragment(', ')', 'boolean'),
  \ javaapi#method(0,1,'sentFullMessage(', ')', 'boolean'),
  \ javaapi#method(0,1,'getBufferSize(', ')', 'int'),
  \ javaapi#method(0,1,'overflow(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'sendMessage(', ')', 'void'),
  \ javaapi#method(0,1,'setOutputObject(', 'Object)', 'void'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ ])

call javaapi#class('BufferManagerWriteCollect', 'BufferManagerWrite', [
  \ javaapi#method(0,1,'sentFragment(', ')', 'boolean'),
  \ javaapi#method(0,1,'getBufferSize(', ')', 'int'),
  \ javaapi#method(0,1,'overflow(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'sendMessage(', ')', 'void'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ ])

call javaapi#class('BufferManagerWriteGrow', 'BufferManagerWrite', [
  \ javaapi#method(0,1,'sentFragment(', ')', 'boolean'),
  \ javaapi#method(0,1,'getBufferSize(', ')', 'int'),
  \ javaapi#method(0,1,'overflow(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'sendMessage(', ')', 'void'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ ])

call javaapi#class('BufferManagerWriteStream', 'BufferManagerWrite', [
  \ javaapi#method(0,1,'sentFragment(', ')', 'boolean'),
  \ javaapi#method(0,1,'getBufferSize(', ')', 'int'),
  \ javaapi#method(0,1,'overflow(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'sendMessage(', ')', 'void'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ ])

call javaapi#class('BufferQueue', '', [
  \ javaapi#method(0,1,'BufferQueue(', ')', ''),
  \ javaapi#method(0,1,'enqueue(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'dequeue(', ') throws NoSuchElementException', 'ByteBufferWithInfo'),
  \ javaapi#method(0,1,'size(', ')', 'int'),
  \ javaapi#method(0,1,'push(', 'ByteBufferWithInfo)', 'void'),
  \ ])

call javaapi#class('ByteBufferWithInfo', '', [
  \ javaapi#field(0,1,'byteBuffer', 'ByteBuffer'),
  \ javaapi#field(0,1,'buflen', 'int'),
  \ javaapi#field(0,1,'needed', 'int'),
  \ javaapi#field(0,1,'fragmented', 'boolean'),
  \ javaapi#method(0,1,'ByteBufferWithInfo(', 'ORB, ByteBuffer, int)', ''),
  \ javaapi#method(0,1,'ByteBufferWithInfo(', 'ORB, ByteBuffer)', ''),
  \ javaapi#method(0,1,'ByteBufferWithInfo(', 'ORB, BufferManagerWrite)', ''),
  \ javaapi#method(0,1,'ByteBufferWithInfo(', 'ORB, BufferManagerWrite, boolean)', ''),
  \ javaapi#method(0,1,'ByteBufferWithInfo(', 'ByteBufferWithInfo)', ''),
  \ javaapi#method(0,1,'getSize(', ')', 'int'),
  \ javaapi#method(0,1,'getLength(', ')', 'int'),
  \ javaapi#method(0,1,'position(', ')', 'int'),
  \ javaapi#method(0,1,'position(', 'int)', 'void'),
  \ javaapi#method(0,1,'setLength(', 'int)', 'void'),
  \ javaapi#method(0,1,'growBuffer(', 'ORB)', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ ])

call javaapi#class('CDRInputObject', 'CDRInputStream', [
  \ javaapi#method(0,1,'CDRInputObject(', 'ORB, CorbaConnection, ByteBuffer, Message)', ''),
  \ javaapi#method(0,1,'getConnection(', ')', 'CorbaConnection'),
  \ javaapi#method(0,1,'getMessageHeader(', ')', 'Message'),
  \ javaapi#method(0,1,'unmarshalHeader(', ')', 'void'),
  \ javaapi#method(0,1,'unmarshaledHeader(', ')', 'boolean'),
  \ javaapi#method(0,0,'createCharBTCConverter(', ')', 'BTCConverter'),
  \ javaapi#method(0,0,'createWCharBTCConverter(', ')', 'BTCConverter'),
  \ javaapi#method(0,1,'getCodeBase(', ')', 'CodeBase'),
  \ javaapi#method(0,1,'dup(', ')', 'CDRInputStream'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ ])

call javaapi#class('CDRInputStream', 'InputStream', [
  \ javaapi#field(0,0,'messageMediator', 'CorbaMessageMediator'),
  \ javaapi#method(0,1,'CDRInputStream(', ')', ''),
  \ javaapi#method(0,1,'CDRInputStream(', 'CDRInputStream)', ''),
  \ javaapi#method(0,1,'CDRInputStream(', 'ORB, ByteBuffer, int, boolean, GIOPVersion, byte, BufferManagerRead)', ''),
  \ javaapi#method(0,1,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,1,'read_char(', ')', 'char'),
  \ javaapi#method(0,1,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,1,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,1,'read_short(', ')', 'short'),
  \ javaapi#method(0,1,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,1,'read_long(', ')', 'int'),
  \ javaapi#method(0,1,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,1,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,1,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,1,'read_float(', ')', 'float'),
  \ javaapi#method(0,1,'read_double(', ')', 'double'),
  \ javaapi#method(0,1,'read_string(', ')', 'String'),
  \ javaapi#method(0,1,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,1,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,1,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,1,'read_any(', ')', 'Any'),
  \ javaapi#method(0,1,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,1,'read(', ') throws IOException', 'int'),
  \ javaapi#method(0,1,'read_fixed(', ')', 'BigDecimal'),
  \ javaapi#method(0,1,'read_Context(', ')', 'Context'),
  \ javaapi#method(0,1,'read_Object(', 'Class)', 'Object'),
  \ javaapi#method(0,1,'orb(', ')', 'ORB'),
  \ javaapi#method(0,1,'read_value(', ')', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'Class)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'BoxedValueHelper)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'String)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'Serializable)', 'Serializable'),
  \ javaapi#method(0,1,'read_abstract_interface(', ')', 'Object'),
  \ javaapi#method(0,1,'read_abstract_interface(', 'Class)', 'Object'),
  \ javaapi#method(0,1,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,1,'getPosition(', ')', 'int'),
  \ javaapi#method(0,1,'read_Abstract(', ')', 'Object'),
  \ javaapi#method(0,1,'read_Value(', ')', 'Serializable'),
  \ javaapi#method(0,1,'read_any_array(', 'AnySeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_boolean_array(', 'BooleanSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_char_array(', 'CharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_wchar_array(', 'WCharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_octet_array(', 'OctetSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_short_array(', 'ShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ushort_array(', 'UShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_long_array(', 'LongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulong_array(', 'ULongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulonglong_array(', 'ULongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_longlong_array(', 'LongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_float_array(', 'FloatSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_double_array(', 'DoubleSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'read(', 'byte[]) throws IOException', 'int'),
  \ javaapi#method(0,1,'read(', 'byte[], int, int) throws IOException', 'int'),
  \ javaapi#method(0,1,'skip(', 'long) throws IOException', 'long'),
  \ javaapi#method(0,1,'available(', ') throws IOException', 'int'),
  \ javaapi#method(0,1,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'mark(', 'int)', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'markSupported(', ')', 'boolean'),
  \ javaapi#method(0,1,'dup(', ')', 'CDRInputStream'),
  \ javaapi#method(0,1,'read_fixed(', 'short, short)', 'BigDecimal'),
  \ javaapi#method(0,1,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,0,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,0,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,0,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'getBufferLength(', ')', 'int'),
  \ javaapi#method(0,0,'setBufferLength(', 'int)', 'void'),
  \ javaapi#method(0,0,'getIndex(', ')', 'int'),
  \ javaapi#method(0,0,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,1,'orb(', 'ORB)', 'void'),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,1,'getBufferManager(', ')', 'BufferManagerRead'),
  \ javaapi#method(0,1,'getCodeBase(', ')', 'CodeBase'),
  \ javaapi#method(0,0,'createCharBTCConverter(', ')', 'BTCConverter'),
  \ javaapi#method(0,0,'createWCharBTCConverter(', ')', 'BTCConverter'),
  \ javaapi#method(0,1,'alignOnBoundary(', 'int)', 'void'),
  \ javaapi#method(0,1,'setHeaderPadding(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'performORBVersionSpecificInit(', ')', 'void'),
  \ javaapi#method(0,1,'resetCodeSetConverters(', ')', 'void'),
  \ javaapi#method(0,1,'setMessageMediator(', 'MessageMediator)', 'void'),
  \ javaapi#method(0,1,'getMessageMediator(', ')', 'MessageMediator'),
  \ javaapi#method(0,1,'start_value(', ')', 'void'),
  \ javaapi#method(0,1,'end_value(', ')', 'void'),
  \ ])

call javaapi#class('CDRInputStreamBase', 'InputStream', [
  \ javaapi#field(0,0,'parent', 'CDRInputStream'),
  \ javaapi#method(0,1,'setParent(', 'CDRInputStream)', 'void'),
  \ javaapi#method(0,1,'init(', 'ORB, ByteBuffer, int, boolean, BufferManagerRead)', 'void'),
  \ javaapi#method(0,1,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,1,'read_char(', ')', 'char'),
  \ javaapi#method(0,1,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,1,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,1,'read_short(', ')', 'short'),
  \ javaapi#method(0,1,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,1,'read_long(', ')', 'int'),
  \ javaapi#method(0,1,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,1,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,1,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,1,'read_float(', ')', 'float'),
  \ javaapi#method(0,1,'read_double(', ')', 'double'),
  \ javaapi#method(0,1,'read_string(', ')', 'String'),
  \ javaapi#method(0,1,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,1,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,1,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,1,'read_any(', ')', 'Any'),
  \ javaapi#method(0,1,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,1,'read(', ') throws IOException', 'int'),
  \ javaapi#method(0,1,'read_fixed(', ')', 'BigDecimal'),
  \ javaapi#method(0,1,'read_Context(', ')', 'Context'),
  \ javaapi#method(0,1,'read_Object(', 'Class)', 'Object'),
  \ javaapi#method(0,1,'orb(', ')', 'ORB'),
  \ javaapi#method(0,1,'read_value(', ')', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'Class)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'BoxedValueHelper)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'String)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'Serializable)', 'Serializable'),
  \ javaapi#method(0,1,'read_abstract_interface(', ')', 'Object'),
  \ javaapi#method(0,1,'read_abstract_interface(', 'Class)', 'Object'),
  \ javaapi#method(0,1,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,1,'getPosition(', ')', 'int'),
  \ javaapi#method(0,1,'read_Abstract(', ')', 'Object'),
  \ javaapi#method(0,1,'read_Value(', ')', 'Serializable'),
  \ javaapi#method(0,1,'read_any_array(', 'AnySeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_boolean_array(', 'BooleanSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_char_array(', 'CharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_wchar_array(', 'WCharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_octet_array(', 'OctetSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_short_array(', 'ShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ushort_array(', 'UShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_long_array(', 'LongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulong_array(', 'ULongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulonglong_array(', 'ULongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_longlong_array(', 'LongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_float_array(', 'FloatSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_double_array(', 'DoubleSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'mark(', 'int)', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'markSupported(', ')', 'boolean'),
  \ javaapi#method(0,1,'dup(', ')', 'CDRInputStreamBase'),
  \ javaapi#method(0,1,'read_fixed(', 'short, short)', 'BigDecimal'),
  \ javaapi#method(0,1,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,1,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,1,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,1,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'getBufferLength(', ')', 'int'),
  \ javaapi#method(0,1,'setBufferLength(', 'int)', 'void'),
  \ javaapi#method(0,1,'getIndex(', ')', 'int'),
  \ javaapi#method(0,1,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,1,'orb(', 'ORB)', 'void'),
  \ javaapi#method(0,1,'getBufferManager(', ')', 'BufferManagerRead'),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,1,'resetCodeSetConverters(', ')', 'void'),
  \ javaapi#method(0,1,'start_value(', ')', 'void'),
  \ javaapi#method(0,1,'end_value(', ')', 'void'),
  \ ])

call javaapi#class('CDRInputStream_1_0', 'CDRInputStreamBase', [
  \ javaapi#field(0,0,'bufferManagerRead', 'BufferManagerRead'),
  \ javaapi#field(0,0,'bbwi', 'ByteBufferWithInfo'),
  \ javaapi#field(0,0,'littleEndian', 'boolean'),
  \ javaapi#field(0,0,'orb', 'ORB'),
  \ javaapi#field(0,0,'wrapper', 'ORBUtilSystemException'),
  \ javaapi#field(0,0,'omgWrapper', 'OMGSystemException'),
  \ javaapi#field(0,0,'valueHandler', 'ValueHandler'),
  \ javaapi#field(0,0,'blockLength', 'int'),
  \ javaapi#field(0,0,'end_flag', 'int'),
  \ javaapi#field(0,0,'valueIndirection', 'int'),
  \ javaapi#field(0,0,'stringIndirection', 'int'),
  \ javaapi#field(0,0,'isChunked', 'boolean'),
  \ javaapi#field(0,0,'markAndResetHandler', 'MarkAndResetHandler'),
  \ javaapi#method(0,1,'CDRInputStream_1_0(', ')', ''),
  \ javaapi#method(0,1,'dup(', ')', 'CDRInputStreamBase'),
  \ javaapi#method(0,1,'init(', 'ORB, ByteBuffer, int, boolean, BufferManagerRead)', 'void'),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,0,'computeAlignment(', 'int, int)', 'int'),
  \ javaapi#method(0,1,'getSize(', ')', 'int'),
  \ javaapi#method(0,0,'checkBlockLength(', 'int, int)', 'void'),
  \ javaapi#method(0,0,'alignAndCheck(', 'int, int)', 'void'),
  \ javaapi#method(0,0,'grow(', 'int, int)', 'void'),
  \ javaapi#method(0,1,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,1,'read_longdouble(', ')', 'double'),
  \ javaapi#method(0,1,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,1,'read_char(', ')', 'char'),
  \ javaapi#method(0,1,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,1,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,1,'read_short(', ')', 'short'),
  \ javaapi#method(0,1,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,1,'read_long(', ')', 'int'),
  \ javaapi#method(0,1,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,1,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,1,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,1,'read_float(', ')', 'float'),
  \ javaapi#method(0,1,'read_double(', ')', 'double'),
  \ javaapi#method(0,0,'checkForNegativeLength(', 'int)', 'void'),
  \ javaapi#method(0,0,'readStringOrIndirection(', 'boolean)', 'String'),
  \ javaapi#method(0,1,'read_string(', ')', 'String'),
  \ javaapi#method(0,1,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,1,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,1,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,1,'read_any(', ')', 'Any'),
  \ javaapi#method(0,1,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,1,'read_Object(', 'Class)', 'Object'),
  \ javaapi#method(1,1,'internalIORToObject(', 'IOR, StubFactory, ORB)', 'Object'),
  \ javaapi#method(0,1,'read_abstract_interface(', ')', 'Object'),
  \ javaapi#method(0,1,'read_abstract_interface(', 'Class)', 'Object'),
  \ javaapi#method(0,1,'read_value(', ')', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'Class)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'BoxedValueHelper)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'Serializable)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'String)', 'Serializable'),
  \ javaapi#method(0,0,'get_offset(', ')', 'int'),
  \ javaapi#method(0,1,'orb(', ')', 'ORB'),
  \ javaapi#method(0,1,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_any_array(', 'Any[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_Abstract(', ')', 'Object'),
  \ javaapi#method(0,1,'read_Value(', ')', 'Serializable'),
  \ javaapi#method(0,1,'read_any_array(', 'AnySeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_boolean_array(', 'BooleanSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_char_array(', 'CharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_wchar_array(', 'WCharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_octet_array(', 'OctetSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_short_array(', 'ShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ushort_array(', 'UShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_long_array(', 'LongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulong_array(', 'ULongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulonglong_array(', 'ULongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_longlong_array(', 'LongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_float_array(', 'FloatSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_double_array(', 'DoubleSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_fixed(', 'short, short)', 'BigDecimal'),
  \ javaapi#method(0,1,'read_fixed(', ')', 'BigDecimal'),
  \ javaapi#method(0,1,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'printBuffer(', ')', 'void'),
  \ javaapi#method(1,1,'printBuffer(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,1,'getBufferLength(', ')', 'int'),
  \ javaapi#method(0,1,'setBufferLength(', 'int)', 'void'),
  \ javaapi#method(0,1,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,1,'getIndex(', ')', 'int'),
  \ javaapi#method(0,1,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,1,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,1,'orb(', 'ORB)', 'void'),
  \ javaapi#method(0,1,'getBufferManager(', ')', 'BufferManagerRead'),
  \ javaapi#method(0,1,'createStreamMemento(', ')', 'Object'),
  \ javaapi#method(0,1,'restoreInternalState(', 'Object)', 'void'),
  \ javaapi#method(0,1,'getPosition(', ')', 'int'),
  \ javaapi#method(0,1,'mark(', 'int)', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,0,'getCharConverter(', ')', 'BTCConverter'),
  \ javaapi#method(0,0,'getWCharConverter(', ')', 'BTCConverter'),
  \ javaapi#method(0,0,'dprintThrowable(', 'Throwable)', 'void'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ javaapi#method(0,1,'resetCodeSetConverters(', ')', 'void'),
  \ javaapi#method(0,1,'start_value(', ')', 'void'),
  \ javaapi#method(0,1,'end_value(', ')', 'void'),
  \ javaapi#method(0,1,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'markSupported(', ')', 'boolean'),
  \ javaapi#method(0,1,'read_Context(', ')', 'Context'),
  \ javaapi#method(0,1,'read(', ') throws IOException', 'int'),
  \ javaapi#method(0,1,'setParent(', 'CDRInputStream)', 'void'),
  \ ])

call javaapi#class('CDRInputStream_1_1', 'CDRInputStream_1_0', [
  \ javaapi#field(0,0,'fragmentOffset', 'int'),
  \ javaapi#method(0,1,'CDRInputStream_1_1(', ')', ''),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,1,'dup(', ')', 'CDRInputStreamBase'),
  \ javaapi#method(0,0,'get_offset(', ')', 'int'),
  \ javaapi#method(0,0,'alignAndCheck(', 'int, int)', 'void'),
  \ javaapi#method(0,0,'grow(', 'int, int)', 'void'),
  \ javaapi#method(0,1,'createStreamMemento(', ')', 'Object'),
  \ javaapi#method(0,1,'restoreInternalState(', 'Object)', 'void'),
  \ javaapi#method(0,1,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,1,'read_wstring(', ')', 'String'),
  \ ])

call javaapi#class('CDRInputStream_1_2', 'CDRInputStream_1_1', [
  \ javaapi#field(0,0,'headerPadding', 'boolean'),
  \ javaapi#field(0,0,'restoreHeaderPadding', 'boolean'),
  \ javaapi#method(0,1,'CDRInputStream_1_2(', ')', ''),
  \ javaapi#method(0,1,'mark(', 'int)', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'dup(', ')', 'CDRInputStreamBase'),
  \ javaapi#method(0,0,'alignAndCheck(', 'int, int)', 'void'),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,1,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,1,'read_wstring(', ')', 'String'),
  \ ])

call javaapi#class('CDROutputObject', 'CorbaOutputObject', [
  \ javaapi#method(0,1,'CDROutputObject(', 'ORB, MessageMediator, Message, byte)', ''),
  \ javaapi#method(0,1,'CDROutputObject(', 'ORB, MessageMediator, Message, byte, int)', ''),
  \ javaapi#method(0,1,'CDROutputObject(', 'ORB, CorbaMessageMediator, GIOPVersion, CorbaConnection, Message, byte)', ''),
  \ javaapi#method(0,1,'getMessageHeader(', ')', 'Message'),
  \ javaapi#method(0,1,'finishSendingMessage(', ')', 'void'),
  \ javaapi#method(0,1,'writeTo(', 'CorbaConnection) throws IOException', 'void'),
  \ javaapi#method(0,1,'create_input_stream(', ')', 'InputStream'),
  \ javaapi#method(0,1,'getConnection(', ')', 'CorbaConnection'),
  \ javaapi#method(0,1,'getByteBufferWithInfo(', ')', 'ByteBufferWithInfo'),
  \ javaapi#method(0,1,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,0,'createCharCTBConverter(', ')', 'CTBConverter'),
  \ javaapi#method(0,0,'createWCharCTBConverter(', ')', 'CTBConverter'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ ])

call javaapi#class('CDROutputStream', 'OutputStream', [
  \ javaapi#field(0,0,'orb', 'ORB'),
  \ javaapi#field(0,0,'wrapper', 'ORBUtilSystemException'),
  \ javaapi#field(0,0,'corbaMessageMediator', 'CorbaMessageMediator'),
  \ javaapi#method(0,1,'CDROutputStream(', 'ORB, GIOPVersion, byte, boolean, BufferManagerWrite, byte, boolean)', ''),
  \ javaapi#method(0,1,'CDROutputStream(', 'ORB, GIOPVersion, byte, boolean, BufferManagerWrite, byte)', ''),
  \ javaapi#method(0,1,'create_input_stream(', ')', 'InputStream'),
  \ javaapi#method(0,1,'write_boolean(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'write_char(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,1,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,1,'write_ushort(', 'short)', 'void'),
  \ javaapi#method(0,1,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,1,'write_ulong(', 'int)', 'void'),
  \ javaapi#method(0,1,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,1,'write_ulonglong(', 'long)', 'void'),
  \ javaapi#method(0,1,'write_float(', 'float)', 'void'),
  \ javaapi#method(0,1,'write_double(', 'double)', 'void'),
  \ javaapi#method(0,1,'write_string(', 'String)', 'void'),
  \ javaapi#method(0,1,'write_wstring(', 'String)', 'void'),
  \ javaapi#method(0,1,'write_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_Object(', 'Object)', 'void'),
  \ javaapi#method(0,1,'write_TypeCode(', 'TypeCode)', 'void'),
  \ javaapi#method(0,1,'write_any(', 'Any)', 'void'),
  \ javaapi#method(0,1,'write_Principal(', 'Principal)', 'void'),
  \ javaapi#method(0,1,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,1,'write_fixed(', 'BigDecimal)', 'void'),
  \ javaapi#method(0,1,'write_Context(', 'Context, ContextList)', 'void'),
  \ javaapi#method(0,1,'orb(', ')', 'ORB'),
  \ javaapi#method(0,1,'write_value(', 'Serializable)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, Class)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, String)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, BoxedValueHelper)', 'void'),
  \ javaapi#method(0,1,'write_abstract_interface(', 'Object)', 'void'),
  \ javaapi#method(0,1,'write(', 'byte[]) throws IOException', 'void'),
  \ javaapi#method(0,1,'write(', 'byte[], int, int) throws IOException', 'void'),
  \ javaapi#method(0,1,'flush(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'start_block(', ')', 'void'),
  \ javaapi#method(0,1,'end_block(', ')', 'void'),
  \ javaapi#method(0,1,'putEndian(', ')', 'void'),
  \ javaapi#method(0,1,'writeTo(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'toByteArray(', ')', 'byte[]'),
  \ javaapi#method(0,1,'write_Abstract(', 'Object)', 'void'),
  \ javaapi#method(0,1,'write_Value(', 'Serializable)', 'void'),
  \ javaapi#method(0,1,'write_any_array(', 'Any[], int, int)', 'void'),
  \ javaapi#method(0,1,'setMessageMediator(', 'MessageMediator)', 'void'),
  \ javaapi#method(0,1,'getMessageMediator(', ')', 'MessageMediator'),
  \ javaapi#method(0,1,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,0,'getSize(', ')', 'int'),
  \ javaapi#method(0,0,'getIndex(', ')', 'int'),
  \ javaapi#method(0,0,'getRealIndex(', 'int)', 'int'),
  \ javaapi#method(0,0,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,0,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,0,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,1,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,1,'getByteBufferWithInfo(', ')', 'ByteBufferWithInfo'),
  \ javaapi#method(0,0,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'getBufferManager(', ')', 'BufferManagerWrite'),
  \ javaapi#method(0,1,'write_fixed(', 'BigDecimal, short, short)', 'void'),
  \ javaapi#method(0,1,'writeOctetSequenceTo(', 'OutputStream)', 'void'),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,1,'writeIndirection(', 'int, int)', 'void'),
  \ javaapi#method(0,0,'createCharCTBConverter(', ')', 'CTBConverter'),
  \ javaapi#method(0,0,'createWCharCTBConverter(', ')', 'CTBConverter'),
  \ javaapi#method(0,0,'freeInternalCaches(', ')', 'void'),
  \ javaapi#method(0,1,'alignOnBoundary(', 'int)', 'void'),
  \ javaapi#method(0,1,'setHeaderPadding(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'start_value(', 'String)', 'void'),
  \ javaapi#method(0,1,'end_value(', ')', 'void'),
  \ ])

call javaapi#class('CDROutputStreamBase', 'OutputStream', [
  \ javaapi#field(0,0,'parent', 'CDROutputStream'),
  \ javaapi#method(0,1,'setParent(', 'CDROutputStream)', 'void'),
  \ javaapi#method(0,1,'init(', 'ORB, BufferManagerWrite, byte)', 'void'),
  \ javaapi#method(0,0,'init(', 'ORB, boolean, BufferManagerWrite, byte, boolean)', 'void'),
  \ javaapi#method(0,1,'write_boolean(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'write_char(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,1,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,1,'write_ushort(', 'short)', 'void'),
  \ javaapi#method(0,1,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,1,'write_ulong(', 'int)', 'void'),
  \ javaapi#method(0,1,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,1,'write_ulonglong(', 'long)', 'void'),
  \ javaapi#method(0,1,'write_float(', 'float)', 'void'),
  \ javaapi#method(0,1,'write_double(', 'double)', 'void'),
  \ javaapi#method(0,1,'write_string(', 'String)', 'void'),
  \ javaapi#method(0,1,'write_wstring(', 'String)', 'void'),
  \ javaapi#method(0,1,'write_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_Object(', 'Object)', 'void'),
  \ javaapi#method(0,1,'write_TypeCode(', 'TypeCode)', 'void'),
  \ javaapi#method(0,1,'write_any(', 'Any)', 'void'),
  \ javaapi#method(0,1,'write_Principal(', 'Principal)', 'void'),
  \ javaapi#method(0,1,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,1,'write_fixed(', 'BigDecimal)', 'void'),
  \ javaapi#method(0,1,'write_Context(', 'Context, ContextList)', 'void'),
  \ javaapi#method(0,1,'orb(', ')', 'ORB'),
  \ javaapi#method(0,1,'write_value(', 'Serializable)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, Class)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, String)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, BoxedValueHelper)', 'void'),
  \ javaapi#method(0,1,'write_abstract_interface(', 'Object)', 'void'),
  \ javaapi#method(0,1,'start_block(', ')', 'void'),
  \ javaapi#method(0,1,'end_block(', ')', 'void'),
  \ javaapi#method(0,1,'putEndian(', ')', 'void'),
  \ javaapi#method(0,1,'writeTo(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'toByteArray(', ')', 'byte[]'),
  \ javaapi#method(0,1,'write_Abstract(', 'Object)', 'void'),
  \ javaapi#method(0,1,'write_Value(', 'Serializable)', 'void'),
  \ javaapi#method(0,1,'write_any_array(', 'Any[], int, int)', 'void'),
  \ javaapi#method(0,1,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'getSize(', ')', 'int'),
  \ javaapi#method(0,1,'getIndex(', ')', 'int'),
  \ javaapi#method(0,1,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,1,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,1,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,1,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,1,'getByteBufferWithInfo(', ')', 'ByteBufferWithInfo'),
  \ javaapi#method(0,1,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'getBufferManager(', ')', 'BufferManagerWrite'),
  \ javaapi#method(0,1,'write_fixed(', 'BigDecimal, short, short)', 'void'),
  \ javaapi#method(0,1,'writeOctetSequenceTo(', 'OutputStream)', 'void'),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,1,'writeIndirection(', 'int, int)', 'void'),
  \ javaapi#method(0,1,'start_value(', 'String)', 'void'),
  \ javaapi#method(0,1,'end_value(', ')', 'void'),
  \ ])

call javaapi#class('CDROutputStream_1_0', 'CDROutputStreamBase', [
  \ javaapi#field(0,0,'littleEndian', 'boolean'),
  \ javaapi#field(0,0,'bufferManagerWrite', 'BufferManagerWrite'),
  \ javaapi#field(0,0,'orb', 'ORB'),
  \ javaapi#field(0,0,'wrapper', 'ORBUtilSystemException'),
  \ javaapi#field(0,0,'debug', 'boolean'),
  \ javaapi#field(0,0,'blockSizeIndex', 'int'),
  \ javaapi#field(0,0,'blockSizePosition', 'int'),
  \ javaapi#field(0,0,'streamFormatVersion', 'byte'),
  \ javaapi#field(0,0,'inBlock', 'boolean'),
  \ javaapi#method(0,1,'CDROutputStream_1_0(', ')', ''),
  \ javaapi#method(0,1,'init(', 'ORB, boolean, BufferManagerWrite, byte, boolean)', 'void'),
  \ javaapi#method(0,1,'init(', 'ORB, boolean, BufferManagerWrite, byte)', 'void'),
  \ javaapi#method(0,1,'getBufferManager(', ')', 'BufferManagerWrite'),
  \ javaapi#method(0,1,'toByteArray(', ')', 'byte[]'),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,0,'handleSpecialChunkBegin(', 'int)', 'void'),
  \ javaapi#method(0,0,'handleSpecialChunkEnd(', ')', 'void'),
  \ javaapi#method(0,0,'computeAlignment(', 'int)', 'int'),
  \ javaapi#method(0,0,'alignAndReserve(', 'int, int)', 'void'),
  \ javaapi#method(0,0,'grow(', 'int, int)', 'void'),
  \ javaapi#method(0,1,'putEndian(', ') throws SystemException', 'void'),
  \ javaapi#method(0,1,'littleEndian(', ')', 'boolean'),
  \ javaapi#method(0,1,'write_longdouble(', 'double)', 'void'),
  \ javaapi#method(0,1,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,1,'write_boolean(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'write_char(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,1,'write_ushort(', 'short)', 'void'),
  \ javaapi#method(0,1,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,1,'write_ulong(', 'int)', 'void'),
  \ javaapi#method(0,1,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,1,'write_ulonglong(', 'long)', 'void'),
  \ javaapi#method(0,1,'write_float(', 'float)', 'void'),
  \ javaapi#method(0,1,'write_double(', 'double)', 'void'),
  \ javaapi#method(0,1,'write_string(', 'String)', 'void'),
  \ javaapi#method(0,0,'writeString(', 'String)', 'int'),
  \ javaapi#method(0,1,'write_wstring(', 'String)', 'void'),
  \ javaapi#method(0,1,'write_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_Principal(', 'Principal)', 'void'),
  \ javaapi#method(0,1,'write_any(', 'Any)', 'void'),
  \ javaapi#method(0,1,'write_TypeCode(', 'TypeCode)', 'void'),
  \ javaapi#method(0,1,'write_Object(', 'Object)', 'void'),
  \ javaapi#method(0,1,'write_abstract_interface(', 'Object)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, Class)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, String)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, BoxedValueHelper)', 'void'),
  \ javaapi#method(0,1,'get_offset(', ')', 'int'),
  \ javaapi#method(0,1,'start_block(', ')', 'void'),
  \ javaapi#method(0,0,'writeLongWithoutAlign(', 'int)', 'void'),
  \ javaapi#method(0,1,'end_block(', ')', 'void'),
  \ javaapi#method(0,1,'orb(', ')', 'ORB'),
  \ javaapi#method(0,1,'write_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_string_array(', 'String[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_wstring_array(', 'String[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_any_array(', 'Any[], int, int)', 'void'),
  \ javaapi#method(0,1,'writeTo(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'writeOctetSequenceTo(', 'OutputStream)', 'void'),
  \ javaapi#method(0,1,'getSize(', ')', 'int'),
  \ javaapi#method(0,1,'getIndex(', ')', 'int'),
  \ javaapi#method(0,1,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,1,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,1,'getByteBufferWithInfo(', ')', 'ByteBufferWithInfo'),
  \ javaapi#method(0,1,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,1,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,1,'write_Abstract(', 'Object)', 'void'),
  \ javaapi#method(0,1,'write_Value(', 'Serializable)', 'void'),
  \ javaapi#method(0,1,'write_fixed(', 'BigDecimal, short, short)', 'void'),
  \ javaapi#method(0,1,'write_fixed(', 'BigDecimal)', 'void'),
  \ javaapi#method(0,1,'write_fixed(', 'String, int)', 'void'),
  \ javaapi#method(0,1,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'printBuffer(', ')', 'void'),
  \ javaapi#method(1,1,'printBuffer(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'writeIndirection(', 'int, int)', 'void'),
  \ javaapi#method(0,0,'getCharConverter(', ')', 'CTBConverter'),
  \ javaapi#method(0,0,'getWCharConverter(', ')', 'CTBConverter'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ javaapi#method(0,1,'start_value(', 'String)', 'void'),
  \ javaapi#method(0,1,'end_value(', ')', 'void'),
  \ javaapi#method(0,1,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'write_Context(', 'Context, ContextList)', 'void'),
  \ javaapi#method(0,1,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,1,'init(', 'ORB, BufferManagerWrite, byte)', 'void'),
  \ javaapi#method(0,1,'setParent(', 'CDROutputStream)', 'void'),
  \ ])

call javaapi#class('CDROutputStream_1_1', 'CDROutputStream_1_0', [
  \ javaapi#field(0,0,'fragmentOffset', 'int'),
  \ javaapi#method(0,1,'CDROutputStream_1_1(', ')', ''),
  \ javaapi#method(0,0,'alignAndReserve(', 'int, int)', 'void'),
  \ javaapi#method(0,0,'grow(', 'int, int)', 'void'),
  \ javaapi#method(0,1,'get_offset(', ')', 'int'),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,1,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_wstring(', 'String)', 'void'),
  \ ])

call javaapi#class('CDROutputStream_1_2', 'CDROutputStream_1_1', [
  \ javaapi#field(0,0,'primitiveAcrossFragmentedChunk', 'boolean'),
  \ javaapi#field(0,0,'specialChunk', 'boolean'),
  \ javaapi#method(0,1,'CDROutputStream_1_2(', ')', ''),
  \ javaapi#method(0,0,'handleSpecialChunkBegin(', 'int)', 'void'),
  \ javaapi#method(0,0,'handleSpecialChunkEnd(', ')', 'void'),
  \ javaapi#method(0,1,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,1,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,1,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,1,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,0,'alignAndReserve(', 'int, int)', 'void'),
  \ javaapi#method(0,0,'grow(', 'int, int)', 'void'),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,1,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_wstring(', 'String)', 'void'),
  \ ])

call javaapi#class('CachedCodeBase', '_CodeBaseImplBase', [
  \ javaapi#method(0,1,'CachedCodeBase(', 'CorbaConnection)', ''),
  \ javaapi#method(0,1,'get_ir(', ')', 'Repository'),
  \ javaapi#method(0,1,'implementation(', 'String)', 'String'),
  \ javaapi#method(0,1,'implementations(', 'String[])', 'String[]'),
  \ javaapi#method(0,1,'meta(', 'String)', 'FullValueDescription'),
  \ javaapi#method(0,1,'metas(', 'String[])', 'FullValueDescription[]'),
  \ javaapi#method(0,1,'bases(', 'String)', 'String[]'),
  \ ])

call javaapi#class('CodeSetCache', '', [
  \ ])

call javaapi#class('CodeSetComponentInfo', '', [
  \ javaapi#field(1,1,'JAVASOFT_DEFAULT_CODESETS', 'CodeSetComponentInfo'),
  \ javaapi#field(1,1,'LOCAL_CODE_SETS', 'CodeSetContext'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'CodeSetComponentInfo(', ')', ''),
  \ javaapi#method(0,1,'CodeSetComponentInfo(', 'CodeSetComponent, CodeSetComponent)', ''),
  \ javaapi#method(0,1,'read(', 'MarshalInputStream)', 'void'),
  \ javaapi#method(0,1,'write(', 'MarshalOutputStream)', 'void'),
  \ javaapi#method(0,1,'getCharComponent(', ')', 'CodeSetComponent'),
  \ javaapi#method(0,1,'getWCharComponent(', ')', 'CodeSetComponent'),
  \ javaapi#method(1,1,'createFromString(', 'String)', 'CodeSetComponent'),
  \ ])

call javaapi#class('CodeSetConversion', '', [
  \ javaapi#method(0,1,'getCTBConverter(', 'Entry)', 'CTBConverter'),
  \ javaapi#method(0,1,'getCTBConverter(', 'Entry, boolean, boolean)', 'CTBConverter'),
  \ javaapi#method(0,1,'getBTCConverter(', 'Entry)', 'BTCConverter'),
  \ javaapi#method(0,1,'getBTCConverter(', 'Entry, boolean)', 'BTCConverter'),
  \ javaapi#method(0,1,'negotiate(', 'CodeSetComponentInfo, CodeSetComponentInfo)', 'CodeSetContext'),
  \ javaapi#method(1,1,'impl(', ')', 'CodeSetConversion'),
  \ ])

call javaapi#class('EncapsInputStream', 'CDRInputStream', [
  \ javaapi#method(0,1,'EncapsInputStream(', 'ORB, byte[], int, boolean, GIOPVersion)', ''),
  \ javaapi#method(0,1,'EncapsInputStream(', 'ORB, ByteBuffer, int, boolean, GIOPVersion)', ''),
  \ javaapi#method(0,1,'EncapsInputStream(', 'ORB, byte[], int)', ''),
  \ javaapi#method(0,1,'EncapsInputStream(', 'EncapsInputStream)', ''),
  \ javaapi#method(0,1,'EncapsInputStream(', 'ORB, byte[], int, GIOPVersion)', ''),
  \ javaapi#method(0,1,'EncapsInputStream(', 'ORB, byte[], int, GIOPVersion, CodeBase)', ''),
  \ javaapi#method(0,1,'dup(', ')', 'CDRInputStream'),
  \ javaapi#method(0,0,'createCharBTCConverter(', ')', 'BTCConverter'),
  \ javaapi#method(0,0,'createWCharBTCConverter(', ')', 'BTCConverter'),
  \ javaapi#method(0,1,'getCodeBase(', ')', 'CodeBase'),
  \ ])

call javaapi#class('EncapsOutputStream', 'CDROutputStream', [
  \ javaapi#method(0,1,'EncapsOutputStream(', 'ORB)', ''),
  \ javaapi#method(0,1,'EncapsOutputStream(', 'ORB, GIOPVersion)', ''),
  \ javaapi#method(0,1,'EncapsOutputStream(', 'ORB, boolean)', ''),
  \ javaapi#method(0,1,'EncapsOutputStream(', 'ORB, GIOPVersion, boolean)', ''),
  \ javaapi#method(0,1,'create_input_stream(', ')', 'InputStream'),
  \ javaapi#method(0,0,'createCharCTBConverter(', ')', 'CTBConverter'),
  \ javaapi#method(0,0,'createWCharCTBConverter(', ')', 'CTBConverter'),
  \ ])

call javaapi#class('IDLJavaSerializationInputStream', 'CDRInputStreamBase', [
  \ javaapi#field(0,0,'wrapper', 'ORBUtilSystemException'),
  \ javaapi#method(0,1,'IDLJavaSerializationInputStream(', 'byte)', ''),
  \ javaapi#method(0,1,'init(', 'ORB, ByteBuffer, int, boolean, BufferManagerRead)', 'void'),
  \ javaapi#method(0,1,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,1,'read_char(', ')', 'char'),
  \ javaapi#method(0,1,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,1,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,1,'read_short(', ')', 'short'),
  \ javaapi#method(0,1,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,1,'read_long(', ')', 'int'),
  \ javaapi#method(0,1,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,1,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,1,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,1,'read_float(', ')', 'float'),
  \ javaapi#method(0,1,'read_double(', ')', 'double'),
  \ javaapi#method(0,1,'read_string(', ')', 'String'),
  \ javaapi#method(0,1,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,1,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,1,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,1,'read_any(', ')', 'Any'),
  \ javaapi#method(0,1,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,1,'read_fixed(', ')', 'BigDecimal'),
  \ javaapi#method(0,1,'read_Object(', 'Class)', 'Object'),
  \ javaapi#method(0,1,'orb(', ')', 'ORB'),
  \ javaapi#method(0,1,'read_value(', ')', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'Class)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'BoxedValueHelper)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'String)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'Serializable)', 'Serializable'),
  \ javaapi#method(0,1,'read_abstract_interface(', ')', 'Object'),
  \ javaapi#method(0,1,'read_abstract_interface(', 'Class)', 'Object'),
  \ javaapi#method(0,1,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,1,'getPosition(', ')', 'int'),
  \ javaapi#method(0,1,'read_Abstract(', ')', 'Object'),
  \ javaapi#method(0,1,'read_Value(', ')', 'Serializable'),
  \ javaapi#method(0,1,'read_any_array(', 'AnySeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_boolean_array(', 'BooleanSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_char_array(', 'CharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_wchar_array(', 'WCharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_octet_array(', 'OctetSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_short_array(', 'ShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ushort_array(', 'UShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_long_array(', 'LongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulong_array(', 'ULongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulonglong_array(', 'ULongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_longlong_array(', 'LongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_float_array(', 'FloatSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'read_double_array(', 'DoubleSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,1,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'mark(', 'int)', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'markSupported(', ')', 'boolean'),
  \ javaapi#method(0,1,'dup(', ')', 'CDRInputStreamBase'),
  \ javaapi#method(0,1,'read_fixed(', 'short, short)', 'BigDecimal'),
  \ javaapi#method(0,1,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,1,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,1,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,1,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'getBufferLength(', ')', 'int'),
  \ javaapi#method(0,1,'setBufferLength(', 'int)', 'void'),
  \ javaapi#method(0,1,'getIndex(', ')', 'int'),
  \ javaapi#method(0,1,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,1,'orb(', 'ORB)', 'void'),
  \ javaapi#method(0,1,'getBufferManager(', ')', 'BufferManagerRead'),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,1,'resetCodeSetConverters(', ')', 'void'),
  \ javaapi#method(0,1,'start_value(', ')', 'void'),
  \ javaapi#method(0,1,'end_value(', ')', 'void'),
  \ javaapi#method(0,1,'read_Context(', ')', 'Context'),
  \ javaapi#method(0,1,'read(', ') throws IOException', 'int'),
  \ javaapi#method(0,1,'setParent(', 'CDRInputStream)', 'void'),
  \ ])

call javaapi#class('IDLJavaSerializationOutputStream', 'CDROutputStreamBase', [
  \ javaapi#field(0,0,'wrapper', 'ORBUtilSystemException'),
  \ javaapi#method(0,1,'IDLJavaSerializationOutputStream(', 'byte)', ''),
  \ javaapi#method(0,1,'init(', 'ORB, boolean, BufferManagerWrite, byte, boolean)', 'void'),
  \ javaapi#method(0,1,'write_boolean(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'write_char(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,1,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,1,'write_ushort(', 'short)', 'void'),
  \ javaapi#method(0,1,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,1,'write_ulong(', 'int)', 'void'),
  \ javaapi#method(0,1,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,1,'write_ulonglong(', 'long)', 'void'),
  \ javaapi#method(0,1,'write_float(', 'float)', 'void'),
  \ javaapi#method(0,1,'write_double(', 'double)', 'void'),
  \ javaapi#method(0,1,'write_string(', 'String)', 'void'),
  \ javaapi#method(0,1,'write_wstring(', 'String)', 'void'),
  \ javaapi#method(0,1,'write_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_Object(', 'Object)', 'void'),
  \ javaapi#method(0,1,'write_TypeCode(', 'TypeCode)', 'void'),
  \ javaapi#method(0,1,'write_any(', 'Any)', 'void'),
  \ javaapi#method(0,1,'write_Principal(', 'Principal)', 'void'),
  \ javaapi#method(0,1,'write_fixed(', 'BigDecimal)', 'void'),
  \ javaapi#method(0,1,'orb(', ')', 'ORB'),
  \ javaapi#method(0,1,'write_value(', 'Serializable)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, Class)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, String)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable, BoxedValueHelper)', 'void'),
  \ javaapi#method(0,1,'write_abstract_interface(', 'Object)', 'void'),
  \ javaapi#method(0,1,'start_block(', ')', 'void'),
  \ javaapi#method(0,1,'end_block(', ')', 'void'),
  \ javaapi#method(0,1,'putEndian(', ')', 'void'),
  \ javaapi#method(0,1,'writeTo(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'toByteArray(', ')', 'byte[]'),
  \ javaapi#method(0,1,'write_Abstract(', 'Object)', 'void'),
  \ javaapi#method(0,1,'write_Value(', 'Serializable)', 'void'),
  \ javaapi#method(0,1,'write_any_array(', 'Any[], int, int)', 'void'),
  \ javaapi#method(0,1,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'getSize(', ')', 'int'),
  \ javaapi#method(0,1,'getIndex(', ')', 'int'),
  \ javaapi#method(0,0,'getRealIndex(', 'int)', 'int'),
  \ javaapi#method(0,1,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,1,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,1,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,1,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,1,'getByteBufferWithInfo(', ')', 'ByteBufferWithInfo'),
  \ javaapi#method(0,1,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'getBufferManager(', ')', 'BufferManagerWrite'),
  \ javaapi#method(0,1,'write_fixed(', 'BigDecimal, short, short)', 'void'),
  \ javaapi#method(0,1,'writeOctetSequenceTo(', 'OutputStream)', 'void'),
  \ javaapi#method(0,1,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,1,'writeIndirection(', 'int, int)', 'void'),
  \ javaapi#method(0,1,'alignOnBoundary(', 'int)', 'void'),
  \ javaapi#method(0,1,'setHeaderPadding(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'start_value(', 'String)', 'void'),
  \ javaapi#method(0,1,'end_value(', ')', 'void'),
  \ javaapi#method(0,1,'write_Context(', 'Context, ContextList)', 'void'),
  \ javaapi#method(0,1,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,1,'init(', 'ORB, BufferManagerWrite, byte)', 'void'),
  \ javaapi#method(0,1,'setParent(', 'CDROutputStream)', 'void'),
  \ ])

call javaapi#interface('MarkAndResetHandler', '', [
  \ javaapi#method(0,1,'mark(', 'RestorableInputStream)', 'void'),
  \ javaapi#method(0,1,'fragmentationOccured(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ ])

call javaapi#interface('MarshalInputStream', '', [
  \ javaapi#method(0,1,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,1,'read_char(', ')', 'char'),
  \ javaapi#method(0,1,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,1,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,1,'read_short(', ')', 'short'),
  \ javaapi#method(0,1,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,1,'read_long(', ')', 'int'),
  \ javaapi#method(0,1,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,1,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,1,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,1,'read_float(', ')', 'float'),
  \ javaapi#method(0,1,'read_double(', ')', 'double'),
  \ javaapi#method(0,1,'read_string(', ')', 'String'),
  \ javaapi#method(0,1,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,1,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,1,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,1,'read_any(', ')', 'Any'),
  \ javaapi#method(0,1,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,1,'read_Object(', 'Class)', 'Object'),
  \ javaapi#method(0,1,'read_value(', ') throws Exception', 'Serializable'),
  \ javaapi#method(0,1,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,1,'getPosition(', ')', 'int'),
  \ javaapi#method(0,1,'mark(', 'int)', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'performORBVersionSpecificInit(', ')', 'void'),
  \ javaapi#method(0,1,'resetCodeSetConverters(', ')', 'void'),
  \ ])

call javaapi#interface('MarshalOutputStream', '', [
  \ javaapi#method(0,1,'create_input_stream(', ')', 'InputStream'),
  \ javaapi#method(0,1,'write_boolean(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'write_char(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,1,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,1,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,1,'write_ushort(', 'short)', 'void'),
  \ javaapi#method(0,1,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,1,'write_ulong(', 'int)', 'void'),
  \ javaapi#method(0,1,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,1,'write_ulonglong(', 'long)', 'void'),
  \ javaapi#method(0,1,'write_float(', 'float)', 'void'),
  \ javaapi#method(0,1,'write_double(', 'double)', 'void'),
  \ javaapi#method(0,1,'write_string(', 'String)', 'void'),
  \ javaapi#method(0,1,'write_wstring(', 'String)', 'void'),
  \ javaapi#method(0,1,'write_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'write_Object(', 'Object)', 'void'),
  \ javaapi#method(0,1,'write_TypeCode(', 'TypeCode)', 'void'),
  \ javaapi#method(0,1,'write_any(', 'Any)', 'void'),
  \ javaapi#method(0,1,'write_Principal(', 'Principal)', 'void'),
  \ javaapi#method(0,1,'write_value(', 'Serializable)', 'void'),
  \ javaapi#method(0,1,'start_block(', ')', 'void'),
  \ javaapi#method(0,1,'end_block(', ')', 'void'),
  \ javaapi#method(0,1,'putEndian(', ')', 'void'),
  \ javaapi#method(0,1,'writeTo(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'toByteArray(', ')', 'byte[]'),
  \ ])

call javaapi#class('OSFCodeSetRegistry', '', [
  \ javaapi#field(1,1,'ISO_8859_1_VALUE', 'int'),
  \ javaapi#field(1,1,'UTF_16_VALUE', 'int'),
  \ javaapi#field(1,1,'UTF_8_VALUE', 'int'),
  \ javaapi#field(1,1,'UCS_2_VALUE', 'int'),
  \ javaapi#field(1,1,'ISO_646_VALUE', 'int'),
  \ javaapi#field(1,1,'ISO_8859_1', 'Entry'),
  \ javaapi#field(1,1,'UTF_16', 'Entry'),
  \ javaapi#field(1,1,'UTF_8', 'Entry'),
  \ javaapi#field(1,1,'UCS_2', 'Entry'),
  \ javaapi#field(1,1,'ISO_646', 'Entry'),
  \ javaapi#method(1,1,'lookupEntry(', 'int)', 'Entry'),
  \ ])

call javaapi#interface('RestorableInputStream', '', [
  \ javaapi#method(0,1,'createStreamMemento(', ')', 'Object'),
  \ javaapi#method(0,1,'restoreInternalState(', 'Object)', 'void'),
  \ ])

call javaapi#class('TypeCodeInputStream', 'EncapsInputStream', [
  \ javaapi#method(0,1,'TypeCodeInputStream(', 'ORB, byte[], int)', ''),
  \ javaapi#method(0,1,'TypeCodeInputStream(', 'ORB, byte[], int, boolean, GIOPVersion)', ''),
  \ javaapi#method(0,1,'TypeCodeInputStream(', 'ORB, ByteBuffer, int, boolean, GIOPVersion)', ''),
  \ javaapi#method(0,1,'addTypeCodeAtPosition(', 'TypeCodeImpl, int)', 'void'),
  \ javaapi#method(0,1,'getTypeCodeAtPosition(', 'int)', 'TypeCodeImpl'),
  \ javaapi#method(0,1,'setEnclosingInputStream(', 'InputStream)', 'void'),
  \ javaapi#method(0,1,'getTopLevelStream(', ')', 'TypeCodeReader'),
  \ javaapi#method(0,1,'getTopLevelPosition(', ')', 'int'),
  \ javaapi#method(1,1,'readEncapsulation(', 'InputStream, ORB)', 'TypeCodeInputStream'),
  \ javaapi#method(0,0,'makeEncapsulation(', ')', 'void'),
  \ javaapi#method(0,1,'printTypeMap(', ')', 'void'),
  \ ])

call javaapi#class('TypeCodeOutputStream', 'EncapsOutputStream', [
  \ javaapi#method(0,1,'TypeCodeOutputStream(', 'ORB)', ''),
  \ javaapi#method(0,1,'TypeCodeOutputStream(', 'ORB, boolean)', ''),
  \ javaapi#method(0,1,'create_input_stream(', ')', 'InputStream'),
  \ javaapi#method(0,1,'setEnclosingOutputStream(', 'OutputStream)', 'void'),
  \ javaapi#method(0,1,'getTopLevelStream(', ')', 'TypeCodeOutputStream'),
  \ javaapi#method(0,1,'getTopLevelPosition(', ')', 'int'),
  \ javaapi#method(0,1,'addIDAtPosition(', 'String, int)', 'void'),
  \ javaapi#method(0,1,'getPositionForID(', 'String)', 'int'),
  \ javaapi#method(0,1,'writeRawBuffer(', 'OutputStream, int)', 'void'),
  \ javaapi#method(0,1,'createEncapsulation(', 'ORB)', 'TypeCodeOutputStream'),
  \ javaapi#method(0,0,'makeEncapsulation(', ')', 'void'),
  \ javaapi#method(1,1,'wrapOutputStream(', 'OutputStream)', 'TypeCodeOutputStream'),
  \ javaapi#method(0,1,'getPosition(', ')', 'int'),
  \ javaapi#method(0,1,'getRealIndex(', 'int)', 'int'),
  \ javaapi#method(0,1,'getTypeCodeBuffer(', ')', 'byte[]'),
  \ javaapi#method(0,1,'printTypeMap(', ')', 'void'),
  \ ])

call javaapi#interface('TypeCodeReader', 'MarshalInputStream', [
  \ javaapi#method(0,1,'addTypeCodeAtPosition(', 'TypeCodeImpl, int)', 'void'),
  \ javaapi#method(0,1,'getTypeCodeAtPosition(', 'int)', 'TypeCodeImpl'),
  \ javaapi#method(0,1,'setEnclosingInputStream(', 'InputStream)', 'void'),
  \ javaapi#method(0,1,'getTopLevelStream(', ')', 'TypeCodeReader'),
  \ javaapi#method(0,1,'getTopLevelPosition(', ')', 'int'),
  \ javaapi#method(0,1,'getPosition(', ')', 'int'),
  \ javaapi#method(0,1,'printTypeMap(', ')', 'void'),
  \ ])

call javaapi#class('WrapperInputStream', 'InputStream', [
  \ javaapi#method(0,1,'WrapperInputStream(', 'CDRInputStream)', ''),
  \ javaapi#method(0,1,'read(', ') throws IOException', 'int'),
  \ javaapi#method(0,1,'read(', 'byte[]) throws IOException', 'int'),
  \ javaapi#method(0,1,'read(', 'byte[], int, int) throws IOException', 'int'),
  \ javaapi#method(0,1,'skip(', 'long) throws IOException', 'long'),
  \ javaapi#method(0,1,'available(', ') throws IOException', 'int'),
  \ javaapi#method(0,1,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'mark(', 'int)', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'markSupported(', ')', 'boolean'),
  \ javaapi#method(0,1,'getPosition(', ')', 'int'),
  \ javaapi#method(0,1,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,1,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,1,'read_char(', ')', 'char'),
  \ javaapi#method(0,1,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,1,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,1,'read_short(', ')', 'short'),
  \ javaapi#method(0,1,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,1,'read_long(', ')', 'int'),
  \ javaapi#method(0,1,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,1,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,1,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,1,'read_float(', ')', 'float'),
  \ javaapi#method(0,1,'read_double(', ')', 'double'),
  \ javaapi#method(0,1,'read_string(', ')', 'String'),
  \ javaapi#method(0,1,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,1,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,1,'read_value(', ')', 'Serializable'),
  \ javaapi#method(0,1,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,1,'read_any(', ')', 'Any'),
  \ javaapi#method(0,1,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,1,'read_fixed(', ')', 'BigDecimal'),
  \ javaapi#method(0,1,'read_Context(', ')', 'Context'),
  \ javaapi#method(0,1,'orb(', ')', 'ORB'),
  \ javaapi#method(0,1,'addTypeCodeAtPosition(', 'TypeCodeImpl, int)', 'void'),
  \ javaapi#method(0,1,'getTypeCodeAtPosition(', 'int)', 'TypeCodeImpl'),
  \ javaapi#method(0,1,'setEnclosingInputStream(', 'InputStream)', 'void'),
  \ javaapi#method(0,1,'getTopLevelStream(', ')', 'TypeCodeReader'),
  \ javaapi#method(0,1,'getTopLevelPosition(', ')', 'int'),
  \ javaapi#method(0,1,'performORBVersionSpecificInit(', ')', 'void'),
  \ javaapi#method(0,1,'resetCodeSetConverters(', ')', 'void'),
  \ javaapi#method(0,1,'printTypeMap(', ')', 'void'),
  \ ])

