call javaapi#namespace('com.sun.corba.se.impl.transport')

call javaapi#class('ByteBufferPoolImpl', 'ByteBufferPool', [
  \ javaapi#method(0,1,'ByteBufferPoolImpl(', 'ORB)', ''),
  \ javaapi#method(0,1,'getByteBuffer(', 'int)', 'ByteBuffer'),
  \ javaapi#method(0,1,'releaseByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,1,'activeCount(', ')', 'int'),
  \ ])

call javaapi#class('CorbaConnectionCacheBase', 'CorbaConnectionCache', [
  \ javaapi#field(0,0,'orb', 'ORB'),
  \ javaapi#field(0,0,'timestamp', 'long'),
  \ javaapi#field(0,0,'cacheType', 'String'),
  \ javaapi#field(0,0,'monitoringName', 'String'),
  \ javaapi#field(0,0,'wrapper', 'ORBUtilSystemException'),
  \ javaapi#method(0,0,'CorbaConnectionCacheBase(', 'ORB, String, String)', ''),
  \ javaapi#method(0,1,'getCacheType(', ')', 'String'),
  \ javaapi#method(0,1,'stampTime(', 'Connection)', 'void'),
  \ javaapi#method(0,1,'numberOfConnections(', ')', 'long'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ javaapi#method(0,1,'numberOfIdleConnections(', ')', 'long'),
  \ javaapi#method(0,1,'numberOfBusyConnections(', ')', 'long'),
  \ javaapi#method(0,1,'reclaim(', ')', 'boolean'),
  \ javaapi#method(0,1,'getMonitoringName(', ')', 'String'),
  \ javaapi#method(0,1,'values(', ')', 'Collection'),
  \ javaapi#method(0,0,'backingStore(', ')', 'Object'),
  \ javaapi#method(0,0,'registerWithMonitoring(', ')', 'void'),
  \ javaapi#method(0,0,'dprintCreation(', ')', 'void'),
  \ javaapi#method(0,0,'dprintStatistics(', ')', 'void'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ ])

call javaapi#class('CorbaContactInfoBase', 'CorbaContactInfo', [
  \ javaapi#field(0,0,'orb', 'ORB'),
  \ javaapi#field(0,0,'contactInfoList', 'CorbaContactInfoList'),
  \ javaapi#field(0,0,'effectiveTargetIOR', 'IOR'),
  \ javaapi#field(0,0,'addressingDisposition', 'short'),
  \ javaapi#field(0,0,'connectionCache', 'OutboundConnectionCache'),
  \ javaapi#method(0,1,'CorbaContactInfoBase(', ')', ''),
  \ javaapi#method(0,1,'getBroker(', ')', 'Broker'),
  \ javaapi#method(0,1,'getContactInfoList(', ')', 'ContactInfoList'),
  \ javaapi#method(0,1,'getClientRequestDispatcher(', ')', 'ClientRequestDispatcher'),
  \ javaapi#method(0,1,'setConnectionCache(', 'OutboundConnectionCache)', 'void'),
  \ javaapi#method(0,1,'getConnectionCache(', ')', 'OutboundConnectionCache'),
  \ javaapi#method(0,1,'createMessageMediator(', 'Broker, ContactInfo, Connection, String, boolean)', 'MessageMediator'),
  \ javaapi#method(0,1,'createMessageMediator(', 'Broker, Connection)', 'MessageMediator'),
  \ javaapi#method(0,1,'finishCreatingMessageMediator(', 'Broker, Connection, MessageMediator)', 'MessageMediator'),
  \ javaapi#method(0,1,'createOutputObject(', 'MessageMediator)', 'OutputObject'),
  \ javaapi#method(0,1,'createInputObject(', 'Broker, MessageMediator)', 'InputObject'),
  \ javaapi#method(0,1,'getAddressingDisposition(', ')', 'short'),
  \ javaapi#method(0,1,'setAddressingDisposition(', 'short)', 'void'),
  \ javaapi#method(0,1,'getTargetIOR(', ')', 'IOR'),
  \ javaapi#method(0,1,'getEffectiveTargetIOR(', ')', 'IOR'),
  \ javaapi#method(0,1,'getEffectiveProfile(', ')', 'IIOPProfile'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ ])

call javaapi#class('CorbaContactInfoListImpl', 'CorbaContactInfoList', [
  \ javaapi#field(0,0,'orb', 'ORB'),
  \ javaapi#field(0,0,'LocalClientRequestDispatcher', 'LocalClientRequestDispatcher'),
  \ javaapi#field(0,0,'targetIOR', 'IOR'),
  \ javaapi#field(0,0,'effectiveTargetIOR', 'IOR'),
  \ javaapi#field(0,0,'effectiveTargetIORContactInfoList', 'List'),
  \ javaapi#field(0,0,'primaryContactInfo', 'ContactInfo'),
  \ javaapi#method(0,1,'CorbaContactInfoListImpl(', 'ORB)', ''),
  \ javaapi#method(0,1,'CorbaContactInfoListImpl(', 'ORB, IOR)', ''),
  \ javaapi#method(0,1,'iterator(', ')', 'Iterator'),
  \ javaapi#method(0,1,'setTargetIOR(', 'IOR)', 'void'),
  \ javaapi#method(0,1,'getTargetIOR(', ')', 'IOR'),
  \ javaapi#method(0,1,'setEffectiveTargetIOR(', 'IOR)', 'void'),
  \ javaapi#method(0,1,'getEffectiveTargetIOR(', ')', 'IOR'),
  \ javaapi#method(0,1,'getLocalClientRequestDispatcher(', ')', 'LocalClientRequestDispatcher'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,0,'createContactInfoList(', ')', 'void'),
  \ javaapi#method(0,0,'addRemoteContactInfos(', 'IOR, List)', 'void'),
  \ javaapi#method(0,0,'createContactInfo(', 'String, String, int)', 'ContactInfo'),
  \ javaapi#method(0,0,'setLocalSubcontract(', ')', 'void'),
  \ ])

call javaapi#class('CorbaContactInfoListIteratorImpl', 'CorbaContactInfoListIterator', [
  \ javaapi#field(0,0,'orb', 'ORB'),
  \ javaapi#field(0,0,'contactInfoList', 'CorbaContactInfoList'),
  \ javaapi#field(0,0,'successContactInfo', 'CorbaContactInfo'),
  \ javaapi#field(0,0,'failureContactInfo', 'CorbaContactInfo'),
  \ javaapi#field(0,0,'failureException', 'RuntimeException'),
  \ javaapi#field(0,0,'effectiveTargetIORIterator', 'Iterator'),
  \ javaapi#field(0,0,'previousContactInfo', 'CorbaContactInfo'),
  \ javaapi#field(0,0,'isAddrDispositionRetry', 'boolean'),
  \ javaapi#field(0,0,'primaryToContactInfo', 'IIOPPrimaryToContactInfo'),
  \ javaapi#field(0,0,'primaryContactInfo', 'ContactInfo'),
  \ javaapi#field(0,0,'listOfContactInfos', 'List'),
  \ javaapi#method(0,1,'CorbaContactInfoListIteratorImpl(', 'ORB, CorbaContactInfoList, ContactInfo, List)', ''),
  \ javaapi#method(0,1,'hasNext(', ')', 'boolean'),
  \ javaapi#method(0,1,'next(', ')', 'Object'),
  \ javaapi#method(0,1,'remove(', ')', 'void'),
  \ javaapi#method(0,1,'getContactInfoList(', ')', 'ContactInfoList'),
  \ javaapi#method(0,1,'reportSuccess(', 'ContactInfo)', 'void'),
  \ javaapi#method(0,1,'reportException(', 'ContactInfo, RuntimeException)', 'boolean'),
  \ javaapi#method(0,1,'getFailureException(', ')', 'RuntimeException'),
  \ javaapi#method(0,1,'reportAddrDispositionRetry(', 'CorbaContactInfo, short)', 'void'),
  \ javaapi#method(0,1,'reportRedirect(', 'CorbaContactInfo, IOR)', 'void'),
  \ javaapi#method(0,1,'updateEffectiveTargetIOR(', 'IOR)', 'void'),
  \ ])

call javaapi#class('CorbaInboundConnectionCacheImpl', 'CorbaConnectionCacheBase', [
  \ javaapi#field(0,0,'connectionCache', 'Collection'),
  \ javaapi#method(0,1,'CorbaInboundConnectionCacheImpl(', 'ORB, Acceptor)', ''),
  \ javaapi#method(0,1,'get(', 'Acceptor)', 'Connection'),
  \ javaapi#method(0,1,'put(', 'Acceptor, Connection)', 'void'),
  \ javaapi#method(0,1,'remove(', 'Connection)', 'void'),
  \ javaapi#method(0,1,'values(', ')', 'Collection'),
  \ javaapi#method(0,0,'backingStore(', ')', 'Object'),
  \ javaapi#method(0,0,'registerWithMonitoring(', ')', 'void'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ ])

call javaapi#class('CorbaOutboundConnectionCacheImpl', 'CorbaConnectionCacheBase', [
  \ javaapi#field(0,0,'connectionCache', 'Hashtable'),
  \ javaapi#method(0,1,'CorbaOutboundConnectionCacheImpl(', 'ORB, ContactInfo)', ''),
  \ javaapi#method(0,1,'get(', 'ContactInfo)', 'Connection'),
  \ javaapi#method(0,1,'put(', 'ContactInfo, Connection)', 'void'),
  \ javaapi#method(0,1,'remove(', 'ContactInfo)', 'void'),
  \ javaapi#method(0,1,'values(', ')', 'Collection'),
  \ javaapi#method(0,0,'backingStore(', ')', 'Object'),
  \ javaapi#method(0,0,'registerWithMonitoring(', ')', 'void'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ ])

call javaapi#class('CorbaResponseWaitingRoomImpl', 'CorbaResponseWaitingRoom', [
  \ javaapi#method(0,1,'CorbaResponseWaitingRoomImpl(', 'ORB, CorbaConnection)', ''),
  \ javaapi#method(0,1,'registerWaiter(', 'MessageMediator)', 'void'),
  \ javaapi#method(0,1,'unregisterWaiter(', 'MessageMediator)', 'void'),
  \ javaapi#method(0,1,'waitForResponse(', 'MessageMediator)', 'InputObject'),
  \ javaapi#method(0,1,'responseReceived(', 'InputObject)', 'void'),
  \ javaapi#method(0,1,'numberRegistered(', ')', 'int'),
  \ javaapi#method(0,1,'signalExceptionToAllWaiters(', 'SystemException)', 'void'),
  \ javaapi#method(0,1,'getMessageMediator(', 'int)', 'MessageMediator'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ javaapi#method(0,0,'opAndId(', 'CorbaMessageMediator)', 'String'),
  \ ])

call javaapi#class('CorbaTransportManagerImpl', 'CorbaTransportManager', [
  \ javaapi#field(0,0,'orb', 'ORB'),
  \ javaapi#field(0,0,'acceptors', 'List'),
  \ javaapi#field(0,0,'outboundConnectionCaches', 'Map'),
  \ javaapi#field(0,0,'inboundConnectionCaches', 'Map'),
  \ javaapi#field(0,0,'selector', 'Selector'),
  \ javaapi#method(0,1,'CorbaTransportManagerImpl(', 'ORB)', ''),
  \ javaapi#method(0,1,'getByteBufferPool(', 'int)', 'ByteBufferPool'),
  \ javaapi#method(0,1,'getOutboundConnectionCache(', 'ContactInfo)', 'OutboundConnectionCache'),
  \ javaapi#method(0,1,'getOutboundConnectionCaches(', ')', 'Collection'),
  \ javaapi#method(0,1,'getInboundConnectionCache(', 'Acceptor)', 'InboundConnectionCache'),
  \ javaapi#method(0,1,'getInboundConnectionCaches(', ')', 'Collection'),
  \ javaapi#method(0,1,'getSelector(', 'int)', 'Selector'),
  \ javaapi#method(0,1,'registerAcceptor(', 'Acceptor)', 'void'),
  \ javaapi#method(0,1,'getAcceptors(', ')', 'Collection'),
  \ javaapi#method(0,1,'unregisterAcceptor(', 'Acceptor)', 'void'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ javaapi#method(0,1,'getAcceptors(', 'String, ObjectAdapterId)', 'Collection'),
  \ javaapi#method(0,1,'addToIORTemplate(', 'IORTemplate, Policies, String, String, ObjectAdapterId)', 'void'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ ])

call javaapi#class('DefaultIORToSocketInfoImpl', 'IORToSocketInfo', [
  \ javaapi#method(0,1,'DefaultIORToSocketInfoImpl(', ')', ''),
  \ javaapi#method(0,1,'getSocketInfo(', 'IOR)', 'List'),
  \ ])

call javaapi#class('DefaultSocketFactoryImpl', 'ORBSocketFactory', [
  \ javaapi#method(0,1,'DefaultSocketFactoryImpl(', ')', ''),
  \ javaapi#method(0,1,'setORB(', 'ORB)', 'void'),
  \ javaapi#method(0,1,'createServerSocket(', 'String, InetSocketAddress) throws IOException', 'ServerSocket'),
  \ javaapi#method(0,1,'createSocket(', 'String, InetSocketAddress) throws IOException', 'Socket'),
  \ javaapi#method(0,1,'setAcceptedSocketOptions(', 'Acceptor, ServerSocket, Socket) throws SocketException', 'void'),
  \ ])

call javaapi#class('EventHandlerBase', 'EventHandler', [
  \ javaapi#field(0,0,'orb', 'ORB'),
  \ javaapi#field(0,0,'work', 'Work'),
  \ javaapi#field(0,0,'useWorkerThreadForEvent', 'boolean'),
  \ javaapi#field(0,0,'useSelectThreadToWait', 'boolean'),
  \ javaapi#field(0,0,'selectionKey', 'SelectionKey'),
  \ javaapi#method(0,1,'EventHandlerBase(', ')', ''),
  \ javaapi#method(0,1,'setUseSelectThreadToWait(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'shouldUseSelectThreadToWait(', ')', 'boolean'),
  \ javaapi#method(0,1,'setSelectionKey(', 'SelectionKey)', 'void'),
  \ javaapi#method(0,1,'getSelectionKey(', ')', 'SelectionKey'),
  \ javaapi#method(0,1,'handleEvent(', ')', 'void'),
  \ javaapi#method(0,1,'shouldUseWorkerThreadForEvent(', ')', 'boolean'),
  \ javaapi#method(0,1,'setUseWorkerThreadForEvent(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'setWork(', 'Work)', 'void'),
  \ javaapi#method(0,1,'getWork(', ')', 'Work'),
  \ ])

call javaapi#class('ListenerThreadImpl', 'Work', [
  \ javaapi#method(0,1,'ListenerThreadImpl(', 'ORB, Acceptor, Selector)', ''),
  \ javaapi#method(0,1,'getAcceptor(', ')', 'Acceptor'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ javaapi#method(0,1,'doWork(', ')', 'void'),
  \ javaapi#method(0,1,'setEnqueueTime(', 'long)', 'void'),
  \ javaapi#method(0,1,'getEnqueueTime(', ')', 'long'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('ReadTCPTimeoutsImpl', 'ReadTimeouts', [
  \ javaapi#method(0,1,'ReadTCPTimeoutsImpl(', 'int, int, int, int)', ''),
  \ javaapi#method(0,1,'get_initial_time_to_wait(', ')', 'int'),
  \ javaapi#method(0,1,'get_max_time_to_wait(', ')', 'int'),
  \ javaapi#method(0,1,'get_backoff_factor(', ')', 'double'),
  \ javaapi#method(0,1,'get_max_giop_header_time_to_wait(', ')', 'int'),
  \ ])

call javaapi#class('ReaderThreadImpl', 'Work', [
  \ javaapi#method(0,1,'ReaderThreadImpl(', 'ORB, Connection, Selector)', ''),
  \ javaapi#method(0,1,'getConnection(', ')', 'Connection'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ javaapi#method(0,1,'doWork(', ')', 'void'),
  \ javaapi#method(0,1,'setEnqueueTime(', 'long)', 'void'),
  \ javaapi#method(0,1,'getEnqueueTime(', ')', 'long'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,0,'dprint(', 'String, Throwable)', 'void'),
  \ ])

call javaapi#class('SelectorImpl', 'Thread', [
  \ javaapi#method(0,1,'SelectorImpl(', 'ORB)', ''),
  \ javaapi#method(0,1,'setTimeout(', 'long)', 'void'),
  \ javaapi#method(0,1,'getTimeout(', ')', 'long'),
  \ javaapi#method(0,1,'registerInterestOps(', 'EventHandler)', 'void'),
  \ javaapi#method(0,1,'registerForEvent(', 'EventHandler)', 'void'),
  \ javaapi#method(0,1,'unregisterForEvent(', 'EventHandler)', 'void'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ javaapi#method(0,1,'run(', ')', 'void'),
  \ javaapi#method(0,0,'dprint(', 'String, Throwable)', 'void'),
  \ ])

call javaapi#class('SharedCDRContactInfoImpl', 'CorbaContactInfoBase', [
  \ javaapi#field(0,0,'wrapper', 'ORBUtilSystemException'),
  \ javaapi#method(0,1,'SharedCDRContactInfoImpl(', 'ORB, CorbaContactInfoList, IOR, short)', ''),
  \ javaapi#method(0,1,'getClientRequestDispatcher(', ')', 'ClientRequestDispatcher'),
  \ javaapi#method(0,1,'isConnectionBased(', ')', 'boolean'),
  \ javaapi#method(0,1,'shouldCacheConnection(', ')', 'boolean'),
  \ javaapi#method(0,1,'getConnectionCacheType(', ')', 'String'),
  \ javaapi#method(0,1,'createConnection(', ')', 'Connection'),
  \ javaapi#method(0,1,'createMessageMediator(', 'Broker, ContactInfo, Connection, String, boolean)', 'MessageMediator'),
  \ javaapi#method(0,1,'createOutputObject(', 'MessageMediator)', 'OutputObject'),
  \ javaapi#method(0,1,'getMonitoringName(', ')', 'String'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,0,'getWrapper(', ')', 'ORBUtilSystemException'),
  \ ])

call javaapi#class('SocketOrChannelAcceptorImpl', 'EventHandlerBase', [
  \ javaapi#field(0,0,'serverSocketChannel', 'ServerSocketChannel'),
  \ javaapi#field(0,0,'serverSocket', 'ServerSocket'),
  \ javaapi#field(0,0,'port', 'int'),
  \ javaapi#field(0,0,'enqueueTime', 'long'),
  \ javaapi#field(0,0,'initialized', 'boolean'),
  \ javaapi#field(0,0,'wrapper', 'ORBUtilSystemException'),
  \ javaapi#field(0,0,'connectionCache', 'InboundConnectionCache'),
  \ javaapi#field(0,0,'type', 'String'),
  \ javaapi#field(0,0,'name', 'String'),
  \ javaapi#field(0,0,'hostname', 'String'),
  \ javaapi#field(0,0,'locatorPort', 'int'),
  \ javaapi#method(0,1,'SocketOrChannelAcceptorImpl(', 'ORB)', ''),
  \ javaapi#method(0,1,'SocketOrChannelAcceptorImpl(', 'ORB, int)', ''),
  \ javaapi#method(0,1,'SocketOrChannelAcceptorImpl(', 'ORB, int, String, String)', ''),
  \ javaapi#method(0,1,'initialize(', ')', 'boolean'),
  \ javaapi#method(0,0,'internalInitialize(', ') throws Exception', 'void'),
  \ javaapi#method(0,1,'initialized(', ')', 'boolean'),
  \ javaapi#method(0,1,'getConnectionCacheType(', ')', 'String'),
  \ javaapi#method(0,1,'setConnectionCache(', 'InboundConnectionCache)', 'void'),
  \ javaapi#method(0,1,'getConnectionCache(', ')', 'InboundConnectionCache'),
  \ javaapi#method(0,1,'shouldRegisterAcceptEvent(', ')', 'boolean'),
  \ javaapi#method(0,1,'accept(', ')', 'void'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ javaapi#method(0,1,'getEventHandler(', ')', 'EventHandler'),
  \ javaapi#method(0,1,'getObjectAdapterId(', ')', 'String'),
  \ javaapi#method(0,1,'getObjectAdapterManagerId(', ')', 'String'),
  \ javaapi#method(0,1,'addToIORTemplate(', 'IORTemplate, Policies, String)', 'void'),
  \ javaapi#method(0,1,'getMonitoringName(', ')', 'String'),
  \ javaapi#method(0,1,'getChannel(', ')', 'SelectableChannel'),
  \ javaapi#method(0,1,'getInterestOps(', ')', 'int'),
  \ javaapi#method(0,1,'getAcceptor(', ')', 'Acceptor'),
  \ javaapi#method(0,1,'getConnection(', ')', 'Connection'),
  \ javaapi#method(0,1,'doWork(', ')', 'void'),
  \ javaapi#method(0,1,'setEnqueueTime(', 'long)', 'void'),
  \ javaapi#method(0,1,'getEnqueueTime(', ')', 'long'),
  \ javaapi#method(0,1,'createMessageMediator(', 'Broker, Connection)', 'MessageMediator'),
  \ javaapi#method(0,1,'finishCreatingMessageMediator(', 'Broker, Connection, MessageMediator)', 'MessageMediator'),
  \ javaapi#method(0,1,'createInputObject(', 'Broker, MessageMediator)', 'InputObject'),
  \ javaapi#method(0,1,'createOutputObject(', 'Broker, MessageMediator)', 'OutputObject'),
  \ javaapi#method(0,1,'getServerSocket(', ')', 'ServerSocket'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,0,'toStringName(', ')', 'String'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ javaapi#method(0,0,'dprint(', 'String, Throwable)', 'void'),
  \ javaapi#method(0,1,'getType(', ')', 'String'),
  \ javaapi#method(0,1,'getHostName(', ')', 'String'),
  \ javaapi#method(0,1,'getHost(', ')', 'String'),
  \ javaapi#method(0,1,'getPort(', ')', 'int'),
  \ javaapi#method(0,1,'getLocatorPort(', ')', 'int'),
  \ javaapi#method(0,1,'setLocatorPort(', 'int)', 'void'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('SocketOrChannelConnectionImpl', 'EventHandlerBase', [
  \ javaapi#field(1,1,'dprintWriteLocks', 'boolean'),
  \ javaapi#field(0,0,'enqueueTime', 'long'),
  \ javaapi#field(0,0,'socketChannel', 'SocketChannel'),
  \ javaapi#field(0,0,'contactInfo', 'CorbaContactInfo'),
  \ javaapi#field(0,0,'acceptor', 'Acceptor'),
  \ javaapi#field(0,0,'connectionCache', 'ConnectionCache'),
  \ javaapi#field(0,0,'socket', 'Socket'),
  \ javaapi#field(0,0,'timeStamp', 'long'),
  \ javaapi#field(0,0,'isServer', 'boolean'),
  \ javaapi#field(0,0,'requestId', 'int'),
  \ javaapi#field(0,0,'responseWaitingRoom', 'CorbaResponseWaitingRoom'),
  \ javaapi#field(0,0,'state', 'int'),
  \ javaapi#field(0,0,'stateEvent', 'Object'),
  \ javaapi#field(0,0,'writeEvent', 'Object'),
  \ javaapi#field(0,0,'writeLocked', 'boolean'),
  \ javaapi#field(0,0,'serverRequestCount', 'int'),
  \ javaapi#field(0,0,'postInitialContexts', 'boolean'),
  \ javaapi#field(0,0,'codeBaseServerIOR', 'IOR'),
  \ javaapi#field(0,0,'cachedCodeBase', 'CachedCodeBase'),
  \ javaapi#field(0,0,'wrapper', 'ORBUtilSystemException'),
  \ javaapi#field(0,0,'readTimeouts', 'ReadTimeouts'),
  \ javaapi#field(0,0,'shouldReadGiopHeaderOnly', 'boolean'),
  \ javaapi#field(0,0,'partialMessageMediator', 'CorbaMessageMediator'),
  \ javaapi#field(0,0,'codeSetContext', 'CodeSetContext'),
  \ javaapi#field(0,0,'clientReply_1_1', 'MessageMediator'),
  \ javaapi#field(0,0,'serverRequest_1_1', 'MessageMediator'),
  \ javaapi#method(0,1,'getSocketChannel(', ')', 'SocketChannel'),
  \ javaapi#method(0,0,'SocketOrChannelConnectionImpl(', 'ORB)', ''),
  \ javaapi#method(0,0,'SocketOrChannelConnectionImpl(', 'ORB, boolean, boolean)', ''),
  \ javaapi#method(0,1,'SocketOrChannelConnectionImpl(', 'ORB, CorbaContactInfo, boolean, boolean, String, String, int)', ''),
  \ javaapi#method(0,1,'SocketOrChannelConnectionImpl(', 'ORB, CorbaContactInfo, String, String, int)', ''),
  \ javaapi#method(0,1,'SocketOrChannelConnectionImpl(', 'ORB, Acceptor, Socket, boolean, boolean)', ''),
  \ javaapi#method(0,1,'SocketOrChannelConnectionImpl(', 'ORB, Acceptor, Socket)', ''),
  \ javaapi#method(0,1,'shouldRegisterReadEvent(', ')', 'boolean'),
  \ javaapi#method(0,1,'shouldRegisterServerReadEvent(', ')', 'boolean'),
  \ javaapi#method(0,1,'read(', ')', 'boolean'),
  \ javaapi#method(0,0,'readBits(', ')', 'CorbaMessageMediator'),
  \ javaapi#method(0,0,'finishReadingBits(', 'MessageMediator)', 'CorbaMessageMediator'),
  \ javaapi#method(0,0,'dispatch(', 'CorbaMessageMediator)', 'boolean'),
  \ javaapi#method(0,1,'shouldUseDirectByteBuffers(', ')', 'boolean'),
  \ javaapi#method(0,1,'read(', 'int, int, int, long) throws IOException', 'ByteBuffer'),
  \ javaapi#method(0,1,'read(', 'ByteBuffer, int, int, long) throws IOException', 'ByteBuffer'),
  \ javaapi#method(0,1,'readFully(', 'ByteBuffer, int, long) throws IOException', 'void'),
  \ javaapi#method(0,1,'readFully(', 'InputStream, byte[], int, int, long) throws IOException', 'void'),
  \ javaapi#method(0,1,'write(', 'ByteBuffer) throws IOException', 'void'),
  \ javaapi#method(0,1,'close(', ')', 'void'),
  \ javaapi#method(0,1,'closeConnectionResources(', ')', 'void'),
  \ javaapi#method(0,1,'getAcceptor(', ')', 'Acceptor'),
  \ javaapi#method(0,1,'getContactInfo(', ')', 'ContactInfo'),
  \ javaapi#method(0,1,'getEventHandler(', ')', 'EventHandler'),
  \ javaapi#method(0,1,'createOutputObject(', 'MessageMediator)', 'OutputObject'),
  \ javaapi#method(0,1,'isServer(', ')', 'boolean'),
  \ javaapi#method(0,1,'isBusy(', ')', 'boolean'),
  \ javaapi#method(0,1,'getTimeStamp(', ')', 'long'),
  \ javaapi#method(0,1,'setTimeStamp(', 'long)', 'void'),
  \ javaapi#method(0,1,'setState(', 'String)', 'void'),
  \ javaapi#method(0,1,'writeLock(', ')', 'void'),
  \ javaapi#method(0,1,'writeUnlock(', ')', 'void'),
  \ javaapi#method(0,1,'sendWithoutLock(', 'OutputObject)', 'void'),
  \ javaapi#method(0,1,'registerWaiter(', 'MessageMediator)', 'void'),
  \ javaapi#method(0,1,'unregisterWaiter(', 'MessageMediator)', 'void'),
  \ javaapi#method(0,1,'waitForResponse(', 'MessageMediator)', 'InputObject'),
  \ javaapi#method(0,1,'setConnectionCache(', 'ConnectionCache)', 'void'),
  \ javaapi#method(0,1,'getConnectionCache(', ')', 'ConnectionCache'),
  \ javaapi#method(0,1,'setUseSelectThreadToWait(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'handleEvent(', ')', 'void'),
  \ javaapi#method(0,1,'getChannel(', ')', 'SelectableChannel'),
  \ javaapi#method(0,1,'getInterestOps(', ')', 'int'),
  \ javaapi#method(0,1,'getConnection(', ')', 'Connection'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'doWork(', ')', 'void'),
  \ javaapi#method(0,1,'setEnqueueTime(', 'long)', 'void'),
  \ javaapi#method(0,1,'getEnqueueTime(', ')', 'long'),
  \ javaapi#method(0,1,'shouldReadGiopHeaderOnly(', ')', 'boolean'),
  \ javaapi#method(0,0,'setReadGiopHeaderOnly(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getResponseWaitingRoom(', ')', 'ResponseWaitingRoom'),
  \ javaapi#method(0,1,'serverRequestMapPut(', 'int, CorbaMessageMediator)', 'void'),
  \ javaapi#method(0,1,'serverRequestMapGet(', 'int)', 'CorbaMessageMediator'),
  \ javaapi#method(0,1,'serverRequestMapRemove(', 'int)', 'void'),
  \ javaapi#method(0,1,'getSocket(', ')', 'Socket'),
  \ javaapi#method(0,1,'serverRequestProcessingBegins(', ')', 'void'),
  \ javaapi#method(0,1,'serverRequestProcessingEnds(', ')', 'void'),
  \ javaapi#method(0,1,'getNextRequestId(', ')', 'int'),
  \ javaapi#method(0,1,'getBroker(', ')', 'ORB'),
  \ javaapi#method(0,1,'getCodeSetContext(', ')', 'CodeSetContext'),
  \ javaapi#method(0,1,'setCodeSetContext(', 'CodeSetContext)', 'void'),
  \ javaapi#method(0,1,'clientRequestMapGet(', 'int)', 'MessageMediator'),
  \ javaapi#method(0,1,'clientReply_1_1_Put(', 'MessageMediator)', 'void'),
  \ javaapi#method(0,1,'clientReply_1_1_Get(', ')', 'MessageMediator'),
  \ javaapi#method(0,1,'clientReply_1_1_Remove(', ')', 'void'),
  \ javaapi#method(0,1,'serverRequest_1_1_Put(', 'MessageMediator)', 'void'),
  \ javaapi#method(0,1,'serverRequest_1_1_Get(', ')', 'MessageMediator'),
  \ javaapi#method(0,1,'serverRequest_1_1_Remove(', ')', 'void'),
  \ javaapi#method(0,0,'getStateString(', 'int)', 'String'),
  \ javaapi#method(0,1,'isPostInitialContexts(', ')', 'boolean'),
  \ javaapi#method(0,1,'setPostInitialContexts(', ')', 'void'),
  \ javaapi#method(0,1,'purgeCalls(', 'SystemException, boolean, boolean)', 'void'),
  \ javaapi#method(0,1,'sendCloseConnection(', 'GIOPVersion) throws IOException', 'void'),
  \ javaapi#method(0,1,'sendMessageError(', 'GIOPVersion) throws IOException', 'void'),
  \ javaapi#method(0,1,'sendCancelRequest(', 'GIOPVersion, int) throws IOException', 'void'),
  \ javaapi#method(0,0,'sendHelper(', 'GIOPVersion, Message) throws IOException', 'void'),
  \ javaapi#method(0,1,'sendCancelRequestWithLock(', 'GIOPVersion, int) throws IOException', 'void'),
  \ javaapi#method(0,1,'setCodeBaseIOR(', 'IOR)', 'void'),
  \ javaapi#method(0,1,'getCodeBaseIOR(', ')', 'IOR'),
  \ javaapi#method(0,1,'getCodeBase(', ')', 'CodeBase'),
  \ javaapi#method(0,0,'setReadTimeouts(', 'ReadTimeouts)', 'void'),
  \ javaapi#method(0,0,'setPartialMessageMediator(', 'CorbaMessageMediator)', 'void'),
  \ javaapi#method(0,0,'getPartialMessageMediator(', ')', 'CorbaMessageMediator'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'dprint(', 'String)', 'void'),
  \ javaapi#method(0,0,'dprint(', 'String, Throwable)', 'void'),
  \ ])

call javaapi#class('SocketOrChannelContactInfoImpl', 'CorbaContactInfoBase', [
  \ javaapi#field(0,0,'isHashCodeCached', 'boolean'),
  \ javaapi#field(0,0,'cachedHashCode', 'int'),
  \ javaapi#field(0,0,'socketType', 'String'),
  \ javaapi#field(0,0,'hostname', 'String'),
  \ javaapi#field(0,0,'port', 'int'),
  \ javaapi#method(0,0,'SocketOrChannelContactInfoImpl(', ')', ''),
  \ javaapi#method(0,0,'SocketOrChannelContactInfoImpl(', 'ORB, CorbaContactInfoList)', ''),
  \ javaapi#method(0,1,'SocketOrChannelContactInfoImpl(', 'ORB, CorbaContactInfoList, String, String, int)', ''),
  \ javaapi#method(0,1,'SocketOrChannelContactInfoImpl(', 'ORB, CorbaContactInfoList, IOR, short, String, String, int)', ''),
  \ javaapi#method(0,1,'isConnectionBased(', ')', 'boolean'),
  \ javaapi#method(0,1,'shouldCacheConnection(', ')', 'boolean'),
  \ javaapi#method(0,1,'getConnectionCacheType(', ')', 'String'),
  \ javaapi#method(0,1,'createConnection(', ')', 'Connection'),
  \ javaapi#method(0,1,'getMonitoringName(', ')', 'String'),
  \ javaapi#method(0,1,'getType(', ')', 'String'),
  \ javaapi#method(0,1,'getHost(', ')', 'String'),
  \ javaapi#method(0,1,'getPort(', ')', 'int'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,0,'dprint(', 'String)', 'void'),
  \ ])

