call javaapi#namespace('com.sun.java_cup.internal.runtime')

call javaapi#interface('Scanner', '', [
  \ javaapi#method(0,1,'next_token(', ') throws Exception', 'Symbol'),
  \ ])

call javaapi#class('Symbol', '', [
  \ javaapi#field(0,1,'sym', 'int'),
  \ javaapi#field(0,1,'parse_state', 'int'),
  \ javaapi#field(0,1,'left', 'int'),
  \ javaapi#field(0,1,'right', 'int'),
  \ javaapi#field(0,1,'value', 'Object'),
  \ javaapi#method(0,1,'Symbol(', 'int, int, int, Object)', ''),
  \ javaapi#method(0,1,'Symbol(', 'int, Object)', ''),
  \ javaapi#method(0,1,'Symbol(', 'int, int, int)', ''),
  \ javaapi#method(0,1,'Symbol(', 'int)', ''),
  \ javaapi#method(0,1,'Symbol(', 'int, int)', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('lr_parser', '', [
  \ javaapi#field(1,0,'_error_sync_size', 'int'),
  \ javaapi#field(0,0,'_done_parsing', 'boolean'),
  \ javaapi#field(0,0,'tos', 'int'),
  \ javaapi#field(0,0,'cur_token', 'Symbol'),
  \ javaapi#field(0,0,'stack', 'Stack'),
  \ javaapi#field(0,0,'production_tab', 'short[][]'),
  \ javaapi#field(0,0,'action_tab', 'short[][]'),
  \ javaapi#field(0,0,'reduce_tab', 'short[][]'),
  \ javaapi#field(0,0,'lookahead', 'Symbol[]'),
  \ javaapi#field(0,0,'lookahead_pos', 'int'),
  \ javaapi#method(0,1,'lr_parser(', ')', ''),
  \ javaapi#method(0,1,'lr_parser(', 'Scanner)', ''),
  \ javaapi#method(0,0,'error_sync_size(', ')', 'int'),
  \ javaapi#method(0,1,'production_table(', ')', 'short[][]'),
  \ javaapi#method(0,1,'action_table(', ')', 'short[][]'),
  \ javaapi#method(0,1,'reduce_table(', ')', 'short[][]'),
  \ javaapi#method(0,1,'start_state(', ')', 'int'),
  \ javaapi#method(0,1,'start_production(', ')', 'int'),
  \ javaapi#method(0,1,'EOF_sym(', ')', 'int'),
  \ javaapi#method(0,1,'error_sym(', ')', 'int'),
  \ javaapi#method(0,1,'done_parsing(', ')', 'void'),
  \ javaapi#method(0,1,'setScanner(', 'Scanner)', 'void'),
  \ javaapi#method(0,1,'getScanner(', ')', 'Scanner'),
  \ javaapi#method(0,1,'do_action(', 'int, lr_parser, Stack, int) throws Exception', 'Symbol'),
  \ javaapi#method(0,1,'user_init(', ') throws Exception', 'void'),
  \ javaapi#method(0,0,'init_actions(', ') throws Exception', 'void'),
  \ javaapi#method(0,1,'scan(', ') throws Exception', 'Symbol'),
  \ javaapi#method(0,1,'report_fatal_error(', 'String, Object) throws Exception', 'void'),
  \ javaapi#method(0,1,'report_error(', 'String, Object)', 'void'),
  \ javaapi#method(0,1,'syntax_error(', 'Symbol)', 'void'),
  \ javaapi#method(0,1,'unrecovered_syntax_error(', 'Symbol) throws Exception', 'void'),
  \ javaapi#method(0,0,'get_action(', 'int, int)', 'short'),
  \ javaapi#method(0,0,'get_reduce(', 'int, int)', 'short'),
  \ javaapi#method(0,1,'parse(', ') throws Exception', 'Symbol'),
  \ javaapi#method(0,1,'debug_message(', 'String)', 'void'),
  \ javaapi#method(0,1,'dump_stack(', ')', 'void'),
  \ javaapi#method(0,1,'debug_reduce(', 'int, int, int)', 'void'),
  \ javaapi#method(0,1,'debug_shift(', 'Symbol)', 'void'),
  \ javaapi#method(0,1,'debug_stack(', ')', 'void'),
  \ javaapi#method(0,1,'debug_parse(', ') throws Exception', 'Symbol'),
  \ javaapi#method(0,0,'error_recovery(', 'boolean) throws Exception', 'boolean'),
  \ javaapi#method(0,0,'shift_under_error(', ')', 'boolean'),
  \ javaapi#method(0,0,'find_recovery_config(', 'boolean)', 'boolean'),
  \ javaapi#method(0,0,'read_lookahead(', ') throws Exception', 'void'),
  \ javaapi#method(0,0,'cur_err_token(', ')', 'Symbol'),
  \ javaapi#method(0,0,'advance_lookahead(', ')', 'boolean'),
  \ javaapi#method(0,0,'restart_lookahead(', ') throws Exception', 'void'),
  \ javaapi#method(0,0,'try_parse_ahead(', 'boolean) throws Exception', 'boolean'),
  \ javaapi#method(0,0,'parse_lookahead(', 'boolean) throws Exception', 'void'),
  \ javaapi#method(1,0,'unpackFromStrings(', 'String[])', 'short[][]'),
  \ ])

call javaapi#class('virtual_parse_stack', '', [
  \ javaapi#field(0,0,'real_stack', 'Stack'),
  \ javaapi#field(0,0,'real_next', 'int'),
  \ javaapi#field(0,0,'vstack', 'Stack'),
  \ javaapi#method(0,1,'virtual_parse_stack(', 'Stack) throws Exception', ''),
  \ javaapi#method(0,0,'get_from_real(', ')', 'void'),
  \ javaapi#method(0,1,'empty(', ')', 'boolean'),
  \ javaapi#method(0,1,'top(', ') throws Exception', 'int'),
  \ javaapi#method(0,1,'pop(', ') throws Exception', 'void'),
  \ javaapi#method(0,1,'push(', 'int)', 'void'),
  \ ])

