call javaapi#namespace('com.sun.corba.se.impl.dynamicany')

call javaapi#class('DynAnyBasicImpl', 'DynAnyImpl', [
  \ javaapi#method(0,0,'DynAnyBasicImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynAnyBasicImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,1,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'to_any(', ')', 'Any'),
  \ javaapi#method(0,1,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,1,'destroy(', ')', 'void'),
  \ javaapi#method(0,1,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,1,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,1,'component_count(', ')', 'int'),
  \ javaapi#method(0,1,'next(', ')', 'boolean'),
  \ javaapi#method(0,1,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'rewind(', ')', 'void'),
  \ javaapi#method(0,1,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,1,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,1,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,1,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,1,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,1,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,1,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,1,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,1,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,1,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynAnyCollectionImpl', 'DynAnyConstructedImpl', [
  \ javaapi#method(0,0,'DynAnyCollectionImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynAnyCollectionImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,0,'createDefaultComponentAt(', 'int, TypeCode)', 'void'),
  \ javaapi#method(0,0,'getContentType(', ')', 'TypeCode'),
  \ javaapi#method(0,0,'getBound(', ')', 'int'),
  \ javaapi#method(0,1,'get_elements(', ')', 'Any[]'),
  \ javaapi#method(0,0,'checkValue(', 'Object[]) throws InvalidValue', 'void'),
  \ javaapi#method(0,1,'set_elements(', 'Any[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'get_elements_as_dyn_any(', ')', 'DynAny[]'),
  \ javaapi#method(0,1,'set_elements_as_dyn_any(', 'DynAny[]) throws TypeMismatch, InvalidValue', 'void'),
  \ ])

call javaapi#class('DynAnyComplexImpl', 'DynAnyConstructedImpl', [
  \ javaapi#method(0,0,'DynAnyComplexImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynAnyComplexImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,1,'current_member_name(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'current_member_kind(', ') throws TypeMismatch, InvalidValue', 'TCKind'),
  \ javaapi#method(0,1,'set_members(', 'NameValuePair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'set_members_as_dyn_any(', 'NameDynAnyPair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,0,'initializeComponentsFromAny(', ')', 'boolean'),
  \ javaapi#method(0,0,'initializeComponentsFromTypeCode(', ')', 'boolean'),
  \ javaapi#method(0,0,'clearData(', ')', 'void'),
  \ ])

call javaapi#class('DynAnyConstructedImpl', 'DynAnyImpl', [
  \ javaapi#field(1,0,'REPRESENTATION_NONE', 'byte'),
  \ javaapi#field(1,0,'REPRESENTATION_TYPECODE', 'byte'),
  \ javaapi#field(1,0,'REPRESENTATION_ANY', 'byte'),
  \ javaapi#field(1,0,'REPRESENTATION_COMPONENTS', 'byte'),
  \ javaapi#field(1,0,'RECURSIVE_UNDEF', 'byte'),
  \ javaapi#field(1,0,'RECURSIVE_NO', 'byte'),
  \ javaapi#field(1,0,'RECURSIVE_YES', 'byte'),
  \ javaapi#field(1,0,'emptyComponents', 'DynAny[]'),
  \ javaapi#method(0,0,'DynAnyConstructedImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynAnyConstructedImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,0,'isRecursive(', ')', 'boolean'),
  \ javaapi#method(0,1,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,1,'component_count(', ')', 'int'),
  \ javaapi#method(0,1,'next(', ')', 'boolean'),
  \ javaapi#method(0,1,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'rewind(', ')', 'void'),
  \ javaapi#method(0,0,'clearData(', ')', 'void'),
  \ javaapi#method(0,0,'writeAny(', 'OutputStream)', 'void'),
  \ javaapi#method(0,0,'checkInitComponents(', ')', 'boolean'),
  \ javaapi#method(0,0,'checkInitAny(', ')', 'void'),
  \ javaapi#method(0,0,'initializeComponentsFromAny(', ')', 'boolean'),
  \ javaapi#method(0,0,'initializeComponentsFromTypeCode(', ')', 'boolean'),
  \ javaapi#method(0,0,'initializeAnyFromComponents(', ')', 'boolean'),
  \ javaapi#method(0,1,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'to_any(', ')', 'Any'),
  \ javaapi#method(0,1,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,1,'destroy(', ')', 'void'),
  \ javaapi#method(0,1,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,1,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,1,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,1,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,1,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,1,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,1,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,1,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,1,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,1,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ ])

call javaapi#class('DynAnyFactoryImpl', 'LocalObject', [
  \ javaapi#method(0,1,'DynAnyFactoryImpl(', 'ORB)', ''),
  \ javaapi#method(0,1,'create_dyn_any(', 'Any) throws InconsistentTypeCode', 'DynAny'),
  \ javaapi#method(0,1,'create_dyn_any_from_type_code(', 'TypeCode) throws InconsistentTypeCode', 'DynAny'),
  \ javaapi#method(0,1,'_ids(', ')', 'String[]'),
  \ ])

call javaapi#class('DynAnyImpl', 'LocalObject', [
  \ javaapi#field(1,0,'NO_INDEX', 'int'),
  \ javaapi#field(1,0,'STATUS_DESTROYABLE', 'byte'),
  \ javaapi#field(1,0,'STATUS_UNDESTROYABLE', 'byte'),
  \ javaapi#field(1,0,'STATUS_DESTROYED', 'byte'),
  \ javaapi#field(0,0,'orb', 'ORB'),
  \ javaapi#field(0,0,'wrapper', 'ORBUtilSystemException'),
  \ javaapi#field(0,0,'any', 'Any'),
  \ javaapi#field(0,0,'status', 'byte'),
  \ javaapi#field(0,0,'index', 'int'),
  \ javaapi#method(0,0,'DynAnyImpl(', ')', ''),
  \ javaapi#method(0,0,'DynAnyImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynAnyImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,0,'factory(', ')', 'DynAnyFactory'),
  \ javaapi#method(0,0,'getAny(', ')', 'Any'),
  \ javaapi#method(0,0,'getAny(', 'DynAny)', 'Any'),
  \ javaapi#method(0,0,'writeAny(', 'OutputStream)', 'void'),
  \ javaapi#method(0,0,'setStatus(', 'byte)', 'void'),
  \ javaapi#method(0,0,'clearData(', ')', 'void'),
  \ javaapi#method(0,1,'type(', ')', 'TypeCode'),
  \ javaapi#method(0,1,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'to_any(', ')', 'Any'),
  \ javaapi#method(0,1,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,1,'destroy(', ')', 'void'),
  \ javaapi#method(0,1,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,1,'_ids(', ')', 'String[]'),
  \ ])

call javaapi#class('DynAnyUtil', '', [
  \ javaapi#method(0,1,'DynAnyUtil(', ')', ''),
  \ ])

call javaapi#class('DynArrayImpl', 'DynAnyCollectionImpl', [
  \ javaapi#method(0,0,'DynArrayImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynArrayImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,0,'initializeComponentsFromAny(', ')', 'boolean'),
  \ javaapi#method(0,0,'initializeComponentsFromTypeCode(', ')', 'boolean'),
  \ javaapi#method(0,0,'checkValue(', 'Object[]) throws InvalidValue', 'void'),
  \ javaapi#method(0,1,'set_elements_as_dyn_any(', 'DynAny[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'get_elements_as_dyn_any(', ')', 'DynAny[]'),
  \ javaapi#method(0,1,'set_elements(', 'Any[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'get_elements(', ')', 'Any[]'),
  \ javaapi#method(0,1,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,1,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,1,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,1,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,1,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,1,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,1,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,1,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,1,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,1,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,1,'destroy(', ')', 'void'),
  \ javaapi#method(0,1,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,1,'to_any(', ')', 'Any'),
  \ javaapi#method(0,1,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'rewind(', ')', 'void'),
  \ javaapi#method(0,1,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'next(', ')', 'boolean'),
  \ javaapi#method(0,1,'component_count(', ')', 'int'),
  \ javaapi#method(0,1,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,1,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynEnumImpl', 'DynAnyBasicImpl', [
  \ javaapi#method(0,0,'DynEnumImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynEnumImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,1,'component_count(', ')', 'int'),
  \ javaapi#method(0,1,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,1,'get_as_string(', ')', 'String'),
  \ javaapi#method(0,1,'set_as_string(', 'String) throws InvalidValue', 'void'),
  \ javaapi#method(0,1,'get_as_ulong(', ')', 'int'),
  \ javaapi#method(0,1,'set_as_ulong(', 'int) throws InvalidValue', 'void'),
  \ ])

call javaapi#class('DynFixedImpl', 'DynAnyBasicImpl', [
  \ javaapi#method(0,0,'DynFixedImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynFixedImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,1,'get_value(', ')', 'String'),
  \ javaapi#method(0,1,'set_value(', 'String) throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('DynSequenceImpl', 'DynAnyCollectionImpl', [
  \ javaapi#method(0,0,'DynSequenceImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynSequenceImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,0,'initializeComponentsFromAny(', ')', 'boolean'),
  \ javaapi#method(0,0,'initializeComponentsFromTypeCode(', ')', 'boolean'),
  \ javaapi#method(0,0,'initializeAnyFromComponents(', ')', 'boolean'),
  \ javaapi#method(0,1,'get_length(', ')', 'int'),
  \ javaapi#method(0,1,'set_length(', 'int) throws InvalidValue', 'void'),
  \ javaapi#method(0,0,'checkValue(', 'Object[]) throws InvalidValue', 'void'),
  \ javaapi#method(0,1,'set_elements_as_dyn_any(', 'DynAny[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'get_elements_as_dyn_any(', ')', 'DynAny[]'),
  \ javaapi#method(0,1,'set_elements(', 'Any[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'get_elements(', ')', 'Any[]'),
  \ javaapi#method(0,1,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,1,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,1,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,1,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,1,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,1,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,1,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,1,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,1,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,1,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,1,'destroy(', ')', 'void'),
  \ javaapi#method(0,1,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,1,'to_any(', ')', 'Any'),
  \ javaapi#method(0,1,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'rewind(', ')', 'void'),
  \ javaapi#method(0,1,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'next(', ')', 'boolean'),
  \ javaapi#method(0,1,'component_count(', ')', 'int'),
  \ javaapi#method(0,1,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,1,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynStructImpl', 'DynAnyComplexImpl', [
  \ javaapi#method(0,0,'DynStructImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynStructImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,1,'get_members(', ')', 'NameValuePair[]'),
  \ javaapi#method(0,1,'get_members_as_dyn_any(', ')', 'NameDynAnyPair[]'),
  \ javaapi#method(0,1,'set_members_as_dyn_any(', 'NameDynAnyPair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'set_members(', 'NameValuePair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'current_member_kind(', ') throws TypeMismatch, InvalidValue', 'TCKind'),
  \ javaapi#method(0,1,'current_member_name(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,1,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,1,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,1,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,1,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,1,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,1,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,1,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,1,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,1,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,1,'destroy(', ')', 'void'),
  \ javaapi#method(0,1,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,1,'to_any(', ')', 'Any'),
  \ javaapi#method(0,1,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'rewind(', ')', 'void'),
  \ javaapi#method(0,1,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'next(', ')', 'boolean'),
  \ javaapi#method(0,1,'component_count(', ')', 'int'),
  \ javaapi#method(0,1,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,1,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynUnionImpl', 'DynAnyConstructedImpl', [
  \ javaapi#method(0,0,'DynUnionImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynUnionImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,0,'initializeComponentsFromAny(', ')', 'boolean'),
  \ javaapi#method(0,0,'initializeComponentsFromTypeCode(', ')', 'boolean'),
  \ javaapi#method(0,0,'clearData(', ')', 'void'),
  \ javaapi#method(0,1,'get_discriminator(', ')', 'DynAny'),
  \ javaapi#method(0,1,'set_discriminator(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'set_to_default_member(', ') throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'set_to_no_active_member(', ') throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'has_no_active_member(', ')', 'boolean'),
  \ javaapi#method(0,1,'discriminator_kind(', ')', 'TCKind'),
  \ javaapi#method(0,1,'member(', ') throws InvalidValue', 'DynAny'),
  \ javaapi#method(0,1,'member_name(', ') throws InvalidValue', 'String'),
  \ javaapi#method(0,1,'member_kind(', ') throws InvalidValue', 'TCKind'),
  \ javaapi#method(0,1,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,1,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,1,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,1,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,1,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,1,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,1,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,1,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,1,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,1,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,1,'destroy(', ')', 'void'),
  \ javaapi#method(0,1,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,1,'to_any(', ')', 'Any'),
  \ javaapi#method(0,1,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'rewind(', ')', 'void'),
  \ javaapi#method(0,1,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'next(', ')', 'boolean'),
  \ javaapi#method(0,1,'component_count(', ')', 'int'),
  \ javaapi#method(0,1,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,1,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynValueBoxImpl', 'DynValueCommonImpl', [
  \ javaapi#method(0,0,'DynValueBoxImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynValueBoxImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,1,'get_boxed_value(', ') throws InvalidValue', 'Any'),
  \ javaapi#method(0,1,'set_boxed_value(', 'Any) throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'get_boxed_value_as_dyn_any(', ') throws InvalidValue', 'DynAny'),
  \ javaapi#method(0,1,'set_boxed_value_as_dyn_any(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,0,'initializeComponentsFromAny(', ')', 'boolean'),
  \ javaapi#method(0,0,'initializeComponentsFromTypeCode(', ')', 'boolean'),
  \ javaapi#method(0,0,'initializeAnyFromComponents(', ')', 'boolean'),
  \ javaapi#method(0,1,'set_members_as_dyn_any(', 'NameDynAnyPair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'set_members(', 'NameValuePair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'get_members_as_dyn_any(', ') throws InvalidValue', 'NameDynAnyPair[]'),
  \ javaapi#method(0,1,'get_members(', ') throws InvalidValue', 'NameValuePair[]'),
  \ javaapi#method(0,1,'set_to_value(', ')', 'void'),
  \ javaapi#method(0,1,'set_to_null(', ')', 'void'),
  \ javaapi#method(0,1,'is_null(', ')', 'boolean'),
  \ javaapi#method(0,1,'current_member_kind(', ') throws TypeMismatch, InvalidValue', 'TCKind'),
  \ javaapi#method(0,1,'current_member_name(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,1,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,1,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,1,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,1,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,1,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,1,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,1,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,1,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,1,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,1,'destroy(', ')', 'void'),
  \ javaapi#method(0,1,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,1,'to_any(', ')', 'Any'),
  \ javaapi#method(0,1,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'rewind(', ')', 'void'),
  \ javaapi#method(0,1,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'next(', ')', 'boolean'),
  \ javaapi#method(0,1,'component_count(', ')', 'int'),
  \ javaapi#method(0,1,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,1,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'type(', ')', 'TypeCode'),
  \ ])

call javaapi#class('DynValueCommonImpl', 'DynAnyComplexImpl', [
  \ javaapi#field(0,0,'isNull', 'boolean'),
  \ javaapi#method(0,0,'DynValueCommonImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynValueCommonImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,1,'is_null(', ')', 'boolean'),
  \ javaapi#method(0,1,'set_to_null(', ')', 'void'),
  \ javaapi#method(0,1,'set_to_value(', ')', 'void'),
  \ javaapi#method(0,1,'get_members(', ') throws InvalidValue', 'NameValuePair[]'),
  \ javaapi#method(0,1,'get_members_as_dyn_any(', ') throws InvalidValue', 'NameDynAnyPair[]'),
  \ javaapi#method(0,1,'set_members(', 'NameValuePair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'set_members_as_dyn_any(', 'NameDynAnyPair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ ])

call javaapi#class('DynValueImpl', 'DynValueCommonImpl', [
  \ javaapi#method(0,0,'DynValueImpl(', 'ORB, Any, boolean)', ''),
  \ javaapi#method(0,0,'DynValueImpl(', 'ORB, TypeCode)', ''),
  \ javaapi#method(0,1,'set_members_as_dyn_any(', 'NameDynAnyPair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'set_members(', 'NameValuePair[]) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'get_members_as_dyn_any(', ') throws InvalidValue', 'NameDynAnyPair[]'),
  \ javaapi#method(0,1,'get_members(', ') throws InvalidValue', 'NameValuePair[]'),
  \ javaapi#method(0,1,'set_to_value(', ')', 'void'),
  \ javaapi#method(0,1,'set_to_null(', ')', 'void'),
  \ javaapi#method(0,1,'is_null(', ')', 'boolean'),
  \ javaapi#method(0,1,'current_member_kind(', ') throws TypeMismatch, InvalidValue', 'TCKind'),
  \ javaapi#method(0,1,'current_member_name(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_dyn_any(', ') throws TypeMismatch, InvalidValue', 'DynAny'),
  \ javaapi#method(0,1,'get_any(', ') throws TypeMismatch, InvalidValue', 'Any'),
  \ javaapi#method(0,1,'get_wstring(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_wchar(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_ulonglong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_longlong(', ') throws TypeMismatch, InvalidValue', 'long'),
  \ javaapi#method(0,1,'get_typecode(', ') throws TypeMismatch, InvalidValue', 'TypeCode'),
  \ javaapi#method(0,1,'get_reference(', ') throws TypeMismatch, InvalidValue', 'Object'),
  \ javaapi#method(0,1,'get_string(', ') throws TypeMismatch, InvalidValue', 'String'),
  \ javaapi#method(0,1,'get_double(', ') throws TypeMismatch, InvalidValue', 'double'),
  \ javaapi#method(0,1,'get_float(', ') throws TypeMismatch, InvalidValue', 'float'),
  \ javaapi#method(0,1,'get_ulong(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_long(', ') throws TypeMismatch, InvalidValue', 'int'),
  \ javaapi#method(0,1,'get_ushort(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_short(', ') throws TypeMismatch, InvalidValue', 'short'),
  \ javaapi#method(0,1,'get_char(', ') throws TypeMismatch, InvalidValue', 'char'),
  \ javaapi#method(0,1,'get_octet(', ') throws TypeMismatch, InvalidValue', 'byte'),
  \ javaapi#method(0,1,'get_boolean(', ') throws TypeMismatch, InvalidValue', 'boolean'),
  \ javaapi#method(0,1,'get_val(', ') throws TypeMismatch, InvalidValue', 'Serializable'),
  \ javaapi#method(0,1,'insert_val(', 'Serializable) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_dyn_any(', 'DynAny) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wstring(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_wchar(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulonglong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_longlong(', 'long) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_typecode(', 'TypeCode) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_reference(', 'Object) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_string(', 'String) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_double(', 'double) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_float(', 'float) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ulong(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_long(', 'int) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_ushort(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_short(', 'short) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_char(', 'char) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_octet(', 'byte) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'insert_boolean(', 'boolean) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'copy(', ')', 'DynAny'),
  \ javaapi#method(0,1,'destroy(', ')', 'void'),
  \ javaapi#method(0,1,'equal(', 'DynAny)', 'boolean'),
  \ javaapi#method(0,1,'to_any(', ')', 'Any'),
  \ javaapi#method(0,1,'from_any(', 'Any) throws TypeMismatch, InvalidValue', 'void'),
  \ javaapi#method(0,1,'assign(', 'DynAny) throws TypeMismatch', 'void'),
  \ javaapi#method(0,1,'rewind(', ')', 'void'),
  \ javaapi#method(0,1,'seek(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'next(', ')', 'boolean'),
  \ javaapi#method(0,1,'component_count(', ')', 'int'),
  \ javaapi#method(0,1,'current_component(', ') throws TypeMismatch', 'DynAny'),
  \ javaapi#method(0,1,'_ids(', ')', 'String[]'),
  \ javaapi#method(0,1,'type(', ')', 'TypeCode'),
  \ ])

