call javaapi#namespace('com.sun.corba.se.impl.encoding')

call javaapi#class('BufferManagerFactory', '', [
  \ javaapi#field(1,'GROW', 'int'),
  \ javaapi#field(1,'COLLECT', 'int'),
  \ javaapi#field(1,'STREAM', 'int'),
  \ javaapi#method(0,'BufferManagerFactory(', ')', 'public'),
  \ javaapi#method(1,'newBufferManagerRead(', 'GIOPVersion, byte, ORB)', 'BufferManagerRead'),
  \ javaapi#method(1,'newBufferManagerRead(', 'int, byte, ORB)', 'BufferManagerRead'),
  \ javaapi#method(1,'newBufferManagerWrite(', 'int, byte, ORB)', 'BufferManagerWrite'),
  \ javaapi#method(1,'newBufferManagerWrite(', 'GIOPVersion, byte, ORB)', 'BufferManagerWrite'),
  \ javaapi#method(1,'defaultBufferManagerRead(', 'ORB)', 'BufferManagerRead'),
  \ ])

call javaapi#interface('BufferManagerRead', '', [
  \ javaapi#method(0,'processFragment(', 'ByteBuffer, FragmentMessage)', 'void'),
  \ javaapi#method(0,'underflow(', 'ByteBufferWithInfo)', 'ByteBufferWithInfo'),
  \ javaapi#method(0,'init(', 'Message)', 'void'),
  \ javaapi#method(0,'getMarkAndResetHandler(', ')', 'MarkAndResetHandler'),
  \ javaapi#method(0,'cancelProcessing(', 'int)', 'void'),
  \ javaapi#method(0,'close(', 'ByteBufferWithInfo)', 'void'),
  \ ])

call javaapi#class('BufferManagerReadGrow', 'MarkAndResetHandler', [
  \ javaapi#method(0,'processFragment(', 'ByteBuffer, FragmentMessage)', 'void'),
  \ javaapi#method(0,'init(', 'Message)', 'void'),
  \ javaapi#method(0,'underflow(', 'ByteBufferWithInfo)', 'ByteBufferWithInfo'),
  \ javaapi#method(0,'cancelProcessing(', 'int)', 'void'),
  \ javaapi#method(0,'getMarkAndResetHandler(', ')', 'MarkAndResetHandler'),
  \ javaapi#method(0,'mark(', 'RestorableInputStream)', 'void'),
  \ javaapi#method(0,'fragmentationOccured(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'close(', 'ByteBufferWithInfo)', 'void'),
  \ ])

call javaapi#class('BufferManagerReadStream', 'MarkAndResetHandler', [
  \ javaapi#method(0,'cancelProcessing(', 'int)', 'void'),
  \ javaapi#method(0,'processFragment(', 'ByteBuffer, FragmentMessage)', 'void'),
  \ javaapi#method(0,'underflow(', 'ByteBufferWithInfo)', 'ByteBufferWithInfo'),
  \ javaapi#method(0,'init(', 'Message)', 'void'),
  \ javaapi#method(0,'close(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'mark(', 'RestorableInputStream)', 'void'),
  \ javaapi#method(0,'fragmentationOccured(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'getMarkAndResetHandler(', ')', 'MarkAndResetHandler'),
  \ ])

call javaapi#class('BufferManagerWrite', '', [
  \ javaapi#method(0,'sentFragment(', ')', 'boolean'),
  \ javaapi#method(0,'sentFullMessage(', ')', 'boolean'),
  \ javaapi#method(0,'getBufferSize(', ')', 'int'),
  \ javaapi#method(0,'overflow(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'sendMessage(', ')', 'void'),
  \ javaapi#method(0,'setOutputObject(', 'Object)', 'void'),
  \ javaapi#method(0,'close(', ')', 'void'),
  \ ])

call javaapi#class('1', '', [
  \ ])

call javaapi#class('BufferManagerWriteCollectIterator', 'Iterator', [
  \ javaapi#method(0,'hasNext(', ')', 'boolean'),
  \ javaapi#method(0,'next(', ')', 'Object'),
  \ javaapi#method(0,'remove(', ')', 'void'),
  \ ])

call javaapi#class('BufferManagerWriteCollect', 'BufferManagerWrite', [
  \ javaapi#method(0,'sentFragment(', ')', 'boolean'),
  \ javaapi#method(0,'getBufferSize(', ')', 'int'),
  \ javaapi#method(0,'overflow(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'sendMessage(', ')', 'void'),
  \ javaapi#method(0,'close(', ')', 'void'),
  \ ])

call javaapi#class('BufferManagerWriteGrow', 'BufferManagerWrite', [
  \ javaapi#method(0,'sentFragment(', ')', 'boolean'),
  \ javaapi#method(0,'getBufferSize(', ')', 'int'),
  \ javaapi#method(0,'overflow(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'sendMessage(', ')', 'void'),
  \ javaapi#method(0,'close(', ')', 'void'),
  \ ])

call javaapi#class('BufferManagerWriteStream', 'BufferManagerWrite', [
  \ javaapi#method(0,'sentFragment(', ')', 'boolean'),
  \ javaapi#method(0,'getBufferSize(', ')', 'int'),
  \ javaapi#method(0,'overflow(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'sendMessage(', ')', 'void'),
  \ javaapi#method(0,'close(', ')', 'void'),
  \ ])

call javaapi#class('BufferQueue', '', [
  \ javaapi#method(0,'BufferQueue(', ')', 'public'),
  \ javaapi#method(0,'enqueue(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'dequeue(', ') throws NoSuchElementException', 'ByteBufferWithInfo'),
  \ javaapi#method(0,'size(', ')', 'int'),
  \ javaapi#method(0,'push(', 'ByteBufferWithInfo)', 'void'),
  \ ])

call javaapi#class('ByteBufferWithInfo', '', [
  \ javaapi#field(0,'byteBuffer', 'ByteBuffer'),
  \ javaapi#field(0,'buflen', 'int'),
  \ javaapi#field(0,'needed', 'int'),
  \ javaapi#field(0,'fragmented', 'boolean'),
  \ javaapi#method(0,'ByteBufferWithInfo(', 'ORB, ByteBuffer, int)', 'public'),
  \ javaapi#method(0,'ByteBufferWithInfo(', 'ORB, ByteBuffer)', 'public'),
  \ javaapi#method(0,'ByteBufferWithInfo(', 'ORB, BufferManagerWrite)', 'public'),
  \ javaapi#method(0,'ByteBufferWithInfo(', 'ORB, BufferManagerWrite, boolean)', 'public'),
  \ javaapi#method(0,'ByteBufferWithInfo(', 'ByteBufferWithInfo)', 'public'),
  \ javaapi#method(0,'getSize(', ')', 'int'),
  \ javaapi#method(0,'getLength(', ')', 'int'),
  \ javaapi#method(0,'position(', ')', 'int'),
  \ javaapi#method(0,'position(', 'int)', 'void'),
  \ javaapi#method(0,'setLength(', 'int)', 'void'),
  \ javaapi#method(0,'growBuffer(', 'ORB)', 'void'),
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ ])

call javaapi#class('CDRInputObject', 'CDRInputStream', [
  \ javaapi#method(0,'CDRInputObject(', 'ORB, CorbaConnection, ByteBuffer, Message)', 'public'),
  \ javaapi#method(0,'getConnection(', ')', 'CorbaConnection'),
  \ javaapi#method(0,'getMessageHeader(', ')', 'Message'),
  \ javaapi#method(0,'unmarshalHeader(', ')', 'void'),
  \ javaapi#method(0,'unmarshaledHeader(', ')', 'boolean'),
  \ javaapi#method(0,'getCodeBase(', ')', 'CodeBase'),
  \ javaapi#method(0,'dup(', ')', 'CDRInputStream'),
  \ ])

call javaapi#class('InputStreamFactory', '', [
  \ javaapi#method(1,'newInputStream(', 'ORB, GIOPVersion, byte)', 'CDRInputStreamBase'),
  \ ])

call javaapi#class('CDRInputStream', 'InputStream', [
  \ javaapi#method(0,'CDRInputStream(', ')', 'public'),
  \ javaapi#method(0,'CDRInputStream(', 'CDRInputStream)', 'public'),
  \ javaapi#method(0,'CDRInputStream(', 'ORB, ByteBuffer, int, boolean, GIOPVersion, byte, BufferManagerRead)', 'public'),
  \ javaapi#method(0,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,'read_char(', ')', 'char'),
  \ javaapi#method(0,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,'read_short(', ')', 'short'),
  \ javaapi#method(0,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,'read_long(', ')', 'int'),
  \ javaapi#method(0,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,'read_float(', ')', 'float'),
  \ javaapi#method(0,'read_double(', ')', 'double'),
  \ javaapi#method(0,'read_string(', ')', 'String'),
  \ javaapi#method(0,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,'read_any(', ')', 'Any'),
  \ javaapi#method(0,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,'read(', ') throws IOException', 'int'),
  \ javaapi#method(0,'read_fixed(', ')', 'BigDecimal'),
  \ javaapi#method(0,'read_Context(', ')', 'Context'),
  \ javaapi#method(0,'read_Object(', 'Class)', 'Object'),
  \ javaapi#method(0,'orb(', ')', 'ORB'),
  \ javaapi#method(0,'read_value(', ')', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'Class)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'BoxedValueHelper)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'String)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'Serializable)', 'Serializable'),
  \ javaapi#method(0,'read_abstract_interface(', ')', 'Object'),
  \ javaapi#method(0,'read_abstract_interface(', 'Class)', 'Object'),
  \ javaapi#method(0,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,'getPosition(', ')', 'int'),
  \ javaapi#method(0,'read_Abstract(', ')', 'Object'),
  \ javaapi#method(0,'read_Value(', ')', 'Serializable'),
  \ javaapi#method(0,'read_any_array(', 'AnySeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_boolean_array(', 'BooleanSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_char_array(', 'CharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_wchar_array(', 'WCharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_octet_array(', 'OctetSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_short_array(', 'ShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ushort_array(', 'UShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_long_array(', 'LongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ulong_array(', 'ULongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ulonglong_array(', 'ULongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_longlong_array(', 'LongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_float_array(', 'FloatSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_double_array(', 'DoubleSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,'read(', 'byte[]) throws IOException', 'int'),
  \ javaapi#method(0,'read(', 'byte[], int, int) throws IOException', 'int'),
  \ javaapi#method(0,'skip(', 'long) throws IOException', 'long'),
  \ javaapi#method(0,'available(', ') throws IOException', 'int'),
  \ javaapi#method(0,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,'mark(', 'int)', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'markSupported(', ')', 'boolean'),
  \ javaapi#method(0,'dup(', ')', 'CDRInputStream'),
  \ javaapi#method(0,'read_fixed(', 'short, short)', 'BigDecimal'),
  \ javaapi#method(0,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,'getBufferLength(', ')', 'int'),
  \ javaapi#method(0,'orb(', 'ORB)', 'void'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'getBufferManager(', ')', 'BufferManagerRead'),
  \ javaapi#method(0,'getCodeBase(', ')', 'CodeBase'),
  \ javaapi#method(0,'alignOnBoundary(', 'int)', 'void'),
  \ javaapi#method(0,'setHeaderPadding(', 'boolean)', 'void'),
  \ javaapi#method(0,'performORBVersionSpecificInit(', ')', 'void'),
  \ javaapi#method(0,'resetCodeSetConverters(', ')', 'void'),
  \ javaapi#method(0,'setMessageMediator(', 'MessageMediator)', 'void'),
  \ javaapi#method(0,'getMessageMediator(', ')', 'MessageMediator'),
  \ javaapi#method(0,'start_value(', ')', 'void'),
  \ javaapi#method(0,'end_value(', ')', 'void'),
  \ ])

call javaapi#class('CDRInputStreamBase', 'InputStream', [
  \ javaapi#method(0,'setParent(', 'CDRInputStream)', 'void'),
  \ javaapi#method(0,'init(', 'ORB, ByteBuffer, int, boolean, BufferManagerRead)', 'void'),
  \ javaapi#method(0,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,'read_char(', ')', 'char'),
  \ javaapi#method(0,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,'read_short(', ')', 'short'),
  \ javaapi#method(0,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,'read_long(', ')', 'int'),
  \ javaapi#method(0,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,'read_float(', ')', 'float'),
  \ javaapi#method(0,'read_double(', ')', 'double'),
  \ javaapi#method(0,'read_string(', ')', 'String'),
  \ javaapi#method(0,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,'read_any(', ')', 'Any'),
  \ javaapi#method(0,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,'read(', ') throws IOException', 'int'),
  \ javaapi#method(0,'read_fixed(', ')', 'BigDecimal'),
  \ javaapi#method(0,'read_Context(', ')', 'Context'),
  \ javaapi#method(0,'read_Object(', 'Class)', 'Object'),
  \ javaapi#method(0,'orb(', ')', 'ORB'),
  \ javaapi#method(0,'read_value(', ')', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'Class)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'BoxedValueHelper)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'String)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'Serializable)', 'Serializable'),
  \ javaapi#method(0,'read_abstract_interface(', ')', 'Object'),
  \ javaapi#method(0,'read_abstract_interface(', 'Class)', 'Object'),
  \ javaapi#method(0,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,'getPosition(', ')', 'int'),
  \ javaapi#method(0,'read_Abstract(', ')', 'Object'),
  \ javaapi#method(0,'read_Value(', ')', 'Serializable'),
  \ javaapi#method(0,'read_any_array(', 'AnySeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_boolean_array(', 'BooleanSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_char_array(', 'CharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_wchar_array(', 'WCharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_octet_array(', 'OctetSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_short_array(', 'ShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ushort_array(', 'UShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_long_array(', 'LongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ulong_array(', 'ULongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ulonglong_array(', 'ULongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_longlong_array(', 'LongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_float_array(', 'FloatSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_double_array(', 'DoubleSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,'mark(', 'int)', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'markSupported(', ')', 'boolean'),
  \ javaapi#method(0,'dup(', ')', 'CDRInputStreamBase'),
  \ javaapi#method(0,'read_fixed(', 'short, short)', 'BigDecimal'),
  \ javaapi#method(0,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'getBufferLength(', ')', 'int'),
  \ javaapi#method(0,'setBufferLength(', 'int)', 'void'),
  \ javaapi#method(0,'getIndex(', ')', 'int'),
  \ javaapi#method(0,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,'orb(', 'ORB)', 'void'),
  \ javaapi#method(0,'getBufferManager(', ')', 'BufferManagerRead'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'resetCodeSetConverters(', ')', 'void'),
  \ javaapi#method(0,'start_value(', ')', 'void'),
  \ javaapi#method(0,'end_value(', ')', 'void'),
  \ ])

call javaapi#class('1', 'PrivilegedExceptionAction', [
  \ javaapi#method(0,'run(', ') throws NoSuchMethodException', 'Object'),
  \ ])

call javaapi#class('StreamMemento', '', [
  \ javaapi#method(0,'StreamMemento(', 'CDRInputStream_1_0)', 'public'),
  \ ])

call javaapi#class('CDRInputStream_1_0', 'CDRInputStreamBase', [
  \ javaapi#method(0,'CDRInputStream_1_0(', ')', 'public'),
  \ javaapi#method(0,'dup(', ')', 'CDRInputStreamBase'),
  \ javaapi#method(0,'init(', 'ORB, ByteBuffer, int, boolean, BufferManagerRead)', 'void'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'getSize(', ')', 'int'),
  \ javaapi#method(0,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,'read_longdouble(', ')', 'double'),
  \ javaapi#method(0,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,'read_char(', ')', 'char'),
  \ javaapi#method(0,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,'read_short(', ')', 'short'),
  \ javaapi#method(0,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,'read_long(', ')', 'int'),
  \ javaapi#method(0,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,'read_float(', ')', 'float'),
  \ javaapi#method(0,'read_double(', ')', 'double'),
  \ javaapi#method(0,'read_string(', ')', 'String'),
  \ javaapi#method(0,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,'read_any(', ')', 'Any'),
  \ javaapi#method(0,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,'read_Object(', 'Class)', 'Object'),
  \ javaapi#method(1,'internalIORToObject(', 'IOR, StubFactory, ORB)', 'Object'),
  \ javaapi#method(0,'read_abstract_interface(', ')', 'Object'),
  \ javaapi#method(0,'read_abstract_interface(', 'Class)', 'Object'),
  \ javaapi#method(0,'read_value(', ')', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'Class)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'BoxedValueHelper)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'Serializable)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'String)', 'Serializable'),
  \ javaapi#method(0,'orb(', ')', 'ORB'),
  \ javaapi#method(0,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,'read_any_array(', 'Any[], int, int)', 'void'),
  \ javaapi#method(0,'read_Abstract(', ')', 'Object'),
  \ javaapi#method(0,'read_Value(', ')', 'Serializable'),
  \ javaapi#method(0,'read_any_array(', 'AnySeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_boolean_array(', 'BooleanSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_char_array(', 'CharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_wchar_array(', 'WCharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_octet_array(', 'OctetSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_short_array(', 'ShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ushort_array(', 'UShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_long_array(', 'LongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ulong_array(', 'ULongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ulonglong_array(', 'ULongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_longlong_array(', 'LongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_float_array(', 'FloatSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_double_array(', 'DoubleSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_fixed(', 'short, short)', 'BigDecimal'),
  \ javaapi#method(0,'read_fixed(', ')', 'BigDecimal'),
  \ javaapi#method(0,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,'printBuffer(', ')', 'void'),
  \ javaapi#method(1,'printBuffer(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,'getBufferLength(', ')', 'int'),
  \ javaapi#method(0,'setBufferLength(', 'int)', 'void'),
  \ javaapi#method(0,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,'getIndex(', ')', 'int'),
  \ javaapi#method(0,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,'orb(', 'ORB)', 'void'),
  \ javaapi#method(0,'getBufferManager(', ')', 'BufferManagerRead'),
  \ javaapi#method(0,'createStreamMemento(', ')', 'Object'),
  \ javaapi#method(0,'restoreInternalState(', 'Object)', 'void'),
  \ javaapi#method(0,'getPosition(', ')', 'int'),
  \ javaapi#method(0,'mark(', 'int)', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'resetCodeSetConverters(', ')', 'void'),
  \ javaapi#method(0,'start_value(', ')', 'void'),
  \ javaapi#method(0,'end_value(', ')', 'void'),
  \ javaapi#method(0,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,'markSupported(', ')', 'boolean'),
  \ javaapi#method(0,'read_Context(', ')', 'Context'),
  \ javaapi#method(0,'read(', ') throws IOException', 'int'),
  \ javaapi#method(0,'setParent(', 'CDRInputStream)', 'void'),
  \ ])

call javaapi#class('FragmentableStreamMemento', 'StreamMemento', [
  \ javaapi#method(0,'FragmentableStreamMemento(', 'CDRInputStream_1_1)', 'public'),
  \ ])

call javaapi#class('CDRInputStream_1_1', 'CDRInputStream_1_0', [
  \ javaapi#method(0,'CDRInputStream_1_1(', ')', 'public'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'dup(', ')', 'CDRInputStreamBase'),
  \ javaapi#method(0,'createStreamMemento(', ')', 'Object'),
  \ javaapi#method(0,'restoreInternalState(', 'Object)', 'void'),
  \ javaapi#method(0,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,'read_wstring(', ')', 'String'),
  \ ])

call javaapi#class('CDRInputStream_1_2', 'CDRInputStream_1_1', [
  \ javaapi#method(0,'CDRInputStream_1_2(', ')', 'public'),
  \ javaapi#method(0,'mark(', 'int)', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'dup(', ')', 'CDRInputStreamBase'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,'read_wstring(', ')', 'String'),
  \ ])

call javaapi#class('CDROutputObject', 'CorbaOutputObject', [
  \ javaapi#method(0,'CDROutputObject(', 'ORB, MessageMediator, Message, byte)', 'public'),
  \ javaapi#method(0,'CDROutputObject(', 'ORB, MessageMediator, Message, byte, int)', 'public'),
  \ javaapi#method(0,'CDROutputObject(', 'ORB, CorbaMessageMediator, GIOPVersion, CorbaConnection, Message, byte)', 'public'),
  \ javaapi#method(0,'getMessageHeader(', ')', 'Message'),
  \ javaapi#method(0,'finishSendingMessage(', ')', 'void'),
  \ javaapi#method(0,'writeTo(', 'CorbaConnection) throws IOException', 'void'),
  \ javaapi#method(0,'create_input_stream(', ')', 'InputStream'),
  \ javaapi#method(0,'getConnection(', ')', 'CorbaConnection'),
  \ javaapi#method(0,'getByteBufferWithInfo(', ')', 'ByteBufferWithInfo'),
  \ javaapi#method(0,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ ])

call javaapi#class('OutputStreamFactory', '', [
  \ javaapi#method(1,'newOutputStream(', 'ORB, GIOPVersion, byte)', 'CDROutputStreamBase'),
  \ ])

call javaapi#class('CDROutputStream', 'OutputStream', [
  \ javaapi#method(0,'CDROutputStream(', 'ORB, GIOPVersion, byte, boolean, BufferManagerWrite, byte, boolean)', 'public'),
  \ javaapi#method(0,'CDROutputStream(', 'ORB, GIOPVersion, byte, boolean, BufferManagerWrite, byte)', 'public'),
  \ javaapi#method(0,'create_input_stream(', ')', 'InputStream'),
  \ javaapi#method(0,'write_boolean(', 'boolean)', 'void'),
  \ javaapi#method(0,'write_char(', 'char)', 'void'),
  \ javaapi#method(0,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,'write_ushort(', 'short)', 'void'),
  \ javaapi#method(0,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,'write_ulong(', 'int)', 'void'),
  \ javaapi#method(0,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,'write_ulonglong(', 'long)', 'void'),
  \ javaapi#method(0,'write_float(', 'float)', 'void'),
  \ javaapi#method(0,'write_double(', 'double)', 'void'),
  \ javaapi#method(0,'write_string(', 'String)', 'void'),
  \ javaapi#method(0,'write_wstring(', 'String)', 'void'),
  \ javaapi#method(0,'write_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,'write_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'write_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,'write_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'write_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'write_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'write_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'write_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'write_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'write_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,'write_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,'write_Object(', 'Object)', 'void'),
  \ javaapi#method(0,'write_TypeCode(', 'TypeCode)', 'void'),
  \ javaapi#method(0,'write_any(', 'Any)', 'void'),
  \ javaapi#method(0,'write_Principal(', 'Principal)', 'void'),
  \ javaapi#method(0,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,'write_fixed(', 'BigDecimal)', 'void'),
  \ javaapi#method(0,'write_Context(', 'Context, ContextList)', 'void'),
  \ javaapi#method(0,'orb(', ')', 'ORB'),
  \ javaapi#method(0,'write_value(', 'Serializable)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, Class)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, String)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, BoxedValueHelper)', 'void'),
  \ javaapi#method(0,'write_abstract_interface(', 'Object)', 'void'),
  \ javaapi#method(0,'write(', 'byte[]) throws IOException', 'void'),
  \ javaapi#method(0,'write(', 'byte[], int, int) throws IOException', 'void'),
  \ javaapi#method(0,'flush(', ') throws IOException', 'void'),
  \ javaapi#method(0,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,'start_block(', ')', 'void'),
  \ javaapi#method(0,'end_block(', ')', 'void'),
  \ javaapi#method(0,'putEndian(', ')', 'void'),
  \ javaapi#method(0,'writeTo(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,'toByteArray(', ')', 'byte[]'),
  \ javaapi#method(0,'write_Abstract(', 'Object)', 'void'),
  \ javaapi#method(0,'write_Value(', 'Serializable)', 'void'),
  \ javaapi#method(0,'write_any_array(', 'Any[], int, int)', 'void'),
  \ javaapi#method(0,'setMessageMediator(', 'MessageMediator)', 'void'),
  \ javaapi#method(0,'getMessageMediator(', ')', 'MessageMediator'),
  \ javaapi#method(0,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,'getByteBufferWithInfo(', ')', 'ByteBufferWithInfo'),
  \ javaapi#method(0,'getBufferManager(', ')', 'BufferManagerWrite'),
  \ javaapi#method(0,'write_fixed(', 'BigDecimal, short, short)', 'void'),
  \ javaapi#method(0,'writeOctetSequenceTo(', 'OutputStream)', 'void'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'writeIndirection(', 'int, int)', 'void'),
  \ javaapi#method(0,'alignOnBoundary(', 'int)', 'void'),
  \ javaapi#method(0,'setHeaderPadding(', 'boolean)', 'void'),
  \ javaapi#method(0,'start_value(', 'String)', 'void'),
  \ javaapi#method(0,'end_value(', ')', 'void'),
  \ ])

call javaapi#class('CDROutputStreamBase', 'OutputStream', [
  \ javaapi#method(0,'setParent(', 'CDROutputStream)', 'void'),
  \ javaapi#method(0,'init(', 'ORB, BufferManagerWrite, byte)', 'void'),
  \ javaapi#method(0,'write_boolean(', 'boolean)', 'void'),
  \ javaapi#method(0,'write_char(', 'char)', 'void'),
  \ javaapi#method(0,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,'write_ushort(', 'short)', 'void'),
  \ javaapi#method(0,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,'write_ulong(', 'int)', 'void'),
  \ javaapi#method(0,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,'write_ulonglong(', 'long)', 'void'),
  \ javaapi#method(0,'write_float(', 'float)', 'void'),
  \ javaapi#method(0,'write_double(', 'double)', 'void'),
  \ javaapi#method(0,'write_string(', 'String)', 'void'),
  \ javaapi#method(0,'write_wstring(', 'String)', 'void'),
  \ javaapi#method(0,'write_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,'write_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'write_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,'write_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'write_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'write_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'write_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'write_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'write_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'write_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,'write_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,'write_Object(', 'Object)', 'void'),
  \ javaapi#method(0,'write_TypeCode(', 'TypeCode)', 'void'),
  \ javaapi#method(0,'write_any(', 'Any)', 'void'),
  \ javaapi#method(0,'write_Principal(', 'Principal)', 'void'),
  \ javaapi#method(0,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,'write_fixed(', 'BigDecimal)', 'void'),
  \ javaapi#method(0,'write_Context(', 'Context, ContextList)', 'void'),
  \ javaapi#method(0,'orb(', ')', 'ORB'),
  \ javaapi#method(0,'write_value(', 'Serializable)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, Class)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, String)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, BoxedValueHelper)', 'void'),
  \ javaapi#method(0,'write_abstract_interface(', 'Object)', 'void'),
  \ javaapi#method(0,'start_block(', ')', 'void'),
  \ javaapi#method(0,'end_block(', ')', 'void'),
  \ javaapi#method(0,'putEndian(', ')', 'void'),
  \ javaapi#method(0,'writeTo(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,'toByteArray(', ')', 'byte[]'),
  \ javaapi#method(0,'write_Abstract(', 'Object)', 'void'),
  \ javaapi#method(0,'write_Value(', 'Serializable)', 'void'),
  \ javaapi#method(0,'write_any_array(', 'Any[], int, int)', 'void'),
  \ javaapi#method(0,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,'getSize(', ')', 'int'),
  \ javaapi#method(0,'getIndex(', ')', 'int'),
  \ javaapi#method(0,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,'getByteBufferWithInfo(', ')', 'ByteBufferWithInfo'),
  \ javaapi#method(0,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'getBufferManager(', ')', 'BufferManagerWrite'),
  \ javaapi#method(0,'write_fixed(', 'BigDecimal, short, short)', 'void'),
  \ javaapi#method(0,'writeOctetSequenceTo(', 'OutputStream)', 'void'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'writeIndirection(', 'int, int)', 'void'),
  \ javaapi#method(0,'start_value(', 'String)', 'void'),
  \ javaapi#method(0,'end_value(', ')', 'void'),
  \ ])

call javaapi#class('1', 'PrivilegedExceptionAction', [
  \ javaapi#method(0,'run(', ') throws NoSuchMethodException', 'Object'),
  \ ])

call javaapi#class('CDROutputStream_1_0', 'CDROutputStreamBase', [
  \ javaapi#method(0,'CDROutputStream_1_0(', ')', 'public'),
  \ javaapi#method(0,'init(', 'ORB, boolean, BufferManagerWrite, byte, boolean)', 'void'),
  \ javaapi#method(0,'init(', 'ORB, boolean, BufferManagerWrite, byte)', 'void'),
  \ javaapi#method(0,'getBufferManager(', ')', 'BufferManagerWrite'),
  \ javaapi#method(0,'toByteArray(', ')', 'byte[]'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'putEndian(', ') throws SystemException', 'void'),
  \ javaapi#method(0,'littleEndian(', ')', 'boolean'),
  \ javaapi#method(0,'write_longdouble(', 'double)', 'void'),
  \ javaapi#method(0,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,'write_boolean(', 'boolean)', 'void'),
  \ javaapi#method(0,'write_char(', 'char)', 'void'),
  \ javaapi#method(0,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,'write_ushort(', 'short)', 'void'),
  \ javaapi#method(0,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,'write_ulong(', 'int)', 'void'),
  \ javaapi#method(0,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,'write_ulonglong(', 'long)', 'void'),
  \ javaapi#method(0,'write_float(', 'float)', 'void'),
  \ javaapi#method(0,'write_double(', 'double)', 'void'),
  \ javaapi#method(0,'write_string(', 'String)', 'void'),
  \ javaapi#method(0,'write_wstring(', 'String)', 'void'),
  \ javaapi#method(0,'write_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,'write_Principal(', 'Principal)', 'void'),
  \ javaapi#method(0,'write_any(', 'Any)', 'void'),
  \ javaapi#method(0,'write_TypeCode(', 'TypeCode)', 'void'),
  \ javaapi#method(0,'write_Object(', 'Object)', 'void'),
  \ javaapi#method(0,'write_abstract_interface(', 'Object)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, Class)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, String)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, BoxedValueHelper)', 'void'),
  \ javaapi#method(0,'get_offset(', ')', 'int'),
  \ javaapi#method(0,'start_block(', ')', 'void'),
  \ javaapi#method(0,'end_block(', ')', 'void'),
  \ javaapi#method(0,'orb(', ')', 'ORB'),
  \ javaapi#method(0,'write_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,'write_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'write_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'write_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'write_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'write_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'write_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'write_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'write_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,'write_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,'write_string_array(', 'String[], int, int)', 'void'),
  \ javaapi#method(0,'write_wstring_array(', 'String[], int, int)', 'void'),
  \ javaapi#method(0,'write_any_array(', 'Any[], int, int)', 'void'),
  \ javaapi#method(0,'writeTo(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,'writeOctetSequenceTo(', 'OutputStream)', 'void'),
  \ javaapi#method(0,'getSize(', ')', 'int'),
  \ javaapi#method(0,'getIndex(', ')', 'int'),
  \ javaapi#method(0,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,'getByteBufferWithInfo(', ')', 'ByteBufferWithInfo'),
  \ javaapi#method(0,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,'write_Abstract(', 'Object)', 'void'),
  \ javaapi#method(0,'write_Value(', 'Serializable)', 'void'),
  \ javaapi#method(0,'write_fixed(', 'BigDecimal, short, short)', 'void'),
  \ javaapi#method(0,'write_fixed(', 'BigDecimal)', 'void'),
  \ javaapi#method(0,'write_fixed(', 'String, int)', 'void'),
  \ javaapi#method(0,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,'printBuffer(', ')', 'void'),
  \ javaapi#method(1,'printBuffer(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'writeIndirection(', 'int, int)', 'void'),
  \ javaapi#method(0,'start_value(', 'String)', 'void'),
  \ javaapi#method(0,'end_value(', ')', 'void'),
  \ javaapi#method(0,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,'write_Context(', 'Context, ContextList)', 'void'),
  \ javaapi#method(0,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,'init(', 'ORB, BufferManagerWrite, byte)', 'void'),
  \ javaapi#method(0,'setParent(', 'CDROutputStream)', 'void'),
  \ ])

call javaapi#class('CDROutputStream_1_1', 'CDROutputStream_1_0', [
  \ javaapi#method(0,'CDROutputStream_1_1(', ')', 'public'),
  \ javaapi#method(0,'get_offset(', ')', 'int'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,'write_wstring(', 'String)', 'void'),
  \ ])

call javaapi#class('CDROutputStream_1_2', 'CDROutputStream_1_1', [
  \ javaapi#method(0,'CDROutputStream_1_2(', ')', 'public'),
  \ javaapi#method(0,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'write_wstring(', 'String)', 'void'),
  \ ])

call javaapi#class('CachedCodeBase', '_CodeBaseImplBase', [
  \ javaapi#method(0,'CachedCodeBase(', 'CorbaConnection)', 'public'),
  \ javaapi#method(0,'get_ir(', ')', 'Repository'),
  \ javaapi#method(0,'implementation(', 'String)', 'String'),
  \ javaapi#method(0,'implementations(', 'String[])', 'String[]'),
  \ javaapi#method(0,'meta(', 'String)', 'FullValueDescription'),
  \ javaapi#method(0,'metas(', 'String[])', 'FullValueDescription[]'),
  \ javaapi#method(0,'bases(', 'String)', 'String[]'),
  \ ])

call javaapi#class('1', 'ThreadLocal', [
  \ javaapi#method(0,'initialValue(', ')', 'Object'),
  \ ])

call javaapi#class('CodeSetCache', '', [
  \ ])

call javaapi#class('CodeSetComponent', '', [
  \ javaapi#method(0,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,'hashCode(', ')', 'int'),
  \ javaapi#method(0,'CodeSetComponent(', ')', 'public'),
  \ javaapi#method(0,'CodeSetComponent(', 'int, int[])', 'public'),
  \ javaapi#method(0,'read(', 'MarshalInputStream)', 'void'),
  \ javaapi#method(0,'write(', 'MarshalOutputStream)', 'void'),
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ ])

call javaapi#class('CodeSetContext', '', [
  \ javaapi#method(0,'CodeSetContext(', ')', 'public'),
  \ javaapi#method(0,'CodeSetContext(', 'int, int)', 'public'),
  \ javaapi#method(0,'read(', 'MarshalInputStream)', 'void'),
  \ javaapi#method(0,'write(', 'MarshalOutputStream)', 'void'),
  \ javaapi#method(0,'getCharCodeSet(', ')', 'int'),
  \ javaapi#method(0,'getWCharCodeSet(', ')', 'int'),
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ ])

call javaapi#class('CodeSetComponentInfo', '', [
  \ javaapi#field(1,'JAVASOFT_DEFAULT_CODESETS', 'CodeSetComponentInfo'),
  \ javaapi#field(1,'LOCAL_CODE_SETS', 'CodeSetContext'),
  \ javaapi#method(0,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,'hashCode(', ')', 'int'),
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ javaapi#method(0,'CodeSetComponentInfo(', ')', 'public'),
  \ javaapi#method(0,'CodeSetComponentInfo(', 'CodeSetComponent, CodeSetComponent)', 'public'),
  \ javaapi#method(0,'read(', 'MarshalInputStream)', 'void'),
  \ javaapi#method(0,'write(', 'MarshalOutputStream)', 'void'),
  \ javaapi#method(0,'getCharComponent(', ')', 'CodeSetComponent'),
  \ javaapi#method(0,'getWCharComponent(', ')', 'CodeSetComponent'),
  \ javaapi#method(1,'createFromString(', 'String)', 'CodeSetComponent'),
  \ ])

call javaapi#class('1', '', [
  \ ])

call javaapi#class('BTCConverter', '', [
  \ javaapi#method(0,'BTCConverter(', ')', 'public'),
  \ javaapi#method(0,'isFixedWidthEncoding(', ')', 'boolean'),
  \ javaapi#method(0,'getFixedCharWidth(', ')', 'int'),
  \ javaapi#method(0,'getNumChars(', ')', 'int'),
  \ javaapi#method(0,'getChars(', 'byte[], int, int)', 'char[]'),
  \ ])

call javaapi#class('CTBConverter', '', [
  \ javaapi#method(0,'CTBConverter(', ')', 'public'),
  \ javaapi#method(0,'convert(', 'char)', 'void'),
  \ javaapi#method(0,'convert(', 'String)', 'void'),
  \ javaapi#method(0,'getNumBytes(', ')', 'int'),
  \ javaapi#method(0,'getMaxBytesPerChar(', ')', 'float'),
  \ javaapi#method(0,'isFixedWidthEncoding(', ')', 'boolean'),
  \ javaapi#method(0,'getAlignment(', ')', 'int'),
  \ javaapi#method(0,'getBytes(', ')', 'byte[]'),
  \ ])

call javaapi#class('CodeSetConversionHolder', '', [
  \ ])

call javaapi#class('JavaBTCConverter', 'BTCConverter', [
  \ javaapi#method(0,'JavaBTCConverter(', 'CodeSetConversion, Entry)', 'public'),
  \ javaapi#method(0,'isFixedWidthEncoding(', ')', 'boolean'),
  \ javaapi#method(0,'getFixedCharWidth(', ')', 'int'),
  \ javaapi#method(0,'getNumChars(', ')', 'int'),
  \ javaapi#method(0,'getChars(', 'byte[], int, int)', 'char[]'),
  \ ])

call javaapi#class('JavaCTBConverter', 'CTBConverter', [
  \ javaapi#method(0,'JavaCTBConverter(', 'CodeSetConversion, Entry, int)', 'public'),
  \ javaapi#method(0,'getMaxBytesPerChar(', ')', 'float'),
  \ javaapi#method(0,'convert(', 'char)', 'void'),
  \ javaapi#method(0,'convert(', 'String)', 'void'),
  \ javaapi#method(0,'getNumBytes(', ')', 'int'),
  \ javaapi#method(0,'getAlignment(', ')', 'int'),
  \ javaapi#method(0,'isFixedWidthEncoding(', ')', 'boolean'),
  \ javaapi#method(0,'getBytes(', ')', 'byte[]'),
  \ ])

call javaapi#class('UTF16BTCConverter', 'JavaBTCConverter', [
  \ javaapi#method(0,'UTF16BTCConverter(', 'CodeSetConversion, boolean)', 'public'),
  \ javaapi#method(0,'getChars(', 'byte[], int, int)', 'char[]'),
  \ ])

call javaapi#class('UTF16CTBConverter', 'JavaCTBConverter', [
  \ javaapi#method(0,'UTF16CTBConverter(', 'CodeSetConversion)', 'public'),
  \ javaapi#method(0,'UTF16CTBConverter(', 'CodeSetConversion, boolean)', 'public'),
  \ ])

call javaapi#class('CodeSetConversion', '', [
  \ javaapi#method(0,'getCTBConverter(', 'Entry)', 'CTBConverter'),
  \ javaapi#method(0,'getCTBConverter(', 'Entry, boolean, boolean)', 'CTBConverter'),
  \ javaapi#method(0,'getBTCConverter(', 'Entry)', 'BTCConverter'),
  \ javaapi#method(0,'getBTCConverter(', 'Entry, boolean)', 'BTCConverter'),
  \ javaapi#method(0,'negotiate(', 'CodeSetComponentInfo, CodeSetComponentInfo)', 'CodeSetContext'),
  \ javaapi#method(1,'impl(', ')', 'CodeSetConversion'),
  \ ])

call javaapi#class('EncapsInputStream', 'CDRInputStream', [
  \ javaapi#method(0,'EncapsInputStream(', 'ORB, byte[], int, boolean, GIOPVersion)', 'public'),
  \ javaapi#method(0,'EncapsInputStream(', 'ORB, ByteBuffer, int, boolean, GIOPVersion)', 'public'),
  \ javaapi#method(0,'EncapsInputStream(', 'ORB, byte[], int)', 'public'),
  \ javaapi#method(0,'EncapsInputStream(', 'EncapsInputStream)', 'public'),
  \ javaapi#method(0,'EncapsInputStream(', 'ORB, byte[], int, GIOPVersion)', 'public'),
  \ javaapi#method(0,'EncapsInputStream(', 'ORB, byte[], int, GIOPVersion, CodeBase)', 'public'),
  \ javaapi#method(0,'dup(', ')', 'CDRInputStream'),
  \ javaapi#method(0,'getCodeBase(', ')', 'CodeBase'),
  \ ])

call javaapi#class('EncapsOutputStream', 'CDROutputStream', [
  \ javaapi#method(0,'EncapsOutputStream(', 'ORB)', 'public'),
  \ javaapi#method(0,'EncapsOutputStream(', 'ORB, GIOPVersion)', 'public'),
  \ javaapi#method(0,'EncapsOutputStream(', 'ORB, boolean)', 'public'),
  \ javaapi#method(0,'EncapsOutputStream(', 'ORB, GIOPVersion, boolean)', 'public'),
  \ javaapi#method(0,'create_input_stream(', ')', 'InputStream'),
  \ ])

call javaapi#class('1', 'PrivilegedAction', [
  \ javaapi#method(0,'run(', ')', 'Object'),
  \ ])

call javaapi#class('MarshalObjectInputStream', 'ObjectInputStream', [
  \ ])

call javaapi#class('_ByteArrayInputStream', 'ByteArrayInputStream', [
  \ ])

call javaapi#class('IDLJavaSerializationInputStream', 'CDRInputStreamBase', [
  \ javaapi#method(0,'IDLJavaSerializationInputStream(', 'byte)', 'public'),
  \ javaapi#method(0,'init(', 'ORB, ByteBuffer, int, boolean, BufferManagerRead)', 'void'),
  \ javaapi#method(0,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,'read_char(', ')', 'char'),
  \ javaapi#method(0,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,'read_short(', ')', 'short'),
  \ javaapi#method(0,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,'read_long(', ')', 'int'),
  \ javaapi#method(0,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,'read_float(', ')', 'float'),
  \ javaapi#method(0,'read_double(', ')', 'double'),
  \ javaapi#method(0,'read_string(', ')', 'String'),
  \ javaapi#method(0,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,'read_any(', ')', 'Any'),
  \ javaapi#method(0,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,'read_fixed(', ')', 'BigDecimal'),
  \ javaapi#method(0,'read_Object(', 'Class)', 'Object'),
  \ javaapi#method(0,'orb(', ')', 'ORB'),
  \ javaapi#method(0,'read_value(', ')', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'Class)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'BoxedValueHelper)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'String)', 'Serializable'),
  \ javaapi#method(0,'read_value(', 'Serializable)', 'Serializable'),
  \ javaapi#method(0,'read_abstract_interface(', ')', 'Object'),
  \ javaapi#method(0,'read_abstract_interface(', 'Class)', 'Object'),
  \ javaapi#method(0,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,'getPosition(', ')', 'int'),
  \ javaapi#method(0,'read_Abstract(', ')', 'Object'),
  \ javaapi#method(0,'read_Value(', ')', 'Serializable'),
  \ javaapi#method(0,'read_any_array(', 'AnySeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_boolean_array(', 'BooleanSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_char_array(', 'CharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_wchar_array(', 'WCharSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_octet_array(', 'OctetSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_short_array(', 'ShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ushort_array(', 'UShortSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_long_array(', 'LongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ulong_array(', 'ULongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_ulonglong_array(', 'ULongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_longlong_array(', 'LongLongSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_float_array(', 'FloatSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'read_double_array(', 'DoubleSeqHolder, int, int)', 'void'),
  \ javaapi#method(0,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,'mark(', 'int)', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'markSupported(', ')', 'boolean'),
  \ javaapi#method(0,'dup(', ')', 'CDRInputStreamBase'),
  \ javaapi#method(0,'read_fixed(', 'short, short)', 'BigDecimal'),
  \ javaapi#method(0,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'getBufferLength(', ')', 'int'),
  \ javaapi#method(0,'setBufferLength(', 'int)', 'void'),
  \ javaapi#method(0,'getIndex(', ')', 'int'),
  \ javaapi#method(0,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,'orb(', 'ORB)', 'void'),
  \ javaapi#method(0,'getBufferManager(', ')', 'BufferManagerRead'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'resetCodeSetConverters(', ')', 'void'),
  \ javaapi#method(0,'start_value(', ')', 'void'),
  \ javaapi#method(0,'end_value(', ')', 'void'),
  \ javaapi#method(0,'read_Context(', ')', 'Context'),
  \ javaapi#method(0,'read(', ') throws IOException', 'int'),
  \ javaapi#method(0,'setParent(', 'CDRInputStream)', 'void'),
  \ ])

call javaapi#class('1', 'PrivilegedAction', [
  \ javaapi#method(0,'run(', ')', 'Object'),
  \ ])

call javaapi#class('MarshalObjectOutputStream', 'ObjectOutputStream', [
  \ ])

call javaapi#class('_ByteArrayOutputStream', 'ByteArrayOutputStream', [
  \ ])

call javaapi#class('IDLJavaSerializationOutputStream', 'CDROutputStreamBase', [
  \ javaapi#method(0,'IDLJavaSerializationOutputStream(', 'byte)', 'public'),
  \ javaapi#method(0,'init(', 'ORB, boolean, BufferManagerWrite, byte, boolean)', 'void'),
  \ javaapi#method(0,'write_boolean(', 'boolean)', 'void'),
  \ javaapi#method(0,'write_char(', 'char)', 'void'),
  \ javaapi#method(0,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,'write_ushort(', 'short)', 'void'),
  \ javaapi#method(0,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,'write_ulong(', 'int)', 'void'),
  \ javaapi#method(0,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,'write_ulonglong(', 'long)', 'void'),
  \ javaapi#method(0,'write_float(', 'float)', 'void'),
  \ javaapi#method(0,'write_double(', 'double)', 'void'),
  \ javaapi#method(0,'write_string(', 'String)', 'void'),
  \ javaapi#method(0,'write_wstring(', 'String)', 'void'),
  \ javaapi#method(0,'write_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,'write_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'write_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,'write_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'write_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'write_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'write_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'write_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'write_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'write_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,'write_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,'write_Object(', 'Object)', 'void'),
  \ javaapi#method(0,'write_TypeCode(', 'TypeCode)', 'void'),
  \ javaapi#method(0,'write_any(', 'Any)', 'void'),
  \ javaapi#method(0,'write_Principal(', 'Principal)', 'void'),
  \ javaapi#method(0,'write_fixed(', 'BigDecimal)', 'void'),
  \ javaapi#method(0,'orb(', ')', 'ORB'),
  \ javaapi#method(0,'write_value(', 'Serializable)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, Class)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, String)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable, BoxedValueHelper)', 'void'),
  \ javaapi#method(0,'write_abstract_interface(', 'Object)', 'void'),
  \ javaapi#method(0,'start_block(', ')', 'void'),
  \ javaapi#method(0,'end_block(', ')', 'void'),
  \ javaapi#method(0,'putEndian(', ')', 'void'),
  \ javaapi#method(0,'writeTo(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,'toByteArray(', ')', 'byte[]'),
  \ javaapi#method(0,'write_Abstract(', 'Object)', 'void'),
  \ javaapi#method(0,'write_Value(', 'Serializable)', 'void'),
  \ javaapi#method(0,'write_any_array(', 'Any[], int, int)', 'void'),
  \ javaapi#method(0,'_truncatable_ids(', ')', 'String[]'),
  \ javaapi#method(0,'getSize(', ')', 'int'),
  \ javaapi#method(0,'getIndex(', ')', 'int'),
  \ javaapi#method(0,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,'getByteBuffer(', ')', 'ByteBuffer'),
  \ javaapi#method(0,'setByteBuffer(', 'ByteBuffer)', 'void'),
  \ javaapi#method(0,'isLittleEndian(', ')', 'boolean'),
  \ javaapi#method(0,'getByteBufferWithInfo(', ')', 'ByteBufferWithInfo'),
  \ javaapi#method(0,'setByteBufferWithInfo(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'getBufferManager(', ')', 'BufferManagerWrite'),
  \ javaapi#method(0,'write_fixed(', 'BigDecimal, short, short)', 'void'),
  \ javaapi#method(0,'writeOctetSequenceTo(', 'OutputStream)', 'void'),
  \ javaapi#method(0,'getGIOPVersion(', ')', 'GIOPVersion'),
  \ javaapi#method(0,'writeIndirection(', 'int, int)', 'void'),
  \ javaapi#method(0,'alignOnBoundary(', 'int)', 'void'),
  \ javaapi#method(0,'setHeaderPadding(', 'boolean)', 'void'),
  \ javaapi#method(0,'start_value(', 'String)', 'void'),
  \ javaapi#method(0,'end_value(', ')', 'void'),
  \ javaapi#method(0,'write_Context(', 'Context, ContextList)', 'void'),
  \ javaapi#method(0,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,'init(', 'ORB, BufferManagerWrite, byte)', 'void'),
  \ javaapi#method(0,'setParent(', 'CDROutputStream)', 'void'),
  \ ])

call javaapi#interface('MarkAndResetHandler', '', [
  \ javaapi#method(0,'mark(', 'RestorableInputStream)', 'void'),
  \ javaapi#method(0,'fragmentationOccured(', 'ByteBufferWithInfo)', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ ])

call javaapi#interface('MarshalInputStream', '', [
  \ javaapi#method(0,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,'read_char(', ')', 'char'),
  \ javaapi#method(0,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,'read_short(', ')', 'short'),
  \ javaapi#method(0,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,'read_long(', ')', 'int'),
  \ javaapi#method(0,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,'read_float(', ')', 'float'),
  \ javaapi#method(0,'read_double(', ')', 'double'),
  \ javaapi#method(0,'read_string(', ')', 'String'),
  \ javaapi#method(0,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,'read_any(', ')', 'Any'),
  \ javaapi#method(0,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,'read_Object(', 'Class)', 'Object'),
  \ javaapi#method(0,'read_value(', ') throws Exception', 'Serializable'),
  \ javaapi#method(0,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,'getPosition(', ')', 'int'),
  \ javaapi#method(0,'mark(', 'int)', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'performORBVersionSpecificInit(', ')', 'void'),
  \ javaapi#method(0,'resetCodeSetConverters(', ')', 'void'),
  \ ])

call javaapi#interface('MarshalOutputStream', '', [
  \ javaapi#method(0,'create_input_stream(', ')', 'InputStream'),
  \ javaapi#method(0,'write_boolean(', 'boolean)', 'void'),
  \ javaapi#method(0,'write_char(', 'char)', 'void'),
  \ javaapi#method(0,'write_wchar(', 'char)', 'void'),
  \ javaapi#method(0,'write_octet(', 'byte)', 'void'),
  \ javaapi#method(0,'write_short(', 'short)', 'void'),
  \ javaapi#method(0,'write_ushort(', 'short)', 'void'),
  \ javaapi#method(0,'write_long(', 'int)', 'void'),
  \ javaapi#method(0,'write_ulong(', 'int)', 'void'),
  \ javaapi#method(0,'write_longlong(', 'long)', 'void'),
  \ javaapi#method(0,'write_ulonglong(', 'long)', 'void'),
  \ javaapi#method(0,'write_float(', 'float)', 'void'),
  \ javaapi#method(0,'write_double(', 'double)', 'void'),
  \ javaapi#method(0,'write_string(', 'String)', 'void'),
  \ javaapi#method(0,'write_wstring(', 'String)', 'void'),
  \ javaapi#method(0,'write_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,'write_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'write_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'write_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,'write_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'write_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'write_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'write_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'write_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'write_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'write_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,'write_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,'write_Object(', 'Object)', 'void'),
  \ javaapi#method(0,'write_TypeCode(', 'TypeCode)', 'void'),
  \ javaapi#method(0,'write_any(', 'Any)', 'void'),
  \ javaapi#method(0,'write_Principal(', 'Principal)', 'void'),
  \ javaapi#method(0,'write_value(', 'Serializable)', 'void'),
  \ javaapi#method(0,'start_block(', ')', 'void'),
  \ javaapi#method(0,'end_block(', ')', 'void'),
  \ javaapi#method(0,'putEndian(', ')', 'void'),
  \ javaapi#method(0,'writeTo(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,'toByteArray(', ')', 'byte[]'),
  \ ])

call javaapi#class('1', '', [
  \ ])

call javaapi#class('Entry', '', [
  \ javaapi#method(0,'getName(', ')', 'String'),
  \ javaapi#method(0,'getNumber(', ')', 'int'),
  \ javaapi#method(0,'isFixedWidth(', ')', 'boolean'),
  \ javaapi#method(0,'getMaxBytesPerChar(', ')', 'int'),
  \ javaapi#method(0,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,'hashCode(', ')', 'int'),
  \ ])

call javaapi#class('OSFCodeSetRegistry', '', [
  \ javaapi#field(1,'ISO_8859_1_VALUE', 'int'),
  \ javaapi#field(1,'UTF_16_VALUE', 'int'),
  \ javaapi#field(1,'UTF_8_VALUE', 'int'),
  \ javaapi#field(1,'UCS_2_VALUE', 'int'),
  \ javaapi#field(1,'ISO_646_VALUE', 'int'),
  \ javaapi#field(1,'ISO_8859_1', 'Entry'),
  \ javaapi#field(1,'UTF_16', 'Entry'),
  \ javaapi#field(1,'UTF_8', 'Entry'),
  \ javaapi#field(1,'UCS_2', 'Entry'),
  \ javaapi#field(1,'ISO_646', 'Entry'),
  \ javaapi#method(1,'lookupEntry(', 'int)', 'Entry'),
  \ ])

call javaapi#interface('RestorableInputStream', '', [
  \ javaapi#method(0,'createStreamMemento(', ')', 'Object'),
  \ javaapi#method(0,'restoreInternalState(', 'Object)', 'void'),
  \ ])

call javaapi#class('TypeCodeInputStream', 'EncapsInputStream', [
  \ javaapi#method(0,'TypeCodeInputStream(', 'ORB, byte[], int)', 'public'),
  \ javaapi#method(0,'TypeCodeInputStream(', 'ORB, byte[], int, boolean, GIOPVersion)', 'public'),
  \ javaapi#method(0,'TypeCodeInputStream(', 'ORB, ByteBuffer, int, boolean, GIOPVersion)', 'public'),
  \ javaapi#method(0,'addTypeCodeAtPosition(', 'TypeCodeImpl, int)', 'void'),
  \ javaapi#method(0,'getTypeCodeAtPosition(', 'int)', 'TypeCodeImpl'),
  \ javaapi#method(0,'setEnclosingInputStream(', 'InputStream)', 'void'),
  \ javaapi#method(0,'getTopLevelStream(', ')', 'TypeCodeReader'),
  \ javaapi#method(0,'getTopLevelPosition(', ')', 'int'),
  \ javaapi#method(1,'readEncapsulation(', 'InputStream, ORB)', 'TypeCodeInputStream'),
  \ javaapi#method(0,'printTypeMap(', ')', 'void'),
  \ ])

call javaapi#class('TypeCodeOutputStream', 'EncapsOutputStream', [
  \ javaapi#method(0,'TypeCodeOutputStream(', 'ORB)', 'public'),
  \ javaapi#method(0,'TypeCodeOutputStream(', 'ORB, boolean)', 'public'),
  \ javaapi#method(0,'create_input_stream(', ')', 'InputStream'),
  \ javaapi#method(0,'setEnclosingOutputStream(', 'OutputStream)', 'void'),
  \ javaapi#method(0,'getTopLevelStream(', ')', 'TypeCodeOutputStream'),
  \ javaapi#method(0,'getTopLevelPosition(', ')', 'int'),
  \ javaapi#method(0,'addIDAtPosition(', 'String, int)', 'void'),
  \ javaapi#method(0,'getPositionForID(', 'String)', 'int'),
  \ javaapi#method(0,'writeRawBuffer(', 'OutputStream, int)', 'void'),
  \ javaapi#method(0,'createEncapsulation(', 'ORB)', 'TypeCodeOutputStream'),
  \ javaapi#method(1,'wrapOutputStream(', 'OutputStream)', 'TypeCodeOutputStream'),
  \ javaapi#method(0,'getPosition(', ')', 'int'),
  \ javaapi#method(0,'getRealIndex(', 'int)', 'int'),
  \ javaapi#method(0,'getTypeCodeBuffer(', ')', 'byte[]'),
  \ javaapi#method(0,'printTypeMap(', ')', 'void'),
  \ ])

call javaapi#interface('TypeCodeReader', 'MarshalInputStream', [
  \ javaapi#method(0,'addTypeCodeAtPosition(', 'TypeCodeImpl, int)', 'void'),
  \ javaapi#method(0,'getTypeCodeAtPosition(', 'int)', 'TypeCodeImpl'),
  \ javaapi#method(0,'setEnclosingInputStream(', 'InputStream)', 'void'),
  \ javaapi#method(0,'getTopLevelStream(', ')', 'TypeCodeReader'),
  \ javaapi#method(0,'getTopLevelPosition(', ')', 'int'),
  \ javaapi#method(0,'getPosition(', ')', 'int'),
  \ javaapi#method(0,'printTypeMap(', ')', 'void'),
  \ ])

call javaapi#class('WrapperInputStream', 'InputStream', [
  \ javaapi#method(0,'WrapperInputStream(', 'CDRInputStream)', 'public'),
  \ javaapi#method(0,'read(', ') throws IOException', 'int'),
  \ javaapi#method(0,'read(', 'byte[]) throws IOException', 'int'),
  \ javaapi#method(0,'read(', 'byte[], int, int) throws IOException', 'int'),
  \ javaapi#method(0,'skip(', 'long) throws IOException', 'long'),
  \ javaapi#method(0,'available(', ') throws IOException', 'int'),
  \ javaapi#method(0,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,'mark(', 'int)', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'markSupported(', ')', 'boolean'),
  \ javaapi#method(0,'getPosition(', ')', 'int'),
  \ javaapi#method(0,'consumeEndian(', ')', 'void'),
  \ javaapi#method(0,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,'read_char(', ')', 'char'),
  \ javaapi#method(0,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,'read_short(', ')', 'short'),
  \ javaapi#method(0,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,'read_long(', ')', 'int'),
  \ javaapi#method(0,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,'read_float(', ')', 'float'),
  \ javaapi#method(0,'read_double(', ')', 'double'),
  \ javaapi#method(0,'read_string(', ')', 'String'),
  \ javaapi#method(0,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,'read_value(', ')', 'Serializable'),
  \ javaapi#method(0,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,'read_any(', ')', 'Any'),
  \ javaapi#method(0,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,'read_fixed(', ')', 'BigDecimal'),
  \ javaapi#method(0,'read_Context(', ')', 'Context'),
  \ javaapi#method(0,'orb(', ')', 'ORB'),
  \ javaapi#method(0,'addTypeCodeAtPosition(', 'TypeCodeImpl, int)', 'void'),
  \ javaapi#method(0,'getTypeCodeAtPosition(', 'int)', 'TypeCodeImpl'),
  \ javaapi#method(0,'setEnclosingInputStream(', 'InputStream)', 'void'),
  \ javaapi#method(0,'getTopLevelStream(', ')', 'TypeCodeReader'),
  \ javaapi#method(0,'getTopLevelPosition(', ')', 'int'),
  \ javaapi#method(0,'performORBVersionSpecificInit(', ')', 'void'),
  \ javaapi#method(0,'resetCodeSetConverters(', ')', 'void'),
  \ javaapi#method(0,'printTypeMap(', ')', 'void'),
  \ ])

