call javaapi#namespace('com.sun.xml.internal.bind.v2.model.nav')

call javaapi#class('GenericArrayTypeImpl', 'GenericArrayType', [
  \ javaapi#method(0,'getGenericComponentType(', ')', 'Type'),
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ javaapi#method(0,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,'hashCode(', ')', 'int'),
  \ ])

call javaapi#interface('Navigator<T,C,F,M>', '', [
  \ javaapi#field(1,'REFLECTION', 'ReflectionNavigator'),
  \ javaapi#method(0,'getSuperClass(', 'C)', 'C'),
  \ javaapi#method(0,'getBaseClass(', 'T, C)', 'T'),
  \ javaapi#method(0,'getClassName(', 'C)', 'String'),
  \ javaapi#method(0,'getTypeName(', 'T)', 'String'),
  \ javaapi#method(0,'getClassShortName(', 'C)', 'String'),
  \ javaapi#method(0,'getDeclaredFields(', 'C)', 'F>'),
  \ javaapi#method(0,'getDeclaredField(', 'C, String)', 'F'),
  \ javaapi#method(0,'getDeclaredMethods(', 'C)', 'M>'),
  \ javaapi#method(0,'getDeclaringClassForField(', 'F)', 'C'),
  \ javaapi#method(0,'getDeclaringClassForMethod(', 'M)', 'C'),
  \ javaapi#method(0,'getFieldType(', 'F)', 'T'),
  \ javaapi#method(0,'getFieldName(', 'F)', 'String'),
  \ javaapi#method(0,'getMethodName(', 'M)', 'String'),
  \ javaapi#method(0,'getReturnType(', 'M)', 'T'),
  \ javaapi#method(0,'getMethodParameters(', 'M)', 'T[]'),
  \ javaapi#method(0,'isStaticMethod(', 'M)', 'boolean'),
  \ javaapi#method(0,'isSubClassOf(', 'T, T)', 'boolean'),
  \ javaapi#method(0,'ref(', 'Class)', 'T'),
  \ javaapi#method(0,'use(', 'C)', 'T'),
  \ javaapi#method(0,'asDecl(', 'T)', 'C'),
  \ javaapi#method(0,'asDecl(', 'Class)', 'C'),
  \ javaapi#method(0,'isArray(', 'T)', 'boolean'),
  \ javaapi#method(0,'isArrayButNotByteArray(', 'T)', 'boolean'),
  \ javaapi#method(0,'getComponentType(', 'T)', 'T'),
  \ javaapi#method(0,'getTypeArgument(', 'T, int)', 'T'),
  \ javaapi#method(0,'isParameterizedType(', 'T)', 'boolean'),
  \ javaapi#method(0,'isPrimitive(', 'T)', 'boolean'),
  \ javaapi#method(0,'getPrimitive(', 'Class)', 'T'),
  \ javaapi#method(0,'getClassLocation(', 'C)', 'Location'),
  \ javaapi#method(0,'getFieldLocation(', 'F)', 'Location'),
  \ javaapi#method(0,'getMethodLocation(', 'M)', 'Location'),
  \ javaapi#method(0,'hasDefaultConstructor(', 'C)', 'boolean'),
  \ javaapi#method(0,'isStaticField(', 'F)', 'boolean'),
  \ javaapi#method(0,'isPublicMethod(', 'M)', 'boolean'),
  \ javaapi#method(0,'isFinalMethod(', 'M)', 'boolean'),
  \ javaapi#method(0,'isPublicField(', 'F)', 'boolean'),
  \ javaapi#method(0,'isEnum(', 'C)', 'boolean'),
  \ javaapi#method(0,'erasure(', 'T)', 'T'),
  \ javaapi#method(0,'isAbstract(', 'C)', 'boolean'),
  \ javaapi#method(0,'isFinal(', 'C)', 'boolean'),
  \ javaapi#method(0,'getEnumConstants(', 'C)', 'F[]'),
  \ javaapi#method(0,'getVoidType(', ')', 'T'),
  \ javaapi#method(0,'getPackageName(', 'C)', 'String'),
  \ javaapi#method(0,'findClass(', 'String, C)', 'C'),
  \ javaapi#method(0,'isBridgeMethod(', 'M)', 'boolean'),
  \ javaapi#method(0,'isOverriding(', 'M, C)', 'boolean'),
  \ javaapi#method(0,'isInterface(', 'C)', 'boolean'),
  \ javaapi#method(0,'isTransient(', 'F)', 'boolean'),
  \ javaapi#method(0,'isInnerClass(', 'C)', 'boolean'),
  \ ])

call javaapi#class('ParameterizedTypeImpl', 'ParameterizedType', [
  \ javaapi#method(0,'getActualTypeArguments(', ')', 'Type[]'),
  \ javaapi#method(0,'getRawType(', ')', 'Class<?>'),
  \ javaapi#method(0,'getOwnerType(', ')', 'Type'),
  \ javaapi#method(0,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,'hashCode(', ')', 'int'),
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ javaapi#method(0,'getRawType(', ')', 'Type'),
  \ ])

call javaapi#class('1', 'Class>', [
  \ javaapi#method(0,'onClass(', 'Class, Class)', 'Type'),
  \ javaapi#method(0,'onParameterizdType(', 'ParameterizedType, Class)', 'Type'),
  \ javaapi#method(0,'onGenericArray(', 'GenericArrayType, Class)', 'Type'),
  \ javaapi#method(0,'onVariable(', 'TypeVariable, Class)', 'Type'),
  \ javaapi#method(0,'onWildcard(', 'WildcardType, Class)', 'Type'),
  \ javaapi#method(0,'onWildcard(', 'WildcardType, Object)', 'Object'),
  \ javaapi#method(0,'onVariable(', 'TypeVariable, Object)', 'Object'),
  \ javaapi#method(0,'onGenericArray(', 'GenericArrayType, Object)', 'Object'),
  \ javaapi#method(0,'onParameterizdType(', 'ParameterizedType, Object)', 'Object'),
  \ javaapi#method(0,'onClass(', 'Class, Object)', 'Object'),
  \ ])

call javaapi#class('2', 'BinderArg>', [
  \ javaapi#method(0,'onClass(', 'Class, BinderArg)', 'Type'),
  \ javaapi#method(0,'onParameterizdType(', 'ParameterizedType, BinderArg)', 'Type'),
  \ javaapi#method(0,'onGenericArray(', 'GenericArrayType, BinderArg)', 'Type'),
  \ javaapi#method(0,'onVariable(', 'TypeVariable, BinderArg)', 'Type'),
  \ javaapi#method(0,'onWildcard(', 'WildcardType, BinderArg)', 'Type'),
  \ javaapi#method(0,'onWildcard(', 'WildcardType, Object)', 'Object'),
  \ javaapi#method(0,'onVariable(', 'TypeVariable, Object)', 'Object'),
  \ javaapi#method(0,'onGenericArray(', 'GenericArrayType, Object)', 'Object'),
  \ javaapi#method(0,'onParameterizdType(', 'ParameterizedType, Object)', 'Object'),
  \ javaapi#method(0,'onClass(', 'Class, Object)', 'Object'),
  \ ])

call javaapi#class('3', 'Void>', [
  \ javaapi#method(0,'onClass(', 'Class, Void)', 'Class'),
  \ javaapi#method(0,'onParameterizdType(', 'ParameterizedType, Void)', 'Class'),
  \ javaapi#method(0,'onGenericArray(', 'GenericArrayType, Void)', 'Class'),
  \ javaapi#method(0,'onVariable(', 'TypeVariable, Void)', 'Class'),
  \ javaapi#method(0,'onWildcard(', 'WildcardType, Void)', 'Class'),
  \ javaapi#method(0,'onWildcard(', 'WildcardType, Object)', 'Object'),
  \ javaapi#method(0,'onVariable(', 'TypeVariable, Object)', 'Object'),
  \ javaapi#method(0,'onGenericArray(', 'GenericArrayType, Object)', 'Object'),
  \ javaapi#method(0,'onParameterizdType(', 'ParameterizedType, Object)', 'Object'),
  \ javaapi#method(0,'onClass(', 'Class, Object)', 'Object'),
  \ ])

call javaapi#class('4', 'Location', [
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ ])

call javaapi#class('5', 'Location', [
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ ])

call javaapi#class('6', 'Location', [
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ ])

call javaapi#class('BinderArg', '', [
  \ javaapi#method(0,'BinderArg(', 'GenericDeclaration, Type[])', 'public'),
  \ ])

call javaapi#class('ReflectionNavigator', 'Method>', [
  \ javaapi#method(0,'getSuperClass(', 'Class)', 'Class'),
  \ javaapi#method(0,'getBaseClass(', 'Type, Class)', 'Type'),
  \ javaapi#method(0,'getClassName(', 'Class)', 'String'),
  \ javaapi#method(0,'getTypeName(', 'Type)', 'String'),
  \ javaapi#method(0,'getClassShortName(', 'Class)', 'String'),
  \ javaapi#method(0,'getDeclaredFields(', 'Class)', 'Field>'),
  \ javaapi#method(0,'getDeclaredField(', 'Class, String)', 'Field'),
  \ javaapi#method(0,'getDeclaredMethods(', 'Class)', 'Method>'),
  \ javaapi#method(0,'getDeclaringClassForField(', 'Field)', 'Class'),
  \ javaapi#method(0,'getDeclaringClassForMethod(', 'Method)', 'Class'),
  \ javaapi#method(0,'getFieldType(', 'Field)', 'Type'),
  \ javaapi#method(0,'getFieldName(', 'Field)', 'String'),
  \ javaapi#method(0,'getMethodName(', 'Method)', 'String'),
  \ javaapi#method(0,'getReturnType(', 'Method)', 'Type'),
  \ javaapi#method(0,'getMethodParameters(', 'Method)', 'Type[]'),
  \ javaapi#method(0,'isStaticMethod(', 'Method)', 'boolean'),
  \ javaapi#method(0,'isFinalMethod(', 'Method)', 'boolean'),
  \ javaapi#method(0,'isSubClassOf(', 'Type, Type)', 'boolean'),
  \ javaapi#method(0,'ref(', 'Class)', 'Class'),
  \ javaapi#method(0,'use(', 'Class)', 'Class'),
  \ javaapi#method(0,'asDecl(', 'Type)', 'Class'),
  \ javaapi#method(0,'asDecl(', 'Class)', 'Class'),
  \ javaapi#method(0,'erasure(', 'Type)', 'Class<T>'),
  \ javaapi#method(0,'isAbstract(', 'Class)', 'boolean'),
  \ javaapi#method(0,'isFinal(', 'Class)', 'boolean'),
  \ javaapi#method(0,'createParameterizedType(', 'Class, )', 'Type'),
  \ javaapi#method(0,'isArray(', 'Type)', 'boolean'),
  \ javaapi#method(0,'isArrayButNotByteArray(', 'Type)', 'boolean'),
  \ javaapi#method(0,'getComponentType(', 'Type)', 'Type'),
  \ javaapi#method(0,'getTypeArgument(', 'Type, int)', 'Type'),
  \ javaapi#method(0,'isParameterizedType(', 'Type)', 'boolean'),
  \ javaapi#method(0,'isPrimitive(', 'Type)', 'boolean'),
  \ javaapi#method(0,'getPrimitive(', 'Class)', 'Type'),
  \ javaapi#method(0,'getClassLocation(', 'Class)', 'Location'),
  \ javaapi#method(0,'getFieldLocation(', 'Field)', 'Location'),
  \ javaapi#method(0,'getMethodLocation(', 'Method)', 'Location'),
  \ javaapi#method(0,'hasDefaultConstructor(', 'Class)', 'boolean'),
  \ javaapi#method(0,'isStaticField(', 'Field)', 'boolean'),
  \ javaapi#method(0,'isPublicMethod(', 'Method)', 'boolean'),
  \ javaapi#method(0,'isPublicField(', 'Field)', 'boolean'),
  \ javaapi#method(0,'isEnum(', 'Class)', 'boolean'),
  \ javaapi#method(0,'getEnumConstants(', 'Class)', 'Field[]'),
  \ javaapi#method(0,'getVoidType(', ')', 'Type'),
  \ javaapi#method(0,'getPackageName(', 'Class)', 'String'),
  \ javaapi#method(0,'findClass(', 'String, Class)', 'Class'),
  \ javaapi#method(0,'isBridgeMethod(', 'Method)', 'boolean'),
  \ javaapi#method(0,'isOverriding(', 'Method, Class)', 'boolean'),
  \ javaapi#method(0,'isInterface(', 'Class)', 'boolean'),
  \ javaapi#method(0,'isTransient(', 'Field)', 'boolean'),
  \ javaapi#method(0,'isInnerClass(', 'Class)', 'boolean'),
  \ javaapi#method(0,'isInnerClass(', 'Object)', 'boolean'),
  \ javaapi#method(0,'isTransient(', 'Object)', 'boolean'),
  \ javaapi#method(0,'isInterface(', 'Object)', 'boolean'),
  \ javaapi#method(0,'isOverriding(', 'Object, Object)', 'boolean'),
  \ javaapi#method(0,'isBridgeMethod(', 'Object)', 'boolean'),
  \ javaapi#method(0,'findClass(', 'String, Object)', 'Object'),
  \ javaapi#method(0,'getPackageName(', 'Object)', 'String'),
  \ javaapi#method(0,'getVoidType(', ')', 'Object'),
  \ javaapi#method(0,'getEnumConstants(', 'Object)', 'Object[]'),
  \ javaapi#method(0,'isFinal(', 'Object)', 'boolean'),
  \ javaapi#method(0,'isAbstract(', 'Object)', 'boolean'),
  \ javaapi#method(0,'erasure(', 'Object)', 'Object'),
  \ javaapi#method(0,'isEnum(', 'Object)', 'boolean'),
  \ javaapi#method(0,'isPublicField(', 'Object)', 'boolean'),
  \ javaapi#method(0,'isFinalMethod(', 'Object)', 'boolean'),
  \ javaapi#method(0,'isPublicMethod(', 'Object)', 'boolean'),
  \ javaapi#method(0,'isStaticField(', 'Object)', 'boolean'),
  \ javaapi#method(0,'hasDefaultConstructor(', 'Object)', 'boolean'),
  \ javaapi#method(0,'getMethodLocation(', 'Object)', 'Location'),
  \ javaapi#method(0,'getFieldLocation(', 'Object)', 'Location'),
  \ javaapi#method(0,'getClassLocation(', 'Object)', 'Location'),
  \ javaapi#method(0,'getPrimitive(', 'Class)', 'Object'),
  \ javaapi#method(0,'isPrimitive(', 'Object)', 'boolean'),
  \ javaapi#method(0,'isParameterizedType(', 'Object)', 'boolean'),
  \ javaapi#method(0,'getTypeArgument(', 'Object, int)', 'Object'),
  \ javaapi#method(0,'getComponentType(', 'Object)', 'Object'),
  \ javaapi#method(0,'isArrayButNotByteArray(', 'Object)', 'boolean'),
  \ javaapi#method(0,'isArray(', 'Object)', 'boolean'),
  \ javaapi#method(0,'asDecl(', 'Class)', 'Object'),
  \ javaapi#method(0,'asDecl(', 'Object)', 'Object'),
  \ javaapi#method(0,'use(', 'Object)', 'Object'),
  \ javaapi#method(0,'ref(', 'Class)', 'Object'),
  \ javaapi#method(0,'isSubClassOf(', 'Object, Object)', 'boolean'),
  \ javaapi#method(0,'isStaticMethod(', 'Object)', 'boolean'),
  \ javaapi#method(0,'getMethodParameters(', 'Object)', 'Object[]'),
  \ javaapi#method(0,'getReturnType(', 'Object)', 'Object'),
  \ javaapi#method(0,'getMethodName(', 'Object)', 'String'),
  \ javaapi#method(0,'getFieldName(', 'Object)', 'String'),
  \ javaapi#method(0,'getFieldType(', 'Object)', 'Object'),
  \ javaapi#method(0,'getDeclaringClassForMethod(', 'Object)', 'Object'),
  \ javaapi#method(0,'getDeclaringClassForField(', 'Object)', 'Object'),
  \ javaapi#method(0,'getDeclaredMethods(', 'Object)', 'Collection'),
  \ javaapi#method(0,'getDeclaredField(', 'Object, String)', 'Object'),
  \ javaapi#method(0,'getDeclaredFields(', 'Object)', 'Collection'),
  \ javaapi#method(0,'getClassShortName(', 'Object)', 'String'),
  \ javaapi#method(0,'getTypeName(', 'Object)', 'String'),
  \ javaapi#method(0,'getClassName(', 'Object)', 'String'),
  \ javaapi#method(0,'getBaseClass(', 'Object, Object)', 'Object'),
  \ javaapi#method(0,'getSuperClass(', 'Object)', 'Object'),
  \ ])

call javaapi#class('TypeVisitor<T,P>', '', [
  \ javaapi#method(0,'visit(', 'Type, P)', 'T'),
  \ ])

call javaapi#class('WildcardTypeImpl', 'WildcardType', [
  \ javaapi#method(0,'WildcardTypeImpl(', 'Type[], Type[])', 'public'),
  \ javaapi#method(0,'getUpperBounds(', ')', 'Type[]'),
  \ javaapi#method(0,'getLowerBounds(', ')', 'Type[]'),
  \ javaapi#method(0,'hashCode(', ')', 'int'),
  \ javaapi#method(0,'equals(', 'Object)', 'boolean'),
  \ ])

