call javaapi#namespace('com.sun.xml.internal.ws.model.wsdl')

call javaapi#class('UnknownWSDLExtension', 'WSDLObject', [
  \ javaapi#method(0,'UnknownWSDLExtension(', 'QName, Locator)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'QName'),
  \ javaapi#method(0,'getLocation(', ')', 'Locator'),
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ ])

call javaapi#class('AbstractExtensibleImpl', 'AbstractObjectImpl', [
  \ javaapi#method(0,'getExtensions(', ')', 'WSDLExtension>'),
  \ javaapi#method(0,'getExtensions(', 'Class<T>)', 'Iterable<T>'),
  \ javaapi#method(0,'getExtension(', 'Class<T>)', 'T'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ ])

call javaapi#class('AbstractFeaturedObjectImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,'addFeature(', 'WebServiceFeature)', 'void'),
  \ javaapi#method(0,'getFeatures(', ')', 'WebServiceFeatureList'),
  \ javaapi#method(0,'getFeature(', 'String)', 'WebServiceFeature'),
  \ javaapi#method(0,'getFeature(', 'Class<F>)', 'F'),
  \ javaapi#method(0,'getFeatures(', ')', 'WSFeatureList'),
  \ ])

call javaapi#class('AbstractObjectImpl', 'WSDLObject', [
  \ javaapi#method(0,'getLocation(', ')', 'Locator'),
  \ ])

call javaapi#class('WSDLBoundFaultImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,'WSDLBoundFaultImpl(', 'XMLStreamReader, String, WSDLBoundOperationImpl)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'String'),
  \ javaapi#method(0,'getQName(', ')', 'QName'),
  \ javaapi#method(0,'getFault(', ')', 'WSDLFault'),
  \ javaapi#method(0,'getBoundOperation(', ')', 'WSDLBoundOperation'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ ])

call javaapi#class('WSDLBoundOperationImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,'WSDLBoundOperationImpl(', 'XMLStreamReader, WSDLBoundPortTypeImpl, QName)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'QName'),
  \ javaapi#method(0,'getSOAPAction(', ')', 'String'),
  \ javaapi#method(0,'setSoapAction(', 'String)', 'void'),
  \ javaapi#method(0,'getPart(', 'String, Mode)', 'WSDLPartImpl'),
  \ javaapi#method(0,'addPart(', 'WSDLPartImpl, Mode)', 'void'),
  \ javaapi#method(0,'getInputParts(', ')', 'ParameterBinding>'),
  \ javaapi#method(0,'getOutputParts(', ')', 'ParameterBinding>'),
  \ javaapi#method(0,'getFaultParts(', ')', 'ParameterBinding>'),
  \ javaapi#method(0,'getInParts(', ')', 'WSDLPart>'),
  \ javaapi#method(0,'getOutParts(', ')', 'WSDLPart>'),
  \ javaapi#method(0,'getFaults(', ')', 'WSDLBoundFaultImpl>'),
  \ javaapi#method(0,'addFault(', 'WSDLBoundFaultImpl)', 'void'),
  \ javaapi#method(0,'getInputMimeTypes(', ')', 'String>'),
  \ javaapi#method(0,'getOutputMimeTypes(', ')', 'String>'),
  \ javaapi#method(0,'getFaultMimeTypes(', ')', 'String>'),
  \ javaapi#method(0,'getInputBinding(', 'String)', 'ParameterBinding'),
  \ javaapi#method(0,'getOutputBinding(', 'String)', 'ParameterBinding'),
  \ javaapi#method(0,'getFaultBinding(', 'String)', 'ParameterBinding'),
  \ javaapi#method(0,'getMimeTypeForInputPart(', 'String)', 'String'),
  \ javaapi#method(0,'getMimeTypeForOutputPart(', 'String)', 'String'),
  \ javaapi#method(0,'getMimeTypeForFaultPart(', 'String)', 'String'),
  \ javaapi#method(0,'getOperation(', ')', 'WSDLOperationImpl'),
  \ javaapi#method(0,'getBoundPortType(', ')', 'WSDLBoundPortType'),
  \ javaapi#method(0,'setInputExplicitBodyParts(', 'boolean)', 'void'),
  \ javaapi#method(0,'setOutputExplicitBodyParts(', 'boolean)', 'void'),
  \ javaapi#method(0,'setFaultExplicitBodyParts(', 'boolean)', 'void'),
  \ javaapi#method(0,'setStyle(', 'Style)', 'void'),
  \ javaapi#method(0,'getReqPayloadName(', ')', 'QName'),
  \ javaapi#method(0,'getResPayloadName(', ')', 'QName'),
  \ javaapi#method(0,'getRequestNamespace(', ')', 'String'),
  \ javaapi#method(0,'setRequestNamespace(', 'String)', 'void'),
  \ javaapi#method(0,'getResponseNamespace(', ')', 'String'),
  \ javaapi#method(0,'setResponseNamespace(', 'String)', 'void'),
  \ javaapi#method(0,'setAnonymous(', 'ANONYMOUS)', 'void'),
  \ javaapi#method(0,'getAnonymous(', ')', 'ANONYMOUS'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,'getFaults(', ')', 'Iterable'),
  \ javaapi#method(0,'getPart(', 'String, Mode)', 'WSDLPart'),
  \ javaapi#method(0,'getOperation(', ')', 'WSDLOperation'),
  \ ])

call javaapi#class('WSDLBoundPortTypeImpl', 'AbstractFeaturedObjectImpl', [
  \ javaapi#method(0,'WSDLBoundPortTypeImpl(', 'XMLStreamReader, WSDLModelImpl, QName, QName)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'QName'),
  \ javaapi#method(0,'getOwner(', ')', 'WSDLModelImpl'),
  \ javaapi#method(0,'get(', 'QName)', 'WSDLBoundOperationImpl'),
  \ javaapi#method(0,'put(', 'QName, WSDLBoundOperationImpl)', 'void'),
  \ javaapi#method(0,'getPortTypeName(', ')', 'QName'),
  \ javaapi#method(0,'getPortType(', ')', 'WSDLPortTypeImpl'),
  \ javaapi#method(0,'getBindingOperations(', ')', 'WSDLBoundOperationImpl>'),
  \ javaapi#method(0,'getBindingId(', ')', 'BindingID'),
  \ javaapi#method(0,'setBindingId(', 'BindingID)', 'void'),
  \ javaapi#method(0,'setStyle(', 'Style)', 'void'),
  \ javaapi#method(0,'getStyle(', ')', 'Style'),
  \ javaapi#method(0,'isRpcLit(', ')', 'boolean'),
  \ javaapi#method(0,'isDoclit(', ')', 'boolean'),
  \ javaapi#method(0,'getBinding(', 'QName, String, Mode)', 'ParameterBinding'),
  \ javaapi#method(0,'getMimeType(', 'QName, String, Mode)', 'String'),
  \ javaapi#method(0,'getOperation(', 'String, String)', 'WSDLBoundOperationImpl'),
  \ javaapi#method(0,'enableMTOM(', ')', 'void'),
  \ javaapi#method(0,'isMTOMEnabled(', ')', 'boolean'),
  \ javaapi#method(0,'getSOAPVersion(', ')', 'SOAPVersion'),
  \ javaapi#method(0,'getFeature(', 'Class)', 'WebServiceFeature'),
  \ javaapi#method(0,'getFeatures(', ')', 'WebServiceFeatureList'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,'getOperation(', 'String, String)', 'WSDLBoundOperation'),
  \ javaapi#method(0,'getPortType(', ')', 'WSDLPortType'),
  \ javaapi#method(0,'get(', 'QName)', 'WSDLBoundOperation'),
  \ javaapi#method(0,'getOwner(', ')', 'WSDLModel'),
  \ ])

call javaapi#class('WSDLFaultImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,'WSDLFaultImpl(', 'XMLStreamReader, String, QName, WSDLOperationImpl)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'String'),
  \ javaapi#method(0,'getMessage(', ')', 'WSDLMessageImpl'),
  \ javaapi#method(0,'getOperation(', ')', 'WSDLOperation'),
  \ javaapi#method(0,'getQName(', ')', 'QName'),
  \ javaapi#method(0,'getAction(', ')', 'String'),
  \ javaapi#method(0,'setAction(', 'String)', 'void'),
  \ javaapi#method(0,'isDefaultAction(', ')', 'boolean'),
  \ javaapi#method(0,'setDefaultAction(', 'boolean)', 'void'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,'getMessage(', ')', 'WSDLMessage'),
  \ ])

call javaapi#class('WSDLInputImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,'WSDLInputImpl(', 'XMLStreamReader, String, QName, WSDLOperationImpl)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'String'),
  \ javaapi#method(0,'getMessage(', ')', 'WSDLMessage'),
  \ javaapi#method(0,'getAction(', ')', 'String'),
  \ javaapi#method(0,'getOperation(', ')', 'WSDLOperation'),
  \ javaapi#method(0,'getQName(', ')', 'QName'),
  \ javaapi#method(0,'setAction(', 'String)', 'void'),
  \ javaapi#method(0,'isDefaultAction(', ')', 'boolean'),
  \ javaapi#method(0,'setDefaultAction(', 'boolean)', 'void'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ ])

call javaapi#class('WSDLMessageImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,'WSDLMessageImpl(', 'XMLStreamReader, QName)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'QName'),
  \ javaapi#method(0,'add(', 'WSDLPartImpl)', 'void'),
  \ javaapi#method(0,'parts(', ')', 'WSDLPartImpl>'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ ])

call javaapi#class('WSDLModelImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,'WSDLModelImpl(', 'String)', 'public'),
  \ javaapi#method(0,'WSDLModelImpl(', ')', 'public'),
  \ javaapi#method(0,'addMessage(', 'WSDLMessageImpl)', 'void'),
  \ javaapi#method(0,'getMessage(', 'QName)', 'WSDLMessageImpl'),
  \ javaapi#method(0,'addPortType(', 'WSDLPortTypeImpl)', 'void'),
  \ javaapi#method(0,'getPortType(', 'QName)', 'WSDLPortTypeImpl'),
  \ javaapi#method(0,'addBinding(', 'WSDLBoundPortTypeImpl)', 'void'),
  \ javaapi#method(0,'getBinding(', 'QName)', 'WSDLBoundPortTypeImpl'),
  \ javaapi#method(0,'addService(', 'WSDLServiceImpl)', 'void'),
  \ javaapi#method(0,'getService(', 'QName)', 'WSDLServiceImpl'),
  \ javaapi#method(0,'getMessages(', ')', 'WSDLMessageImpl>'),
  \ javaapi#method(0,'getPortTypes(', ')', 'WSDLPortTypeImpl>'),
  \ javaapi#method(0,'getBindings(', ')', 'WSDLBoundPortType>'),
  \ javaapi#method(0,'getServices(', ')', 'WSDLServiceImpl>'),
  \ javaapi#method(0,'getFirstServiceName(', ')', 'QName'),
  \ javaapi#method(0,'getFirstPortName(', ')', 'QName'),
  \ javaapi#method(0,'getMatchingPort(', 'QName, QName)', 'WSDLPortImpl'),
  \ javaapi#method(0,'getBinding(', 'QName, QName)', 'WSDLBoundPortTypeImpl'),
  \ javaapi#method(0,'getPolicyMap(', ')', 'PolicyMap'),
  \ javaapi#method(0,'setPolicyMap(', 'PolicyMap)', 'void'),
  \ javaapi#method(0,'freeze(', ')', 'void'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,'getService(', 'QName)', 'WSDLService'),
  \ javaapi#method(0,'getBinding(', 'QName, QName)', 'WSDLBoundPortType'),
  \ javaapi#method(0,'getBinding(', 'QName)', 'WSDLBoundPortType'),
  \ javaapi#method(0,'getPortType(', 'QName)', 'WSDLPortType'),
  \ ])

call javaapi#class('WSDLOperationImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,'WSDLOperationImpl(', 'XMLStreamReader, WSDLPortTypeImpl, QName)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'QName'),
  \ javaapi#method(0,'getParameterOrder(', ')', 'String'),
  \ javaapi#method(0,'setParameterOrder(', 'String)', 'void'),
  \ javaapi#method(0,'getInput(', ')', 'WSDLInputImpl'),
  \ javaapi#method(0,'setInput(', 'WSDLInputImpl)', 'void'),
  \ javaapi#method(0,'getOutput(', ')', 'WSDLOutputImpl'),
  \ javaapi#method(0,'isOneWay(', ')', 'boolean'),
  \ javaapi#method(0,'setOutput(', 'WSDLOutputImpl)', 'void'),
  \ javaapi#method(0,'getFaults(', ')', 'WSDLFaultImpl>'),
  \ javaapi#method(0,'getFault(', 'QName)', 'WSDLFault'),
  \ javaapi#method(0,'getPortTypeName(', ')', 'QName'),
  \ javaapi#method(0,'addFault(', 'WSDLFaultImpl)', 'void'),
  \ javaapi#method(0,'freez(', 'WSDLModelImpl)', 'void'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,'getOutput(', ')', 'WSDLOutput'),
  \ javaapi#method(0,'getInput(', ')', 'WSDLInput'),
  \ ])

call javaapi#class('WSDLOutputImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,'WSDLOutputImpl(', 'XMLStreamReader, String, QName, WSDLOperationImpl)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'String'),
  \ javaapi#method(0,'getMessage(', ')', 'WSDLMessage'),
  \ javaapi#method(0,'getAction(', ')', 'String'),
  \ javaapi#method(0,'isDefaultAction(', ')', 'boolean'),
  \ javaapi#method(0,'setDefaultAction(', 'boolean)', 'void'),
  \ javaapi#method(0,'getOperation(', ')', 'WSDLOperation'),
  \ javaapi#method(0,'getQName(', ')', 'QName'),
  \ javaapi#method(0,'setAction(', 'String)', 'void'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ ])

call javaapi#class('WSDLPartDescriptorImpl', 'AbstractObjectImpl', [
  \ javaapi#method(0,'WSDLPartDescriptorImpl(', 'XMLStreamReader, QName, WSDLDescriptorKind)', 'public'),
  \ javaapi#method(0,'name(', ')', 'QName'),
  \ javaapi#method(0,'type(', ')', 'WSDLDescriptorKind'),
  \ ])

call javaapi#class('WSDLPartImpl', 'AbstractObjectImpl', [
  \ javaapi#method(0,'WSDLPartImpl(', 'XMLStreamReader, String, int, WSDLPartDescriptor)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'String'),
  \ javaapi#method(0,'getBinding(', ')', 'ParameterBinding'),
  \ javaapi#method(0,'setBinding(', 'ParameterBinding)', 'void'),
  \ javaapi#method(0,'getIndex(', ')', 'int'),
  \ javaapi#method(0,'setIndex(', 'int)', 'void'),
  \ javaapi#method(0,'getDescriptor(', ')', 'WSDLPartDescriptor'),
  \ ])

call javaapi#class('WSDLPortImpl', 'AbstractFeaturedObjectImpl', [
  \ javaapi#method(0,'WSDLPortImpl(', 'XMLStreamReader, WSDLServiceImpl, QName, QName)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'QName'),
  \ javaapi#method(0,'getBindingName(', ')', 'QName'),
  \ javaapi#method(0,'getAddress(', ')', 'EndpointAddress'),
  \ javaapi#method(0,'getOwner(', ')', 'WSDLServiceImpl'),
  \ javaapi#method(0,'setAddress(', 'EndpointAddress)', 'void'),
  \ javaapi#method(0,'setEPR(', 'WSEndpointReference)', 'void'),
  \ javaapi#method(0,'getEPR(', ')', 'WSEndpointReference'),
  \ javaapi#method(0,'getBinding(', ')', 'WSDLBoundPortTypeImpl'),
  \ javaapi#method(0,'getSOAPVersion(', ')', 'SOAPVersion'),
  \ javaapi#method(0,'getFeature(', 'Class)', 'WebServiceFeature'),
  \ javaapi#method(0,'getFeatures(', ')', 'WebServiceFeatureList'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,'getOwner(', ')', 'WSDLService'),
  \ javaapi#method(0,'getBinding(', ')', 'WSDLBoundPortType'),
  \ ])

call javaapi#class('WSDLPortTypeImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,'WSDLPortTypeImpl(', 'XMLStreamReader, WSDLModelImpl, QName)', 'public'),
  \ javaapi#method(0,'getName(', ')', 'QName'),
  \ javaapi#method(0,'get(', 'String)', 'WSDLOperationImpl'),
  \ javaapi#method(0,'getOperations(', ')', 'WSDLOperationImpl>'),
  \ javaapi#method(0,'put(', 'String, WSDLOperationImpl)', 'void'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,'get(', 'String)', 'WSDLOperation'),
  \ ])

call javaapi#class('WSDLProperties', 'PropertySet', [
  \ javaapi#method(0,'WSDLProperties(', 'WSDLPort)', 'public'),
  \ javaapi#method(0,'getWSDLService(', ')', 'QName'),
  \ javaapi#method(0,'getWSDLPort(', ')', 'QName'),
  \ javaapi#method(0,'getWSDLPortType(', ')', 'QName'),
  \ ])

call javaapi#class('WSDLServiceImpl', 'AbstractExtensibleImpl', [
  \ javaapi#method(0,'WSDLServiceImpl(', 'XMLStreamReader, WSDLModelImpl, QName)', 'public'),
  \ javaapi#method(0,'getParent(', ')', 'WSDLModelImpl'),
  \ javaapi#method(0,'getName(', ')', 'QName'),
  \ javaapi#method(0,'get(', 'QName)', 'WSDLPortImpl'),
  \ javaapi#method(0,'getFirstPort(', ')', 'WSDLPort'),
  \ javaapi#method(0,'getPorts(', ')', 'WSDLPortImpl>'),
  \ javaapi#method(0,'getMatchingPort(', 'QName)', 'WSDLPortImpl'),
  \ javaapi#method(0,'put(', 'QName, WSDLPortImpl)', 'void'),
  \ javaapi#method(0,'areRequiredExtensionsUnderstood(', ')', 'boolean'),
  \ javaapi#method(0,'addNotUnderstoodExtension(', 'QName, Locator)', 'void'),
  \ javaapi#method(0,'addExtension(', 'WSDLExtension)', 'void'),
  \ javaapi#method(0,'getExtension(', 'Class)', 'WSDLExtension'),
  \ javaapi#method(0,'get(', 'QName)', 'WSDLPort'),
  \ javaapi#method(0,'getParent(', ')', 'WSDLModel'),
  \ ])

