call javaapi#namespace('com.sun.org.apache.xerces.internal.parsers')

call javaapi#class('AbstractDOMParser', 'AbstractXMLDocumentParser', [
  \ javaapi#field(1,0,'NAMESPACES', 'String'),
  \ javaapi#field(1,0,'CREATE_ENTITY_REF_NODES', 'String'),
  \ javaapi#field(1,0,'INCLUDE_COMMENTS_FEATURE', 'String'),
  \ javaapi#field(1,0,'CREATE_CDATA_NODES_FEATURE', 'String'),
  \ javaapi#field(1,0,'INCLUDE_IGNORABLE_WHITESPACE', 'String'),
  \ javaapi#field(1,0,'DEFER_NODE_EXPANSION', 'String'),
  \ javaapi#field(1,0,'DOCUMENT_CLASS_NAME', 'String'),
  \ javaapi#field(1,0,'CURRENT_ELEMENT_NODE', 'String'),
  \ javaapi#field(1,0,'DEFAULT_DOCUMENT_CLASS_NAME', 'String'),
  \ javaapi#field(1,0,'CORE_DOCUMENT_CLASS_NAME', 'String'),
  \ javaapi#field(1,0,'PSVI_DOCUMENT_CLASS_NAME', 'String'),
  \ javaapi#field(0,0,'fErrorHandler', 'DOMErrorHandlerWrapper'),
  \ javaapi#field(0,0,'fInDTD', 'boolean'),
  \ javaapi#field(0,0,'fCreateEntityRefNodes', 'boolean'),
  \ javaapi#field(0,0,'fIncludeIgnorableWhitespace', 'boolean'),
  \ javaapi#field(0,0,'fIncludeComments', 'boolean'),
  \ javaapi#field(0,0,'fCreateCDATANodes', 'boolean'),
  \ javaapi#field(0,0,'fDocument', 'Document'),
  \ javaapi#field(0,0,'fDocumentImpl', 'CoreDocumentImpl'),
  \ javaapi#field(0,0,'fStorePSVI', 'boolean'),
  \ javaapi#field(0,0,'fDocumentClassName', 'String'),
  \ javaapi#field(0,0,'fDocumentType', 'DocumentType'),
  \ javaapi#field(0,0,'fCurrentNode', 'Node'),
  \ javaapi#field(0,0,'fCurrentCDATASection', 'CDATASection'),
  \ javaapi#field(0,0,'fCurrentEntityDecl', 'EntityImpl'),
  \ javaapi#field(0,0,'fDeferredEntityDecl', 'int'),
  \ javaapi#field(0,0,'fStringBuilder', 'StringBuilder'),
  \ javaapi#field(0,0,'fInternalSubset', 'StringBuilder'),
  \ javaapi#field(0,0,'fDeferNodeExpansion', 'boolean'),
  \ javaapi#field(0,0,'fNamespaceAware', 'boolean'),
  \ javaapi#field(0,0,'fDeferredDocumentImpl', 'DeferredDocumentImpl'),
  \ javaapi#field(0,0,'fDocumentIndex', 'int'),
  \ javaapi#field(0,0,'fDocumentTypeIndex', 'int'),
  \ javaapi#field(0,0,'fCurrentNodeIndex', 'int'),
  \ javaapi#field(0,0,'fCurrentCDATASectionIndex', 'int'),
  \ javaapi#field(0,0,'fInDTDExternalSubset', 'boolean'),
  \ javaapi#field(0,0,'fRoot', 'Node'),
  \ javaapi#field(0,0,'fInCDATASection', 'boolean'),
  \ javaapi#field(0,0,'fFirstChunk', 'boolean'),
  \ javaapi#field(0,0,'fFilterReject', 'boolean'),
  \ javaapi#field(0,0,'fBaseURIStack', 'Stack'),
  \ javaapi#field(0,0,'fRejectedElementDepth', 'int'),
  \ javaapi#field(0,0,'fSkippedElemStack', 'Stack'),
  \ javaapi#field(0,0,'fInEntityRef', 'boolean'),
  \ javaapi#field(0,0,'fDOMFilter', 'LSParserFilter'),
  \ javaapi#method(0,0,'AbstractDOMParser(', 'XMLParserConfiguration)', ''),
  \ javaapi#method(0,0,'getDocumentClassName(', ')', 'String'),
  \ javaapi#method(0,0,'setDocumentClassName(', 'String)', 'void'),
  \ javaapi#method(0,1,'getDocument(', ')', 'Document'),
  \ javaapi#method(0,1,'dropDocumentReferences(', ')', 'void'),
  \ javaapi#method(0,1,'reset(', ') throws XNIException', 'void'),
  \ javaapi#method(0,1,'setLocale(', 'Locale)', 'void'),
  \ javaapi#method(0,1,'startGeneralEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'textDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'comment(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'processingInstruction(', 'String, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startDocument(', 'XMLLocator, String, NamespaceContext, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'xmlDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'doctypeDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'emptyElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'characters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'ignorableWhitespace(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endElement(', 'QName, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDocument(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endGeneralEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,0,'handleBaseURI(', 'Node)', 'void'),
  \ javaapi#method(0,0,'handleBaseURI(', 'int)', 'void'),
  \ javaapi#method(0,1,'startDTD(', 'XMLLocator, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDTD(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startConditional(', 'short, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endConditional(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startExternalSubset(', 'XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endExternalSubset(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'internalEntityDecl(', 'String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'externalEntityDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startParameterEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endParameterEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'unparsedEntityDecl(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'notationDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'ignoredCharacters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'elementDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'attributeDecl(', 'String, String, String, String[], String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startAttlist(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endAttlist(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,0,'createElementNode(', 'QName)', 'Element'),
  \ javaapi#method(0,0,'createAttrNode(', 'QName)', 'Attr'),
  \ javaapi#method(0,0,'setCharacterData(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'abort(', ')', 'void'),
  \ ])

call javaapi#class('AbstractSAXParser', 'AbstractXMLDocumentParser', [
  \ javaapi#field(1,0,'NAMESPACES', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_PREFIXES', 'String'),
  \ javaapi#field(1,0,'STRING_INTERNING', 'String'),
  \ javaapi#field(1,0,'ALLOW_UE_AND_NOTATION_EVENTS', 'String'),
  \ javaapi#field(1,0,'LEXICAL_HANDLER', 'String'),
  \ javaapi#field(1,0,'DECLARATION_HANDLER', 'String'),
  \ javaapi#field(1,0,'DOM_NODE', 'String'),
  \ javaapi#field(0,0,'fNamespaces', 'boolean'),
  \ javaapi#field(0,0,'fNamespacePrefixes', 'boolean'),
  \ javaapi#field(0,0,'fLexicalHandlerParameterEntities', 'boolean'),
  \ javaapi#field(0,0,'fStandalone', 'boolean'),
  \ javaapi#field(0,0,'fResolveDTDURIs', 'boolean'),
  \ javaapi#field(0,0,'fUseEntityResolver2', 'boolean'),
  \ javaapi#field(0,0,'fXMLNSURIs', 'boolean'),
  \ javaapi#field(0,0,'fContentHandler', 'ContentHandler'),
  \ javaapi#field(0,0,'fDocumentHandler', 'DocumentHandler'),
  \ javaapi#field(0,0,'fNamespaceContext', 'NamespaceContext'),
  \ javaapi#field(0,0,'fDTDHandler', 'DTDHandler'),
  \ javaapi#field(0,0,'fDeclHandler', 'DeclHandler'),
  \ javaapi#field(0,0,'fLexicalHandler', 'LexicalHandler'),
  \ javaapi#field(0,0,'fQName', 'QName'),
  \ javaapi#field(0,0,'fParseInProgress', 'boolean'),
  \ javaapi#field(0,0,'fVersion', 'String'),
  \ javaapi#field(0,0,'fDeclaredAttrs', 'SymbolHash'),
  \ javaapi#method(0,0,'AbstractSAXParser(', 'XMLParserConfiguration)', ''),
  \ javaapi#method(0,1,'startDocument(', 'XMLLocator, String, NamespaceContext, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'xmlDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'doctypeDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startGeneralEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endGeneralEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'characters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'ignorableWhitespace(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endElement(', 'QName, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'comment(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'processingInstruction(', 'String, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDocument(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startExternalSubset(', 'XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endExternalSubset(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startParameterEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endParameterEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'elementDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'attributeDecl(', 'String, String, String, String[], String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'internalEntityDecl(', 'String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'externalEntityDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'unparsedEntityDecl(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'notationDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDTD(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'parse(', 'String) throws SAXException, IOException', 'void'),
  \ javaapi#method(0,1,'parse(', 'InputSource) throws SAXException, IOException', 'void'),
  \ javaapi#method(0,1,'setEntityResolver(', 'EntityResolver)', 'void'),
  \ javaapi#method(0,1,'getEntityResolver(', ')', 'EntityResolver'),
  \ javaapi#method(0,1,'setErrorHandler(', 'ErrorHandler)', 'void'),
  \ javaapi#method(0,1,'getErrorHandler(', ')', 'ErrorHandler'),
  \ javaapi#method(0,1,'setLocale(', 'Locale) throws SAXException', 'void'),
  \ javaapi#method(0,1,'setDTDHandler(', 'DTDHandler)', 'void'),
  \ javaapi#method(0,1,'setDocumentHandler(', 'DocumentHandler)', 'void'),
  \ javaapi#method(0,1,'setContentHandler(', 'ContentHandler)', 'void'),
  \ javaapi#method(0,1,'getContentHandler(', ')', 'ContentHandler'),
  \ javaapi#method(0,1,'getDTDHandler(', ')', 'DTDHandler'),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean) throws SAXNotRecognizedException, SAXNotSupportedException', 'void'),
  \ javaapi#method(0,1,'getFeature(', 'String) throws SAXNotRecognizedException, SAXNotSupportedException', 'boolean'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws SAXNotRecognizedException, SAXNotSupportedException', 'void'),
  \ javaapi#method(0,1,'getProperty(', 'String) throws SAXNotRecognizedException, SAXNotSupportedException', 'Object'),
  \ javaapi#method(0,0,'setDeclHandler(', 'DeclHandler) throws SAXNotRecognizedException, SAXNotSupportedException', 'void'),
  \ javaapi#method(0,0,'getDeclHandler(', ') throws SAXNotRecognizedException, SAXNotSupportedException', 'DeclHandler'),
  \ javaapi#method(0,0,'setLexicalHandler(', 'LexicalHandler) throws SAXNotRecognizedException, SAXNotSupportedException', 'void'),
  \ javaapi#method(0,0,'getLexicalHandler(', ') throws SAXNotRecognizedException, SAXNotSupportedException', 'LexicalHandler'),
  \ javaapi#method(0,0,'startNamespaceMapping(', ') throws SAXException', 'void'),
  \ javaapi#method(0,0,'endNamespaceMapping(', ') throws SAXException', 'void'),
  \ javaapi#method(0,1,'reset(', ') throws XNIException', 'void'),
  \ javaapi#method(0,1,'getElementPSVI(', ')', 'ElementPSVI'),
  \ javaapi#method(0,1,'getAttributePSVI(', 'int)', 'AttributePSVI'),
  \ javaapi#method(0,1,'getAttributePSVIByName(', 'String, String)', 'AttributePSVI'),
  \ ])

call javaapi#class('AbstractXMLDocumentParser', 'XMLParser', [
  \ javaapi#field(0,0,'fInDTD', 'boolean'),
  \ javaapi#field(0,0,'fDocumentSource', 'XMLDocumentSource'),
  \ javaapi#field(0,0,'fDTDSource', 'XMLDTDSource'),
  \ javaapi#field(0,0,'fDTDContentModelSource', 'XMLDTDContentModelSource'),
  \ javaapi#method(0,0,'AbstractXMLDocumentParser(', 'XMLParserConfiguration)', ''),
  \ javaapi#method(0,1,'startDocument(', 'XMLLocator, String, NamespaceContext, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'xmlDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'doctypeDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'emptyElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'characters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'ignorableWhitespace(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endElement(', 'QName, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDocument(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startGeneralEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'textDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endGeneralEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'comment(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'processingInstruction(', 'String, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'setDocumentSource(', 'XMLDocumentSource)', 'void'),
  \ javaapi#method(0,1,'getDocumentSource(', ')', 'XMLDocumentSource'),
  \ javaapi#method(0,1,'startDTD(', 'XMLLocator, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startExternalSubset(', 'XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endExternalSubset(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startParameterEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endParameterEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'ignoredCharacters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'elementDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startAttlist(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'attributeDecl(', 'String, String, String, String[], String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endAttlist(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'internalEntityDecl(', 'String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'externalEntityDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'unparsedEntityDecl(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'notationDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startConditional(', 'short, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endConditional(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDTD(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'setDTDSource(', 'XMLDTDSource)', 'void'),
  \ javaapi#method(0,1,'getDTDSource(', ')', 'XMLDTDSource'),
  \ javaapi#method(0,1,'startContentModel(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'any(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'empty(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startGroup(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'pcdata(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'element(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'separator(', 'short, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'occurrence(', 'short, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endGroup(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endContentModel(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'setDTDContentModelSource(', 'XMLDTDContentModelSource)', 'void'),
  \ javaapi#method(0,1,'getDTDContentModelSource(', ')', 'XMLDTDContentModelSource'),
  \ javaapi#method(0,0,'reset(', ') throws XNIException', 'void'),
  \ ])

call javaapi#class('BasicParserConfiguration', 'ParserConfigurationSettings', [
  \ javaapi#field(1,0,'VALIDATION', 'String'),
  \ javaapi#field(1,0,'NAMESPACES', 'String'),
  \ javaapi#field(1,0,'EXTERNAL_GENERAL_ENTITIES', 'String'),
  \ javaapi#field(1,0,'EXTERNAL_PARAMETER_ENTITIES', 'String'),
  \ javaapi#field(1,0,'XML_STRING', 'String'),
  \ javaapi#field(1,0,'SYMBOL_TABLE', 'String'),
  \ javaapi#field(1,0,'ERROR_HANDLER', 'String'),
  \ javaapi#field(1,0,'ENTITY_RESOLVER', 'String'),
  \ javaapi#field(0,0,'fSymbolTable', 'SymbolTable'),
  \ javaapi#field(0,0,'fLocale', 'Locale'),
  \ javaapi#field(0,0,'fComponents', 'ArrayList'),
  \ javaapi#field(0,0,'fDocumentHandler', 'XMLDocumentHandler'),
  \ javaapi#field(0,0,'fDTDHandler', 'XMLDTDHandler'),
  \ javaapi#field(0,0,'fDTDContentModelHandler', 'XMLDTDContentModelHandler'),
  \ javaapi#field(0,0,'fLastComponent', 'XMLDocumentSource'),
  \ javaapi#method(0,0,'BasicParserConfiguration(', ')', ''),
  \ javaapi#method(0,0,'BasicParserConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,0,'BasicParserConfiguration(', 'SymbolTable, XMLComponentManager)', ''),
  \ javaapi#method(0,0,'addComponent(', 'XMLComponent)', 'void'),
  \ javaapi#method(0,1,'parse(', 'XMLInputSource) throws XNIException, IOException', 'void'),
  \ javaapi#method(0,1,'setDocumentHandler(', 'XMLDocumentHandler)', 'void'),
  \ javaapi#method(0,1,'getDocumentHandler(', ')', 'XMLDocumentHandler'),
  \ javaapi#method(0,1,'setDTDHandler(', 'XMLDTDHandler)', 'void'),
  \ javaapi#method(0,1,'getDTDHandler(', ')', 'XMLDTDHandler'),
  \ javaapi#method(0,1,'setDTDContentModelHandler(', 'XMLDTDContentModelHandler)', 'void'),
  \ javaapi#method(0,1,'getDTDContentModelHandler(', ')', 'XMLDTDContentModelHandler'),
  \ javaapi#method(0,1,'setEntityResolver(', 'XMLEntityResolver)', 'void'),
  \ javaapi#method(0,1,'getEntityResolver(', ')', 'XMLEntityResolver'),
  \ javaapi#method(0,1,'setErrorHandler(', 'XMLErrorHandler)', 'void'),
  \ javaapi#method(0,1,'getErrorHandler(', ')', 'XMLErrorHandler'),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'setLocale(', 'Locale) throws XNIException', 'void'),
  \ javaapi#method(0,1,'getLocale(', ')', 'Locale'),
  \ javaapi#method(0,0,'reset(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'checkProperty(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,0,'checkFeature(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ ])

call javaapi#class('CachingParserPool', '', [
  \ javaapi#field(1,1,'DEFAULT_SHADOW_SYMBOL_TABLE', 'boolean'),
  \ javaapi#field(1,1,'DEFAULT_SHADOW_GRAMMAR_POOL', 'boolean'),
  \ javaapi#field(0,0,'fSynchronizedSymbolTable', 'SymbolTable'),
  \ javaapi#field(0,0,'fSynchronizedGrammarPool', 'XMLGrammarPool'),
  \ javaapi#field(0,0,'fShadowSymbolTable', 'boolean'),
  \ javaapi#field(0,0,'fShadowGrammarPool', 'boolean'),
  \ javaapi#method(0,1,'CachingParserPool(', ')', ''),
  \ javaapi#method(0,1,'CachingParserPool(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'getSymbolTable(', ')', 'SymbolTable'),
  \ javaapi#method(0,1,'getXMLGrammarPool(', ')', 'XMLGrammarPool'),
  \ javaapi#method(0,1,'setShadowSymbolTable(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'createDOMParser(', ')', 'DOMParser'),
  \ javaapi#method(0,1,'createSAXParser(', ')', 'SAXParser'),
  \ ])

call javaapi#class('DOMParser', 'AbstractDOMParser', [
  \ javaapi#field(1,0,'USE_ENTITY_RESOLVER2', 'String'),
  \ javaapi#field(1,0,'REPORT_WHITESPACE', 'String'),
  \ javaapi#field(1,0,'SYMBOL_TABLE', 'String'),
  \ javaapi#field(1,0,'XMLGRAMMAR_POOL', 'String'),
  \ javaapi#field(0,0,'fUseEntityResolver2', 'boolean'),
  \ javaapi#method(0,1,'DOMParser(', 'XMLParserConfiguration)', ''),
  \ javaapi#method(0,1,'DOMParser(', ')', ''),
  \ javaapi#method(0,1,'DOMParser(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'DOMParser(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'parse(', 'String) throws SAXException, IOException', 'void'),
  \ javaapi#method(0,1,'parse(', 'InputSource) throws SAXException, IOException', 'void'),
  \ javaapi#method(0,1,'setEntityResolver(', 'EntityResolver)', 'void'),
  \ javaapi#method(0,1,'getEntityResolver(', ')', 'EntityResolver'),
  \ javaapi#method(0,1,'setErrorHandler(', 'ErrorHandler)', 'void'),
  \ javaapi#method(0,1,'getErrorHandler(', ')', 'ErrorHandler'),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean) throws SAXNotRecognizedException, SAXNotSupportedException', 'void'),
  \ javaapi#method(0,1,'getFeature(', 'String) throws SAXNotRecognizedException, SAXNotSupportedException', 'boolean'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws SAXNotRecognizedException, SAXNotSupportedException', 'void'),
  \ javaapi#method(0,1,'getProperty(', 'String) throws SAXNotRecognizedException, SAXNotSupportedException', 'Object'),
  \ javaapi#method(0,1,'getXMLParserConfiguration(', ')', 'XMLParserConfiguration'),
  \ ])

call javaapi#class('DOMParserImpl', 'AbstractDOMParser', [
  \ javaapi#field(1,0,'NAMESPACES', 'String'),
  \ javaapi#field(1,0,'VALIDATION_FEATURE', 'String'),
  \ javaapi#field(1,0,'XMLSCHEMA', 'String'),
  \ javaapi#field(1,0,'XMLSCHEMA_FULL_CHECKING', 'String'),
  \ javaapi#field(1,0,'DYNAMIC_VALIDATION', 'String'),
  \ javaapi#field(1,0,'NORMALIZE_DATA', 'String'),
  \ javaapi#field(1,0,'DISALLOW_DOCTYPE_DECL_FEATURE', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_GROWTH', 'String'),
  \ javaapi#field(1,0,'TOLERATE_DUPLICATES', 'String'),
  \ javaapi#field(1,0,'SYMBOL_TABLE', 'String'),
  \ javaapi#field(1,0,'PSVI_AUGMENT', 'String'),
  \ javaapi#field(0,0,'fNamespaceDeclarations', 'boolean'),
  \ javaapi#field(0,0,'fSchemaType', 'String'),
  \ javaapi#field(0,0,'fBusy', 'boolean'),
  \ javaapi#field(1,0,'DEBUG', 'boolean'),
  \ javaapi#method(0,1,'DOMParserImpl(', 'String, String)', ''),
  \ javaapi#method(0,1,'DOMParserImpl(', 'XMLParserConfiguration)', ''),
  \ javaapi#method(0,1,'DOMParserImpl(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'DOMParserImpl(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'getDomConfig(', ')', 'DOMConfiguration'),
  \ javaapi#method(0,1,'getFilter(', ')', 'LSParserFilter'),
  \ javaapi#method(0,1,'setFilter(', 'LSParserFilter)', 'void'),
  \ javaapi#method(0,1,'setParameter(', 'String, Object) throws DOMException', 'void'),
  \ javaapi#method(0,1,'getParameter(', 'String) throws DOMException', 'Object'),
  \ javaapi#method(0,1,'canSetParameter(', 'String, Object)', 'boolean'),
  \ javaapi#method(0,1,'getParameterNames(', ')', 'DOMStringList'),
  \ javaapi#method(0,1,'parseURI(', 'String) throws LSException', 'Document'),
  \ javaapi#method(0,1,'parse(', 'LSInput) throws LSException', 'Document'),
  \ javaapi#method(0,1,'parseWithContext(', 'LSInput, Node, short) throws DOMException, LSException', 'Node'),
  \ javaapi#method(0,1,'getAsync(', ')', 'boolean'),
  \ javaapi#method(0,1,'getBusy(', ')', 'boolean'),
  \ javaapi#method(0,1,'abort(', ')', 'void'),
  \ javaapi#method(0,1,'startElement(', 'QName, XMLAttributes, Augmentations)', 'void'),
  \ ])

call javaapi#class('DTDConfiguration', 'BasicParserConfiguration', [
  \ javaapi#field(1,0,'WARN_ON_DUPLICATE_ATTDEF', 'String'),
  \ javaapi#field(1,0,'WARN_ON_DUPLICATE_ENTITYDEF', 'String'),
  \ javaapi#field(1,0,'WARN_ON_UNDECLARED_ELEMDEF', 'String'),
  \ javaapi#field(1,0,'ALLOW_JAVA_ENCODINGS', 'String'),
  \ javaapi#field(1,0,'CONTINUE_AFTER_FATAL_ERROR', 'String'),
  \ javaapi#field(1,0,'LOAD_EXTERNAL_DTD', 'String'),
  \ javaapi#field(1,0,'NOTIFY_BUILTIN_REFS', 'String'),
  \ javaapi#field(1,0,'NOTIFY_CHAR_REFS', 'String'),
  \ javaapi#field(1,0,'ERROR_REPORTER', 'String'),
  \ javaapi#field(1,0,'ENTITY_MANAGER', 'String'),
  \ javaapi#field(1,0,'DOCUMENT_SCANNER', 'String'),
  \ javaapi#field(1,0,'DTD_SCANNER', 'String'),
  \ javaapi#field(1,0,'XMLGRAMMAR_POOL', 'String'),
  \ javaapi#field(1,0,'DTD_PROCESSOR', 'String'),
  \ javaapi#field(1,0,'DTD_VALIDATOR', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_BINDER', 'String'),
  \ javaapi#field(1,0,'DATATYPE_VALIDATOR_FACTORY', 'String'),
  \ javaapi#field(1,0,'VALIDATION_MANAGER', 'String'),
  \ javaapi#field(1,0,'JAXP_SCHEMA_LANGUAGE', 'String'),
  \ javaapi#field(1,0,'JAXP_SCHEMA_SOURCE', 'String'),
  \ javaapi#field(1,0,'LOCALE', 'String'),
  \ javaapi#field(1,0,'PRINT_EXCEPTION_STACK_TRACE', 'boolean'),
  \ javaapi#field(0,0,'fGrammarPool', 'XMLGrammarPool'),
  \ javaapi#field(0,0,'fDatatypeValidatorFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fErrorReporter', 'XMLErrorReporter'),
  \ javaapi#field(0,0,'fEntityManager', 'XMLEntityManager'),
  \ javaapi#field(0,0,'fScanner', 'XMLDocumentScanner'),
  \ javaapi#field(0,0,'fInputSource', 'XMLInputSource'),
  \ javaapi#field(0,0,'fDTDScanner', 'XMLDTDScanner'),
  \ javaapi#field(0,0,'fDTDProcessor', 'XMLDTDProcessor'),
  \ javaapi#field(0,0,'fDTDValidator', 'XMLDTDValidator'),
  \ javaapi#field(0,0,'fNamespaceBinder', 'XMLNamespaceBinder'),
  \ javaapi#field(0,0,'fValidationManager', 'ValidationManager'),
  \ javaapi#field(0,0,'fLocator', 'XMLLocator'),
  \ javaapi#field(0,0,'fParseInProgress', 'boolean'),
  \ javaapi#method(0,1,'DTDConfiguration(', ')', ''),
  \ javaapi#method(0,1,'DTDConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'DTDConfiguration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'DTDConfiguration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,1,'getPropertyState(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'setLocale(', 'Locale) throws XNIException', 'void'),
  \ javaapi#method(0,1,'setInputSource(', 'XMLInputSource) throws XMLConfigurationException, IOException', 'void'),
  \ javaapi#method(0,1,'parse(', 'boolean) throws XNIException, IOException', 'boolean'),
  \ javaapi#method(0,1,'cleanup(', ')', 'void'),
  \ javaapi#method(0,1,'parse(', 'XMLInputSource) throws XNIException, IOException', 'void'),
  \ javaapi#method(0,0,'reset(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'configurePipeline(', ')', 'void'),
  \ javaapi#method(0,0,'configureDTDPipeline(', ')', 'void'),
  \ javaapi#method(0,0,'checkFeature(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,0,'checkProperty(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,0,'createEntityManager(', ')', 'XMLEntityManager'),
  \ javaapi#method(0,0,'createErrorReporter(', ')', 'XMLErrorReporter'),
  \ javaapi#method(0,0,'createDocumentScanner(', ')', 'XMLDocumentScanner'),
  \ javaapi#method(0,0,'createDTDScanner(', ')', 'XMLDTDScanner'),
  \ javaapi#method(0,0,'createDTDProcessor(', ')', 'XMLDTDProcessor'),
  \ javaapi#method(0,0,'createDTDValidator(', ')', 'XMLDTDValidator'),
  \ javaapi#method(0,0,'createNamespaceBinder(', ')', 'XMLNamespaceBinder'),
  \ javaapi#method(0,0,'createDatatypeValidatorFactory(', ')', 'DTDDVFactory'),
  \ javaapi#method(0,0,'createValidationManager(', ')', 'ValidationManager'),
  \ ])

call javaapi#class('DTDParser', 'XMLGrammarParser', [
  \ javaapi#field(0,0,'fDTDScanner', 'XMLDTDScanner'),
  \ javaapi#method(0,1,'DTDParser(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'getDTDGrammar(', ')', 'DTDGrammar'),
  \ javaapi#method(0,1,'startEntity(', 'String, String, String, String) throws XNIException', 'void'),
  \ javaapi#method(0,1,'textDecl(', 'String, String) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startDTD(', 'XMLLocator, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'comment(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'processingInstruction(', 'String, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startExternalSubset(', 'XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endExternalSubset(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'elementDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startAttlist(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'attributeDecl(', 'String, String, String, String[], String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endAttlist(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'internalEntityDecl(', 'String, XMLString, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'externalEntityDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'unparsedEntityDecl(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'notationDecl(', 'String, XMLResourceIdentifier, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startConditional(', 'short, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endConditional(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDTD(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startContentModel(', 'String, short) throws XNIException', 'void'),
  \ javaapi#method(0,1,'mixedElement(', 'String) throws XNIException', 'void'),
  \ javaapi#method(0,1,'childrenStartGroup(', ') throws XNIException', 'void'),
  \ javaapi#method(0,1,'childrenElement(', 'String) throws XNIException', 'void'),
  \ javaapi#method(0,1,'childrenSeparator(', 'short) throws XNIException', 'void'),
  \ javaapi#method(0,1,'childrenOccurrence(', 'short) throws XNIException', 'void'),
  \ javaapi#method(0,1,'childrenEndGroup(', ') throws XNIException', 'void'),
  \ javaapi#method(0,1,'endContentModel(', ') throws XNIException', 'void'),
  \ ])

call javaapi#class('IntegratedParserConfiguration', 'StandardParserConfiguration', [
  \ javaapi#field(0,0,'fNamespaceScanner', 'XMLNSDocumentScannerImpl'),
  \ javaapi#field(0,0,'fNonNSScanner', 'XMLDocumentScannerImpl'),
  \ javaapi#field(0,0,'fNonNSDTDValidator', 'XMLDTDValidator'),
  \ javaapi#method(0,1,'IntegratedParserConfiguration(', ')', ''),
  \ javaapi#method(0,1,'IntegratedParserConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'IntegratedParserConfiguration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'IntegratedParserConfiguration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,0,'configurePipeline(', ')', 'void'),
  \ javaapi#method(0,0,'createDocumentScanner(', ')', 'XMLDocumentScanner'),
  \ javaapi#method(0,0,'createDTDValidator(', ')', 'XMLDTDValidator'),
  \ ])

call javaapi#class('NonValidatingConfiguration', 'BasicParserConfiguration', [
  \ javaapi#field(1,0,'WARN_ON_DUPLICATE_ATTDEF', 'String'),
  \ javaapi#field(1,0,'WARN_ON_DUPLICATE_ENTITYDEF', 'String'),
  \ javaapi#field(1,0,'WARN_ON_UNDECLARED_ELEMDEF', 'String'),
  \ javaapi#field(1,0,'ALLOW_JAVA_ENCODINGS', 'String'),
  \ javaapi#field(1,0,'CONTINUE_AFTER_FATAL_ERROR', 'String'),
  \ javaapi#field(1,0,'LOAD_EXTERNAL_DTD', 'String'),
  \ javaapi#field(1,0,'NOTIFY_BUILTIN_REFS', 'String'),
  \ javaapi#field(1,0,'NOTIFY_CHAR_REFS', 'String'),
  \ javaapi#field(1,0,'NORMALIZE_DATA', 'String'),
  \ javaapi#field(1,0,'SCHEMA_ELEMENT_DEFAULT', 'String'),
  \ javaapi#field(1,0,'ERROR_REPORTER', 'String'),
  \ javaapi#field(1,0,'ENTITY_MANAGER', 'String'),
  \ javaapi#field(1,0,'DOCUMENT_SCANNER', 'String'),
  \ javaapi#field(1,0,'DTD_SCANNER', 'String'),
  \ javaapi#field(1,0,'XMLGRAMMAR_POOL', 'String'),
  \ javaapi#field(1,0,'DTD_VALIDATOR', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_BINDER', 'String'),
  \ javaapi#field(1,0,'DATATYPE_VALIDATOR_FACTORY', 'String'),
  \ javaapi#field(1,0,'VALIDATION_MANAGER', 'String'),
  \ javaapi#field(1,0,'SCHEMA_VALIDATOR', 'String'),
  \ javaapi#field(1,0,'LOCALE', 'String'),
  \ javaapi#field(0,0,'fGrammarPool', 'XMLGrammarPool'),
  \ javaapi#field(0,0,'fDatatypeValidatorFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fErrorReporter', 'XMLErrorReporter'),
  \ javaapi#field(0,0,'fEntityManager', 'XMLEntityManager'),
  \ javaapi#field(0,0,'fScanner', 'XMLDocumentScanner'),
  \ javaapi#field(0,0,'fInputSource', 'XMLInputSource'),
  \ javaapi#field(0,0,'fDTDScanner', 'XMLDTDScanner'),
  \ javaapi#field(0,0,'fValidationManager', 'ValidationManager'),
  \ javaapi#field(0,0,'fConfigUpdated', 'boolean'),
  \ javaapi#field(0,0,'fLocator', 'XMLLocator'),
  \ javaapi#field(0,0,'fParseInProgress', 'boolean'),
  \ javaapi#method(0,1,'NonValidatingConfiguration(', ')', ''),
  \ javaapi#method(0,1,'NonValidatingConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'NonValidatingConfiguration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'NonValidatingConfiguration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'getPropertyState(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'setLocale(', 'Locale) throws XNIException', 'void'),
  \ javaapi#method(0,1,'getFeatureState(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,1,'setInputSource(', 'XMLInputSource) throws XMLConfigurationException, IOException', 'void'),
  \ javaapi#method(0,1,'parse(', 'boolean) throws XNIException, IOException', 'boolean'),
  \ javaapi#method(0,1,'cleanup(', ')', 'void'),
  \ javaapi#method(0,1,'parse(', 'XMLInputSource) throws XNIException, IOException', 'void'),
  \ javaapi#method(0,0,'reset(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'configurePipeline(', ')', 'void'),
  \ javaapi#method(0,0,'checkFeature(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,0,'checkProperty(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,0,'createEntityManager(', ')', 'XMLEntityManager'),
  \ javaapi#method(0,0,'createErrorReporter(', ')', 'XMLErrorReporter'),
  \ javaapi#method(0,0,'createDocumentScanner(', ')', 'XMLDocumentScanner'),
  \ javaapi#method(0,0,'createDTDScanner(', ')', 'XMLDTDScanner'),
  \ javaapi#method(0,0,'createDatatypeValidatorFactory(', ')', 'DTDDVFactory'),
  \ javaapi#method(0,0,'createValidationManager(', ')', 'ValidationManager'),
  \ ])

call javaapi#class('SAXParser', 'AbstractSAXParser', [
  \ javaapi#field(1,0,'NOTIFY_BUILTIN_REFS', 'String'),
  \ javaapi#field(1,0,'REPORT_WHITESPACE', 'String'),
  \ javaapi#field(1,0,'SYMBOL_TABLE', 'String'),
  \ javaapi#field(1,0,'XMLGRAMMAR_POOL', 'String'),
  \ javaapi#method(0,1,'SAXParser(', 'XMLParserConfiguration)', ''),
  \ javaapi#method(0,1,'SAXParser(', ')', ''),
  \ javaapi#method(0,1,'SAXParser(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'SAXParser(', 'SymbolTable, XMLGrammarPool)', ''),
  \ ])

call javaapi#class('SecurityConfiguration', 'XIncludeAwareParserConfiguration', [
  \ javaapi#field(1,0,'SECURITY_MANAGER_PROPERTY', 'String'),
  \ javaapi#method(0,1,'SecurityConfiguration(', ')', ''),
  \ javaapi#method(0,1,'SecurityConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'SecurityConfiguration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'SecurityConfiguration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ ])

call javaapi#class('StandardParserConfiguration', 'DTDConfiguration', [
  \ javaapi#field(1,0,'NORMALIZE_DATA', 'String'),
  \ javaapi#field(1,0,'SCHEMA_ELEMENT_DEFAULT', 'String'),
  \ javaapi#field(1,0,'SCHEMA_AUGMENT_PSVI', 'String'),
  \ javaapi#field(1,0,'XMLSCHEMA_VALIDATION', 'String'),
  \ javaapi#field(1,0,'XMLSCHEMA_FULL_CHECKING', 'String'),
  \ javaapi#field(1,0,'GENERATE_SYNTHETIC_ANNOTATIONS', 'String'),
  \ javaapi#field(1,0,'VALIDATE_ANNOTATIONS', 'String'),
  \ javaapi#field(1,0,'HONOUR_ALL_SCHEMALOCATIONS', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_GROWTH', 'String'),
  \ javaapi#field(1,0,'TOLERATE_DUPLICATES', 'String'),
  \ javaapi#field(1,0,'SCHEMA_VALIDATOR', 'String'),
  \ javaapi#field(1,0,'SCHEMA_LOCATION', 'String'),
  \ javaapi#field(1,0,'SCHEMA_NONS_LOCATION', 'String'),
  \ javaapi#field(1,0,'SCHEMA_DV_FACTORY', 'String'),
  \ javaapi#field(0,0,'fSchemaValidator', 'XMLSchemaValidator'),
  \ javaapi#method(0,1,'StandardParserConfiguration(', ')', ''),
  \ javaapi#method(0,1,'StandardParserConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'StandardParserConfiguration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'StandardParserConfiguration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,0,'configurePipeline(', ')', 'void'),
  \ javaapi#method(0,0,'checkFeature(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,0,'checkProperty(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ ])

call javaapi#class('XIncludeAwareParserConfiguration', 'XML11Configuration', [
  \ javaapi#field(1,0,'ALLOW_UE_AND_NOTATION_EVENTS', 'String'),
  \ javaapi#field(1,0,'XINCLUDE_FIXUP_BASE_URIS', 'String'),
  \ javaapi#field(1,0,'XINCLUDE_FIXUP_LANGUAGE', 'String'),
  \ javaapi#field(1,0,'XINCLUDE_FEATURE', 'String'),
  \ javaapi#field(1,0,'XINCLUDE_HANDLER', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_CONTEXT', 'String'),
  \ javaapi#field(0,0,'fXIncludeHandler', 'XIncludeHandler'),
  \ javaapi#field(0,0,'fNonXIncludeNSContext', 'NamespaceSupport'),
  \ javaapi#field(0,0,'fXIncludeNSContext', 'XIncludeNamespaceSupport'),
  \ javaapi#field(0,0,'fCurrentNSContext', 'NamespaceContext'),
  \ javaapi#field(0,0,'fXIncludeEnabled', 'boolean'),
  \ javaapi#method(0,1,'XIncludeAwareParserConfiguration(', ')', ''),
  \ javaapi#method(0,1,'XIncludeAwareParserConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'XIncludeAwareParserConfiguration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'XIncludeAwareParserConfiguration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,0,'configurePipeline(', ')', 'void'),
  \ javaapi#method(0,0,'configureXML11Pipeline(', ')', 'void'),
  \ javaapi#method(0,1,'getFeatureState(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean) throws XMLConfigurationException', 'void'),
  \ ])

call javaapi#class('XIncludeParserConfiguration', 'XML11Configuration', [
  \ javaapi#field(1,0,'ALLOW_UE_AND_NOTATION_EVENTS', 'String'),
  \ javaapi#field(1,0,'XINCLUDE_FIXUP_BASE_URIS', 'String'),
  \ javaapi#field(1,0,'XINCLUDE_FIXUP_LANGUAGE', 'String'),
  \ javaapi#field(1,0,'XINCLUDE_HANDLER', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_CONTEXT', 'String'),
  \ javaapi#method(0,1,'XIncludeParserConfiguration(', ')', ''),
  \ javaapi#method(0,1,'XIncludeParserConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'XIncludeParserConfiguration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'XIncludeParserConfiguration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,0,'configurePipeline(', ')', 'void'),
  \ javaapi#method(0,0,'configureXML11Pipeline(', ')', 'void'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws XMLConfigurationException', 'void'),
  \ ])

call javaapi#interface('XML11Configurable', '', [
  \ ])

call javaapi#class('XML11Configuration', 'ParserConfigurationSettings', [
  \ javaapi#field(1,0,'XML11_DATATYPE_VALIDATOR_FACTORY', 'String'),
  \ javaapi#field(1,0,'WARN_ON_DUPLICATE_ATTDEF', 'String'),
  \ javaapi#field(1,0,'WARN_ON_DUPLICATE_ENTITYDEF', 'String'),
  \ javaapi#field(1,0,'WARN_ON_UNDECLARED_ELEMDEF', 'String'),
  \ javaapi#field(1,0,'ALLOW_JAVA_ENCODINGS', 'String'),
  \ javaapi#field(1,0,'CONTINUE_AFTER_FATAL_ERROR', 'String'),
  \ javaapi#field(1,0,'LOAD_EXTERNAL_DTD', 'String'),
  \ javaapi#field(1,0,'NOTIFY_BUILTIN_REFS', 'String'),
  \ javaapi#field(1,0,'NOTIFY_CHAR_REFS', 'String'),
  \ javaapi#field(1,0,'NORMALIZE_DATA', 'String'),
  \ javaapi#field(1,0,'SCHEMA_ELEMENT_DEFAULT', 'String'),
  \ javaapi#field(1,0,'SCHEMA_AUGMENT_PSVI', 'String'),
  \ javaapi#field(1,0,'XMLSCHEMA_VALIDATION', 'String'),
  \ javaapi#field(1,0,'XMLSCHEMA_FULL_CHECKING', 'String'),
  \ javaapi#field(1,0,'GENERATE_SYNTHETIC_ANNOTATIONS', 'String'),
  \ javaapi#field(1,0,'VALIDATE_ANNOTATIONS', 'String'),
  \ javaapi#field(1,0,'HONOUR_ALL_SCHEMALOCATIONS', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_GROWTH', 'String'),
  \ javaapi#field(1,0,'TOLERATE_DUPLICATES', 'String'),
  \ javaapi#field(1,0,'USE_GRAMMAR_POOL_ONLY', 'String'),
  \ javaapi#field(1,0,'VALIDATION', 'String'),
  \ javaapi#field(1,0,'NAMESPACES', 'String'),
  \ javaapi#field(1,0,'EXTERNAL_GENERAL_ENTITIES', 'String'),
  \ javaapi#field(1,0,'EXTERNAL_PARAMETER_ENTITIES', 'String'),
  \ javaapi#field(1,0,'XML_STRING', 'String'),
  \ javaapi#field(1,0,'SYMBOL_TABLE', 'String'),
  \ javaapi#field(1,0,'ERROR_HANDLER', 'String'),
  \ javaapi#field(1,0,'ENTITY_RESOLVER', 'String'),
  \ javaapi#field(1,0,'SCHEMA_VALIDATOR', 'String'),
  \ javaapi#field(1,0,'SCHEMA_LOCATION', 'String'),
  \ javaapi#field(1,0,'SCHEMA_NONS_LOCATION', 'String'),
  \ javaapi#field(1,0,'ERROR_REPORTER', 'String'),
  \ javaapi#field(1,0,'ENTITY_MANAGER', 'String'),
  \ javaapi#field(1,0,'DOCUMENT_SCANNER', 'String'),
  \ javaapi#field(1,0,'DTD_SCANNER', 'String'),
  \ javaapi#field(1,0,'XMLGRAMMAR_POOL', 'String'),
  \ javaapi#field(1,0,'DTD_PROCESSOR', 'String'),
  \ javaapi#field(1,0,'DTD_VALIDATOR', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_BINDER', 'String'),
  \ javaapi#field(1,0,'DATATYPE_VALIDATOR_FACTORY', 'String'),
  \ javaapi#field(1,0,'VALIDATION_MANAGER', 'String'),
  \ javaapi#field(1,0,'JAXP_SCHEMA_LANGUAGE', 'String'),
  \ javaapi#field(1,0,'JAXP_SCHEMA_SOURCE', 'String'),
  \ javaapi#field(1,0,'LOCALE', 'String'),
  \ javaapi#field(1,0,'SCHEMA_DV_FACTORY', 'String'),
  \ javaapi#field(1,0,'PRINT_EXCEPTION_STACK_TRACE', 'boolean'),
  \ javaapi#field(0,0,'fSymbolTable', 'SymbolTable'),
  \ javaapi#field(0,0,'fInputSource', 'XMLInputSource'),
  \ javaapi#field(0,0,'fValidationManager', 'ValidationManager'),
  \ javaapi#field(0,0,'fVersionDetector', 'XMLVersionDetector'),
  \ javaapi#field(0,0,'fLocator', 'XMLLocator'),
  \ javaapi#field(0,0,'fLocale', 'Locale'),
  \ javaapi#field(0,0,'fComponents', 'ArrayList'),
  \ javaapi#field(0,0,'fXML11Components', 'ArrayList'),
  \ javaapi#field(0,0,'fCommonComponents', 'ArrayList'),
  \ javaapi#field(0,0,'fDocumentHandler', 'XMLDocumentHandler'),
  \ javaapi#field(0,0,'fDTDHandler', 'XMLDTDHandler'),
  \ javaapi#field(0,0,'fDTDContentModelHandler', 'XMLDTDContentModelHandler'),
  \ javaapi#field(0,0,'fLastComponent', 'XMLDocumentSource'),
  \ javaapi#field(0,0,'fParseInProgress', 'boolean'),
  \ javaapi#field(0,0,'fConfigUpdated', 'boolean'),
  \ javaapi#field(0,0,'fDatatypeValidatorFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fNamespaceScanner', 'XMLNSDocumentScannerImpl'),
  \ javaapi#field(0,0,'fNonNSScanner', 'XMLDocumentScannerImpl'),
  \ javaapi#field(0,0,'fDTDValidator', 'XMLDTDValidator'),
  \ javaapi#field(0,0,'fNonNSDTDValidator', 'XMLDTDValidator'),
  \ javaapi#field(0,0,'fDTDScanner', 'XMLDTDScanner'),
  \ javaapi#field(0,0,'fDTDProcessor', 'XMLDTDProcessor'),
  \ javaapi#field(0,0,'fXML11DatatypeFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fXML11NSDocScanner', 'XML11NSDocumentScannerImpl'),
  \ javaapi#field(0,0,'fXML11DocScanner', 'XML11DocumentScannerImpl'),
  \ javaapi#field(0,0,'fXML11NSDTDValidator', 'XML11NSDTDValidator'),
  \ javaapi#field(0,0,'fXML11DTDValidator', 'XML11DTDValidator'),
  \ javaapi#field(0,0,'fXML11DTDScanner', 'XML11DTDScannerImpl'),
  \ javaapi#field(0,0,'fXML11DTDProcessor', 'XML11DTDProcessor'),
  \ javaapi#field(0,0,'fGrammarPool', 'XMLGrammarPool'),
  \ javaapi#field(0,0,'fErrorReporter', 'XMLErrorReporter'),
  \ javaapi#field(0,0,'fEntityManager', 'XMLEntityManager'),
  \ javaapi#field(0,0,'fSchemaValidator', 'XMLSchemaValidator'),
  \ javaapi#field(0,0,'fCurrentScanner', 'XMLDocumentScanner'),
  \ javaapi#field(0,0,'fCurrentDVFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fCurrentDTDScanner', 'XMLDTDScanner'),
  \ javaapi#method(0,1,'XML11Configuration(', ')', ''),
  \ javaapi#method(0,1,'XML11Configuration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'XML11Configuration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'XML11Configuration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,1,'setInputSource(', 'XMLInputSource) throws XMLConfigurationException, IOException', 'void'),
  \ javaapi#method(0,1,'setLocale(', 'Locale) throws XNIException', 'void'),
  \ javaapi#method(0,1,'setDocumentHandler(', 'XMLDocumentHandler)', 'void'),
  \ javaapi#method(0,1,'getDocumentHandler(', ')', 'XMLDocumentHandler'),
  \ javaapi#method(0,1,'setDTDHandler(', 'XMLDTDHandler)', 'void'),
  \ javaapi#method(0,1,'getDTDHandler(', ')', 'XMLDTDHandler'),
  \ javaapi#method(0,1,'setDTDContentModelHandler(', 'XMLDTDContentModelHandler)', 'void'),
  \ javaapi#method(0,1,'getDTDContentModelHandler(', ')', 'XMLDTDContentModelHandler'),
  \ javaapi#method(0,1,'setEntityResolver(', 'XMLEntityResolver)', 'void'),
  \ javaapi#method(0,1,'getEntityResolver(', ')', 'XMLEntityResolver'),
  \ javaapi#method(0,1,'setErrorHandler(', 'XMLErrorHandler)', 'void'),
  \ javaapi#method(0,1,'getErrorHandler(', ')', 'XMLErrorHandler'),
  \ javaapi#method(0,1,'cleanup(', ')', 'void'),
  \ javaapi#method(0,1,'parse(', 'XMLInputSource) throws XNIException, IOException', 'void'),
  \ javaapi#method(0,1,'parse(', 'boolean) throws XNIException, IOException', 'boolean'),
  \ javaapi#method(0,1,'getFeatureState(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'getPropertyState(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'getLocale(', ')', 'Locale'),
  \ javaapi#method(0,0,'reset(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'resetCommon(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'resetXML11(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'configureXML11Pipeline(', ')', 'void'),
  \ javaapi#method(0,0,'configurePipeline(', ')', 'void'),
  \ javaapi#method(0,0,'checkFeature(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,0,'checkProperty(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,0,'addComponent(', 'XMLComponent)', 'void'),
  \ javaapi#method(0,0,'addCommonComponent(', 'XMLComponent)', 'void'),
  \ javaapi#method(0,0,'addXML11Component(', 'XMLComponent)', 'void'),
  \ javaapi#method(0,0,'addRecognizedParamsAndSetDefaults(', 'XMLComponent)', 'void'),
  \ ])

call javaapi#class('XML11DTDConfiguration', 'ParserConfigurationSettings', [
  \ javaapi#field(1,0,'XML11_DATATYPE_VALIDATOR_FACTORY', 'String'),
  \ javaapi#field(1,0,'VALIDATION', 'String'),
  \ javaapi#field(1,0,'NAMESPACES', 'String'),
  \ javaapi#field(1,0,'EXTERNAL_GENERAL_ENTITIES', 'String'),
  \ javaapi#field(1,0,'EXTERNAL_PARAMETER_ENTITIES', 'String'),
  \ javaapi#field(1,0,'CONTINUE_AFTER_FATAL_ERROR', 'String'),
  \ javaapi#field(1,0,'LOAD_EXTERNAL_DTD', 'String'),
  \ javaapi#field(1,0,'XML_STRING', 'String'),
  \ javaapi#field(1,0,'SYMBOL_TABLE', 'String'),
  \ javaapi#field(1,0,'ERROR_HANDLER', 'String'),
  \ javaapi#field(1,0,'ENTITY_RESOLVER', 'String'),
  \ javaapi#field(1,0,'ERROR_REPORTER', 'String'),
  \ javaapi#field(1,0,'ENTITY_MANAGER', 'String'),
  \ javaapi#field(1,0,'DOCUMENT_SCANNER', 'String'),
  \ javaapi#field(1,0,'DTD_SCANNER', 'String'),
  \ javaapi#field(1,0,'XMLGRAMMAR_POOL', 'String'),
  \ javaapi#field(1,0,'DTD_PROCESSOR', 'String'),
  \ javaapi#field(1,0,'DTD_VALIDATOR', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_BINDER', 'String'),
  \ javaapi#field(1,0,'DATATYPE_VALIDATOR_FACTORY', 'String'),
  \ javaapi#field(1,0,'VALIDATION_MANAGER', 'String'),
  \ javaapi#field(1,0,'JAXP_SCHEMA_LANGUAGE', 'String'),
  \ javaapi#field(1,0,'JAXP_SCHEMA_SOURCE', 'String'),
  \ javaapi#field(1,0,'PRINT_EXCEPTION_STACK_TRACE', 'boolean'),
  \ javaapi#field(0,0,'fSymbolTable', 'SymbolTable'),
  \ javaapi#field(0,0,'fInputSource', 'XMLInputSource'),
  \ javaapi#field(0,0,'fValidationManager', 'ValidationManager'),
  \ javaapi#field(0,0,'fVersionDetector', 'XMLVersionDetector'),
  \ javaapi#field(0,0,'fLocator', 'XMLLocator'),
  \ javaapi#field(0,0,'fLocale', 'Locale'),
  \ javaapi#field(0,0,'fComponents', 'ArrayList'),
  \ javaapi#field(0,0,'fXML11Components', 'ArrayList'),
  \ javaapi#field(0,0,'fCommonComponents', 'ArrayList'),
  \ javaapi#field(0,0,'fDocumentHandler', 'XMLDocumentHandler'),
  \ javaapi#field(0,0,'fDTDHandler', 'XMLDTDHandler'),
  \ javaapi#field(0,0,'fDTDContentModelHandler', 'XMLDTDContentModelHandler'),
  \ javaapi#field(0,0,'fLastComponent', 'XMLDocumentSource'),
  \ javaapi#field(0,0,'fParseInProgress', 'boolean'),
  \ javaapi#field(0,0,'fConfigUpdated', 'boolean'),
  \ javaapi#field(0,0,'fDatatypeValidatorFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fNamespaceScanner', 'XMLNSDocumentScannerImpl'),
  \ javaapi#field(0,0,'fNonNSScanner', 'XMLDocumentScannerImpl'),
  \ javaapi#field(0,0,'fDTDValidator', 'XMLDTDValidator'),
  \ javaapi#field(0,0,'fNonNSDTDValidator', 'XMLDTDValidator'),
  \ javaapi#field(0,0,'fDTDScanner', 'XMLDTDScanner'),
  \ javaapi#field(0,0,'fDTDProcessor', 'XMLDTDProcessor'),
  \ javaapi#field(0,0,'fXML11DatatypeFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fXML11NSDocScanner', 'XML11NSDocumentScannerImpl'),
  \ javaapi#field(0,0,'fXML11DocScanner', 'XML11DocumentScannerImpl'),
  \ javaapi#field(0,0,'fXML11NSDTDValidator', 'XML11NSDTDValidator'),
  \ javaapi#field(0,0,'fXML11DTDValidator', 'XML11DTDValidator'),
  \ javaapi#field(0,0,'fXML11DTDScanner', 'XML11DTDScannerImpl'),
  \ javaapi#field(0,0,'fXML11DTDProcessor', 'XML11DTDProcessor'),
  \ javaapi#field(0,0,'fGrammarPool', 'XMLGrammarPool'),
  \ javaapi#field(0,0,'fErrorReporter', 'XMLErrorReporter'),
  \ javaapi#field(0,0,'fEntityManager', 'XMLEntityManager'),
  \ javaapi#field(0,0,'fCurrentScanner', 'XMLDocumentScanner'),
  \ javaapi#field(0,0,'fCurrentDVFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fCurrentDTDScanner', 'XMLDTDScanner'),
  \ javaapi#method(0,1,'XML11DTDConfiguration(', ')', ''),
  \ javaapi#method(0,1,'XML11DTDConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'XML11DTDConfiguration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'XML11DTDConfiguration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,1,'setInputSource(', 'XMLInputSource) throws XMLConfigurationException, IOException', 'void'),
  \ javaapi#method(0,1,'setLocale(', 'Locale) throws XNIException', 'void'),
  \ javaapi#method(0,1,'setDocumentHandler(', 'XMLDocumentHandler)', 'void'),
  \ javaapi#method(0,1,'getDocumentHandler(', ')', 'XMLDocumentHandler'),
  \ javaapi#method(0,1,'setDTDHandler(', 'XMLDTDHandler)', 'void'),
  \ javaapi#method(0,1,'getDTDHandler(', ')', 'XMLDTDHandler'),
  \ javaapi#method(0,1,'setDTDContentModelHandler(', 'XMLDTDContentModelHandler)', 'void'),
  \ javaapi#method(0,1,'getDTDContentModelHandler(', ')', 'XMLDTDContentModelHandler'),
  \ javaapi#method(0,1,'setEntityResolver(', 'XMLEntityResolver)', 'void'),
  \ javaapi#method(0,1,'getEntityResolver(', ')', 'XMLEntityResolver'),
  \ javaapi#method(0,1,'setErrorHandler(', 'XMLErrorHandler)', 'void'),
  \ javaapi#method(0,1,'getErrorHandler(', ')', 'XMLErrorHandler'),
  \ javaapi#method(0,1,'cleanup(', ')', 'void'),
  \ javaapi#method(0,1,'parse(', 'XMLInputSource) throws XNIException, IOException', 'void'),
  \ javaapi#method(0,1,'parse(', 'boolean) throws XNIException, IOException', 'boolean'),
  \ javaapi#method(0,1,'getFeatureState(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'getLocale(', ')', 'Locale'),
  \ javaapi#method(0,0,'reset(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'resetCommon(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'resetXML11(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'configureXML11Pipeline(', ')', 'void'),
  \ javaapi#method(0,0,'configurePipeline(', ')', 'void'),
  \ javaapi#method(0,0,'checkFeature(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,0,'checkProperty(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,0,'addComponent(', 'XMLComponent)', 'void'),
  \ javaapi#method(0,0,'addCommonComponent(', 'XMLComponent)', 'void'),
  \ javaapi#method(0,0,'addXML11Component(', 'XMLComponent)', 'void'),
  \ javaapi#method(0,0,'addRecognizedParamsAndSetDefaults(', 'XMLComponent)', 'void'),
  \ ])

call javaapi#class('XML11NonValidatingConfiguration', 'ParserConfigurationSettings', [
  \ javaapi#field(1,0,'XML11_DATATYPE_VALIDATOR_FACTORY', 'String'),
  \ javaapi#field(1,0,'VALIDATION', 'String'),
  \ javaapi#field(1,0,'NAMESPACES', 'String'),
  \ javaapi#field(1,0,'EXTERNAL_GENERAL_ENTITIES', 'String'),
  \ javaapi#field(1,0,'EXTERNAL_PARAMETER_ENTITIES', 'String'),
  \ javaapi#field(1,0,'CONTINUE_AFTER_FATAL_ERROR', 'String'),
  \ javaapi#field(1,0,'XML_STRING', 'String'),
  \ javaapi#field(1,0,'SYMBOL_TABLE', 'String'),
  \ javaapi#field(1,0,'ERROR_HANDLER', 'String'),
  \ javaapi#field(1,0,'ENTITY_RESOLVER', 'String'),
  \ javaapi#field(1,0,'ERROR_REPORTER', 'String'),
  \ javaapi#field(1,0,'ENTITY_MANAGER', 'String'),
  \ javaapi#field(1,0,'DOCUMENT_SCANNER', 'String'),
  \ javaapi#field(1,0,'DTD_SCANNER', 'String'),
  \ javaapi#field(1,0,'XMLGRAMMAR_POOL', 'String'),
  \ javaapi#field(1,0,'DTD_VALIDATOR', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_BINDER', 'String'),
  \ javaapi#field(1,0,'DATATYPE_VALIDATOR_FACTORY', 'String'),
  \ javaapi#field(1,0,'VALIDATION_MANAGER', 'String'),
  \ javaapi#field(1,0,'PRINT_EXCEPTION_STACK_TRACE', 'boolean'),
  \ javaapi#field(0,0,'fSymbolTable', 'SymbolTable'),
  \ javaapi#field(0,0,'fInputSource', 'XMLInputSource'),
  \ javaapi#field(0,0,'fValidationManager', 'ValidationManager'),
  \ javaapi#field(0,0,'fVersionDetector', 'XMLVersionDetector'),
  \ javaapi#field(0,0,'fLocator', 'XMLLocator'),
  \ javaapi#field(0,0,'fLocale', 'Locale'),
  \ javaapi#field(0,0,'fComponents', 'ArrayList'),
  \ javaapi#field(0,0,'fXML11Components', 'ArrayList'),
  \ javaapi#field(0,0,'fCommonComponents', 'ArrayList'),
  \ javaapi#field(0,0,'fDocumentHandler', 'XMLDocumentHandler'),
  \ javaapi#field(0,0,'fDTDHandler', 'XMLDTDHandler'),
  \ javaapi#field(0,0,'fDTDContentModelHandler', 'XMLDTDContentModelHandler'),
  \ javaapi#field(0,0,'fLastComponent', 'XMLDocumentSource'),
  \ javaapi#field(0,0,'fParseInProgress', 'boolean'),
  \ javaapi#field(0,0,'fConfigUpdated', 'boolean'),
  \ javaapi#field(0,0,'fDatatypeValidatorFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fNamespaceScanner', 'XMLNSDocumentScannerImpl'),
  \ javaapi#field(0,0,'fNonNSScanner', 'XMLDocumentScannerImpl'),
  \ javaapi#field(0,0,'fDTDScanner', 'XMLDTDScanner'),
  \ javaapi#field(0,0,'fXML11DatatypeFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fXML11NSDocScanner', 'XML11NSDocumentScannerImpl'),
  \ javaapi#field(0,0,'fXML11DocScanner', 'XML11DocumentScannerImpl'),
  \ javaapi#field(0,0,'fXML11DTDScanner', 'XML11DTDScannerImpl'),
  \ javaapi#field(0,0,'fGrammarPool', 'XMLGrammarPool'),
  \ javaapi#field(0,0,'fErrorReporter', 'XMLErrorReporter'),
  \ javaapi#field(0,0,'fEntityManager', 'XMLEntityManager'),
  \ javaapi#field(0,0,'fCurrentScanner', 'XMLDocumentScanner'),
  \ javaapi#field(0,0,'fCurrentDVFactory', 'DTDDVFactory'),
  \ javaapi#field(0,0,'fCurrentDTDScanner', 'XMLDTDScanner'),
  \ javaapi#method(0,1,'XML11NonValidatingConfiguration(', ')', ''),
  \ javaapi#method(0,1,'XML11NonValidatingConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'XML11NonValidatingConfiguration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'XML11NonValidatingConfiguration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,1,'setInputSource(', 'XMLInputSource) throws XMLConfigurationException, IOException', 'void'),
  \ javaapi#method(0,1,'setLocale(', 'Locale) throws XNIException', 'void'),
  \ javaapi#method(0,1,'setDocumentHandler(', 'XMLDocumentHandler)', 'void'),
  \ javaapi#method(0,1,'getDocumentHandler(', ')', 'XMLDocumentHandler'),
  \ javaapi#method(0,1,'setDTDHandler(', 'XMLDTDHandler)', 'void'),
  \ javaapi#method(0,1,'getDTDHandler(', ')', 'XMLDTDHandler'),
  \ javaapi#method(0,1,'setDTDContentModelHandler(', 'XMLDTDContentModelHandler)', 'void'),
  \ javaapi#method(0,1,'getDTDContentModelHandler(', ')', 'XMLDTDContentModelHandler'),
  \ javaapi#method(0,1,'setEntityResolver(', 'XMLEntityResolver)', 'void'),
  \ javaapi#method(0,1,'getEntityResolver(', ')', 'XMLEntityResolver'),
  \ javaapi#method(0,1,'setErrorHandler(', 'XMLErrorHandler)', 'void'),
  \ javaapi#method(0,1,'getErrorHandler(', ')', 'XMLErrorHandler'),
  \ javaapi#method(0,1,'cleanup(', ')', 'void'),
  \ javaapi#method(0,1,'parse(', 'XMLInputSource) throws XNIException, IOException', 'void'),
  \ javaapi#method(0,1,'parse(', 'boolean) throws XNIException, IOException', 'boolean'),
  \ javaapi#method(0,1,'getFeatureState(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'getLocale(', ')', 'Locale'),
  \ javaapi#method(0,0,'reset(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'resetCommon(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'resetXML11(', ') throws XNIException', 'void'),
  \ javaapi#method(0,0,'configureXML11Pipeline(', ')', 'void'),
  \ javaapi#method(0,0,'configurePipeline(', ')', 'void'),
  \ javaapi#method(0,0,'checkFeature(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,0,'checkProperty(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ javaapi#method(0,0,'addComponent(', 'XMLComponent)', 'void'),
  \ javaapi#method(0,0,'addCommonComponent(', 'XMLComponent)', 'void'),
  \ javaapi#method(0,0,'addXML11Component(', 'XMLComponent)', 'void'),
  \ javaapi#method(0,0,'addRecognizedParamsAndSetDefaults(', 'XMLComponent)', 'void'),
  \ ])

call javaapi#class('XMLDocumentParser', 'AbstractXMLDocumentParser', [
  \ javaapi#method(0,1,'XMLDocumentParser(', ')', ''),
  \ javaapi#method(0,1,'XMLDocumentParser(', 'XMLParserConfiguration)', ''),
  \ javaapi#method(0,1,'XMLDocumentParser(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'XMLDocumentParser(', 'SymbolTable, XMLGrammarPool)', ''),
  \ ])

call javaapi#class('XMLGrammarCachingConfiguration', 'XIncludeAwareParserConfiguration', [
  \ javaapi#field(1,1,'BIG_PRIME', 'int'),
  \ javaapi#field(1,0,'fStaticSymbolTable', 'SynchronizedSymbolTable'),
  \ javaapi#field(1,0,'fStaticGrammarPool', 'XMLGrammarPoolImpl'),
  \ javaapi#field(1,0,'SCHEMA_FULL_CHECKING', 'String'),
  \ javaapi#field(0,0,'fSchemaLoader', 'XMLSchemaLoader'),
  \ javaapi#field(0,0,'fDTDLoader', 'XMLDTDLoader'),
  \ javaapi#method(0,1,'XMLGrammarCachingConfiguration(', ')', ''),
  \ javaapi#method(0,1,'XMLGrammarCachingConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'XMLGrammarCachingConfiguration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'XMLGrammarCachingConfiguration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,1,'lockGrammarPool(', ')', 'void'),
  \ javaapi#method(0,1,'clearGrammarPool(', ')', 'void'),
  \ javaapi#method(0,1,'unlockGrammarPool(', ')', 'void'),
  \ javaapi#method(0,1,'parseGrammar(', 'String, String) throws XNIException, IOException', 'Grammar'),
  \ javaapi#method(0,1,'parseGrammar(', 'String, XMLInputSource) throws XNIException, IOException', 'Grammar'),
  \ ])

call javaapi#class('XMLGrammarParser', 'XMLParser', [
  \ javaapi#field(0,0,'fDatatypeValidatorFactory', 'DTDDVFactory'),
  \ javaapi#method(0,0,'XMLGrammarParser(', 'SymbolTable)', ''),
  \ ])

call javaapi#class('XMLGrammarPreparser', '', [
  \ javaapi#field(1,0,'SYMBOL_TABLE', 'String'),
  \ javaapi#field(1,0,'ERROR_REPORTER', 'String'),
  \ javaapi#field(1,0,'ERROR_HANDLER', 'String'),
  \ javaapi#field(1,0,'ENTITY_RESOLVER', 'String'),
  \ javaapi#field(1,0,'GRAMMAR_POOL', 'String'),
  \ javaapi#field(0,0,'fSymbolTable', 'SymbolTable'),
  \ javaapi#field(0,0,'fErrorReporter', 'XMLErrorReporter'),
  \ javaapi#field(0,0,'fEntityResolver', 'XMLEntityResolver'),
  \ javaapi#field(0,0,'fGrammarPool', 'XMLGrammarPool'),
  \ javaapi#field(0,0,'fLocale', 'Locale'),
  \ javaapi#method(0,1,'XMLGrammarPreparser(', ')', ''),
  \ javaapi#method(0,1,'XMLGrammarPreparser(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'registerPreparser(', 'String, XMLGrammarLoader)', 'boolean'),
  \ javaapi#method(0,1,'preparseGrammar(', 'String, XMLInputSource) throws XNIException, IOException', 'Grammar'),
  \ javaapi#method(0,1,'setLocale(', 'Locale)', 'void'),
  \ javaapi#method(0,1,'getLocale(', ')', 'Locale'),
  \ javaapi#method(0,1,'setErrorHandler(', 'XMLErrorHandler)', 'void'),
  \ javaapi#method(0,1,'getErrorHandler(', ')', 'XMLErrorHandler'),
  \ javaapi#method(0,1,'setEntityResolver(', 'XMLEntityResolver)', 'void'),
  \ javaapi#method(0,1,'getEntityResolver(', ')', 'XMLEntityResolver'),
  \ javaapi#method(0,1,'setGrammarPool(', 'XMLGrammarPool)', 'void'),
  \ javaapi#method(0,1,'getGrammarPool(', ')', 'XMLGrammarPool'),
  \ javaapi#method(0,1,'getLoader(', 'String)', 'XMLGrammarLoader'),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean)', 'void'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object)', 'void'),
  \ javaapi#method(0,1,'getFeature(', 'String, String)', 'boolean'),
  \ javaapi#method(0,1,'getProperty(', 'String, String)', 'Object'),
  \ ])

call javaapi#class('XMLParser', '', [
  \ javaapi#field(1,0,'ENTITY_RESOLVER', 'String'),
  \ javaapi#field(1,0,'ERROR_HANDLER', 'String'),
  \ javaapi#field(0,0,'fConfiguration', 'XMLParserConfiguration'),
  \ javaapi#method(0,1,'getFeature(', 'String) throws SAXNotSupportedException, SAXNotRecognizedException', 'boolean'),
  \ javaapi#method(0,0,'XMLParser(', 'XMLParserConfiguration)', ''),
  \ javaapi#method(0,1,'parse(', 'XMLInputSource) throws XNIException, IOException', 'void'),
  \ javaapi#method(0,0,'reset(', ') throws XNIException', 'void'),
  \ ])

call javaapi#class('XPointerParserConfiguration', 'XML11Configuration', [
  \ javaapi#field(1,0,'ALLOW_UE_AND_NOTATION_EVENTS', 'String'),
  \ javaapi#field(1,0,'XINCLUDE_FIXUP_BASE_URIS', 'String'),
  \ javaapi#field(1,0,'XINCLUDE_FIXUP_LANGUAGE', 'String'),
  \ javaapi#field(1,0,'XPOINTER_HANDLER', 'String'),
  \ javaapi#field(1,0,'XINCLUDE_HANDLER', 'String'),
  \ javaapi#field(1,0,'NAMESPACE_CONTEXT', 'String'),
  \ javaapi#method(0,1,'XPointerParserConfiguration(', ')', ''),
  \ javaapi#method(0,1,'XPointerParserConfiguration(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'XPointerParserConfiguration(', 'SymbolTable, XMLGrammarPool)', ''),
  \ javaapi#method(0,1,'XPointerParserConfiguration(', 'SymbolTable, XMLGrammarPool, XMLComponentManager)', ''),
  \ javaapi#method(0,0,'configurePipeline(', ')', 'void'),
  \ javaapi#method(0,0,'configureXML11Pipeline(', ')', 'void'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws XMLConfigurationException', 'void'),
  \ ])

