call javaapi#namespace('com.sun.org.apache.xml.internal.resolver')

call javaapi#class('Catalog', '', [
  \ javaapi#field(1,1,'BASE', 'int'),
  \ javaapi#field(1,1,'CATALOG', 'int'),
  \ javaapi#field(1,1,'DOCUMENT', 'int'),
  \ javaapi#field(1,1,'OVERRIDE', 'int'),
  \ javaapi#field(1,1,'SGMLDECL', 'int'),
  \ javaapi#field(1,1,'DELEGATE_PUBLIC', 'int'),
  \ javaapi#field(1,1,'DELEGATE_SYSTEM', 'int'),
  \ javaapi#field(1,1,'DELEGATE_URI', 'int'),
  \ javaapi#field(1,1,'DOCTYPE', 'int'),
  \ javaapi#field(1,1,'DTDDECL', 'int'),
  \ javaapi#field(1,1,'ENTITY', 'int'),
  \ javaapi#field(1,1,'LINKTYPE', 'int'),
  \ javaapi#field(1,1,'NOTATION', 'int'),
  \ javaapi#field(1,1,'PUBLIC', 'int'),
  \ javaapi#field(1,1,'SYSTEM', 'int'),
  \ javaapi#field(1,1,'URI', 'int'),
  \ javaapi#field(1,1,'REWRITE_SYSTEM', 'int'),
  \ javaapi#field(1,1,'REWRITE_URI', 'int'),
  \ javaapi#field(1,1,'SYSTEM_SUFFIX', 'int'),
  \ javaapi#field(1,1,'URI_SUFFIX', 'int'),
  \ javaapi#field(0,0,'base', 'URL'),
  \ javaapi#field(0,0,'catalogCwd', 'URL'),
  \ javaapi#field(0,0,'catalogEntries', 'Vector'),
  \ javaapi#field(0,0,'default_override', 'boolean'),
  \ javaapi#field(0,0,'catalogManager', 'CatalogManager'),
  \ javaapi#field(0,0,'catalogFiles', 'Vector'),
  \ javaapi#field(0,0,'localCatalogFiles', 'Vector'),
  \ javaapi#field(0,0,'catalogs', 'Vector'),
  \ javaapi#field(0,0,'localDelegate', 'Vector'),
  \ javaapi#field(0,0,'readerMap', 'Hashtable'),
  \ javaapi#field(0,0,'readerArr', 'Vector'),
  \ javaapi#method(0,1,'Catalog(', ')', ''),
  \ javaapi#method(0,1,'Catalog(', 'CatalogManager)', ''),
  \ javaapi#method(0,1,'getCatalogManager(', ')', 'CatalogManager'),
  \ javaapi#method(0,1,'setCatalogManager(', 'CatalogManager)', 'void'),
  \ javaapi#method(0,1,'setupReaders(', ')', 'void'),
  \ javaapi#method(0,1,'addReader(', 'String, CatalogReader)', 'void'),
  \ javaapi#method(0,0,'copyReaders(', 'Catalog)', 'void'),
  \ javaapi#method(0,0,'newCatalog(', ')', 'Catalog'),
  \ javaapi#method(0,1,'getCurrentBase(', ')', 'String'),
  \ javaapi#method(0,1,'getDefaultOverride(', ')', 'String'),
  \ javaapi#method(0,1,'loadSystemCatalogs(', ') throws MalformedURLException, IOException', 'void'),
  \ javaapi#method(0,1,'parseCatalog(', 'String) throws MalformedURLException, IOException', 'void'),
  \ javaapi#method(0,1,'parseCatalog(', 'String, InputStream) throws IOException, CatalogException', 'void'),
  \ javaapi#method(0,1,'parseCatalog(', 'URL) throws IOException', 'void'),
  \ javaapi#method(0,0,'parsePendingCatalogs(', ') throws MalformedURLException, IOException', 'void'),
  \ javaapi#method(0,0,'parseCatalogFile(', 'String) throws MalformedURLException, IOException, CatalogException', 'void'),
  \ javaapi#method(0,1,'addEntry(', 'CatalogEntry)', 'void'),
  \ javaapi#method(0,1,'unknownEntry(', 'Vector)', 'void'),
  \ javaapi#method(0,1,'parseAllCatalogs(', ') throws MalformedURLException, IOException', 'void'),
  \ javaapi#method(0,1,'resolveDoctype(', 'String, String, String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,1,'resolveDocument(', ') throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,1,'resolveEntity(', 'String, String, String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,1,'resolveNotation(', 'String, String, String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,1,'resolvePublic(', 'String, String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,0,'resolveLocalPublic(', 'int, String, String, String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,1,'resolveSystem(', 'String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,0,'resolveLocalSystem(', 'String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,1,'resolveURI(', 'String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,0,'resolveLocalURI(', 'String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,0,'resolveSubordinateCatalogs(', 'int, String, String, String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,0,'fixSlashes(', 'String)', 'String'),
  \ javaapi#method(0,0,'makeAbsolute(', 'String)', 'String'),
  \ javaapi#method(0,0,'normalizeURI(', 'String)', 'String'),
  \ javaapi#method(0,0,'encodedByte(', 'int)', 'String'),
  \ javaapi#method(0,0,'addDelegate(', 'CatalogEntry)', 'void'),
  \ ])

call javaapi#class('CatalogEntry', '', [
  \ javaapi#field(1,0,'nextEntry', 'int'),
  \ javaapi#field(1,0,'entryTypes', 'Hashtable'),
  \ javaapi#field(1,0,'entryArgs', 'Vector'),
  \ javaapi#field(0,0,'entryType', 'int'),
  \ javaapi#field(0,0,'args', 'Vector'),
  \ javaapi#method(1,1,'addEntryType(', 'String, int)', 'int'),
  \ javaapi#method(1,1,'getEntryType(', 'String) throws CatalogException', 'int'),
  \ javaapi#method(1,1,'getEntryArgCount(', 'String) throws CatalogException', 'int'),
  \ javaapi#method(1,1,'getEntryArgCount(', 'int) throws CatalogException', 'int'),
  \ javaapi#method(0,1,'CatalogEntry(', ')', ''),
  \ javaapi#method(0,1,'CatalogEntry(', 'String, Vector) throws CatalogException', ''),
  \ javaapi#method(0,1,'CatalogEntry(', 'int, Vector) throws CatalogException', ''),
  \ javaapi#method(0,1,'getEntryType(', ')', 'int'),
  \ javaapi#method(0,1,'getEntryArg(', 'int)', 'String'),
  \ javaapi#method(0,1,'setEntryArg(', 'int, String) throws ArrayIndexOutOfBoundsException', 'void'),
  \ ])

call javaapi#class('CatalogException', 'Exception', [
  \ javaapi#field(1,1,'WRAPPER', 'int'),
  \ javaapi#field(1,1,'INVALID_ENTRY', 'int'),
  \ javaapi#field(1,1,'INVALID_ENTRY_TYPE', 'int'),
  \ javaapi#field(1,1,'NO_XML_PARSER', 'int'),
  \ javaapi#field(1,1,'UNKNOWN_FORMAT', 'int'),
  \ javaapi#field(1,1,'UNPARSEABLE', 'int'),
  \ javaapi#field(1,1,'PARSE_FAILED', 'int'),
  \ javaapi#field(1,1,'UNENDED_COMMENT', 'int'),
  \ javaapi#method(0,1,'CatalogException(', 'int, String)', ''),
  \ javaapi#method(0,1,'CatalogException(', 'int)', ''),
  \ javaapi#method(0,1,'CatalogException(', 'Exception)', ''),
  \ javaapi#method(0,1,'CatalogException(', 'String, Exception)', ''),
  \ javaapi#method(0,1,'getMessage(', ')', 'String'),
  \ javaapi#method(0,1,'getException(', ')', 'Exception'),
  \ javaapi#method(0,1,'getExceptionType(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('CatalogManager', '', [
  \ javaapi#field(0,1,'debug', 'Debug'),
  \ javaapi#method(0,1,'CatalogManager(', ')', ''),
  \ javaapi#method(0,1,'CatalogManager(', 'String)', ''),
  \ javaapi#method(0,1,'setBootstrapResolver(', 'BootstrapResolver)', 'void'),
  \ javaapi#method(0,1,'getBootstrapResolver(', ')', 'BootstrapResolver'),
  \ javaapi#method(1,1,'getStaticManager(', ')', 'CatalogManager'),
  \ javaapi#method(0,1,'getIgnoreMissingProperties(', ')', 'boolean'),
  \ javaapi#method(0,1,'setIgnoreMissingProperties(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'ignoreMissingProperties(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getVerbosity(', ')', 'int'),
  \ javaapi#method(0,1,'setVerbosity(', 'int)', 'void'),
  \ javaapi#method(0,1,'verbosity(', ')', 'int'),
  \ javaapi#method(0,1,'getRelativeCatalogs(', ')', 'boolean'),
  \ javaapi#method(0,1,'setRelativeCatalogs(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'relativeCatalogs(', ')', 'boolean'),
  \ javaapi#method(0,1,'getCatalogFiles(', ')', 'Vector'),
  \ javaapi#method(0,1,'setCatalogFiles(', 'String)', 'void'),
  \ javaapi#method(0,1,'catalogFiles(', ')', 'Vector'),
  \ javaapi#method(0,1,'getPreferPublic(', ')', 'boolean'),
  \ javaapi#method(0,1,'setPreferPublic(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'preferPublic(', ')', 'boolean'),
  \ javaapi#method(0,1,'getUseStaticCatalog(', ')', 'boolean'),
  \ javaapi#method(0,1,'setUseStaticCatalog(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'staticCatalog(', ')', 'boolean'),
  \ javaapi#method(0,1,'getPrivateCatalog(', ')', 'Catalog'),
  \ javaapi#method(0,1,'getCatalog(', ')', 'Catalog'),
  \ javaapi#method(0,1,'queryAllowOasisXMLCatalogPI(', ')', 'boolean'),
  \ javaapi#method(0,1,'getAllowOasisXMLCatalogPI(', ')', 'boolean'),
  \ javaapi#method(0,1,'setAllowOasisXMLCatalogPI(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'allowOasisXMLCatalogPI(', ')', 'boolean'),
  \ javaapi#method(0,1,'queryCatalogClassName(', ')', 'String'),
  \ javaapi#method(0,1,'getCatalogClassName(', ')', 'String'),
  \ javaapi#method(0,1,'setCatalogClassName(', 'String)', 'void'),
  \ javaapi#method(0,1,'catalogClassName(', ')', 'String'),
  \ ])

call javaapi#class('Resolver', 'Catalog', [
  \ javaapi#field(1,1,'URISUFFIX', 'int'),
  \ javaapi#field(1,1,'SYSTEMSUFFIX', 'int'),
  \ javaapi#field(1,1,'RESOLVER', 'int'),
  \ javaapi#field(1,1,'SYSTEMREVERSE', 'int'),
  \ javaapi#method(0,1,'Resolver(', ')', ''),
  \ javaapi#method(0,1,'setupReaders(', ')', 'void'),
  \ javaapi#method(0,1,'addEntry(', 'CatalogEntry)', 'void'),
  \ javaapi#method(0,1,'resolveURI(', 'String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,1,'resolveSystem(', 'String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,1,'resolvePublic(', 'String, String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,0,'resolveExternalSystem(', 'String, String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,0,'resolveExternalPublic(', 'String, String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,0,'queryResolver(', 'String, String, String, String)', 'Resolver'),
  \ javaapi#method(0,1,'resolveAllSystemReverse(', 'String) throws MalformedURLException, IOException', 'Vector'),
  \ javaapi#method(0,1,'resolveSystemReverse(', 'String) throws MalformedURLException, IOException', 'String'),
  \ javaapi#method(0,1,'resolveAllSystem(', 'String) throws MalformedURLException, IOException', 'Vector'),
  \ ])

