call javaapi#namespace('com.sun.xml.internal.stream.writers')

call javaapi#class('UTF8OutputStreamWriter', 'Writer', [
  \ javaapi#method(0,1,'UTF8OutputStreamWriter(', 'OutputStream)', ''),
  \ javaapi#method(0,1,'getEncoding(', ')', 'String'),
  \ javaapi#method(0,1,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,1,'write(', 'char[]) throws IOException', 'void'),
  \ javaapi#method(0,1,'write(', 'char[], int, int) throws IOException', 'void'),
  \ javaapi#method(0,1,'write(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'write(', 'String, int, int) throws IOException', 'void'),
  \ javaapi#method(0,1,'flush(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'close(', ') throws IOException', 'void'),
  \ ])

call javaapi#class('WriterUtility', '', [
  \ javaapi#field(1,1,'START_COMMENT', 'String'),
  \ javaapi#field(1,1,'END_COMMENT', 'String'),
  \ javaapi#field(1,1,'DEFAULT_ENCODING', 'String'),
  \ javaapi#field(1,1,'DEFAULT_XMLDECL', 'String'),
  \ javaapi#field(1,1,'DEFAULT_XML_VERSION', 'String'),
  \ javaapi#field(1,1,'CLOSE_START_TAG', 'char'),
  \ javaapi#field(1,1,'OPEN_START_TAG', 'char'),
  \ javaapi#field(1,1,'OPEN_END_TAG', 'String'),
  \ javaapi#field(1,1,'CLOSE_END_TAG', 'char'),
  \ javaapi#field(1,1,'START_CDATA', 'String'),
  \ javaapi#field(1,1,'END_CDATA', 'String'),
  \ javaapi#field(1,1,'CLOSE_EMPTY_ELEMENT', 'String'),
  \ javaapi#field(1,1,'SPACE', 'String'),
  \ javaapi#field(1,1,'UTF_8', 'String'),
  \ javaapi#method(0,1,'WriterUtility(', ')', ''),
  \ javaapi#method(0,1,'WriterUtility(', 'Writer)', ''),
  \ javaapi#method(0,1,'setWriter(', 'Writer)', 'void'),
  \ javaapi#method(0,1,'setEscapeCharacters(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getEscapeCharacters(', ')', 'boolean'),
  \ javaapi#method(0,1,'writeXMLContent(', 'char[], int, int) throws IOException', 'void'),
  \ javaapi#method(0,1,'writeXMLContent(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'writeXMLAttributeValue(', 'String) throws IOException', 'void'),
  \ ])

call javaapi#class('XMLDOMWriterImpl', 'XMLStreamWriter', [
  \ javaapi#method(0,1,'XMLDOMWriterImpl(', 'DOMResult)', ''),
  \ javaapi#method(0,1,'close(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'flush(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'getNamespaceContext(', ')', 'NamespaceContext'),
  \ javaapi#method(0,1,'getPrefix(', 'String) throws XMLStreamException', 'String'),
  \ javaapi#method(0,1,'getProperty(', 'String) throws IllegalArgumentException', 'Object'),
  \ javaapi#method(0,1,'setDefaultNamespace(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'setNamespaceContext(', 'NamespaceContext) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'setPrefix(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeAttribute(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeAttribute(', 'String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeAttribute(', 'String, String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeCData(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeCharacters(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeCharacters(', 'char[], int, int) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeComment(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeDTD(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeDefaultNamespace(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEmptyElement(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEmptyElement(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEmptyElement(', 'String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEndDocument(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEndElement(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEntityRef(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeNamespace(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeProcessingInstruction(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeProcessingInstruction(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartDocument(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartDocument(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartDocument(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartElement(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartElement(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartElement(', 'String, String, String) throws XMLStreamException', 'void'),
  \ ])

call javaapi#class('XMLEventWriterImpl', 'XMLEventWriter', [
  \ javaapi#method(0,1,'XMLEventWriterImpl(', 'XMLStreamWriter)', ''),
  \ javaapi#method(0,1,'add(', 'XMLEventReader) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'add(', 'XMLEvent) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'close(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'flush(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'getNamespaceContext(', ')', 'NamespaceContext'),
  \ javaapi#method(0,1,'getPrefix(', 'String) throws XMLStreamException', 'String'),
  \ javaapi#method(0,1,'setDefaultNamespace(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'setNamespaceContext(', 'NamespaceContext) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'setPrefix(', 'String, String) throws XMLStreamException', 'void'),
  \ ])

call javaapi#class('XMLOutputSource', '', [
  \ javaapi#method(0,1,'XMLOutputSource(', ')', ''),
  \ ])

call javaapi#class('XMLStreamWriterImpl', 'AbstractMap', [
  \ javaapi#field(1,1,'START_COMMENT', 'String'),
  \ javaapi#field(1,1,'END_COMMENT', 'String'),
  \ javaapi#field(1,1,'DEFAULT_ENCODING', 'String'),
  \ javaapi#field(1,1,'DEFAULT_XMLDECL', 'String'),
  \ javaapi#field(1,1,'DEFAULT_XML_VERSION', 'String'),
  \ javaapi#field(1,1,'CLOSE_START_TAG', 'char'),
  \ javaapi#field(1,1,'OPEN_START_TAG', 'char'),
  \ javaapi#field(1,1,'OPEN_END_TAG', 'String'),
  \ javaapi#field(1,1,'CLOSE_END_TAG', 'char'),
  \ javaapi#field(1,1,'START_CDATA', 'String'),
  \ javaapi#field(1,1,'END_CDATA', 'String'),
  \ javaapi#field(1,1,'CLOSE_EMPTY_ELEMENT', 'String'),
  \ javaapi#field(1,1,'SPACE', 'String'),
  \ javaapi#field(1,1,'UTF_8', 'String'),
  \ javaapi#field(1,1,'OUTPUTSTREAM_PROPERTY', 'String'),
  \ javaapi#method(0,1,'XMLStreamWriterImpl(', 'OutputStream, PropertyManager) throws IOException', ''),
  \ javaapi#method(0,1,'XMLStreamWriterImpl(', 'OutputStream, String, PropertyManager) throws IOException', ''),
  \ javaapi#method(0,1,'XMLStreamWriterImpl(', 'Writer, PropertyManager) throws IOException', ''),
  \ javaapi#method(0,1,'XMLStreamWriterImpl(', 'StreamResult, String, PropertyManager) throws IOException', ''),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'setOutput(', 'StreamResult, String) throws IOException', 'void'),
  \ javaapi#method(0,1,'canReuse(', ')', 'boolean'),
  \ javaapi#method(0,1,'setEscapeCharacters(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getEscapeCharacters(', ')', 'boolean'),
  \ javaapi#method(0,1,'close(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'flush(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'getNamespaceContext(', ')', 'NamespaceContext'),
  \ javaapi#method(0,1,'getPrefix(', 'String) throws XMLStreamException', 'String'),
  \ javaapi#method(0,1,'getProperty(', 'String) throws IllegalArgumentException', 'Object'),
  \ javaapi#method(0,1,'setDefaultNamespace(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'setNamespaceContext(', 'NamespaceContext) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'setPrefix(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeAttribute(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeAttribute(', 'String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeAttribute(', 'String, String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeCData(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeCharacters(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeCharacters(', 'char[], int, int) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeComment(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeDTD(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeDefaultNamespace(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEmptyElement(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEmptyElement(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEmptyElement(', 'String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEndDocument(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEndElement(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeEntityRef(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeNamespace(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeProcessingInstruction(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeProcessingInstruction(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartDocument(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartDocument(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartDocument(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartElement(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartElement(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,1,'writeStartElement(', 'String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,0,'repair(', ')', 'void'),
  \ javaapi#method(0,1,'size(', ')', 'int'),
  \ javaapi#method(0,1,'isEmpty(', ')', 'boolean'),
  \ javaapi#method(0,1,'containsKey(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'get(', 'Object)', 'Object'),
  \ javaapi#method(0,1,'entrySet(', ')', 'Set'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ ])

call javaapi#class('XMLWriter', 'Writer', [
  \ javaapi#method(0,1,'XMLWriter(', 'Writer)', ''),
  \ javaapi#method(0,1,'XMLWriter(', 'Writer, int)', ''),
  \ javaapi#method(0,1,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,1,'write(', 'char[]) throws IOException', 'void'),
  \ javaapi#method(0,1,'write(', 'char[], int, int) throws IOException', 'void'),
  \ javaapi#method(0,1,'write(', 'String, int, int) throws IOException', 'void'),
  \ javaapi#method(0,1,'write(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'flush(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'setWriter(', 'Writer)', 'void'),
  \ javaapi#method(0,1,'setWriter(', 'Writer, int)', 'void'),
  \ javaapi#method(0,0,'getWriter(', ')', 'Writer'),
  \ ])

