call javaapi#namespace('com.sun.jmx.remote.protocol.iiop')

call javaapi#class('ClientProvider', 'JMXConnectorProvider', [
  \ javaapi#method(0,1,'ClientProvider(', ')', ''),
  \ javaapi#method(0,1,'newJMXConnector(', 'JMXServiceURL, Map<String, ?>) throws IOException', 'JMXConnector'),
  \ ])

call javaapi#class('IIOPProxyImpl', 'IIOPProxy', [
  \ javaapi#method(0,1,'IIOPProxyImpl(', ')', ''),
  \ javaapi#method(0,1,'isStub(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'getDelegate(', 'Object)', 'Object'),
  \ javaapi#method(0,1,'setDelegate(', 'Object, Object)', 'void'),
  \ javaapi#method(0,1,'getOrb(', 'Object)', 'Object'),
  \ javaapi#method(0,1,'connect(', 'Object, Object) throws RemoteException', 'void'),
  \ javaapi#method(0,1,'isOrb(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'createOrb(', 'String[], Properties)', 'Object'),
  \ javaapi#method(0,1,'stringToObject(', 'Object, String)', 'Object'),
  \ javaapi#method(0,1,'objectToString(', 'Object, Object)', 'String'),
  \ javaapi#method(0,1,'narrow(', 'Object, Class<T>)', 'T'),
  \ javaapi#method(0,1,'exportObject(', 'Remote) throws RemoteException', 'void'),
  \ javaapi#method(0,1,'unexportObject(', 'Remote) throws NoSuchObjectException', 'void'),
  \ javaapi#method(0,1,'toStub(', 'Remote) throws NoSuchObjectException', 'Remote'),
  \ ])

call javaapi#class('ProxyInputStream', 'InputStream', [
  \ javaapi#field(0,0,'in', 'InputStream'),
  \ javaapi#method(0,1,'ProxyInputStream(', 'InputStream)', ''),
  \ javaapi#method(0,1,'read_boolean(', ')', 'boolean'),
  \ javaapi#method(0,1,'read_char(', ')', 'char'),
  \ javaapi#method(0,1,'read_wchar(', ')', 'char'),
  \ javaapi#method(0,1,'read_octet(', ')', 'byte'),
  \ javaapi#method(0,1,'read_short(', ')', 'short'),
  \ javaapi#method(0,1,'read_ushort(', ')', 'short'),
  \ javaapi#method(0,1,'read_long(', ')', 'int'),
  \ javaapi#method(0,1,'read_ulong(', ')', 'int'),
  \ javaapi#method(0,1,'read_longlong(', ')', 'long'),
  \ javaapi#method(0,1,'read_ulonglong(', ')', 'long'),
  \ javaapi#method(0,1,'read_float(', ')', 'float'),
  \ javaapi#method(0,1,'read_double(', ')', 'double'),
  \ javaapi#method(0,1,'read_string(', ')', 'String'),
  \ javaapi#method(0,1,'read_wstring(', ')', 'String'),
  \ javaapi#method(0,1,'read_boolean_array(', 'boolean[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_char_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_wchar_array(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_octet_array(', 'byte[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_short_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ushort_array(', 'short[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_long_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulong_array(', 'int[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_longlong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_ulonglong_array(', 'long[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_float_array(', 'float[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_double_array(', 'double[], int, int)', 'void'),
  \ javaapi#method(0,1,'read_Object(', ')', 'Object'),
  \ javaapi#method(0,1,'read_TypeCode(', ')', 'TypeCode'),
  \ javaapi#method(0,1,'read_any(', ')', 'Any'),
  \ javaapi#method(0,1,'read_Principal(', ')', 'Principal'),
  \ javaapi#method(0,1,'read(', ') throws IOException', 'int'),
  \ javaapi#method(0,1,'read_fixed(', ')', 'BigDecimal'),
  \ javaapi#method(0,1,'read_Context(', ')', 'Context'),
  \ javaapi#method(0,1,'read_Object(', 'Class)', 'Object'),
  \ javaapi#method(0,1,'orb(', ')', 'ORB'),
  \ javaapi#method(0,1,'read_value(', ')', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'Class)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'BoxedValueHelper)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'String)', 'Serializable'),
  \ javaapi#method(0,1,'read_value(', 'Serializable)', 'Serializable'),
  \ javaapi#method(0,1,'read_abstract_interface(', ')', 'Object'),
  \ javaapi#method(0,1,'read_abstract_interface(', 'Class)', 'Object'),
  \ javaapi#method(0,0,'narrow(', ')', 'InputStream'),
  \ javaapi#method(0,1,'getProxiedInputStream(', ')', 'InputStream'),
  \ ])

call javaapi#class('ServerProvider', 'JMXConnectorServerProvider', [
  \ javaapi#method(0,1,'ServerProvider(', ')', ''),
  \ javaapi#method(0,1,'newJMXConnectorServer(', 'JMXServiceURL, Map<String, ?>, MBeanServer) throws IOException', 'JMXConnectorServer'),
  \ ])

