call javaapi#namespace('com.sun.rowset')

call javaapi#class('CachedRowSetImpl', 'BaseRowSet', [
  \ javaapi#field(0,0,'resBundle', 'JdbcRowSetResourceBundle'),
  \ javaapi#method(0,1,'CachedRowSetImpl(', ') throws SQLException', ''),
  \ javaapi#method(0,1,'CachedRowSetImpl(', 'Hashtable) throws SQLException', ''),
  \ javaapi#method(0,1,'setCommand(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'populate(', 'ResultSet) throws SQLException', 'void'),
  \ javaapi#method(0,1,'execute(', 'Connection) throws SQLException', 'void'),
  \ javaapi#method(0,1,'acceptChanges(', ') throws SyncProviderException', 'void'),
  \ javaapi#method(0,1,'acceptChanges(', 'Connection) throws SyncProviderException', 'void'),
  \ javaapi#method(0,1,'restoreOriginal(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'release(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'undoDelete(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'undoInsert(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'undoUpdate(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'createShared(', ') throws SQLException', 'RowSet'),
  \ javaapi#method(0,0,'clone(', ') throws CloneNotSupportedException', 'Object'),
  \ javaapi#method(0,1,'createCopy(', ') throws SQLException', 'CachedRowSet'),
  \ javaapi#method(0,1,'createCopySchema(', ') throws SQLException', 'CachedRowSet'),
  \ javaapi#method(0,1,'createCopyNoConstraints(', ') throws SQLException', 'CachedRowSet'),
  \ javaapi#method(0,1,'toCollection(', ') throws SQLException', 'Collection'),
  \ javaapi#method(0,1,'toCollection(', 'int) throws SQLException', 'Collection'),
  \ javaapi#method(0,1,'toCollection(', 'String) throws SQLException', 'Collection'),
  \ javaapi#method(0,1,'getSyncProvider(', ') throws SQLException', 'SyncProvider'),
  \ javaapi#method(0,1,'setSyncProvider(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'execute(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'next(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,0,'internalNext(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'close(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'wasNull(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,0,'getCurrentRow(', ')', 'BaseRow'),
  \ javaapi#method(0,0,'removeCurrentRow(', ')', 'void'),
  \ javaapi#method(0,1,'getString(', 'int) throws SQLException', 'String'),
  \ javaapi#method(0,1,'getBoolean(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'getByte(', 'int) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getShort(', 'int) throws SQLException', 'short'),
  \ javaapi#method(0,1,'getInt(', 'int) throws SQLException', 'int'),
  \ javaapi#method(0,1,'getLong(', 'int) throws SQLException', 'long'),
  \ javaapi#method(0,1,'getFloat(', 'int) throws SQLException', 'float'),
  \ javaapi#method(0,1,'getDouble(', 'int) throws SQLException', 'double'),
  \ javaapi#method(0,1,'getBigDecimal(', 'int, int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'getBytes(', 'int) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getDate(', 'int) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getTime(', 'int) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTimestamp(', 'int) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'getAsciiStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getUnicodeStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getBinaryStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getString(', 'String) throws SQLException', 'String'),
  \ javaapi#method(0,1,'getBoolean(', 'String) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'getByte(', 'String) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getShort(', 'String) throws SQLException', 'short'),
  \ javaapi#method(0,1,'getInt(', 'String) throws SQLException', 'int'),
  \ javaapi#method(0,1,'getLong(', 'String) throws SQLException', 'long'),
  \ javaapi#method(0,1,'getFloat(', 'String) throws SQLException', 'float'),
  \ javaapi#method(0,1,'getDouble(', 'String) throws SQLException', 'double'),
  \ javaapi#method(0,1,'getBigDecimal(', 'String, int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'getBytes(', 'String) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getDate(', 'String) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getTime(', 'String) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTimestamp(', 'String) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'getAsciiStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getUnicodeStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getBinaryStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getWarnings(', ')', 'SQLWarning'),
  \ javaapi#method(0,1,'clearWarnings(', ')', 'void'),
  \ javaapi#method(0,1,'getCursorName(', ') throws SQLException', 'String'),
  \ javaapi#method(0,1,'getMetaData(', ') throws SQLException', 'ResultSetMetaData'),
  \ javaapi#method(0,1,'getObject(', 'int) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'getObject(', 'String) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'findColumn(', 'String) throws SQLException', 'int'),
  \ javaapi#method(0,1,'getCharacterStream(', 'int) throws SQLException', 'Reader'),
  \ javaapi#method(0,1,'getCharacterStream(', 'String) throws SQLException', 'Reader'),
  \ javaapi#method(0,1,'getBigDecimal(', 'int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'getBigDecimal(', 'String) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'size(', ')', 'int'),
  \ javaapi#method(0,1,'isBeforeFirst(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'isAfterLast(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'isFirst(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'isLast(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'beforeFirst(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'afterLast(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'first(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,0,'internalFirst(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'last(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,0,'internalLast(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'getRow(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'absolute(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'relative(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'previous(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,0,'internalPrevious(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'rowUpdated(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'columnUpdated(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'columnUpdated(', 'String) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'rowInserted(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'rowDeleted(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'updateNull(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBoolean(', 'int, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateByte(', 'int, byte) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateShort(', 'int, short) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateInt(', 'int, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateLong(', 'int, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateFloat(', 'int, float) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDouble(', 'int, double) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBigDecimal(', 'int, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateString(', 'int, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBytes(', 'int, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDate(', 'int, Date) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTime(', 'int, Time) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTimestamp(', 'int, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'int, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'int, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'int, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'int, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'int, Object) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNull(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBoolean(', 'String, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateByte(', 'String, byte) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateShort(', 'String, short) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateInt(', 'String, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateLong(', 'String, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateFloat(', 'String, float) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDouble(', 'String, double) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBigDecimal(', 'String, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateString(', 'String, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBytes(', 'String, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDate(', 'String, Date) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTime(', 'String, Time) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTimestamp(', 'String, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'String, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'String, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'String, Object) throws SQLException', 'void'),
  \ javaapi#method(0,1,'insertRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'deleteRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'refreshRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'cancelRowUpdates(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'moveToInsertRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'moveToCurrentRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'getStatement(', ') throws SQLException', 'Statement'),
  \ javaapi#method(0,1,'getObject(', 'int, Map<String, Class<?>>) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'getRef(', 'int) throws SQLException', 'Ref'),
  \ javaapi#method(0,1,'getBlob(', 'int) throws SQLException', 'Blob'),
  \ javaapi#method(0,1,'getClob(', 'int) throws SQLException', 'Clob'),
  \ javaapi#method(0,1,'getArray(', 'int) throws SQLException', 'Array'),
  \ javaapi#method(0,1,'getObject(', 'String, Map<String, Class<?>>) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'getRef(', 'String) throws SQLException', 'Ref'),
  \ javaapi#method(0,1,'getBlob(', 'String) throws SQLException', 'Blob'),
  \ javaapi#method(0,1,'getClob(', 'String) throws SQLException', 'Clob'),
  \ javaapi#method(0,1,'getArray(', 'String) throws SQLException', 'Array'),
  \ javaapi#method(0,1,'getDate(', 'int, Calendar) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getDate(', 'String, Calendar) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getTime(', 'int, Calendar) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTime(', 'String, Calendar) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTimestamp(', 'int, Calendar) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'getTimestamp(', 'String, Calendar) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'getConnection(', ') throws SQLException', 'Connection'),
  \ javaapi#method(0,1,'setMetaData(', 'RowSetMetaData) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getOriginal(', ') throws SQLException', 'ResultSet'),
  \ javaapi#method(0,1,'getOriginalRow(', ') throws SQLException', 'ResultSet'),
  \ javaapi#method(0,1,'setOriginalRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'setOriginal(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'getTableName(', ') throws SQLException', 'String'),
  \ javaapi#method(0,1,'setTableName(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getKeyColumns(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'setKeyColumns(', 'int[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateRef(', 'int, Ref) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateRef(', 'String, Ref) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'int, Clob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'String, Clob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'int, Blob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'String, Blob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateArray(', 'int, Array) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateArray(', 'String, Array) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getURL(', 'int) throws SQLException', 'URL'),
  \ javaapi#method(0,1,'getURL(', 'String) throws SQLException', 'URL'),
  \ javaapi#method(0,1,'getRowSetWarnings(', ')', 'RowSetWarning'),
  \ javaapi#method(0,1,'commit(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'rollback(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'rollback(', 'Savepoint) throws SQLException', 'void'),
  \ javaapi#method(0,1,'unsetMatchColumn(', 'int[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'unsetMatchColumn(', 'String[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getMatchColumnNames(', ') throws SQLException', 'String'),
  \ javaapi#method(0,1,'getMatchColumnIndexes(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'setMatchColumn(', 'int[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setMatchColumn(', 'String[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setMatchColumn(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setMatchColumn(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'unsetMatchColumn(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'unsetMatchColumn(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'rowSetPopulated(', 'RowSetEvent, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'populate(', 'ResultSet, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'nextPage(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'setPageSize(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getPageSize(', ')', 'int'),
  \ javaapi#method(0,1,'previousPage(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'setRowInserted(', 'boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getSQLXML(', 'int) throws SQLException', 'SQLXML'),
  \ javaapi#method(0,1,'getSQLXML(', 'String) throws SQLException', 'SQLXML'),
  \ javaapi#method(0,1,'getRowId(', 'int) throws SQLException', 'RowId'),
  \ javaapi#method(0,1,'getRowId(', 'String) throws SQLException', 'RowId'),
  \ javaapi#method(0,1,'updateRowId(', 'int, RowId) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateRowId(', 'String, RowId) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getHoldability(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'isClosed(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'updateNString(', 'int, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNString(', 'String, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'int, NClob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'String, NClob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getNClob(', 'int) throws SQLException', 'NClob'),
  \ javaapi#method(0,1,'getNClob(', 'String) throws SQLException', 'NClob'),
  \ javaapi#method(0,1,'unwrap(', 'Class<T>) throws SQLException', 'T'),
  \ javaapi#method(0,1,'isWrapperFor(', 'Class<?>) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'setSQLXML(', 'int, SQLXML) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setSQLXML(', 'String, SQLXML) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setRowId(', 'int, RowId) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setRowId(', 'String, RowId) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNCharacterStream(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'String, NClob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getNCharacterStream(', 'int) throws SQLException', 'Reader'),
  \ javaapi#method(0,1,'getNCharacterStream(', 'String) throws SQLException', 'Reader'),
  \ javaapi#method(0,1,'updateSQLXML(', 'int, SQLXML) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateSQLXML(', 'String, SQLXML) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getNString(', 'int) throws SQLException', 'String'),
  \ javaapi#method(0,1,'getNString(', 'String) throws SQLException', 'String'),
  \ javaapi#method(0,1,'updateNCharacterStream(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNCharacterStream(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNCharacterStream(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNCharacterStream(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'int, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'String, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'int, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'int, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'int, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'String, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'String, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'int, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'int, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setURL(', 'int, URL) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'int, NClob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNString(', 'int, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNString(', 'String, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNCharacterStream(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNCharacterStream(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNCharacterStream(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setTimestamp(', 'String, Timestamp, Calendar) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setClob(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setClob(', 'String, Clob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setClob(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setDate(', 'String, Date) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setDate(', 'String, Date, Calendar) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setTime(', 'String, Time) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setTime(', 'String, Time, Calendar) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setClob(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setClob(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBlob(', 'int, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBlob(', 'int, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBlob(', 'String, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBlob(', 'String, Blob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBlob(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setObject(', 'String, Object, int, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setObject(', 'String, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setObject(', 'String, Object) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setAsciiStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBinaryStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setCharacterStream(', 'String, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setAsciiStream(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBinaryStream(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setCharacterStream(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBigDecimal(', 'String, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setString(', 'String, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBytes(', 'String, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setTimestamp(', 'String, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNull(', 'String, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNull(', 'String, int, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBoolean(', 'String, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setByte(', 'String, byte) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setShort(', 'String, short) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setInt(', 'String, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setLong(', 'String, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setFloat(', 'String, float) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setDouble(', 'String, double) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getObject(', 'int, Class<T>) throws SQLException', 'T'),
  \ javaapi#method(0,1,'getObject(', 'String, Class<T>) throws SQLException', 'T'),
  \ ])

call javaapi#class('FilteredRowSetImpl', 'WebRowSetImpl', [
  \ javaapi#method(0,1,'FilteredRowSetImpl(', ') throws SQLException', ''),
  \ javaapi#method(0,1,'FilteredRowSetImpl(', 'Hashtable) throws SQLException', ''),
  \ javaapi#method(0,1,'setFilter(', 'Predicate) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getFilter(', ')', 'Predicate'),
  \ javaapi#method(0,0,'internalNext(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,0,'internalPrevious(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,0,'internalFirst(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,0,'internalLast(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'relative(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'absolute(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'moveToInsertRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateInt(', 'int, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateInt(', 'String, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBoolean(', 'int, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBoolean(', 'String, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateByte(', 'int, byte) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateByte(', 'String, byte) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateShort(', 'int, short) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateShort(', 'String, short) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateLong(', 'int, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateLong(', 'String, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateFloat(', 'int, float) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateFloat(', 'String, float) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDouble(', 'int, double) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDouble(', 'String, double) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBigDecimal(', 'int, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBigDecimal(', 'String, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateString(', 'int, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateString(', 'String, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBytes(', 'int, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBytes(', 'String, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDate(', 'int, Date) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDate(', 'String, Date) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTime(', 'int, Time) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTime(', 'String, Time) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTimestamp(', 'int, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTimestamp(', 'String, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'int, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'int, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'String, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'int, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'int, Object) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'String, Object) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'int, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'String, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'insertRow(', ') throws SQLException', 'void'),
  \ ])

call javaapi#class('JdbcRowSetImpl', 'BaseRowSet', [
  \ javaapi#field(0,0,'resBundle', 'JdbcRowSetResourceBundle'),
  \ javaapi#method(0,1,'JdbcRowSetImpl(', ')', ''),
  \ javaapi#method(0,1,'JdbcRowSetImpl(', 'Connection) throws SQLException', ''),
  \ javaapi#method(0,1,'JdbcRowSetImpl(', 'String, String, String) throws SQLException', ''),
  \ javaapi#method(0,1,'JdbcRowSetImpl(', 'ResultSet) throws SQLException', ''),
  \ javaapi#method(0,0,'initMetaData(', 'RowSetMetaData, ResultSetMetaData) throws SQLException', 'void'),
  \ javaapi#method(0,0,'checkState(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'execute(', ') throws SQLException', 'void'),
  \ javaapi#method(0,0,'setProperties(', 'PreparedStatement) throws SQLException', 'void'),
  \ javaapi#method(0,0,'connect(', ') throws SQLException', 'Connection'),
  \ javaapi#method(0,0,'prepare(', ') throws SQLException', 'PreparedStatement'),
  \ javaapi#method(0,1,'next(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'close(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'wasNull(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'getString(', 'int) throws SQLException', 'String'),
  \ javaapi#method(0,1,'getBoolean(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'getByte(', 'int) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getShort(', 'int) throws SQLException', 'short'),
  \ javaapi#method(0,1,'getInt(', 'int) throws SQLException', 'int'),
  \ javaapi#method(0,1,'getLong(', 'int) throws SQLException', 'long'),
  \ javaapi#method(0,1,'getFloat(', 'int) throws SQLException', 'float'),
  \ javaapi#method(0,1,'getDouble(', 'int) throws SQLException', 'double'),
  \ javaapi#method(0,1,'getBigDecimal(', 'int, int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'getBytes(', 'int) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getDate(', 'int) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getTime(', 'int) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTimestamp(', 'int) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'getAsciiStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getUnicodeStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getBinaryStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getString(', 'String) throws SQLException', 'String'),
  \ javaapi#method(0,1,'getBoolean(', 'String) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'getByte(', 'String) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getShort(', 'String) throws SQLException', 'short'),
  \ javaapi#method(0,1,'getInt(', 'String) throws SQLException', 'int'),
  \ javaapi#method(0,1,'getLong(', 'String) throws SQLException', 'long'),
  \ javaapi#method(0,1,'getFloat(', 'String) throws SQLException', 'float'),
  \ javaapi#method(0,1,'getDouble(', 'String) throws SQLException', 'double'),
  \ javaapi#method(0,1,'getBigDecimal(', 'String, int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'getBytes(', 'String) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getDate(', 'String) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getTime(', 'String) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTimestamp(', 'String) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'getAsciiStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getUnicodeStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getBinaryStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getWarnings(', ') throws SQLException', 'SQLWarning'),
  \ javaapi#method(0,1,'clearWarnings(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'getCursorName(', ') throws SQLException', 'String'),
  \ javaapi#method(0,1,'getMetaData(', ') throws SQLException', 'ResultSetMetaData'),
  \ javaapi#method(0,1,'getObject(', 'int) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'getObject(', 'String) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'findColumn(', 'String) throws SQLException', 'int'),
  \ javaapi#method(0,1,'getCharacterStream(', 'int) throws SQLException', 'Reader'),
  \ javaapi#method(0,1,'getCharacterStream(', 'String) throws SQLException', 'Reader'),
  \ javaapi#method(0,1,'getBigDecimal(', 'int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'getBigDecimal(', 'String) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'isBeforeFirst(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'isAfterLast(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'isFirst(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'isLast(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'beforeFirst(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'afterLast(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'first(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'last(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'getRow(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'absolute(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'relative(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'previous(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'setFetchDirection(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getFetchDirection(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'setFetchSize(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getType(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'getConcurrency(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'rowUpdated(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'rowInserted(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'rowDeleted(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'updateNull(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBoolean(', 'int, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateByte(', 'int, byte) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateShort(', 'int, short) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateInt(', 'int, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateLong(', 'int, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateFloat(', 'int, float) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDouble(', 'int, double) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBigDecimal(', 'int, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateString(', 'int, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBytes(', 'int, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDate(', 'int, Date) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTime(', 'int, Time) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTimestamp(', 'int, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'int, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'int, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'int, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'int, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'int, Object) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNull(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBoolean(', 'String, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateByte(', 'String, byte) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateShort(', 'String, short) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateInt(', 'String, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateLong(', 'String, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateFloat(', 'String, float) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDouble(', 'String, double) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBigDecimal(', 'String, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateString(', 'String, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBytes(', 'String, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDate(', 'String, Date) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTime(', 'String, Time) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTimestamp(', 'String, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'String, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'String, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'String, Object) throws SQLException', 'void'),
  \ javaapi#method(0,1,'insertRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'deleteRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'refreshRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'cancelRowUpdates(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'moveToInsertRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'moveToCurrentRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'getStatement(', ') throws SQLException', 'Statement'),
  \ javaapi#method(0,1,'getObject(', 'int, Map<String, Class<?>>) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'getRef(', 'int) throws SQLException', 'Ref'),
  \ javaapi#method(0,1,'getBlob(', 'int) throws SQLException', 'Blob'),
  \ javaapi#method(0,1,'getClob(', 'int) throws SQLException', 'Clob'),
  \ javaapi#method(0,1,'getArray(', 'int) throws SQLException', 'Array'),
  \ javaapi#method(0,1,'getObject(', 'String, Map<String, Class<?>>) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'getRef(', 'String) throws SQLException', 'Ref'),
  \ javaapi#method(0,1,'getBlob(', 'String) throws SQLException', 'Blob'),
  \ javaapi#method(0,1,'getClob(', 'String) throws SQLException', 'Clob'),
  \ javaapi#method(0,1,'getArray(', 'String) throws SQLException', 'Array'),
  \ javaapi#method(0,1,'getDate(', 'int, Calendar) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getDate(', 'String, Calendar) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getTime(', 'int, Calendar) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTime(', 'String, Calendar) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTimestamp(', 'int, Calendar) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'getTimestamp(', 'String, Calendar) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'updateRef(', 'int, Ref) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateRef(', 'String, Ref) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'int, Clob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'String, Clob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'int, Blob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'String, Blob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateArray(', 'int, Array) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateArray(', 'String, Array) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getURL(', 'int) throws SQLException', 'URL'),
  \ javaapi#method(0,1,'getURL(', 'String) throws SQLException', 'URL'),
  \ javaapi#method(0,1,'getRowSetWarnings(', ') throws SQLException', 'RowSetWarning'),
  \ javaapi#method(0,1,'unsetMatchColumn(', 'int[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'unsetMatchColumn(', 'String[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getMatchColumnNames(', ') throws SQLException', 'String'),
  \ javaapi#method(0,1,'getMatchColumnIndexes(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'setMatchColumn(', 'int[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setMatchColumn(', 'String[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setMatchColumn(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setMatchColumn(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'unsetMatchColumn(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'unsetMatchColumn(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getDatabaseMetaData(', ') throws SQLException', 'DatabaseMetaData'),
  \ javaapi#method(0,1,'getParameterMetaData(', ') throws SQLException', 'ParameterMetaData'),
  \ javaapi#method(0,1,'commit(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'setAutoCommit(', 'boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getAutoCommit(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'rollback(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'rollback(', 'Savepoint) throws SQLException', 'void'),
  \ javaapi#method(0,0,'setParams(', ') throws SQLException', 'void'),
  \ javaapi#method(0,0,'getConnection(', ')', 'Connection'),
  \ javaapi#method(0,0,'setConnection(', 'Connection)', 'void'),
  \ javaapi#method(0,0,'getPreparedStatement(', ')', 'PreparedStatement'),
  \ javaapi#method(0,0,'setPreparedStatement(', 'PreparedStatement)', 'void'),
  \ javaapi#method(0,0,'getResultSet(', ') throws SQLException', 'ResultSet'),
  \ javaapi#method(0,0,'setResultSet(', 'ResultSet)', 'void'),
  \ javaapi#method(0,1,'setCommand(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setDataSourceName(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setUrl(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setUsername(', 'String)', 'void'),
  \ javaapi#method(0,1,'setPassword(', 'String)', 'void'),
  \ javaapi#method(0,1,'setType(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setConcurrency(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setTransactionIsolation(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setMaxRows(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getSQLXML(', 'int) throws SQLException', 'SQLXML'),
  \ javaapi#method(0,1,'getSQLXML(', 'String) throws SQLException', 'SQLXML'),
  \ javaapi#method(0,1,'getRowId(', 'int) throws SQLException', 'RowId'),
  \ javaapi#method(0,1,'getRowId(', 'String) throws SQLException', 'RowId'),
  \ javaapi#method(0,1,'updateRowId(', 'int, RowId) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateRowId(', 'String, RowId) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getHoldability(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'isClosed(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'updateNString(', 'int, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNString(', 'String, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'int, NClob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'String, NClob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getNClob(', 'int) throws SQLException', 'NClob'),
  \ javaapi#method(0,1,'getNClob(', 'String) throws SQLException', 'NClob'),
  \ javaapi#method(0,1,'unwrap(', 'Class<T>) throws SQLException', 'T'),
  \ javaapi#method(0,1,'isWrapperFor(', 'Class<?>) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'setSQLXML(', 'int, SQLXML) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setSQLXML(', 'String, SQLXML) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setRowId(', 'int, RowId) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setRowId(', 'String, RowId) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNString(', 'int, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNCharacterStream(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'String, NClob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getNCharacterStream(', 'int) throws SQLException', 'Reader'),
  \ javaapi#method(0,1,'getNCharacterStream(', 'String) throws SQLException', 'Reader'),
  \ javaapi#method(0,1,'updateSQLXML(', 'int, SQLXML) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateSQLXML(', 'String, SQLXML) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getNString(', 'int) throws SQLException', 'String'),
  \ javaapi#method(0,1,'getNString(', 'String) throws SQLException', 'String'),
  \ javaapi#method(0,1,'updateNCharacterStream(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNCharacterStream(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNCharacterStream(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNCharacterStream(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'int, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'String, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'int, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNClob(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'int, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'int, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'String, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'int, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'String, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'int, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setURL(', 'int, URL) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNClob(', 'int, NClob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNString(', 'String, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNCharacterStream(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNCharacterStream(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNCharacterStream(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setTimestamp(', 'String, Timestamp, Calendar) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setClob(', 'String, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setClob(', 'String, Clob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setClob(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setDate(', 'String, Date) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setDate(', 'String, Date, Calendar) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setTime(', 'String, Time) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setTime(', 'String, Time, Calendar) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setClob(', 'int, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setClob(', 'int, Reader, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBlob(', 'int, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBlob(', 'int, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBlob(', 'String, InputStream, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBlob(', 'String, Blob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBlob(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setObject(', 'String, Object, int, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setObject(', 'String, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setObject(', 'String, Object) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setAsciiStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBinaryStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setCharacterStream(', 'String, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setAsciiStream(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBinaryStream(', 'String, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setCharacterStream(', 'String, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBigDecimal(', 'String, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setString(', 'String, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBytes(', 'String, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setTimestamp(', 'String, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNull(', 'String, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setNull(', 'String, int, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setBoolean(', 'String, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setByte(', 'String, byte) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setShort(', 'String, short) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setInt(', 'String, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setLong(', 'String, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setFloat(', 'String, float) throws SQLException', 'void'),
  \ javaapi#method(0,1,'setDouble(', 'String, double) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getObject(', 'int, Class<T>) throws SQLException', 'T'),
  \ javaapi#method(0,1,'getObject(', 'String, Class<T>) throws SQLException', 'T'),
  \ ])

call javaapi#class('JdbcRowSetResourceBundle', 'Serializable', [
  \ javaapi#method(1,1,'getJdbcRowSetResourceBundle(', ') throws IOException', 'JdbcRowSetResourceBundle'),
  \ javaapi#method(0,1,'getKeys(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'handleGetObject(', 'String)', 'Object'),
  \ ])

call javaapi#class('JoinRowSetImpl', 'WebRowSetImpl', [
  \ javaapi#method(0,1,'JoinRowSetImpl(', ') throws SQLException', ''),
  \ javaapi#method(0,1,'addRowSet(', 'Joinable) throws SQLException', 'void'),
  \ javaapi#method(0,1,'addRowSet(', 'RowSet, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'addRowSet(', 'RowSet, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'addRowSet(', 'RowSet[], int[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'addRowSet(', 'RowSet[], String[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getRowSets(', ') throws SQLException', 'Collection'),
  \ javaapi#method(0,1,'getRowSetNames(', ') throws SQLException', 'String'),
  \ javaapi#method(0,1,'toCachedRowSet(', ') throws SQLException', 'CachedRowSet'),
  \ javaapi#method(0,1,'supportsCrossJoin(', ')', 'boolean'),
  \ javaapi#method(0,1,'supportsInnerJoin(', ')', 'boolean'),
  \ javaapi#method(0,1,'supportsLeftOuterJoin(', ')', 'boolean'),
  \ javaapi#method(0,1,'supportsRightOuterJoin(', ')', 'boolean'),
  \ javaapi#method(0,1,'supportsFullJoin(', ')', 'boolean'),
  \ javaapi#method(0,1,'setJoinType(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getWhereClause(', ') throws SQLException', 'String'),
  \ javaapi#method(0,1,'next(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'close(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'wasNull(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'getString(', 'int) throws SQLException', 'String'),
  \ javaapi#method(0,1,'getBoolean(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'getByte(', 'int) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getShort(', 'int) throws SQLException', 'short'),
  \ javaapi#method(0,1,'getInt(', 'int) throws SQLException', 'int'),
  \ javaapi#method(0,1,'getLong(', 'int) throws SQLException', 'long'),
  \ javaapi#method(0,1,'getFloat(', 'int) throws SQLException', 'float'),
  \ javaapi#method(0,1,'getDouble(', 'int) throws SQLException', 'double'),
  \ javaapi#method(0,1,'getBigDecimal(', 'int, int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'getBytes(', 'int) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getDate(', 'int) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getTime(', 'int) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTimestamp(', 'int) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'getAsciiStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getUnicodeStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getBinaryStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getString(', 'String) throws SQLException', 'String'),
  \ javaapi#method(0,1,'getBoolean(', 'String) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'getByte(', 'String) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getShort(', 'String) throws SQLException', 'short'),
  \ javaapi#method(0,1,'getInt(', 'String) throws SQLException', 'int'),
  \ javaapi#method(0,1,'getLong(', 'String) throws SQLException', 'long'),
  \ javaapi#method(0,1,'getFloat(', 'String) throws SQLException', 'float'),
  \ javaapi#method(0,1,'getDouble(', 'String) throws SQLException', 'double'),
  \ javaapi#method(0,1,'getBigDecimal(', 'String, int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'getBytes(', 'String) throws SQLException', 'byte'),
  \ javaapi#method(0,1,'getDate(', 'String) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getTime(', 'String) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTimestamp(', 'String) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'getAsciiStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getUnicodeStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getBinaryStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,1,'getWarnings(', ')', 'SQLWarning'),
  \ javaapi#method(0,1,'clearWarnings(', ')', 'void'),
  \ javaapi#method(0,1,'getCursorName(', ') throws SQLException', 'String'),
  \ javaapi#method(0,1,'getMetaData(', ') throws SQLException', 'ResultSetMetaData'),
  \ javaapi#method(0,1,'getObject(', 'int) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'getObject(', 'int, Map<String, Class<?>>) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'getObject(', 'String) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'getObject(', 'String, Map<String, Class<?>>) throws SQLException', 'Object'),
  \ javaapi#method(0,1,'getCharacterStream(', 'int) throws SQLException', 'Reader'),
  \ javaapi#method(0,1,'getCharacterStream(', 'String) throws SQLException', 'Reader'),
  \ javaapi#method(0,1,'getBigDecimal(', 'int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'getBigDecimal(', 'String) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,1,'size(', ')', 'int'),
  \ javaapi#method(0,1,'isBeforeFirst(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'isAfterLast(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'isFirst(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'isLast(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'beforeFirst(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'afterLast(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'first(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'last(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'getRow(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'absolute(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'relative(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'previous(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'findColumn(', 'String) throws SQLException', 'int'),
  \ javaapi#method(0,1,'rowUpdated(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'columnUpdated(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'rowInserted(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'rowDeleted(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,1,'updateNull(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBoolean(', 'int, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateByte(', 'int, byte) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateShort(', 'int, short) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateInt(', 'int, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateLong(', 'int, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateFloat(', 'int, float) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDouble(', 'int, double) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBigDecimal(', 'int, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateString(', 'int, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBytes(', 'int, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDate(', 'int, Date) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTime(', 'int, Time) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTimestamp(', 'int, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'int, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'int, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'int, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'int, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'int, Object) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateNull(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBoolean(', 'String, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateByte(', 'String, byte) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateShort(', 'String, short) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateInt(', 'String, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateLong(', 'String, long) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateFloat(', 'String, float) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDouble(', 'String, double) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBigDecimal(', 'String, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateString(', 'String, String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBytes(', 'String, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateDate(', 'String, Date) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTime(', 'String, Time) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateTimestamp(', 'String, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateAsciiStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBinaryStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateCharacterStream(', 'String, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'String, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateObject(', 'String, Object) throws SQLException', 'void'),
  \ javaapi#method(0,1,'insertRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'deleteRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'refreshRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'cancelRowUpdates(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'moveToInsertRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'moveToCurrentRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'getStatement(', ') throws SQLException', 'Statement'),
  \ javaapi#method(0,1,'getRef(', 'int) throws SQLException', 'Ref'),
  \ javaapi#method(0,1,'getBlob(', 'int) throws SQLException', 'Blob'),
  \ javaapi#method(0,1,'getClob(', 'int) throws SQLException', 'Clob'),
  \ javaapi#method(0,1,'getArray(', 'int) throws SQLException', 'Array'),
  \ javaapi#method(0,1,'getRef(', 'String) throws SQLException', 'Ref'),
  \ javaapi#method(0,1,'getBlob(', 'String) throws SQLException', 'Blob'),
  \ javaapi#method(0,1,'getClob(', 'String) throws SQLException', 'Clob'),
  \ javaapi#method(0,1,'getArray(', 'String) throws SQLException', 'Array'),
  \ javaapi#method(0,1,'getDate(', 'int, Calendar) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getDate(', 'String, Calendar) throws SQLException', 'Date'),
  \ javaapi#method(0,1,'getTime(', 'int, Calendar) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTime(', 'String, Calendar) throws SQLException', 'Time'),
  \ javaapi#method(0,1,'getTimestamp(', 'int, Calendar) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'getTimestamp(', 'String, Calendar) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,1,'setMetaData(', 'RowSetMetaData) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getOriginal(', ') throws SQLException', 'ResultSet'),
  \ javaapi#method(0,1,'getOriginalRow(', ') throws SQLException', 'ResultSet'),
  \ javaapi#method(0,1,'setOriginalRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'getKeyColumns(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'setKeyColumns(', 'int[]) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateRef(', 'int, Ref) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateRef(', 'String, Ref) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'int, Clob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateClob(', 'String, Clob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'int, Blob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateBlob(', 'String, Blob) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateArray(', 'int, Array) throws SQLException', 'void'),
  \ javaapi#method(0,1,'updateArray(', 'String, Array) throws SQLException', 'void'),
  \ javaapi#method(0,1,'execute(', ') throws SQLException', 'void'),
  \ javaapi#method(0,1,'execute(', 'Connection) throws SQLException', 'void'),
  \ javaapi#method(0,1,'getURL(', 'int) throws SQLException', 'URL'),
  \ javaapi#method(0,1,'getURL(', 'String) throws SQLException', 'URL'),
  \ javaapi#method(0,1,'writeXml(', 'ResultSet, Writer) throws SQLException', 'void'),
  \ javaapi#method(0,1,'writeXml(', 'Writer) throws SQLException', 'void'),
  \ javaapi#method(0,1,'readXml(', 'Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'readXml(', 'InputStream) throws SQLException, IOException', 'void'),
  \ javaapi#method(0,1,'writeXml(', 'OutputStream) throws SQLException, IOException', 'void'),
  \ javaapi#method(0,1,'writeXml(', 'ResultSet, OutputStream) throws SQLException, IOException', 'void'),
  \ javaapi#method(0,1,'getJoinType(', ') throws SQLException', 'int'),
  \ javaapi#method(0,1,'addRowSetListener(', 'RowSetListener)', 'void'),
  \ javaapi#method(0,1,'removeRowSetListener(', 'RowSetListener)', 'void'),
  \ javaapi#method(0,1,'toCollection(', ') throws SQLException', 'Collection'),
  \ javaapi#method(0,1,'toCollection(', 'int) throws SQLException', 'Collection'),
  \ javaapi#method(0,1,'toCollection(', 'String) throws SQLException', 'Collection'),
  \ javaapi#method(0,1,'createCopySchema(', ') throws SQLException', 'CachedRowSet'),
  \ javaapi#method(0,1,'setSyncProvider(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,1,'acceptChanges(', ') throws SyncProviderException', 'void'),
  \ javaapi#method(0,1,'getSyncProvider(', ') throws SQLException', 'SyncProvider'),
  \ ])

call javaapi#class('RowSetFactoryImpl', 'RowSetFactory', [
  \ javaapi#method(0,1,'RowSetFactoryImpl(', ')', ''),
  \ javaapi#method(0,1,'createCachedRowSet(', ') throws SQLException', 'CachedRowSet'),
  \ javaapi#method(0,1,'createFilteredRowSet(', ') throws SQLException', 'FilteredRowSet'),
  \ javaapi#method(0,1,'createJdbcRowSet(', ') throws SQLException', 'JdbcRowSet'),
  \ javaapi#method(0,1,'createJoinRowSet(', ') throws SQLException', 'JoinRowSet'),
  \ javaapi#method(0,1,'createWebRowSet(', ') throws SQLException', 'WebRowSet'),
  \ ])

call javaapi#class('WebRowSetImpl', 'CachedRowSetImpl', [
  \ javaapi#method(0,1,'WebRowSetImpl(', ') throws SQLException', ''),
  \ javaapi#method(0,1,'WebRowSetImpl(', 'Hashtable) throws SQLException', ''),
  \ javaapi#method(0,1,'writeXml(', 'ResultSet, Writer) throws SQLException', 'void'),
  \ javaapi#method(0,1,'writeXml(', 'Writer) throws SQLException', 'void'),
  \ javaapi#method(0,1,'readXml(', 'Reader) throws SQLException', 'void'),
  \ javaapi#method(0,1,'readXml(', 'InputStream) throws SQLException, IOException', 'void'),
  \ javaapi#method(0,1,'writeXml(', 'OutputStream) throws SQLException, IOException', 'void'),
  \ javaapi#method(0,1,'writeXml(', 'ResultSet, OutputStream) throws SQLException, IOException', 'void'),
  \ ])

