call javaapi#namespace('com.sun.org.apache.xerces.internal.util')

call javaapi#class('AttributesProxy', 'Attributes2', [
  \ javaapi#method(0,1,'AttributesProxy(', 'XMLAttributes)', ''),
  \ javaapi#method(0,1,'setAttributes(', 'XMLAttributes)', 'void'),
  \ javaapi#method(0,1,'getAttributes(', ')', 'XMLAttributes'),
  \ javaapi#method(0,1,'getLength(', ')', 'int'),
  \ javaapi#method(0,1,'getQName(', 'int)', 'String'),
  \ javaapi#method(0,1,'getURI(', 'int)', 'String'),
  \ javaapi#method(0,1,'getLocalName(', 'int)', 'String'),
  \ javaapi#method(0,1,'getType(', 'int)', 'String'),
  \ javaapi#method(0,1,'getType(', 'String)', 'String'),
  \ javaapi#method(0,1,'getType(', 'String, String)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'int)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'String)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'String, String)', 'String'),
  \ javaapi#method(0,1,'getIndex(', 'String)', 'int'),
  \ javaapi#method(0,1,'getIndex(', 'String, String)', 'int'),
  \ javaapi#method(0,1,'isDeclared(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'isDeclared(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'isDeclared(', 'String, String)', 'boolean'),
  \ javaapi#method(0,1,'isSpecified(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'isSpecified(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'isSpecified(', 'String, String)', 'boolean'),
  \ javaapi#method(0,1,'getName(', 'int)', 'String'),
  \ ])

call javaapi#class('AugmentationsImpl', 'Augmentations', [
  \ javaapi#method(0,1,'AugmentationsImpl(', ')', ''),
  \ javaapi#method(0,1,'putItem(', 'String, Object)', 'Object'),
  \ javaapi#method(0,1,'getItem(', 'String)', 'Object'),
  \ javaapi#method(0,1,'removeItem(', 'String)', 'Object'),
  \ javaapi#method(0,1,'keys(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'removeAllItems(', ')', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('DOMEntityResolverWrapper', 'XMLEntityResolver', [
  \ javaapi#field(0,0,'fEntityResolver', 'LSResourceResolver'),
  \ javaapi#method(0,1,'DOMEntityResolverWrapper(', ')', ''),
  \ javaapi#method(0,1,'DOMEntityResolverWrapper(', 'LSResourceResolver)', ''),
  \ javaapi#method(0,1,'setEntityResolver(', 'LSResourceResolver)', 'void'),
  \ javaapi#method(0,1,'getEntityResolver(', ')', 'LSResourceResolver'),
  \ javaapi#method(0,1,'resolveEntity(', 'XMLResourceIdentifier) throws XNIException, IOException', 'XMLInputSource'),
  \ ])

call javaapi#class('DOMErrorHandlerWrapper', 'DOMErrorHandler', [
  \ javaapi#field(0,0,'fDomErrorHandler', 'DOMErrorHandler'),
  \ javaapi#field(0,0,'fOut', 'PrintWriter'),
  \ javaapi#field(0,1,'fCurrentNode', 'Node'),
  \ javaapi#field(0,0,'fErrorCode', 'XMLErrorCode'),
  \ javaapi#field(0,0,'fDOMError', 'DOMErrorImpl'),
  \ javaapi#method(0,1,'DOMErrorHandlerWrapper(', ')', ''),
  \ javaapi#method(0,1,'DOMErrorHandlerWrapper(', 'DOMErrorHandler)', ''),
  \ javaapi#method(0,1,'setErrorHandler(', 'DOMErrorHandler)', 'void'),
  \ javaapi#method(0,1,'getErrorHandler(', ')', 'DOMErrorHandler'),
  \ javaapi#method(0,1,'warning(', 'String, String, XMLParseException) throws XNIException', 'void'),
  \ javaapi#method(0,1,'error(', 'String, String, XMLParseException) throws XNIException', 'void'),
  \ javaapi#method(0,1,'fatalError(', 'String, String, XMLParseException) throws XNIException', 'void'),
  \ javaapi#method(0,1,'handleError(', 'DOMError)', 'boolean'),
  \ ])

call javaapi#class('DOMInputSource', 'XMLInputSource', [
  \ javaapi#method(0,1,'DOMInputSource(', ')', ''),
  \ javaapi#method(0,1,'DOMInputSource(', 'Node)', ''),
  \ javaapi#method(0,1,'DOMInputSource(', 'Node, String)', ''),
  \ javaapi#method(0,1,'getNode(', ')', 'Node'),
  \ javaapi#method(0,1,'setNode(', 'Node)', 'void'),
  \ ])

call javaapi#class('DOMUtil', '', [
  \ javaapi#method(0,0,'DOMUtil(', ')', ''),
  \ javaapi#method(1,1,'copyInto(', 'Node, Node) throws DOMException', 'void'),
  \ javaapi#method(1,1,'getFirstChildElement(', 'Node)', 'Element'),
  \ javaapi#method(1,1,'getFirstVisibleChildElement(', 'Node)', 'Element'),
  \ javaapi#method(1,1,'getFirstVisibleChildElement(', 'Node, Hashtable)', 'Element'),
  \ javaapi#method(1,1,'getLastChildElement(', 'Node)', 'Element'),
  \ javaapi#method(1,1,'getLastVisibleChildElement(', 'Node)', 'Element'),
  \ javaapi#method(1,1,'getLastVisibleChildElement(', 'Node, Hashtable)', 'Element'),
  \ javaapi#method(1,1,'getNextSiblingElement(', 'Node)', 'Element'),
  \ javaapi#method(1,1,'getNextVisibleSiblingElement(', 'Node)', 'Element'),
  \ javaapi#method(1,1,'getNextVisibleSiblingElement(', 'Node, Hashtable)', 'Element'),
  \ javaapi#method(1,1,'setHidden(', 'Node)', 'void'),
  \ javaapi#method(1,1,'setHidden(', 'Node, Hashtable)', 'void'),
  \ javaapi#method(1,1,'setVisible(', 'Node)', 'void'),
  \ javaapi#method(1,1,'setVisible(', 'Node, Hashtable)', 'void'),
  \ javaapi#method(1,1,'isHidden(', 'Node)', 'boolean'),
  \ javaapi#method(1,1,'isHidden(', 'Node, Hashtable)', 'boolean'),
  \ javaapi#method(1,1,'getFirstChildElement(', 'Node, String)', 'Element'),
  \ javaapi#method(1,1,'getLastChildElement(', 'Node, String)', 'Element'),
  \ javaapi#method(1,1,'getNextSiblingElement(', 'Node, String)', 'Element'),
  \ javaapi#method(1,1,'getFirstChildElementNS(', 'Node, String, String)', 'Element'),
  \ javaapi#method(1,1,'getLastChildElementNS(', 'Node, String, String)', 'Element'),
  \ javaapi#method(1,1,'getNextSiblingElementNS(', 'Node, String, String)', 'Element'),
  \ javaapi#method(1,1,'getFirstChildElement(', 'Node, String[])', 'Element'),
  \ javaapi#method(1,1,'getLastChildElement(', 'Node, String[])', 'Element'),
  \ javaapi#method(1,1,'getNextSiblingElement(', 'Node, String[])', 'Element'),
  \ javaapi#method(1,1,'getFirstChildElementNS(', 'Node, String[][])', 'Element'),
  \ javaapi#method(1,1,'getLastChildElementNS(', 'Node, String[][])', 'Element'),
  \ javaapi#method(1,1,'getNextSiblingElementNS(', 'Node, String[][])', 'Element'),
  \ javaapi#method(1,1,'getFirstChildElement(', 'Node, String, String, String)', 'Element'),
  \ javaapi#method(1,1,'getLastChildElement(', 'Node, String, String, String)', 'Element'),
  \ javaapi#method(1,1,'getNextSiblingElement(', 'Node, String, String, String)', 'Element'),
  \ javaapi#method(1,1,'getChildText(', 'Node)', 'String'),
  \ javaapi#method(1,1,'getName(', 'Node)', 'String'),
  \ javaapi#method(1,1,'getLocalName(', 'Node)', 'String'),
  \ javaapi#method(1,1,'getParent(', 'Element)', 'Element'),
  \ javaapi#method(1,1,'getDocument(', 'Node)', 'Document'),
  \ javaapi#method(1,1,'getRoot(', 'Document)', 'Element'),
  \ javaapi#method(1,1,'getAttr(', 'Element, String)', 'Attr'),
  \ javaapi#method(1,1,'getAttrNS(', 'Element, String, String)', 'Attr'),
  \ javaapi#method(1,1,'getAttrs(', 'Element)', 'Attr'),
  \ javaapi#method(1,1,'getValue(', 'Attr)', 'String'),
  \ javaapi#method(1,1,'getAttrValue(', 'Element, String)', 'String'),
  \ javaapi#method(1,1,'getAttrValueNS(', 'Element, String, String)', 'String'),
  \ javaapi#method(1,1,'getPrefix(', 'Node)', 'String'),
  \ javaapi#method(1,1,'getNamespaceURI(', 'Node)', 'String'),
  \ javaapi#method(1,1,'getAnnotation(', 'Node)', 'String'),
  \ javaapi#method(1,1,'getSyntheticAnnotation(', 'Node)', 'String'),
  \ javaapi#method(1,1,'createDOMException(', 'short, Throwable)', 'DOMException'),
  \ javaapi#method(1,1,'createLSException(', 'short, Throwable)', 'LSException'),
  \ ])

call javaapi#class('DatatypeMessageFormatter', '', [
  \ javaapi#method(0,1,'DatatypeMessageFormatter(', ')', ''),
  \ javaapi#method(1,1,'formatMessage(', 'Locale, String, Object[]) throws MissingResourceException', 'String'),
  \ ])

call javaapi#class('DefaultErrorHandler', 'XMLErrorHandler', [
  \ javaapi#field(0,0,'fOut', 'PrintWriter'),
  \ javaapi#method(0,1,'DefaultErrorHandler(', ')', ''),
  \ javaapi#method(0,1,'DefaultErrorHandler(', 'PrintWriter)', ''),
  \ javaapi#method(0,1,'warning(', 'String, String, XMLParseException) throws XNIException', 'void'),
  \ javaapi#method(0,1,'error(', 'String, String, XMLParseException) throws XNIException', 'void'),
  \ javaapi#method(0,1,'fatalError(', 'String, String, XMLParseException) throws XNIException', 'void'),
  \ ])

call javaapi#class('DraconianErrorHandler', 'ErrorHandler', [
  \ javaapi#field(1,1,'theInstance', 'ErrorHandler'),
  \ javaapi#method(0,1,'error(', 'SAXParseException) throws SAXException', 'void'),
  \ javaapi#method(0,1,'fatalError(', 'SAXParseException) throws SAXException', 'void'),
  \ javaapi#method(0,1,'warning(', 'SAXParseException) throws SAXException', 'void'),
  \ ])

call javaapi#class('EncodingMap', '', [
  \ javaapi#field(1,0,'fIANA2JavaMap', 'Hashtable'),
  \ javaapi#field(1,0,'fJava2IANAMap', 'Hashtable'),
  \ javaapi#method(0,1,'EncodingMap(', ')', ''),
  \ javaapi#method(1,1,'putIANA2JavaMapping(', 'String, String)', 'void'),
  \ javaapi#method(1,1,'getIANA2JavaMapping(', 'String)', 'String'),
  \ javaapi#method(1,1,'removeIANA2JavaMapping(', 'String)', 'String'),
  \ javaapi#method(1,1,'putJava2IANAMapping(', 'String, String)', 'void'),
  \ javaapi#method(1,1,'getJava2IANAMapping(', 'String)', 'String'),
  \ javaapi#method(1,1,'removeJava2IANAMapping(', 'String)', 'String'),
  \ ])

call javaapi#class('EntityResolver2Wrapper', 'ExternalSubsetResolver', [
  \ javaapi#field(0,0,'fEntityResolver', 'EntityResolver2'),
  \ javaapi#method(0,1,'EntityResolver2Wrapper(', ')', ''),
  \ javaapi#method(0,1,'EntityResolver2Wrapper(', 'EntityResolver2)', ''),
  \ javaapi#method(0,1,'setEntityResolver(', 'EntityResolver2)', 'void'),
  \ javaapi#method(0,1,'getEntityResolver(', ')', 'EntityResolver2'),
  \ javaapi#method(0,1,'getExternalSubset(', 'XMLDTDDescription) throws XNIException, IOException', 'XMLInputSource'),
  \ javaapi#method(0,1,'resolveEntity(', 'XMLResourceIdentifier) throws XNIException, IOException', 'XMLInputSource'),
  \ ])

call javaapi#class('EntityResolverWrapper', 'XMLEntityResolver', [
  \ javaapi#field(0,0,'fEntityResolver', 'EntityResolver'),
  \ javaapi#method(0,1,'EntityResolverWrapper(', ')', ''),
  \ javaapi#method(0,1,'EntityResolverWrapper(', 'EntityResolver)', ''),
  \ javaapi#method(0,1,'setEntityResolver(', 'EntityResolver)', 'void'),
  \ javaapi#method(0,1,'getEntityResolver(', ')', 'EntityResolver'),
  \ javaapi#method(0,1,'resolveEntity(', 'XMLResourceIdentifier) throws XNIException, IOException', 'XMLInputSource'),
  \ ])

call javaapi#class('ErrorHandlerProxy', 'ErrorHandler', [
  \ javaapi#method(0,1,'ErrorHandlerProxy(', ')', ''),
  \ javaapi#method(0,1,'error(', 'SAXParseException) throws SAXException', 'void'),
  \ javaapi#method(0,1,'fatalError(', 'SAXParseException) throws SAXException', 'void'),
  \ javaapi#method(0,1,'warning(', 'SAXParseException) throws SAXException', 'void'),
  \ javaapi#method(0,0,'getErrorHandler(', ')', 'XMLErrorHandler'),
  \ ])

call javaapi#class('ErrorHandlerWrapper', 'XMLErrorHandler', [
  \ javaapi#field(0,0,'fErrorHandler', 'ErrorHandler'),
  \ javaapi#method(0,1,'ErrorHandlerWrapper(', ')', ''),
  \ javaapi#method(0,1,'ErrorHandlerWrapper(', 'ErrorHandler)', ''),
  \ javaapi#method(0,1,'setErrorHandler(', 'ErrorHandler)', 'void'),
  \ javaapi#method(0,1,'getErrorHandler(', ')', 'ErrorHandler'),
  \ javaapi#method(0,1,'warning(', 'String, String, XMLParseException) throws XNIException', 'void'),
  \ javaapi#method(0,1,'error(', 'String, String, XMLParseException) throws XNIException', 'void'),
  \ javaapi#method(0,1,'fatalError(', 'String, String, XMLParseException) throws XNIException', 'void'),
  \ javaapi#method(1,0,'createSAXParseException(', 'XMLParseException)', 'SAXParseException'),
  \ javaapi#method(1,0,'createXMLParseException(', 'SAXParseException)', 'XMLParseException'),
  \ javaapi#method(1,0,'createXNIException(', 'SAXException)', 'XNIException'),
  \ ])

call javaapi#class('FeatureState', '', [
  \ javaapi#field(0,1,'status', 'Status'),
  \ javaapi#field(0,1,'state', 'boolean'),
  \ javaapi#field(1,1,'SET_ENABLED', 'FeatureState'),
  \ javaapi#field(1,1,'SET_DISABLED', 'FeatureState'),
  \ javaapi#field(1,1,'UNKNOWN', 'FeatureState'),
  \ javaapi#field(1,1,'RECOGNIZED', 'FeatureState'),
  \ javaapi#field(1,1,'NOT_SUPPORTED', 'FeatureState'),
  \ javaapi#field(1,1,'NOT_RECOGNIZED', 'FeatureState'),
  \ javaapi#field(1,1,'NOT_ALLOWED', 'FeatureState'),
  \ javaapi#method(0,1,'FeatureState(', 'Status, boolean)', ''),
  \ javaapi#method(1,1,'of(', 'Status)', 'FeatureState'),
  \ javaapi#method(1,1,'is(', 'boolean)', 'FeatureState'),
  \ javaapi#method(0,1,'isExceptional(', ')', 'boolean'),
  \ ])

call javaapi#class('HTTPInputSource', 'XMLInputSource', [
  \ javaapi#field(0,0,'fFollowRedirects', 'boolean'),
  \ javaapi#field(0,0,'fHTTPRequestProperties', 'Map'),
  \ javaapi#method(0,1,'HTTPInputSource(', 'String, String, String)', ''),
  \ javaapi#method(0,1,'HTTPInputSource(', 'XMLResourceIdentifier)', ''),
  \ javaapi#method(0,1,'HTTPInputSource(', 'String, String, String, InputStream, String)', ''),
  \ javaapi#method(0,1,'HTTPInputSource(', 'String, String, String, Reader, String)', ''),
  \ javaapi#method(0,1,'getFollowHTTPRedirects(', ')', 'boolean'),
  \ javaapi#method(0,1,'setFollowHTTPRedirects(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getHTTPRequestProperty(', 'String)', 'String'),
  \ javaapi#method(0,1,'getHTTPRequestProperties(', ')', 'Iterator'),
  \ javaapi#method(0,1,'setHTTPRequestProperty(', 'String, String)', 'void'),
  \ ])

call javaapi#class('IntStack', '', [
  \ javaapi#method(0,1,'IntStack(', ')', ''),
  \ javaapi#method(0,1,'size(', ')', 'int'),
  \ javaapi#method(0,1,'push(', 'int)', 'void'),
  \ javaapi#method(0,1,'peek(', ')', 'int'),
  \ javaapi#method(0,1,'elementAt(', 'int)', 'int'),
  \ javaapi#method(0,1,'pop(', ')', 'int'),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ javaapi#method(0,1,'print(', ')', 'void'),
  \ ])

call javaapi#class('JAXPNamespaceContextWrapper', 'NamespaceContext', [
  \ javaapi#method(0,1,'JAXPNamespaceContextWrapper(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'setNamespaceContext(', 'NamespaceContext)', 'void'),
  \ javaapi#method(0,1,'getNamespaceContext(', ')', 'NamespaceContext'),
  \ javaapi#method(0,1,'setSymbolTable(', 'SymbolTable)', 'void'),
  \ javaapi#method(0,1,'getSymbolTable(', ')', 'SymbolTable'),
  \ javaapi#method(0,1,'setDeclaredPrefixes(', 'List)', 'void'),
  \ javaapi#method(0,1,'getDeclaredPrefixes(', ')', 'List'),
  \ javaapi#method(0,1,'getURI(', 'String)', 'String'),
  \ javaapi#method(0,1,'getPrefix(', 'String)', 'String'),
  \ javaapi#method(0,1,'getAllPrefixes(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'pushContext(', ')', 'void'),
  \ javaapi#method(0,1,'popContext(', ')', 'void'),
  \ javaapi#method(0,1,'declarePrefix(', 'String, String)', 'boolean'),
  \ javaapi#method(0,1,'getDeclaredPrefixCount(', ')', 'int'),
  \ javaapi#method(0,1,'getDeclaredPrefixAt(', 'int)', 'String'),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ ])

call javaapi#class('LocatorProxy', 'Locator2', [
  \ javaapi#method(0,1,'LocatorProxy(', 'XMLLocator)', ''),
  \ javaapi#method(0,1,'getPublicId(', ')', 'String'),
  \ javaapi#method(0,1,'getSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getLineNumber(', ')', 'int'),
  \ javaapi#method(0,1,'getColumnNumber(', ')', 'int'),
  \ javaapi#method(0,1,'getXMLVersion(', ')', 'String'),
  \ javaapi#method(0,1,'getEncoding(', ')', 'String'),
  \ ])

call javaapi#class('LocatorWrapper', 'XMLLocator', [
  \ javaapi#method(0,1,'LocatorWrapper(', 'Locator)', ''),
  \ javaapi#method(0,1,'getColumnNumber(', ')', 'int'),
  \ javaapi#method(0,1,'getLineNumber(', ')', 'int'),
  \ javaapi#method(0,1,'getBaseSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getExpandedSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getLiteralSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getPublicId(', ')', 'String'),
  \ javaapi#method(0,1,'getEncoding(', ')', 'String'),
  \ javaapi#method(0,1,'getCharacterOffset(', ')', 'int'),
  \ javaapi#method(0,1,'getXMLVersion(', ')', 'String'),
  \ ])

call javaapi#interface('MessageFormatter', '', [
  \ javaapi#method(0,1,'formatMessage(', 'Locale, String, Object[]) throws MissingResourceException', 'String'),
  \ ])

call javaapi#class('NamespaceContextWrapper', 'NamespaceContext', [
  \ javaapi#method(0,1,'NamespaceContextWrapper(', 'NamespaceSupport)', ''),
  \ javaapi#method(0,1,'getNamespaceURI(', 'String)', 'String'),
  \ javaapi#method(0,1,'getPrefix(', 'String)', 'String'),
  \ javaapi#method(0,1,'getPrefixes(', 'String)', 'Iterator'),
  \ javaapi#method(0,1,'getNamespaceContext(', ')', 'NamespaceContext'),
  \ ])

call javaapi#class('NamespaceSupport', 'NamespaceContext', [
  \ javaapi#field(0,0,'fNamespace', 'String'),
  \ javaapi#field(0,0,'fNamespaceSize', 'int'),
  \ javaapi#field(0,0,'fContext', 'int'),
  \ javaapi#field(0,0,'fCurrentContext', 'int'),
  \ javaapi#field(0,0,'fPrefixes', 'String'),
  \ javaapi#method(0,1,'NamespaceSupport(', ')', ''),
  \ javaapi#method(0,1,'NamespaceSupport(', 'NamespaceContext)', ''),
  \ javaapi#method(0,1,'reset(', ')', 'void'),
  \ javaapi#method(0,1,'pushContext(', ')', 'void'),
  \ javaapi#method(0,1,'popContext(', ')', 'void'),
  \ javaapi#method(0,1,'declarePrefix(', 'String, String)', 'boolean'),
  \ javaapi#method(0,1,'getURI(', 'String)', 'String'),
  \ javaapi#method(0,1,'getPrefix(', 'String)', 'String'),
  \ javaapi#method(0,1,'getDeclaredPrefixCount(', ')', 'int'),
  \ javaapi#method(0,1,'getDeclaredPrefixAt(', 'int)', 'String'),
  \ javaapi#method(0,1,'getPrefixes(', ')', 'Iterator'),
  \ javaapi#method(0,1,'getAllPrefixes(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getPrefixes(', 'String)', 'Vector'),
  \ javaapi#method(0,1,'containsPrefix(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'containsPrefixInCurrentContext(', 'String)', 'boolean'),
  \ ])

call javaapi#class('ParserConfigurationSettings', 'XMLComponentManager', [
  \ javaapi#field(1,0,'PARSER_SETTINGS', 'String'),
  \ javaapi#field(0,0,'fRecognizedProperties', 'Set'),
  \ javaapi#field(0,0,'fProperties', 'Object>'),
  \ javaapi#field(0,0,'fRecognizedFeatures', 'Set'),
  \ javaapi#field(0,0,'fFeatures', 'Boolean>'),
  \ javaapi#field(0,0,'fParentSettings', 'XMLComponentManager'),
  \ javaapi#method(0,1,'ParserConfigurationSettings(', ')', ''),
  \ javaapi#method(0,1,'ParserConfigurationSettings(', 'XMLComponentManager)', ''),
  \ javaapi#method(0,1,'addRecognizedFeatures(', 'String[])', 'void'),
  \ javaapi#method(0,1,'setFeature(', 'String, boolean) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'addRecognizedProperties(', 'String[])', 'void'),
  \ javaapi#method(0,1,'setProperty(', 'String, Object) throws XMLConfigurationException', 'void'),
  \ javaapi#method(0,1,'getFeature(', 'String) throws XMLConfigurationException', 'boolean'),
  \ javaapi#method(0,1,'getFeature(', 'String, boolean)', 'boolean'),
  \ javaapi#method(0,1,'getFeatureState(', 'String)', 'FeatureState'),
  \ javaapi#method(0,1,'getProperty(', 'String) throws XMLConfigurationException', 'Object'),
  \ javaapi#method(0,1,'getProperty(', 'String, Object)', 'Object'),
  \ javaapi#method(0,1,'getPropertyState(', 'String)', 'PropertyState'),
  \ javaapi#method(0,0,'checkFeature(', 'String) throws XMLConfigurationException', 'FeatureState'),
  \ javaapi#method(0,0,'checkProperty(', 'String) throws XMLConfigurationException', 'PropertyState'),
  \ ])

call javaapi#class('PropertyState', '', [
  \ javaapi#field(0,1,'status', 'Status'),
  \ javaapi#field(0,1,'state', 'Object'),
  \ javaapi#field(1,1,'UNKNOWN', 'PropertyState'),
  \ javaapi#field(1,1,'RECOGNIZED', 'PropertyState'),
  \ javaapi#field(1,1,'NOT_SUPPORTED', 'PropertyState'),
  \ javaapi#field(1,1,'NOT_RECOGNIZED', 'PropertyState'),
  \ javaapi#field(1,1,'NOT_ALLOWED', 'PropertyState'),
  \ javaapi#method(0,1,'PropertyState(', 'Status, Object)', ''),
  \ javaapi#method(1,1,'of(', 'Status)', 'PropertyState'),
  \ javaapi#method(1,1,'is(', 'Object)', 'PropertyState'),
  \ javaapi#method(0,1,'isExceptional(', ')', 'boolean'),
  \ ])

call javaapi#class('SAX2XNI', 'XMLDocumentSource', [
  \ javaapi#method(0,1,'SAX2XNI(', 'XMLDocumentHandler)', ''),
  \ javaapi#method(0,1,'setDocumentHandler(', 'XMLDocumentHandler)', 'void'),
  \ javaapi#method(0,1,'getDocumentHandler(', ')', 'XMLDocumentHandler'),
  \ javaapi#method(0,1,'startDocument(', ') throws SAXException', 'void'),
  \ javaapi#method(0,1,'endDocument(', ') throws SAXException', 'void'),
  \ javaapi#method(0,1,'startElement(', 'String, String, String, Attributes) throws SAXException', 'void'),
  \ javaapi#method(0,1,'endElement(', 'String, String, String) throws SAXException', 'void'),
  \ javaapi#method(0,1,'characters(', 'char[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,1,'ignorableWhitespace(', 'char[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,1,'startPrefixMapping(', 'String, String)', 'void'),
  \ javaapi#method(0,1,'endPrefixMapping(', 'String)', 'void'),
  \ javaapi#method(0,1,'processingInstruction(', 'String, String) throws SAXException', 'void'),
  \ javaapi#method(0,1,'skippedEntity(', 'String)', 'void'),
  \ javaapi#method(0,1,'setDocumentLocator(', 'Locator)', 'void'),
  \ ])

call javaapi#class('SAXInputSource', 'XMLInputSource', [
  \ javaapi#method(0,1,'SAXInputSource(', ')', ''),
  \ javaapi#method(0,1,'SAXInputSource(', 'InputSource)', ''),
  \ javaapi#method(0,1,'SAXInputSource(', 'XMLReader, InputSource)', ''),
  \ javaapi#method(0,1,'setXMLReader(', 'XMLReader)', 'void'),
  \ javaapi#method(0,1,'getXMLReader(', ')', 'XMLReader'),
  \ javaapi#method(0,1,'setInputSource(', 'InputSource)', 'void'),
  \ javaapi#method(0,1,'getInputSource(', ')', 'InputSource'),
  \ javaapi#method(0,1,'setPublicId(', 'String)', 'void'),
  \ javaapi#method(0,1,'setSystemId(', 'String)', 'void'),
  \ javaapi#method(0,1,'setByteStream(', 'InputStream)', 'void'),
  \ javaapi#method(0,1,'setCharacterStream(', 'Reader)', 'void'),
  \ javaapi#method(0,1,'setEncoding(', 'String)', 'void'),
  \ ])

call javaapi#class('SAXLocatorWrapper', 'XMLLocator', [
  \ javaapi#method(0,1,'SAXLocatorWrapper(', ')', ''),
  \ javaapi#method(0,1,'setLocator(', 'Locator)', 'void'),
  \ javaapi#method(0,1,'getLocator(', ')', 'Locator'),
  \ javaapi#method(0,1,'getPublicId(', ')', 'String'),
  \ javaapi#method(0,1,'getLiteralSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getBaseSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getExpandedSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getLineNumber(', ')', 'int'),
  \ javaapi#method(0,1,'getColumnNumber(', ')', 'int'),
  \ javaapi#method(0,1,'getCharacterOffset(', ')', 'int'),
  \ javaapi#method(0,1,'getEncoding(', ')', 'String'),
  \ javaapi#method(0,1,'getXMLVersion(', ')', 'String'),
  \ ])

call javaapi#class('SAXMessageFormatter', '', [
  \ javaapi#method(0,1,'SAXMessageFormatter(', ')', ''),
  \ javaapi#method(1,1,'formatMessage(', 'Locale, String, Object[]) throws MissingResourceException', 'String'),
  \ ])

call javaapi#class('SecurityManager', '', [
  \ javaapi#method(0,1,'SecurityManager(', ')', ''),
  \ javaapi#method(0,1,'setEntityExpansionLimit(', 'int)', 'void'),
  \ javaapi#method(0,1,'getEntityExpansionLimit(', ')', 'int'),
  \ javaapi#method(0,1,'setMaxOccurNodeLimit(', 'int)', 'void'),
  \ javaapi#method(0,1,'getMaxOccurNodeLimit(', ')', 'int'),
  \ javaapi#method(0,1,'getElementAttrLimit(', ')', 'int'),
  \ javaapi#method(0,1,'setElementAttrLimit(', 'int)', 'void'),
  \ ])

call javaapi#class('ShadowedSymbolTable', 'SymbolTable', [
  \ javaapi#field(0,0,'fSymbolTable', 'SymbolTable'),
  \ javaapi#method(0,1,'ShadowedSymbolTable(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'addSymbol(', 'String)', 'String'),
  \ javaapi#method(0,1,'addSymbol(', 'char[], int, int)', 'String'),
  \ javaapi#method(0,1,'hash(', 'String)', 'int'),
  \ javaapi#method(0,1,'hash(', 'char[], int, int)', 'int'),
  \ ])

call javaapi#class('StAXInputSource', 'XMLInputSource', [
  \ javaapi#method(0,1,'StAXInputSource(', 'XMLStreamReader)', ''),
  \ javaapi#method(0,1,'StAXInputSource(', 'XMLStreamReader, boolean)', ''),
  \ javaapi#method(0,1,'StAXInputSource(', 'XMLEventReader)', ''),
  \ javaapi#method(0,1,'StAXInputSource(', 'XMLEventReader, boolean)', ''),
  \ javaapi#method(0,1,'getXMLStreamReader(', ')', 'XMLStreamReader'),
  \ javaapi#method(0,1,'getXMLEventReader(', ')', 'XMLEventReader'),
  \ javaapi#method(0,1,'shouldConsumeRemainingContent(', ')', 'boolean'),
  \ javaapi#method(0,1,'setSystemId(', 'String)', 'void'),
  \ ])

call javaapi#class('StAXLocationWrapper', 'XMLLocator', [
  \ javaapi#method(0,1,'StAXLocationWrapper(', ')', ''),
  \ javaapi#method(0,1,'setLocation(', 'Location)', 'void'),
  \ javaapi#method(0,1,'getLocation(', ')', 'Location'),
  \ javaapi#method(0,1,'getPublicId(', ')', 'String'),
  \ javaapi#method(0,1,'getLiteralSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getBaseSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getExpandedSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getLineNumber(', ')', 'int'),
  \ javaapi#method(0,1,'getColumnNumber(', ')', 'int'),
  \ javaapi#method(0,1,'getCharacterOffset(', ')', 'int'),
  \ javaapi#method(0,1,'getEncoding(', ')', 'String'),
  \ javaapi#method(0,1,'getXMLVersion(', ')', 'String'),
  \ ])

call javaapi#class('Status', 'Enum', [
  \ javaapi#field(1,1,'SET', 'Status'),
  \ javaapi#field(1,1,'UNKNOWN', 'Status'),
  \ javaapi#field(1,1,'RECOGNIZED', 'Status'),
  \ javaapi#field(1,1,'NOT_SUPPORTED', 'Status'),
  \ javaapi#field(1,1,'NOT_RECOGNIZED', 'Status'),
  \ javaapi#field(1,1,'NOT_ALLOWED', 'Status'),
  \ javaapi#method(1,1,'values(', ')', 'Status'),
  \ javaapi#method(1,1,'valueOf(', 'String)', 'Status'),
  \ javaapi#method(0,1,'getType(', ')', 'short'),
  \ javaapi#method(0,1,'isExceptional(', ')', 'boolean'),
  \ ])

call javaapi#class('SymbolHash', '', [
  \ javaapi#field(0,0,'fTableSize', 'int'),
  \ javaapi#field(0,0,'fBuckets', 'Entry'),
  \ javaapi#field(0,0,'fNum', 'int'),
  \ javaapi#method(0,1,'SymbolHash(', ')', ''),
  \ javaapi#method(0,1,'SymbolHash(', 'int)', ''),
  \ javaapi#method(0,1,'put(', 'Object, Object)', 'void'),
  \ javaapi#method(0,1,'get(', 'Object)', 'Object'),
  \ javaapi#method(0,1,'getLength(', ')', 'int'),
  \ javaapi#method(0,1,'getValues(', 'Object[], int)', 'int'),
  \ javaapi#method(0,1,'getEntries(', ')', 'Object'),
  \ javaapi#method(0,1,'makeClone(', ')', 'SymbolHash'),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ javaapi#method(0,0,'search(', 'Object, int)', 'Entry'),
  \ ])

call javaapi#class('SymbolTable', '', [
  \ javaapi#field(1,0,'TABLE_SIZE', 'int'),
  \ javaapi#field(0,0,'fBuckets', 'Entry'),
  \ javaapi#field(0,0,'fTableSize', 'int'),
  \ javaapi#method(0,1,'SymbolTable(', ')', ''),
  \ javaapi#method(0,1,'SymbolTable(', 'int)', ''),
  \ javaapi#method(0,1,'addSymbol(', 'String)', 'String'),
  \ javaapi#method(0,1,'addSymbol(', 'char[], int, int)', 'String'),
  \ javaapi#method(0,1,'hash(', 'String)', 'int'),
  \ javaapi#method(0,1,'hash(', 'char[], int, int)', 'int'),
  \ javaapi#method(0,1,'containsSymbol(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'containsSymbol(', 'char[], int, int)', 'boolean'),
  \ ])

call javaapi#class('SynchronizedSymbolTable', 'SymbolTable', [
  \ javaapi#field(0,0,'fSymbolTable', 'SymbolTable'),
  \ javaapi#method(0,1,'SynchronizedSymbolTable(', 'SymbolTable)', ''),
  \ javaapi#method(0,1,'SynchronizedSymbolTable(', ')', ''),
  \ javaapi#method(0,1,'SynchronizedSymbolTable(', 'int)', ''),
  \ javaapi#method(0,1,'addSymbol(', 'String)', 'String'),
  \ javaapi#method(0,1,'addSymbol(', 'char[], int, int)', 'String'),
  \ javaapi#method(0,1,'containsSymbol(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'containsSymbol(', 'char[], int, int)', 'boolean'),
  \ ])

call javaapi#class('TeeXMLDocumentFilterImpl', 'XMLDocumentFilter', [
  \ javaapi#method(0,1,'TeeXMLDocumentFilterImpl(', ')', ''),
  \ javaapi#method(0,1,'getSide(', ')', 'XMLDocumentHandler'),
  \ javaapi#method(0,1,'setSide(', 'XMLDocumentHandler)', 'void'),
  \ javaapi#method(0,1,'getDocumentSource(', ')', 'XMLDocumentSource'),
  \ javaapi#method(0,1,'setDocumentSource(', 'XMLDocumentSource)', 'void'),
  \ javaapi#method(0,1,'getDocumentHandler(', ')', 'XMLDocumentHandler'),
  \ javaapi#method(0,1,'setDocumentHandler(', 'XMLDocumentHandler)', 'void'),
  \ javaapi#method(0,1,'characters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'comment(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'doctypeDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'emptyElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDocument(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endElement(', 'QName, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endGeneralEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'ignorableWhitespace(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'processingInstruction(', 'String, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startDocument(', 'XMLLocator, String, NamespaceContext, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startGeneralEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'textDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'xmlDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ ])

call javaapi#class('TypeInfoImpl', 'TypeInfo', [
  \ javaapi#method(0,1,'TypeInfoImpl(', ')', ''),
  \ javaapi#method(0,1,'TypeInfoImpl(', 'String, String)', ''),
  \ javaapi#method(0,1,'TypeInfoImpl(', 'XSTypeDefinition)', ''),
  \ javaapi#method(0,1,'getTypeName(', ')', 'String'),
  \ javaapi#method(0,1,'getTypeNamespace(', ')', 'String'),
  \ javaapi#method(0,1,'isDerivedFrom(', 'String, String, int)', 'boolean'),
  \ javaapi#method(1,1,'getDTDTypeInfo(', 'String)', 'TypeInfo'),
  \ ])

call javaapi#class('URI', 'Serializable', [
  \ javaapi#method(0,1,'URI(', ')', ''),
  \ javaapi#method(0,1,'URI(', 'URI)', ''),
  \ javaapi#method(0,1,'URI(', 'String) throws MalformedURIException', ''),
  \ javaapi#method(0,1,'URI(', 'String, boolean) throws MalformedURIException', ''),
  \ javaapi#method(0,1,'URI(', 'URI, String) throws MalformedURIException', ''),
  \ javaapi#method(0,1,'URI(', 'URI, String, boolean) throws MalformedURIException', ''),
  \ javaapi#method(0,1,'URI(', 'String, String) throws MalformedURIException', ''),
  \ javaapi#method(0,1,'URI(', 'String, String, String, String, String) throws MalformedURIException', ''),
  \ javaapi#method(0,1,'URI(', 'String, String, String, int, String, String, String) throws MalformedURIException', ''),
  \ javaapi#method(0,1,'absolutize(', 'URI)', 'void'),
  \ javaapi#method(0,1,'getScheme(', ')', 'String'),
  \ javaapi#method(0,1,'getSchemeSpecificPart(', ')', 'String'),
  \ javaapi#method(0,1,'getUserinfo(', ')', 'String'),
  \ javaapi#method(0,1,'getHost(', ')', 'String'),
  \ javaapi#method(0,1,'getPort(', ')', 'int'),
  \ javaapi#method(0,1,'getRegBasedAuthority(', ')', 'String'),
  \ javaapi#method(0,1,'getAuthority(', ')', 'String'),
  \ javaapi#method(0,1,'getPath(', 'boolean, boolean)', 'String'),
  \ javaapi#method(0,1,'getPath(', ')', 'String'),
  \ javaapi#method(0,1,'getQueryString(', ')', 'String'),
  \ javaapi#method(0,1,'getFragment(', ')', 'String'),
  \ javaapi#method(0,1,'setScheme(', 'String) throws MalformedURIException', 'void'),
  \ javaapi#method(0,1,'setUserinfo(', 'String) throws MalformedURIException', 'void'),
  \ javaapi#method(0,1,'setHost(', 'String) throws MalformedURIException', 'void'),
  \ javaapi#method(0,1,'setPort(', 'int) throws MalformedURIException', 'void'),
  \ javaapi#method(0,1,'setRegBasedAuthority(', 'String) throws MalformedURIException', 'void'),
  \ javaapi#method(0,1,'setPath(', 'String) throws MalformedURIException', 'void'),
  \ javaapi#method(0,1,'appendPath(', 'String) throws MalformedURIException', 'void'),
  \ javaapi#method(0,1,'setQueryString(', 'String) throws MalformedURIException', 'void'),
  \ javaapi#method(0,1,'setFragment(', 'String) throws MalformedURIException', 'void'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'isGenericURI(', ')', 'boolean'),
  \ javaapi#method(0,1,'isAbsoluteURI(', ')', 'boolean'),
  \ javaapi#method(1,1,'isConformantSchemeName(', 'String)', 'boolean'),
  \ javaapi#method(1,1,'isWellFormedAddress(', 'String)', 'boolean'),
  \ javaapi#method(1,1,'isWellFormedIPv4Address(', 'String)', 'boolean'),
  \ javaapi#method(1,1,'isWellFormedIPv6Reference(', 'String)', 'boolean'),
  \ ])

call javaapi#class('XML11Char', '', [
  \ javaapi#field(1,1,'MASK_XML11_VALID', 'int'),
  \ javaapi#field(1,1,'MASK_XML11_SPACE', 'int'),
  \ javaapi#field(1,1,'MASK_XML11_NAME_START', 'int'),
  \ javaapi#field(1,1,'MASK_XML11_NAME', 'int'),
  \ javaapi#field(1,1,'MASK_XML11_CONTROL', 'int'),
  \ javaapi#field(1,1,'MASK_XML11_CONTENT', 'int'),
  \ javaapi#field(1,1,'MASK_XML11_NCNAME_START', 'int'),
  \ javaapi#field(1,1,'MASK_XML11_NCNAME', 'int'),
  \ javaapi#field(1,1,'MASK_XML11_CONTENT_INTERNAL', 'int'),
  \ javaapi#method(0,1,'XML11Char(', ')', ''),
  \ javaapi#method(1,1,'isXML11Space(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isXML11Valid(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isXML11Invalid(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isXML11ValidLiteral(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isXML11Content(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isXML11InternalEntityContent(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isXML11NameStart(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isXML11Name(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isXML11NCNameStart(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isXML11NCName(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isXML11NameHighSurrogate(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isXML11ValidName(', 'String)', 'boolean'),
  \ javaapi#method(1,1,'isXML11ValidNCName(', 'String)', 'boolean'),
  \ javaapi#method(1,1,'isXML11ValidNmtoken(', 'String)', 'boolean'),
  \ ])

call javaapi#class('XMLAttributesImpl', 'XMLBufferListener', [
  \ javaapi#field(1,0,'TABLE_SIZE', 'int'),
  \ javaapi#field(1,0,'SIZE_LIMIT', 'int'),
  \ javaapi#field(0,0,'fNamespaces', 'boolean'),
  \ javaapi#field(0,0,'fLargeCount', 'int'),
  \ javaapi#field(0,0,'fLength', 'int'),
  \ javaapi#field(0,0,'fAttributes', 'Attribute'),
  \ javaapi#field(0,0,'fAttributeTableView', 'Attribute'),
  \ javaapi#field(0,0,'fAttributeTableViewChainState', 'int'),
  \ javaapi#field(0,0,'fTableViewBuckets', 'int'),
  \ javaapi#field(0,0,'fIsTableViewConsistent', 'boolean'),
  \ javaapi#method(0,1,'XMLAttributesImpl(', ')', ''),
  \ javaapi#method(0,1,'XMLAttributesImpl(', 'int)', ''),
  \ javaapi#method(0,1,'setNamespaces(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'addAttribute(', 'QName, String, String)', 'int'),
  \ javaapi#method(0,1,'addAttribute(', 'QName, String, String, XMLString)', 'int'),
  \ javaapi#method(0,1,'removeAllAttributes(', ')', 'void'),
  \ javaapi#method(0,1,'removeAttributeAt(', 'int)', 'void'),
  \ javaapi#method(0,1,'setName(', 'int, QName)', 'void'),
  \ javaapi#method(0,1,'getName(', 'int, QName)', 'void'),
  \ javaapi#method(0,1,'setType(', 'int, String)', 'void'),
  \ javaapi#method(0,1,'setValue(', 'int, String)', 'void'),
  \ javaapi#method(0,1,'setValue(', 'int, String, XMLString)', 'void'),
  \ javaapi#method(0,1,'setNonNormalizedValue(', 'int, String)', 'void'),
  \ javaapi#method(0,1,'getNonNormalizedValue(', 'int)', 'String'),
  \ javaapi#method(0,1,'setSpecified(', 'int, boolean)', 'void'),
  \ javaapi#method(0,1,'isSpecified(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'getLength(', ')', 'int'),
  \ javaapi#method(0,1,'getType(', 'int)', 'String'),
  \ javaapi#method(0,1,'getType(', 'String)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'int)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'String)', 'String'),
  \ javaapi#method(0,1,'getName(', 'int)', 'String'),
  \ javaapi#method(0,1,'getIndex(', 'String)', 'int'),
  \ javaapi#method(0,1,'getIndex(', 'String, String)', 'int'),
  \ javaapi#method(0,1,'getIndexByLocalName(', 'String)', 'int'),
  \ javaapi#method(0,1,'getLocalName(', 'int)', 'String'),
  \ javaapi#method(0,1,'getQName(', 'int)', 'String'),
  \ javaapi#method(0,1,'getQualifiedName(', 'int)', 'QName'),
  \ javaapi#method(0,1,'getType(', 'String, String)', 'String'),
  \ javaapi#method(0,1,'getIndexFast(', 'String)', 'int'),
  \ javaapi#method(0,1,'addAttributeNS(', 'QName, String, String)', 'void'),
  \ javaapi#method(0,1,'checkDuplicatesNS(', ')', 'QName'),
  \ javaapi#method(0,1,'getIndexFast(', 'String, String)', 'int'),
  \ javaapi#method(0,0,'getTableViewBucket(', 'String)', 'int'),
  \ javaapi#method(0,0,'getTableViewBucket(', 'String, String)', 'int'),
  \ javaapi#method(0,0,'cleanTableView(', ')', 'void'),
  \ javaapi#method(0,0,'prepareTableView(', ')', 'void'),
  \ javaapi#method(0,0,'prepareAndPopulateTableView(', ')', 'void'),
  \ javaapi#method(0,1,'getPrefix(', 'int)', 'String'),
  \ javaapi#method(0,1,'getURI(', 'int)', 'String'),
  \ javaapi#method(0,1,'getValue(', 'String, String)', 'String'),
  \ javaapi#method(0,1,'getAugmentations(', 'String, String)', 'Augmentations'),
  \ javaapi#method(0,1,'getAugmentations(', 'String)', 'Augmentations'),
  \ javaapi#method(0,1,'getAugmentations(', 'int)', 'Augmentations'),
  \ javaapi#method(0,1,'setAugmentations(', 'int, Augmentations)', 'void'),
  \ javaapi#method(0,1,'setURI(', 'int, String)', 'void'),
  \ javaapi#method(0,1,'setSchemaId(', 'int, boolean)', 'void'),
  \ javaapi#method(0,1,'getSchemaId(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'getSchemaId(', 'String)', 'boolean'),
  \ javaapi#method(0,1,'getSchemaId(', 'String, String)', 'boolean'),
  \ javaapi#method(0,1,'refresh(', ')', 'void'),
  \ javaapi#method(0,1,'refresh(', 'int)', 'void'),
  \ ])

call javaapi#class('XMLAttributesIteratorImpl', 'XMLAttributesImpl', [
  \ javaapi#field(0,0,'fCurrent', 'int'),
  \ javaapi#field(0,0,'fLastReturnedItem', 'Attribute'),
  \ javaapi#method(0,1,'XMLAttributesIteratorImpl(', ')', ''),
  \ javaapi#method(0,1,'hasNext(', ')', 'boolean'),
  \ javaapi#method(0,1,'next(', ')', 'Object'),
  \ javaapi#method(0,1,'remove(', ')', 'void'),
  \ javaapi#method(0,1,'removeAllAttributes(', ')', 'void'),
  \ ])

call javaapi#class('XMLCatalogResolver', 'LSResourceResolver', [
  \ javaapi#method(0,1,'XMLCatalogResolver(', ')', ''),
  \ javaapi#method(0,1,'XMLCatalogResolver(', 'String[])', ''),
  \ javaapi#method(0,1,'XMLCatalogResolver(', 'String[], boolean)', ''),
  \ javaapi#method(0,1,'getCatalogList(', ')', 'String'),
  \ javaapi#method(0,1,'setCatalogList(', 'String[])', 'void'),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ javaapi#method(0,1,'getPreferPublic(', ')', 'boolean'),
  \ javaapi#method(0,1,'setPreferPublic(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getUseLiteralSystemId(', ')', 'boolean'),
  \ javaapi#method(0,1,'setUseLiteralSystemId(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'resolveEntity(', 'String, String) throws SAXException, IOException', 'InputSource'),
  \ javaapi#method(0,1,'resolveEntity(', 'String, String, String, String) throws SAXException, IOException', 'InputSource'),
  \ javaapi#method(0,1,'getExternalSubset(', 'String, String) throws SAXException, IOException', 'InputSource'),
  \ javaapi#method(0,1,'resolveResource(', 'String, String, String, String, String)', 'LSInput'),
  \ javaapi#method(0,1,'resolveEntity(', 'XMLResourceIdentifier) throws XNIException, IOException', 'XMLInputSource'),
  \ javaapi#method(0,1,'resolveIdentifier(', 'XMLResourceIdentifier) throws IOException, XNIException', 'String'),
  \ javaapi#method(0,1,'resolveSystem(', 'String) throws IOException', 'String'),
  \ javaapi#method(0,1,'resolvePublic(', 'String, String) throws IOException', 'String'),
  \ javaapi#method(0,1,'resolveURI(', 'String) throws IOException', 'String'),
  \ ])

call javaapi#class('XMLChar', '', [
  \ javaapi#field(1,1,'MASK_VALID', 'int'),
  \ javaapi#field(1,1,'MASK_SPACE', 'int'),
  \ javaapi#field(1,1,'MASK_NAME_START', 'int'),
  \ javaapi#field(1,1,'MASK_NAME', 'int'),
  \ javaapi#field(1,1,'MASK_PUBID', 'int'),
  \ javaapi#field(1,1,'MASK_CONTENT', 'int'),
  \ javaapi#field(1,1,'MASK_NCNAME_START', 'int'),
  \ javaapi#field(1,1,'MASK_NCNAME', 'int'),
  \ javaapi#method(0,1,'XMLChar(', ')', ''),
  \ javaapi#method(1,1,'isSupplemental(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'supplemental(', 'char, char)', 'int'),
  \ javaapi#method(1,1,'highSurrogate(', 'int)', 'char'),
  \ javaapi#method(1,1,'lowSurrogate(', 'int)', 'char'),
  \ javaapi#method(1,1,'isHighSurrogate(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isLowSurrogate(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isValid(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isInvalid(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isContent(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isMarkup(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isSpace(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isNameStart(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isName(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isNCNameStart(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isNCName(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isPubid(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isValidName(', 'String)', 'boolean'),
  \ javaapi#method(1,1,'isValidNCName(', 'String)', 'boolean'),
  \ javaapi#method(1,1,'isValidNmtoken(', 'String)', 'boolean'),
  \ javaapi#method(1,1,'isValidIANAEncoding(', 'String)', 'boolean'),
  \ javaapi#method(1,1,'isValidJavaEncoding(', 'String)', 'boolean'),
  \ javaapi#method(1,1,'trim(', 'String)', 'String'),
  \ ])

call javaapi#class('XMLDocumentFilterImpl', 'XMLDocumentFilter', [
  \ javaapi#method(0,1,'XMLDocumentFilterImpl(', ')', ''),
  \ javaapi#method(0,1,'setDocumentHandler(', 'XMLDocumentHandler)', 'void'),
  \ javaapi#method(0,1,'getDocumentHandler(', ')', 'XMLDocumentHandler'),
  \ javaapi#method(0,1,'setDocumentSource(', 'XMLDocumentSource)', 'void'),
  \ javaapi#method(0,1,'getDocumentSource(', ')', 'XMLDocumentSource'),
  \ javaapi#method(0,1,'characters(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'comment(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'doctypeDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'emptyElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endDocument(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endElement(', 'QName, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'endGeneralEntity(', 'String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'ignorableWhitespace(', 'XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'processingInstruction(', 'String, XMLString, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startCDATA(', 'Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startDocument(', 'XMLLocator, String, NamespaceContext, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startElement(', 'QName, XMLAttributes, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'startGeneralEntity(', 'String, XMLResourceIdentifier, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'textDecl(', 'String, String, Augmentations) throws XNIException', 'void'),
  \ javaapi#method(0,1,'xmlDecl(', 'String, String, String, Augmentations) throws XNIException', 'void'),
  \ ])

call javaapi#class('XMLEntityDescriptionImpl', 'XMLResourceIdentifierImpl', [
  \ javaapi#field(0,0,'fEntityName', 'String'),
  \ javaapi#method(0,1,'XMLEntityDescriptionImpl(', ')', ''),
  \ javaapi#method(0,1,'XMLEntityDescriptionImpl(', 'String, String, String, String, String)', ''),
  \ javaapi#method(0,1,'XMLEntityDescriptionImpl(', 'String, String, String, String, String, String)', ''),
  \ javaapi#method(0,1,'setEntityName(', 'String)', 'void'),
  \ javaapi#method(0,1,'getEntityName(', ')', 'String'),
  \ javaapi#method(0,1,'setDescription(', 'String, String, String, String, String)', 'void'),
  \ javaapi#method(0,1,'setDescription(', 'String, String, String, String, String, String)', 'void'),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('XMLErrorCode', '', [
  \ javaapi#method(0,1,'XMLErrorCode(', 'String, String)', ''),
  \ javaapi#method(0,1,'setValues(', 'String, String)', 'void'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ ])

call javaapi#class('XMLGrammarPoolImpl', 'XMLGrammarPool', [
  \ javaapi#field(1,0,'TABLE_SIZE', 'int'),
  \ javaapi#field(0,0,'fGrammars', 'Entry'),
  \ javaapi#field(0,0,'fPoolIsLocked', 'boolean'),
  \ javaapi#field(0,0,'fGrammarCount', 'int'),
  \ javaapi#method(0,1,'XMLGrammarPoolImpl(', ')', ''),
  \ javaapi#method(0,1,'XMLGrammarPoolImpl(', 'int)', ''),
  \ javaapi#method(0,1,'retrieveInitialGrammarSet(', 'String)', 'Grammar'),
  \ javaapi#method(0,1,'cacheGrammars(', 'String, Grammar[])', 'void'),
  \ javaapi#method(0,1,'retrieveGrammar(', 'XMLGrammarDescription)', 'Grammar'),
  \ javaapi#method(0,1,'putGrammar(', 'Grammar)', 'void'),
  \ javaapi#method(0,1,'getGrammar(', 'XMLGrammarDescription)', 'Grammar'),
  \ javaapi#method(0,1,'removeGrammar(', 'XMLGrammarDescription)', 'Grammar'),
  \ javaapi#method(0,1,'containsGrammar(', 'XMLGrammarDescription)', 'boolean'),
  \ javaapi#method(0,1,'lockPool(', ')', 'void'),
  \ javaapi#method(0,1,'unlockPool(', ')', 'void'),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ javaapi#method(0,1,'equals(', 'XMLGrammarDescription, XMLGrammarDescription)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', 'XMLGrammarDescription)', 'int'),
  \ ])

call javaapi#class('XMLInputSourceAdaptor', 'Source', [
  \ javaapi#field(0,1,'fSource', 'XMLInputSource'),
  \ javaapi#method(0,1,'XMLInputSourceAdaptor(', 'XMLInputSource)', ''),
  \ javaapi#method(0,1,'setSystemId(', 'String)', 'void'),
  \ javaapi#method(0,1,'getSystemId(', ')', 'String'),
  \ ])

call javaapi#class('XMLResourceIdentifierImpl', 'XMLResourceIdentifier', [
  \ javaapi#field(0,0,'fPublicId', 'String'),
  \ javaapi#field(0,0,'fLiteralSystemId', 'String'),
  \ javaapi#field(0,0,'fBaseSystemId', 'String'),
  \ javaapi#field(0,0,'fExpandedSystemId', 'String'),
  \ javaapi#field(0,0,'fNamespace', 'String'),
  \ javaapi#method(0,1,'XMLResourceIdentifierImpl(', ')', ''),
  \ javaapi#method(0,1,'XMLResourceIdentifierImpl(', 'String, String, String, String)', ''),
  \ javaapi#method(0,1,'XMLResourceIdentifierImpl(', 'String, String, String, String, String)', ''),
  \ javaapi#method(0,1,'setValues(', 'String, String, String, String)', 'void'),
  \ javaapi#method(0,1,'setValues(', 'String, String, String, String, String)', 'void'),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ javaapi#method(0,1,'setPublicId(', 'String)', 'void'),
  \ javaapi#method(0,1,'setLiteralSystemId(', 'String)', 'void'),
  \ javaapi#method(0,1,'setBaseSystemId(', 'String)', 'void'),
  \ javaapi#method(0,1,'setExpandedSystemId(', 'String)', 'void'),
  \ javaapi#method(0,1,'setNamespace(', 'String)', 'void'),
  \ javaapi#method(0,1,'getPublicId(', ')', 'String'),
  \ javaapi#method(0,1,'getLiteralSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getBaseSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getExpandedSystemId(', ')', 'String'),
  \ javaapi#method(0,1,'getNamespace(', ')', 'String'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('XMLStringBuffer', 'XMLString', [
  \ javaapi#field(1,1,'DEFAULT_SIZE', 'int'),
  \ javaapi#method(0,1,'XMLStringBuffer(', ')', ''),
  \ javaapi#method(0,1,'XMLStringBuffer(', 'int)', ''),
  \ javaapi#method(0,1,'XMLStringBuffer(', 'char)', ''),
  \ javaapi#method(0,1,'XMLStringBuffer(', 'String)', ''),
  \ javaapi#method(0,1,'XMLStringBuffer(', 'char[], int, int)', ''),
  \ javaapi#method(0,1,'XMLStringBuffer(', 'XMLString)', ''),
  \ javaapi#method(0,1,'clear(', ')', 'void'),
  \ javaapi#method(0,1,'append(', 'char)', 'void'),
  \ javaapi#method(0,1,'append(', 'String)', 'void'),
  \ javaapi#method(0,1,'append(', 'char[], int, int)', 'void'),
  \ javaapi#method(0,1,'append(', 'XMLString)', 'void'),
  \ ])

call javaapi#class('XMLSymbols', '', [
  \ javaapi#field(1,1,'EMPTY_STRING', 'String'),
  \ javaapi#field(1,1,'PREFIX_XML', 'String'),
  \ javaapi#field(1,1,'PREFIX_XMLNS', 'String'),
  \ javaapi#field(1,1,'fANYSymbol', 'String'),
  \ javaapi#field(1,1,'fCDATASymbol', 'String'),
  \ javaapi#field(1,1,'fIDSymbol', 'String'),
  \ javaapi#field(1,1,'fIDREFSymbol', 'String'),
  \ javaapi#field(1,1,'fIDREFSSymbol', 'String'),
  \ javaapi#field(1,1,'fENTITYSymbol', 'String'),
  \ javaapi#field(1,1,'fENTITIESSymbol', 'String'),
  \ javaapi#field(1,1,'fNMTOKENSymbol', 'String'),
  \ javaapi#field(1,1,'fNMTOKENSSymbol', 'String'),
  \ javaapi#field(1,1,'fNOTATIONSymbol', 'String'),
  \ javaapi#field(1,1,'fENUMERATIONSymbol', 'String'),
  \ javaapi#field(1,1,'fIMPLIEDSymbol', 'String'),
  \ javaapi#field(1,1,'fREQUIREDSymbol', 'String'),
  \ javaapi#field(1,1,'fFIXEDSymbol', 'String'),
  \ javaapi#method(0,1,'XMLSymbols(', ')', ''),
  \ ])

