call javaapi#namespace('com.sun.rowset.internal')

call javaapi#class('BaseRow', 'Cloneable', [
  \ javaapi#method(0,'BaseRow(', ')', 'public'),
  \ javaapi#method(0,'getOrigRow(', ')', 'Object[]'),
  \ javaapi#method(0,'getColumnObject(', 'int) throws SQLException', 'Object'),
  \ javaapi#method(0,'setColumnObject(', 'int, Object) throws SQLException', 'void'),
  \ ])

call javaapi#class('CachedRowSetReader', 'Serializable', [
  \ javaapi#method(0,'CachedRowSetReader(', ')', 'public'),
  \ javaapi#method(0,'readData(', 'RowSetInternal) throws SQLException', 'void'),
  \ javaapi#method(0,'reset(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'connect(', 'RowSetInternal) throws SQLException', 'Connection'),
  \ javaapi#method(0,'setStartPosition(', 'int)', 'void'),
  \ ])

call javaapi#class('CachedRowSetWriter', 'Serializable', [
  \ javaapi#method(0,'CachedRowSetWriter(', ')', 'public'),
  \ javaapi#method(0,'writeData(', 'RowSetInternal) throws SQLException', 'boolean'),
  \ javaapi#method(0,'setReader(', 'CachedRowSetReader) throws SQLException', 'void'),
  \ javaapi#method(0,'getReader(', ') throws SQLException', 'CachedRowSetReader'),
  \ javaapi#method(0,'commit(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'commit(', 'CachedRowSetImpl, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,'rollback(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'rollback(', 'Savepoint) throws SQLException', 'void'),
  \ ])

call javaapi#class('InsertRow', 'BaseRow', [
  \ javaapi#method(0,'InsertRow(', 'int)', 'public'),
  \ javaapi#method(0,'isCompleteRow(', 'RowSetMetaData) throws SQLException', 'boolean'),
  \ javaapi#method(0,'initInsertRow(', ')', 'void'),
  \ javaapi#method(0,'getColumnObject(', 'int) throws SQLException', 'Object'),
  \ javaapi#method(0,'setColumnObject(', 'int, Object)', 'void'),
  \ ])

call javaapi#class('Row', 'BaseRow', [
  \ javaapi#method(0,'Row(', 'int)', 'public'),
  \ javaapi#method(0,'Row(', 'int, Object[])', 'public'),
  \ javaapi#method(0,'initColumnObject(', 'int, Object)', 'void'),
  \ javaapi#method(0,'setColumnObject(', 'int, Object)', 'void'),
  \ javaapi#method(0,'getColumnObject(', 'int) throws SQLException', 'Object'),
  \ javaapi#method(0,'getColUpdated(', 'int)', 'boolean'),
  \ javaapi#method(0,'setDeleted(', ')', 'void'),
  \ javaapi#method(0,'getDeleted(', ')', 'boolean'),
  \ javaapi#method(0,'clearDeleted(', ')', 'void'),
  \ javaapi#method(0,'setInserted(', ')', 'void'),
  \ javaapi#method(0,'getInserted(', ')', 'boolean'),
  \ javaapi#method(0,'clearInserted(', ')', 'void'),
  \ javaapi#method(0,'getUpdated(', ')', 'boolean'),
  \ javaapi#method(0,'setUpdated(', ')', 'void'),
  \ javaapi#method(0,'clearUpdated(', ')', 'void'),
  \ javaapi#method(0,'moveCurrentToOrig(', ')', 'void'),
  \ javaapi#method(0,'getCurrentRow(', ')', 'BaseRow'),
  \ ])

call javaapi#class('SyncResolverImpl', 'CachedRowSetImpl', [
  \ javaapi#method(0,'SyncResolverImpl(', ') throws SQLException', 'public'),
  \ javaapi#method(0,'getStatus(', ')', 'int'),
  \ javaapi#method(0,'getConflictValue(', 'int) throws SQLException', 'Object'),
  \ javaapi#method(0,'getConflictValue(', 'String) throws SQLException', 'Object'),
  \ javaapi#method(0,'setResolvedValue(', 'int, Object) throws SQLException', 'void'),
  \ javaapi#method(0,'setResolvedValue(', 'String, Object) throws SQLException', 'void'),
  \ javaapi#method(0,'nextConflict(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'previousConflict(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'setCommand(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,'populate(', 'ResultSet) throws SQLException', 'void'),
  \ javaapi#method(0,'execute(', 'Connection) throws SQLException', 'void'),
  \ javaapi#method(0,'acceptChanges(', ') throws SyncProviderException', 'void'),
  \ javaapi#method(0,'acceptChanges(', 'Connection) throws SyncProviderException', 'void'),
  \ javaapi#method(0,'restoreOriginal(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'release(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'undoDelete(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'undoInsert(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'undoUpdate(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'createShared(', ') throws SQLException', 'RowSet'),
  \ javaapi#method(0,'createCopy(', ') throws SQLException', 'CachedRowSet'),
  \ javaapi#method(0,'createCopySchema(', ') throws SQLException', 'CachedRowSet'),
  \ javaapi#method(0,'createCopyNoConstraints(', ') throws SQLException', 'CachedRowSet'),
  \ javaapi#method(0,'toCollection(', ') throws SQLException', 'Collection'),
  \ javaapi#method(0,'toCollection(', 'int) throws SQLException', 'Collection'),
  \ javaapi#method(0,'toCollection(', 'String) throws SQLException', 'Collection'),
  \ javaapi#method(0,'getSyncProvider(', ') throws SQLException', 'SyncProvider'),
  \ javaapi#method(0,'setSyncProvider(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,'execute(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'next(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'close(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'wasNull(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'getString(', 'int) throws SQLException', 'String'),
  \ javaapi#method(0,'getBoolean(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,'getByte(', 'int) throws SQLException', 'byte'),
  \ javaapi#method(0,'getShort(', 'int) throws SQLException', 'short'),
  \ javaapi#method(0,'getInt(', 'int) throws SQLException', 'int'),
  \ javaapi#method(0,'getLong(', 'int) throws SQLException', 'long'),
  \ javaapi#method(0,'getFloat(', 'int) throws SQLException', 'float'),
  \ javaapi#method(0,'getDouble(', 'int) throws SQLException', 'double'),
  \ javaapi#method(0,'getBigDecimal(', 'int, int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,'getBytes(', 'int) throws SQLException', 'byte[]'),
  \ javaapi#method(0,'getDate(', 'int) throws SQLException', 'Date'),
  \ javaapi#method(0,'getTime(', 'int) throws SQLException', 'Time'),
  \ javaapi#method(0,'getTimestamp(', 'int) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,'getAsciiStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,'getUnicodeStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,'getBinaryStream(', 'int) throws SQLException', 'InputStream'),
  \ javaapi#method(0,'getString(', 'String) throws SQLException', 'String'),
  \ javaapi#method(0,'getBoolean(', 'String) throws SQLException', 'boolean'),
  \ javaapi#method(0,'getByte(', 'String) throws SQLException', 'byte'),
  \ javaapi#method(0,'getShort(', 'String) throws SQLException', 'short'),
  \ javaapi#method(0,'getInt(', 'String) throws SQLException', 'int'),
  \ javaapi#method(0,'getLong(', 'String) throws SQLException', 'long'),
  \ javaapi#method(0,'getFloat(', 'String) throws SQLException', 'float'),
  \ javaapi#method(0,'getDouble(', 'String) throws SQLException', 'double'),
  \ javaapi#method(0,'getBigDecimal(', 'String, int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,'getBytes(', 'String) throws SQLException', 'byte[]'),
  \ javaapi#method(0,'getDate(', 'String) throws SQLException', 'Date'),
  \ javaapi#method(0,'getTime(', 'String) throws SQLException', 'Time'),
  \ javaapi#method(0,'getTimestamp(', 'String) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,'getAsciiStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,'getUnicodeStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,'getBinaryStream(', 'String) throws SQLException', 'InputStream'),
  \ javaapi#method(0,'getWarnings(', ')', 'SQLWarning'),
  \ javaapi#method(0,'clearWarnings(', ')', 'void'),
  \ javaapi#method(0,'getCursorName(', ') throws SQLException', 'String'),
  \ javaapi#method(0,'getMetaData(', ') throws SQLException', 'ResultSetMetaData'),
  \ javaapi#method(0,'getObject(', 'int) throws SQLException', 'Object'),
  \ javaapi#method(0,'getObject(', 'String) throws SQLException', 'Object'),
  \ javaapi#method(0,'findColumn(', 'String) throws SQLException', 'int'),
  \ javaapi#method(0,'getCharacterStream(', 'int) throws SQLException', 'Reader'),
  \ javaapi#method(0,'getCharacterStream(', 'String) throws SQLException', 'Reader'),
  \ javaapi#method(0,'getBigDecimal(', 'int) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,'getBigDecimal(', 'String) throws SQLException', 'BigDecimal'),
  \ javaapi#method(0,'size(', ')', 'int'),
  \ javaapi#method(0,'isBeforeFirst(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'isAfterLast(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'isFirst(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'isLast(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'beforeFirst(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'afterLast(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'first(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'last(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'getRow(', ') throws SQLException', 'int'),
  \ javaapi#method(0,'absolute(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,'relative(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,'previous(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'rowUpdated(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'columnUpdated(', 'int) throws SQLException', 'boolean'),
  \ javaapi#method(0,'columnUpdated(', 'String) throws SQLException', 'boolean'),
  \ javaapi#method(0,'rowInserted(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'rowDeleted(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'updateNull(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateBoolean(', 'int, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,'updateByte(', 'int, byte) throws SQLException', 'void'),
  \ javaapi#method(0,'updateShort(', 'int, short) throws SQLException', 'void'),
  \ javaapi#method(0,'updateInt(', 'int, int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateLong(', 'int, long) throws SQLException', 'void'),
  \ javaapi#method(0,'updateFloat(', 'int, float) throws SQLException', 'void'),
  \ javaapi#method(0,'updateDouble(', 'int, double) throws SQLException', 'void'),
  \ javaapi#method(0,'updateBigDecimal(', 'int, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,'updateString(', 'int, String) throws SQLException', 'void'),
  \ javaapi#method(0,'updateBytes(', 'int, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,'updateDate(', 'int, Date) throws SQLException', 'void'),
  \ javaapi#method(0,'updateTime(', 'int, Time) throws SQLException', 'void'),
  \ javaapi#method(0,'updateTimestamp(', 'int, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,'updateAsciiStream(', 'int, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateBinaryStream(', 'int, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateCharacterStream(', 'int, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateObject(', 'int, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateObject(', 'int, Object) throws SQLException', 'void'),
  \ javaapi#method(0,'updateNull(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,'updateBoolean(', 'String, boolean) throws SQLException', 'void'),
  \ javaapi#method(0,'updateByte(', 'String, byte) throws SQLException', 'void'),
  \ javaapi#method(0,'updateShort(', 'String, short) throws SQLException', 'void'),
  \ javaapi#method(0,'updateInt(', 'String, int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateLong(', 'String, long) throws SQLException', 'void'),
  \ javaapi#method(0,'updateFloat(', 'String, float) throws SQLException', 'void'),
  \ javaapi#method(0,'updateDouble(', 'String, double) throws SQLException', 'void'),
  \ javaapi#method(0,'updateBigDecimal(', 'String, BigDecimal) throws SQLException', 'void'),
  \ javaapi#method(0,'updateString(', 'String, String) throws SQLException', 'void'),
  \ javaapi#method(0,'updateBytes(', 'String, byte[]) throws SQLException', 'void'),
  \ javaapi#method(0,'updateDate(', 'String, Date) throws SQLException', 'void'),
  \ javaapi#method(0,'updateTime(', 'String, Time) throws SQLException', 'void'),
  \ javaapi#method(0,'updateTimestamp(', 'String, Timestamp) throws SQLException', 'void'),
  \ javaapi#method(0,'updateAsciiStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateBinaryStream(', 'String, InputStream, int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateCharacterStream(', 'String, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateObject(', 'String, Object, int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateObject(', 'String, Object) throws SQLException', 'void'),
  \ javaapi#method(0,'insertRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'updateRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'deleteRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'refreshRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'cancelRowUpdates(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'moveToInsertRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'moveToCurrentRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'getStatement(', ') throws SQLException', 'Statement'),
  \ javaapi#method(0,'getObject(', 'int, Map<String, Class<?>>) throws SQLException', 'Object'),
  \ javaapi#method(0,'getRef(', 'int) throws SQLException', 'Ref'),
  \ javaapi#method(0,'getBlob(', 'int) throws SQLException', 'Blob'),
  \ javaapi#method(0,'getClob(', 'int) throws SQLException', 'Clob'),
  \ javaapi#method(0,'getArray(', 'int) throws SQLException', 'Array'),
  \ javaapi#method(0,'getObject(', 'String, Map<String, Class<?>>) throws SQLException', 'Object'),
  \ javaapi#method(0,'getRef(', 'String) throws SQLException', 'Ref'),
  \ javaapi#method(0,'getBlob(', 'String) throws SQLException', 'Blob'),
  \ javaapi#method(0,'getClob(', 'String) throws SQLException', 'Clob'),
  \ javaapi#method(0,'getArray(', 'String) throws SQLException', 'Array'),
  \ javaapi#method(0,'getDate(', 'int, Calendar) throws SQLException', 'Date'),
  \ javaapi#method(0,'getDate(', 'String, Calendar) throws SQLException', 'Date'),
  \ javaapi#method(0,'getTime(', 'int, Calendar) throws SQLException', 'Time'),
  \ javaapi#method(0,'getTime(', 'String, Calendar) throws SQLException', 'Time'),
  \ javaapi#method(0,'getTimestamp(', 'int, Calendar) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,'getTimestamp(', 'String, Calendar) throws SQLException', 'Timestamp'),
  \ javaapi#method(0,'getConnection(', ') throws SQLException', 'Connection'),
  \ javaapi#method(0,'setMetaData(', 'RowSetMetaData) throws SQLException', 'void'),
  \ javaapi#method(0,'getOriginal(', ') throws SQLException', 'ResultSet'),
  \ javaapi#method(0,'getOriginalRow(', ') throws SQLException', 'ResultSet'),
  \ javaapi#method(0,'setOriginalRow(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'setOriginal(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'getTableName(', ') throws SQLException', 'String'),
  \ javaapi#method(0,'setTableName(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,'getKeyColumns(', ') throws SQLException', 'int[]'),
  \ javaapi#method(0,'setKeyColumns(', 'int[]) throws SQLException', 'void'),
  \ javaapi#method(0,'updateRef(', 'int, Ref) throws SQLException', 'void'),
  \ javaapi#method(0,'updateRef(', 'String, Ref) throws SQLException', 'void'),
  \ javaapi#method(0,'updateClob(', 'int, Clob) throws SQLException', 'void'),
  \ javaapi#method(0,'updateClob(', 'String, Clob) throws SQLException', 'void'),
  \ javaapi#method(0,'updateBlob(', 'int, Blob) throws SQLException', 'void'),
  \ javaapi#method(0,'updateBlob(', 'String, Blob) throws SQLException', 'void'),
  \ javaapi#method(0,'updateArray(', 'int, Array) throws SQLException', 'void'),
  \ javaapi#method(0,'updateArray(', 'String, Array) throws SQLException', 'void'),
  \ javaapi#method(0,'getURL(', 'int) throws SQLException', 'URL'),
  \ javaapi#method(0,'getURL(', 'String) throws SQLException', 'URL'),
  \ javaapi#method(0,'getRowSetWarnings(', ')', 'RowSetWarning'),
  \ javaapi#method(0,'commit(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'rollback(', ') throws SQLException', 'void'),
  \ javaapi#method(0,'rollback(', 'Savepoint) throws SQLException', 'void'),
  \ javaapi#method(0,'unsetMatchColumn(', 'int[]) throws SQLException', 'void'),
  \ javaapi#method(0,'unsetMatchColumn(', 'String[]) throws SQLException', 'void'),
  \ javaapi#method(0,'getMatchColumnNames(', ') throws SQLException', 'String[]'),
  \ javaapi#method(0,'getMatchColumnIndexes(', ') throws SQLException', 'int[]'),
  \ javaapi#method(0,'setMatchColumn(', 'int[]) throws SQLException', 'void'),
  \ javaapi#method(0,'setMatchColumn(', 'String[]) throws SQLException', 'void'),
  \ javaapi#method(0,'setMatchColumn(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,'setMatchColumn(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,'unsetMatchColumn(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,'unsetMatchColumn(', 'String) throws SQLException', 'void'),
  \ javaapi#method(0,'rowSetPopulated(', 'RowSetEvent, int) throws SQLException', 'void'),
  \ javaapi#method(0,'populate(', 'ResultSet, int) throws SQLException', 'void'),
  \ javaapi#method(0,'nextPage(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'setPageSize(', 'int) throws SQLException', 'void'),
  \ javaapi#method(0,'getPageSize(', ')', 'int'),
  \ javaapi#method(0,'previousPage(', ') throws SQLException', 'boolean'),
  \ javaapi#method(0,'updateNCharacterStream(', 'int, Reader, int) throws SQLException', 'void'),
  \ javaapi#method(0,'updateNCharacterStream(', 'String, Reader, int) throws SQLException', 'void'),
  \ ])

call javaapi#class('WebRowSetXmlReader', 'Serializable', [
  \ javaapi#method(0,'WebRowSetXmlReader(', ')', 'public'),
  \ javaapi#method(0,'readXML(', 'WebRowSet, Reader) throws SQLException', 'void'),
  \ javaapi#method(0,'readXML(', 'WebRowSet, InputStream) throws SQLException', 'void'),
  \ javaapi#method(0,'readData(', 'RowSetInternal)', 'void'),
  \ ])

call javaapi#class('WebRowSetXmlWriter', 'Serializable', [
  \ javaapi#method(0,'WebRowSetXmlWriter(', ')', 'public'),
  \ javaapi#method(0,'writeXML(', 'WebRowSet, Writer) throws SQLException', 'void'),
  \ javaapi#method(0,'writeXML(', 'WebRowSet, OutputStream) throws SQLException', 'void'),
  \ javaapi#method(0,'writeData(', 'RowSetInternal)', 'boolean'),
  \ ])

call javaapi#class('XmlErrorHandler', 'DefaultHandler', [
  \ javaapi#field(0,'errorCounter', 'int'),
  \ javaapi#method(0,'XmlErrorHandler(', ')', 'public'),
  \ javaapi#method(0,'error(', 'SAXParseException) throws SAXException', 'void'),
  \ javaapi#method(0,'fatalError(', 'SAXParseException) throws SAXException', 'void'),
  \ javaapi#method(0,'warning(', 'SAXParseException) throws SAXException', 'void'),
  \ ])

call javaapi#class('XmlReaderContentHandler', 'DefaultHandler', [
  \ javaapi#method(0,'XmlReaderContentHandler(', 'RowSet)', 'public'),
  \ javaapi#method(0,'startDocument(', ') throws SAXException', 'void'),
  \ javaapi#method(0,'endDocument(', ') throws SAXException', 'void'),
  \ javaapi#method(0,'startElement(', 'String, String, String, Attributes) throws SAXException', 'void'),
  \ javaapi#method(0,'endElement(', 'String, String, String) throws SAXException', 'void'),
  \ javaapi#method(0,'characters(', 'char[], int, int) throws SAXException', 'void'),
  \ javaapi#method(0,'error(', 'SAXParseException) throws SAXParseException', 'void'),
  \ javaapi#method(0,'warning(', 'SAXParseException) throws SAXParseException', 'void'),
  \ javaapi#method(0,'notationDecl(', 'String, String, String)', 'void'),
  \ javaapi#method(0,'unparsedEntityDecl(', 'String, String, String, String)', 'void'),
  \ ])

call javaapi#class('XmlResolver', 'EntityResolver', [
  \ javaapi#method(0,'XmlResolver(', ')', 'public'),
  \ javaapi#method(0,'resolveEntity(', 'String, String)', 'InputSource'),
  \ ])

