call javaapi#namespace('com.sun.xml.internal.ws.policy.privateutil')

call javaapi#class('LocalizationMessages', '', [
  \ javaapi#method(0,1,'LocalizationMessages(', ')', ''),
  \ javaapi#method(1,1,'localizableWSP_0017_UNABLE_TO_ACCESS_POLICY_SOURCE_MODEL_PLUS_REASON(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0017_UNABLE_TO_ACCESS_POLICY_SOURCE_MODEL_PLUS_REASON(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0028_SERVICE_PROVIDER_COULD_NOT_BE_INSTANTIATED(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0028_SERVICE_PROVIDER_COULD_NOT_BE_INSTANTIATED(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0081_UNABLE_TO_INSERT_CHILD(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0081_UNABLE_TO_INSERT_CHILD(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0018_UNABLE_TO_ACCESS_POLICY_SOURCE_MODEL(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0018_UNABLE_TO_ACCESS_POLICY_SOURCE_MODEL(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0090_UNEXPECTED_ELEMENT(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0090_UNEXPECTED_ELEMENT(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0043_POLICY_MODEL_TRANSLATION_ERROR_INPUT_PARAM_NULL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0043_POLICY_MODEL_TRANSLATION_ERROR_INPUT_PARAM_NULL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0055_NO_ALTERNATIVE_COMBINATIONS_CREATED(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0055_NO_ALTERNATIVE_COMBINATIONS_CREATED(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0072_DIGEST_MUST_NOT_BE_NULL_WHEN_ALG_DEFINED(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0072_DIGEST_MUST_NOT_BE_NULL_WHEN_ALG_DEFINED(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0016_UNABLE_TO_CLONE_POLICY_SOURCE_MODEL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0016_UNABLE_TO_CLONE_POLICY_SOURCE_MODEL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0058_MULTIPLE_POLICY_IDS_NOT_ALLOWED(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0058_MULTIPLE_POLICY_IDS_NOT_ALLOWED(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0061_METHOD_INVOCATION_FAILED(', 'Object, Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0061_METHOD_INVOCATION_FAILED(', 'Object, Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0048_POLICY_ELEMENT_EXPECTED_FIRST(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0048_POLICY_ELEMENT_EXPECTED_FIRST(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0068_FAILED_TO_UNMARSHALL_POLICY_EXPRESSION(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0068_FAILED_TO_UNMARSHALL_POLICY_EXPRESSION(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0029_SERVICE_PORT_OPERATION_PARAM_MUST_NOT_BE_NULL(', 'Object, Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0029_SERVICE_PORT_OPERATION_PARAM_MUST_NOT_BE_NULL(', 'Object, Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0080_IMPLEMENTATION_EXPECTED_NOT_NULL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0080_IMPLEMENTATION_EXPECTED_NOT_NULL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0051_OPERATION_NOT_SUPPORTED_FOR_THIS_BUT_ASSERTION_RELATED_NODE_TYPE(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0051_OPERATION_NOT_SUPPORTED_FOR_THIS_BUT_ASSERTION_RELATED_NODE_TYPE(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0008_UNEXPECTED_CHILD_MODEL_TYPE(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0008_UNEXPECTED_CHILD_MODEL_TYPE(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0023_UNEXPECTED_ERROR_WHILE_CLOSING_RESOURCE(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0023_UNEXPECTED_ERROR_WHILE_CLOSING_RESOURCE(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0091_END_ELEMENT_NO_MATCH(', 'Object, Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0091_END_ELEMENT_NO_MATCH(', 'Object, Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0001_UNSUPPORTED_MODEL_NODE_TYPE(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0001_UNSUPPORTED_MODEL_NODE_TYPE(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0053_INVALID_CLIENT_SIDE_ALTERNATIVE(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0053_INVALID_CLIENT_SIDE_ALTERNATIVE(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0087_UNKNOWN_EVENT(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0087_UNKNOWN_EVENT(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0065_INCONSISTENCY_IN_POLICY_SOURCE_MODEL(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0065_INCONSISTENCY_IN_POLICY_SOURCE_MODEL(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0032_SERVICE_CAN_NOT_BE_NULL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0032_SERVICE_CAN_NOT_BE_NULL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0093_INVALID_URI(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0093_INVALID_URI(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0045_POLICY_MAP_KEY_MUST_NOT_BE_NULL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0045_POLICY_MAP_KEY_MUST_NOT_BE_NULL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0079_ERROR_WHILE_RFC_2396_UNESCAPING(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0079_ERROR_WHILE_RFC_2396_UNESCAPING(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0064_INITIAL_POLICY_COLLECTION_MUST_NOT_BE_EMPTY(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0064_INITIAL_POLICY_COLLECTION_MUST_NOT_BE_EMPTY(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0044_POLICY_MAP_MUTATOR_ALREADY_CONNECTED(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0044_POLICY_MAP_MUTATOR_ALREADY_CONNECTED(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0015_UNABLE_TO_INSTANTIATE_DIGEST_ALG_URI_FIELD(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0015_UNABLE_TO_INSTANTIATE_DIGEST_ALG_URI_FIELD(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0046_POLICY_MAP_KEY_HANDLER_NOT_SET(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0046_POLICY_MAP_KEY_HANDLER_NOT_SET(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0012_UNABLE_TO_UNMARSHALL_POLICY_MALFORMED_URI(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0012_UNABLE_TO_UNMARSHALL_POLICY_MALFORMED_URI(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0003_UNMARSHALLING_FAILED_END_TAG_DOES_NOT_MATCH(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0003_UNMARSHALLING_FAILED_END_TAG_DOES_NOT_MATCH(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0007_UNEXPECTED_MODEL_NODE_TYPE_FOUND(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0007_UNEXPECTED_MODEL_NODE_TYPE_FOUND(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0086_FAILED_CREATE_READER(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0086_FAILED_CREATE_READER(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0077_ASSERTION_CREATOR_DOES_NOT_SUPPORT_ANY_URI(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0077_ASSERTION_CREATOR_DOES_NOT_SUPPORT_ANY_URI(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0082_NO_SUBJECT_TYPE(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0082_NO_SUBJECT_TYPE(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0089_EXPECTED_ELEMENT(', 'Object, Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0089_EXPECTED_ELEMENT(', 'Object, Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0031_SERVICE_PARAM_MUST_NOT_BE_NULL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0031_SERVICE_PARAM_MUST_NOT_BE_NULL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0030_SERVICE_PORT_OPERATION_FAULT_MSG_PARAM_MUST_NOT_BE_NULL(', 'Object, Object, Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0030_SERVICE_PORT_OPERATION_FAULT_MSG_PARAM_MUST_NOT_BE_NULL(', 'Object, Object, Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0040_POLICY_REFERENCE_URI_ATTR_NOT_FOUND(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0040_POLICY_REFERENCE_URI_ATTR_NOT_FOUND(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0034_REMOVE_OPERATION_NOT_SUPPORTED(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0034_REMOVE_OPERATION_NOT_SUPPORTED(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0084_MESSAGE_TYPE_NO_MESSAGE(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0084_MESSAGE_TYPE_NO_MESSAGE(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0004_UNEXPECTED_VISIBILITY_ATTR_VALUE(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0004_UNEXPECTED_VISIBILITY_ATTR_VALUE(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0074_CANNOT_CREATE_ASSERTION_BAD_TYPE(', 'Object, Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0074_CANNOT_CREATE_ASSERTION_BAD_TYPE(', 'Object, Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0052_NUMBER_OF_ALTERNATIVE_COMBINATIONS_CREATED(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0052_NUMBER_OF_ALTERNATIVE_COMBINATIONS_CREATED(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0037_PRIVATE_CONSTRUCTOR_DOES_NOT_TAKE_NULL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0037_PRIVATE_CONSTRUCTOR_DOES_NOT_TAKE_NULL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0067_ILLEGAL_CFG_FILE_SYNTAX(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0067_ILLEGAL_CFG_FILE_SYNTAX(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0085_MESSAGE_FAULT_NO_NAME(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0085_MESSAGE_FAULT_NO_NAME(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0050_OPERATION_NOT_SUPPORTED_FOR_THIS_BUT_POLICY_REFERENCE_NODE_TYPE(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0050_OPERATION_NOT_SUPPORTED_FOR_THIS_BUT_POLICY_REFERENCE_NODE_TYPE(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0042_POLICY_REFERENCE_NODE_EXPECTED_INSTEAD_OF(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0042_POLICY_REFERENCE_NODE_EXPECTED_INSTEAD_OF(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0014_UNABLE_TO_INSTANTIATE_READER_FOR_STORAGE(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0014_UNABLE_TO_INSTANTIATE_READER_FOR_STORAGE(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0054_NO_MORE_ELEMS_IN_POLICY_MAP(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0054_NO_MORE_ELEMS_IN_POLICY_MAP(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0083_MESSAGE_TYPE_NULL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0083_MESSAGE_TYPE_NULL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0011_UNABLE_TO_UNMARSHALL_POLICY_XML_ELEM_EXPECTED(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0011_UNABLE_TO_UNMARSHALL_POLICY_XML_ELEM_EXPECTED(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0025_SPI_FAIL_SERVICE_MSG(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0025_SPI_FAIL_SERVICE_MSG(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0094_INVALID_URN(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0094_INVALID_URN(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0026_SINGLE_EMPTY_ALTERNATIVE_COMBINATION_CREATED(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0026_SINGLE_EMPTY_ALTERNATIVE_COMBINATION_CREATED(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0078_ASSERTION_CREATOR_DISCOVERED(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0078_ASSERTION_CREATOR_DISCOVERED(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0041_POLICY_REFERENCE_NODE_FOUND_WITH_NO_POLICY_REFERENCE_IN_IT(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0041_POLICY_REFERENCE_NODE_FOUND_WITH_NO_POLICY_REFERENCE_IN_IT(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0039_POLICY_SRC_MODEL_INPUT_PARAMETER_MUST_NOT_BE_NULL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0039_POLICY_SRC_MODEL_INPUT_PARAMETER_MUST_NOT_BE_NULL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0070_ERROR_REGISTERING_ASSERTION_CREATOR(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0070_ERROR_REGISTERING_ASSERTION_CREATOR(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0036_PRIVATE_METHOD_DOES_NOT_ACCEPT_NULL_OR_EMPTY_COLLECTION(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0036_PRIVATE_METHOD_DOES_NOT_ACCEPT_NULL_OR_EMPTY_COLLECTION(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0027_SERVICE_PROVIDER_NOT_FOUND(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0027_SERVICE_PROVIDER_NOT_FOUND(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0056_NEITHER_NULL_NOR_EMPTY_POLICY_COLLECTION_EXPECTED(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0056_NEITHER_NULL_NOR_EMPTY_POLICY_COLLECTION_EXPECTED(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0022_STORAGE_TYPE_NOT_SUPPORTED(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0022_STORAGE_TYPE_NOT_SUPPORTED(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0095_INVALID_BOOLEAN_VALUE(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0095_INVALID_BOOLEAN_VALUE(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0059_MULTIPLE_ATTRS_WITH_SAME_NAME_DETECTED_FOR_ASSERTION(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0059_MULTIPLE_ATTRS_WITH_SAME_NAME_DETECTED_FOR_ASSERTION(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0047_POLICY_IS_NULL_RETURNING(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0047_POLICY_IS_NULL_RETURNING(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0088_FAILED_PARSE(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0088_FAILED_PARSE(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0005_UNEXPECTED_POLICY_ELEMENT_FOUND_IN_ASSERTION_PARAM(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0005_UNEXPECTED_POLICY_ELEMENT_FOUND_IN_ASSERTION_PARAM(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0009_UNEXPECTED_CDATA_ON_SOURCE_MODEL_NODE(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0009_UNEXPECTED_CDATA_ON_SOURCE_MODEL_NODE(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0024_SPI_FAIL_SERVICE_URL_LINE_MSG(', 'Object, Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0024_SPI_FAIL_SERVICE_URL_LINE_MSG(', 'Object, Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0057_N_ALTERNATIVE_COMBINATIONS_M_POLICY_ALTERNATIVES_CREATED(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0057_N_ALTERNATIVE_COMBINATIONS_M_POLICY_ALTERNATIVES_CREATED(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0020_SUBJECT_PARAM_MUST_NOT_BE_NULL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0020_SUBJECT_PARAM_MUST_NOT_BE_NULL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0071_ERROR_MULTIPLE_ASSERTION_CREATORS_FOR_NAMESPACE(', 'Object, Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0071_ERROR_MULTIPLE_ASSERTION_CREATORS_FOR_NAMESPACE(', 'Object, Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0038_POLICY_TO_ATTACH_MUST_NOT_BE_NULL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0038_POLICY_TO_ATTACH_MUST_NOT_BE_NULL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0033_SERVICE_AND_PORT_PARAM_MUST_NOT_BE_NULL(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0033_SERVICE_AND_PORT_PARAM_MUST_NOT_BE_NULL(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0060_POLICY_ELEMENT_TYPE_UNKNOWN(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0060_POLICY_ELEMENT_TYPE_UNKNOWN(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0013_UNABLE_TO_SET_PARENT_MODEL_ON_ROOT(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0013_UNABLE_TO_SET_PARENT_MODEL_ON_ROOT(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0019_SUBOPTIMAL_ALTERNATIVE_SELECTED(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0019_SUBOPTIMAL_ALTERNATIVE_SELECTED(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0073_CREATE_CHILD_NODE_OPERATION_NOT_SUPPORTED(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0073_CREATE_CHILD_NODE_OPERATION_NOT_SUPPORTED(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0002_UNRECOGNIZED_SCOPE_TYPE(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0002_UNRECOGNIZED_SCOPE_TYPE(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0062_INPUT_PARAMS_MUST_NOT_BE_NULL(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0062_INPUT_PARAMS_MUST_NOT_BE_NULL(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0063_ERROR_WHILE_CONSTRUCTING_EXCEPTION(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0063_ERROR_WHILE_CONSTRUCTING_EXCEPTION(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0021_SUBJECT_AND_POLICY_PARAM_MUST_NOT_BE_NULL(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0021_SUBJECT_AND_POLICY_PARAM_MUST_NOT_BE_NULL(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0075_PROBLEMATIC_ASSERTION_STATE(', 'Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0075_PROBLEMATIC_ASSERTION_STATE(', 'Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0006_UNEXPECTED_MULTIPLE_POLICY_NODES(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0006_UNEXPECTED_MULTIPLE_POLICY_NODES(', ')', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0092_CHARACTER_DATA_UNEXPECTED(', 'Object, Object, Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0092_CHARACTER_DATA_UNEXPECTED(', 'Object, Object, Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0069_EXCEPTION_WHILE_RETRIEVING_EFFECTIVE_POLICY_FOR_KEY(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0069_EXCEPTION_WHILE_RETRIEVING_EFFECTIVE_POLICY_FOR_KEY(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0010_UNEXPANDED_POLICY_REFERENCE_NODE_FOUND_REFERENCING(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0010_UNEXPANDED_POLICY_REFERENCE_NODE_FOUND_REFERENCING(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0035_RECONFIGURE_ALTERNATIVES(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0035_RECONFIGURE_ALTERNATIVES(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0066_ILLEGAL_PROVIDER_CLASSNAME(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0066_ILLEGAL_PROVIDER_CLASSNAME(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0076_NO_SERVICE_PROVIDERS_FOUND(', 'Object)', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0076_NO_SERVICE_PROVIDERS_FOUND(', 'Object)', 'String'),
  \ javaapi#method(1,1,'localizableWSP_0049_PARENT_MODEL_CAN_NOT_BE_CHANGED(', ')', 'Localizable'),
  \ javaapi#method(1,1,'WSP_0049_PARENT_MODEL_CAN_NOT_BE_CHANGED(', ')', 'String'),
  \ ])

call javaapi#class('PolicyLogger', 'Logger', [
  \ javaapi#method(1,1,'getLogger(', 'Class<?>)', 'PolicyLogger'),
  \ ])

call javaapi#class('PolicyUtils', '', [
  \ ])

call javaapi#class('RuntimePolicyUtilsException', 'RuntimeException', [
  \ ])

call javaapi#class('ServiceConfigurationError', 'Error', [
  \ javaapi#method(0,1,'ServiceConfigurationError(', 'String)', ''),
  \ javaapi#method(0,1,'ServiceConfigurationError(', 'Throwable)', ''),
  \ ])

call javaapi#class('ServiceFinder<T>', 'Iterable<T>', [
  \ javaapi#method(1,1,'find(', 'Class<T>)', 'ServiceFinder<T>'),
  \ javaapi#method(0,1,'iterator(', ')', 'Iterator<T>'),
  \ javaapi#method(0,1,'toArray(', ')', 'T[]'),
  \ ])

