call javaapi#namespace('com.sun.xml.internal.stream.writers')

call javaapi#class('UTF8OutputStreamWriter', '', [
  \ javaapi#method(0,'UTF8OutputStreamWriter(', 'OutputStream)', 'public'),
  \ javaapi#method(0,'getEncoding(', ')', 'String'),
  \ javaapi#method(0,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,'write(', 'char[]) throws IOException', 'void'),
  \ javaapi#method(0,'write(', 'char[], int, int) throws IOException', 'void'),
  \ javaapi#method(0,'write(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,'write(', 'String, int, int) throws IOException', 'void'),
  \ javaapi#method(0,'flush(', ') throws IOException', 'void'),
  \ javaapi#method(0,'close(', ') throws IOException', 'void'),
  \ ])

call javaapi#class('WriterUtility', '', [
  \ javaapi#field(1,'START_COMMENT', 'String'),
  \ javaapi#field(1,'END_COMMENT', 'String'),
  \ javaapi#field(1,'DEFAULT_ENCODING', 'String'),
  \ javaapi#field(1,'DEFAULT_XMLDECL', 'String'),
  \ javaapi#field(1,'DEFAULT_XML_VERSION', 'String'),
  \ javaapi#field(1,'CLOSE_START_TAG', 'char'),
  \ javaapi#field(1,'OPEN_START_TAG', 'char'),
  \ javaapi#field(1,'OPEN_END_TAG', 'String'),
  \ javaapi#field(1,'CLOSE_END_TAG', 'char'),
  \ javaapi#field(1,'START_CDATA', 'String'),
  \ javaapi#field(1,'END_CDATA', 'String'),
  \ javaapi#field(1,'CLOSE_EMPTY_ELEMENT', 'String'),
  \ javaapi#field(1,'SPACE', 'String'),
  \ javaapi#field(1,'UTF_8', 'String'),
  \ javaapi#method(0,'WriterUtility(', ')', 'public'),
  \ javaapi#method(0,'WriterUtility(', 'Writer)', 'public'),
  \ javaapi#method(0,'setWriter(', 'Writer)', 'void'),
  \ javaapi#method(0,'setEscapeCharacters(', 'boolean)', 'void'),
  \ javaapi#method(0,'getEscapeCharacters(', ')', 'boolean'),
  \ javaapi#method(0,'writeXMLContent(', 'char[], int, int) throws IOException', 'void'),
  \ javaapi#method(0,'writeXMLContent(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,'writeXMLAttributeValue(', 'String) throws IOException', 'void'),
  \ ])

call javaapi#class('XMLDOMWriterImpl', 'XMLStreamWriter', [
  \ javaapi#method(0,'XMLDOMWriterImpl(', 'DOMResult)', 'public'),
  \ javaapi#method(0,'close(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'flush(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'getNamespaceContext(', ')', 'NamespaceContext'),
  \ javaapi#method(0,'getPrefix(', 'String) throws XMLStreamException', 'String'),
  \ javaapi#method(0,'getProperty(', 'String) throws IllegalArgumentException', 'Object'),
  \ javaapi#method(0,'setDefaultNamespace(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'setNamespaceContext(', 'NamespaceContext) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'setPrefix(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeAttribute(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeAttribute(', 'String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeAttribute(', 'String, String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeCData(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeCharacters(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeCharacters(', 'char[], int, int) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeComment(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeDTD(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeDefaultNamespace(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEmptyElement(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEmptyElement(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEmptyElement(', 'String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEndDocument(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEndElement(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEntityRef(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeNamespace(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeProcessingInstruction(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeProcessingInstruction(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartDocument(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartDocument(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartDocument(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartElement(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartElement(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartElement(', 'String, String, String) throws XMLStreamException', 'void'),
  \ ])

call javaapi#class('XMLEventWriterImpl', 'XMLEventWriter', [
  \ javaapi#method(0,'XMLEventWriterImpl(', 'XMLStreamWriter)', 'public'),
  \ javaapi#method(0,'add(', 'XMLEventReader) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'add(', 'XMLEvent) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'close(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'flush(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'getNamespaceContext(', ')', 'NamespaceContext'),
  \ javaapi#method(0,'getPrefix(', 'String) throws XMLStreamException', 'String'),
  \ javaapi#method(0,'setDefaultNamespace(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'setNamespaceContext(', 'NamespaceContext) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'setPrefix(', 'String, String) throws XMLStreamException', 'void'),
  \ ])

call javaapi#class('XMLOutputSource', '', [
  \ javaapi#method(0,'XMLOutputSource(', ')', 'public'),
  \ ])

call javaapi#class('Attribute', '', [
  \ ])

call javaapi#class('ElementStack', '', [
  \ javaapi#method(0,'ElementStack(', 'XMLStreamWriterImpl)', 'public'),
  \ javaapi#method(0,'push(', 'ElementState)', 'ElementState'),
  \ javaapi#method(0,'push(', 'String, String, String, String, boolean)', 'ElementState'),
  \ javaapi#method(0,'pop(', ')', 'ElementState'),
  \ javaapi#method(0,'clear(', ')', 'void'),
  \ javaapi#method(0,'peek(', ')', 'ElementState'),
  \ javaapi#method(0,'empty(', ')', 'boolean'),
  \ ])

call javaapi#class('ElementState', '', [
  \ javaapi#field(0,'isEmpty', 'boolean'),
  \ javaapi#method(0,'ElementState(', 'XMLStreamWriterImpl)', 'public'),
  \ javaapi#method(0,'ElementState(', 'XMLStreamWriterImpl, String, String, String, String)', 'public'),
  \ javaapi#method(0,'setValues(', 'String, String, String, String, boolean)', 'void'),
  \ ])

call javaapi#class('NamespaceContextImpl', 'NamespaceContext', [
  \ javaapi#method(0,'getNamespaceURI(', 'String)', 'String'),
  \ javaapi#method(0,'getPrefix(', 'String)', 'String'),
  \ javaapi#method(0,'getPrefixes(', 'String)', 'Iterator'),
  \ ])

call javaapi#class('XMLStreamWriterImpl', '', [
  \ javaapi#field(1,'START_COMMENT', 'String'),
  \ javaapi#field(1,'END_COMMENT', 'String'),
  \ javaapi#field(1,'DEFAULT_ENCODING', 'String'),
  \ javaapi#field(1,'DEFAULT_XMLDECL', 'String'),
  \ javaapi#field(1,'DEFAULT_XML_VERSION', 'String'),
  \ javaapi#field(1,'CLOSE_START_TAG', 'char'),
  \ javaapi#field(1,'OPEN_START_TAG', 'char'),
  \ javaapi#field(1,'OPEN_END_TAG', 'String'),
  \ javaapi#field(1,'CLOSE_END_TAG', 'char'),
  \ javaapi#field(1,'START_CDATA', 'String'),
  \ javaapi#field(1,'END_CDATA', 'String'),
  \ javaapi#field(1,'CLOSE_EMPTY_ELEMENT', 'String'),
  \ javaapi#field(1,'SPACE', 'String'),
  \ javaapi#field(1,'UTF_8', 'String'),
  \ javaapi#field(1,'OUTPUTSTREAM_PROPERTY', 'String'),
  \ javaapi#method(0,'XMLStreamWriterImpl(', 'OutputStream, PropertyManager) throws IOException', 'public'),
  \ javaapi#method(0,'XMLStreamWriterImpl(', 'OutputStream, String, PropertyManager) throws IOException', 'public'),
  \ javaapi#method(0,'XMLStreamWriterImpl(', 'Writer, PropertyManager) throws IOException', 'public'),
  \ javaapi#method(0,'XMLStreamWriterImpl(', 'StreamResult, String, PropertyManager) throws IOException', 'public'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'setOutput(', 'StreamResult, String) throws IOException', 'void'),
  \ javaapi#method(0,'canReuse(', ')', 'boolean'),
  \ javaapi#method(0,'setEscapeCharacters(', 'boolean)', 'void'),
  \ javaapi#method(0,'getEscapeCharacters(', ')', 'boolean'),
  \ javaapi#method(0,'close(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'flush(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'getNamespaceContext(', ')', 'NamespaceContext'),
  \ javaapi#method(0,'getPrefix(', 'String) throws XMLStreamException', 'String'),
  \ javaapi#method(0,'getProperty(', 'String) throws IllegalArgumentException', 'Object'),
  \ javaapi#method(0,'setDefaultNamespace(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'setNamespaceContext(', 'NamespaceContext) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'setPrefix(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeAttribute(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeAttribute(', 'String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeAttribute(', 'String, String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeCData(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeCharacters(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeCharacters(', 'char[], int, int) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeComment(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeDTD(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeDefaultNamespace(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEmptyElement(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEmptyElement(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEmptyElement(', 'String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEndDocument(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEndElement(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeEntityRef(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeNamespace(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeProcessingInstruction(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeProcessingInstruction(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartDocument(', ') throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartDocument(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartDocument(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartElement(', 'String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartElement(', 'String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'writeStartElement(', 'String, String, String) throws XMLStreamException', 'void'),
  \ javaapi#method(0,'size(', ')', 'int'),
  \ javaapi#method(0,'isEmpty(', ')', 'boolean'),
  \ javaapi#method(0,'containsKey(', 'Object)', 'boolean'),
  \ javaapi#method(0,'get(', 'Object)', 'Object'),
  \ javaapi#method(0,'entrySet(', ')', 'Set'),
  \ javaapi#method(0,'toString(', ')', 'String'),
  \ javaapi#method(0,'hashCode(', ')', 'int'),
  \ javaapi#method(0,'equals(', 'Object)', 'boolean'),
  \ ])

call javaapi#class('XMLWriter', '', [
  \ javaapi#method(0,'XMLWriter(', 'Writer)', 'public'),
  \ javaapi#method(0,'XMLWriter(', 'Writer, int)', 'public'),
  \ javaapi#method(0,'write(', 'int) throws IOException', 'void'),
  \ javaapi#method(0,'write(', 'char[]) throws IOException', 'void'),
  \ javaapi#method(0,'write(', 'char[], int, int) throws IOException', 'void'),
  \ javaapi#method(0,'write(', 'String, int, int) throws IOException', 'void'),
  \ javaapi#method(0,'write(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,'flush(', ') throws IOException', 'void'),
  \ javaapi#method(0,'reset(', ')', 'void'),
  \ javaapi#method(0,'setWriter(', 'Writer)', 'void'),
  \ javaapi#method(0,'setWriter(', 'Writer, int)', 'void'),
  \ ])

