call javaapi#namespace('sun.net.ftp.impl')

call javaapi#class('DefaultFtpClientProvider', 'FtpClientProvider', [
  \ javaapi#method(0,1,'DefaultFtpClientProvider(', ')', ''),
  \ javaapi#method(0,1,'createFtpClient(', ')', 'FtpClient'),
  \ ])

call javaapi#class('FtpClient', 'FtpClient', [
  \ javaapi#method(0,0,'FtpClient(', ')', ''),
  \ javaapi#method(1,1,'create(', ')', 'FtpClient'),
  \ javaapi#method(0,1,'enablePassiveMode(', 'boolean)', 'FtpClient'),
  \ javaapi#method(0,1,'isPassiveModeEnabled(', ')', 'boolean'),
  \ javaapi#method(0,1,'setConnectTimeout(', 'int)', 'FtpClient'),
  \ javaapi#method(0,1,'getConnectTimeout(', ')', 'int'),
  \ javaapi#method(0,1,'setReadTimeout(', 'int)', 'FtpClient'),
  \ javaapi#method(0,1,'getReadTimeout(', ')', 'int'),
  \ javaapi#method(0,1,'setProxy(', 'Proxy)', 'FtpClient'),
  \ javaapi#method(0,1,'getProxy(', ')', 'Proxy'),
  \ javaapi#method(0,1,'isConnected(', ')', 'boolean'),
  \ javaapi#method(0,1,'getServerAddress(', ')', 'SocketAddress'),
  \ javaapi#method(0,1,'connect(', 'SocketAddress) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'connect(', 'SocketAddress, int) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'login(', 'String, char[]) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'login(', 'String, char[], String) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'close(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'isLoggedIn(', ')', 'boolean'),
  \ javaapi#method(0,1,'changeDirectory(', 'String) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'changeToParentDirectory(', ') throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'getWorkingDirectory(', ') throws FtpProtocolException, IOException', 'String'),
  \ javaapi#method(0,1,'setRestartOffset(', 'long)', 'FtpClient'),
  \ javaapi#method(0,1,'getFile(', 'String, OutputStream) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'getFileStream(', 'String) throws FtpProtocolException, IOException', 'InputStream'),
  \ javaapi#method(0,1,'putFileStream(', 'String, boolean) throws FtpProtocolException, IOException', 'OutputStream'),
  \ javaapi#method(0,1,'putFile(', 'String, InputStream, boolean) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'appendFile(', 'String, InputStream) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'rename(', 'String, String) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'deleteFile(', 'String) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'makeDirectory(', 'String) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'removeDirectory(', 'String) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'noop(', ') throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'getStatus(', 'String) throws FtpProtocolException, IOException', 'String'),
  \ javaapi#method(0,1,'getFeatures(', ') throws FtpProtocolException, IOException', 'List'),
  \ javaapi#method(0,1,'abort(', ') throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'completePending(', ') throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'reInit(', ') throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'setType(', 'TransferType) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'list(', 'String) throws FtpProtocolException, IOException', 'InputStream'),
  \ javaapi#method(0,1,'nameList(', 'String) throws FtpProtocolException, IOException', 'InputStream'),
  \ javaapi#method(0,1,'getSize(', 'String) throws FtpProtocolException, IOException', 'long'),
  \ javaapi#method(0,1,'getLastModified(', 'String) throws FtpProtocolException, IOException', 'Date'),
  \ javaapi#method(0,1,'setDirParser(', 'FtpDirParser)', 'FtpClient'),
  \ javaapi#method(0,1,'listFiles(', 'String) throws FtpProtocolException, IOException', 'Iterator'),
  \ javaapi#method(0,1,'useKerberos(', ') throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'getWelcomeMsg(', ')', 'String'),
  \ javaapi#method(0,1,'getLastReplyCode(', ')', 'FtpReplyCode'),
  \ javaapi#method(0,1,'getLastResponseString(', ')', 'String'),
  \ javaapi#method(0,1,'getLastTransferSize(', ')', 'long'),
  \ javaapi#method(0,1,'getLastFileName(', ')', 'String'),
  \ javaapi#method(0,1,'startSecureSession(', ') throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'endSecureSession(', ') throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'allocate(', 'long) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'structureMount(', 'String) throws FtpProtocolException, IOException', 'FtpClient'),
  \ javaapi#method(0,1,'getSystem(', ') throws FtpProtocolException, IOException', 'String'),
  \ javaapi#method(0,1,'getHelp(', 'String) throws FtpProtocolException, IOException', 'String'),
  \ javaapi#method(0,1,'siteCmd(', 'String) throws FtpProtocolException, IOException', 'FtpClient'),
  \ ])

