call javaapi#namespace('sun.util.calendar')

call javaapi#class('Era', '', [
  \ javaapi#method(0,1,'Era(', 'String, String, long, boolean)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getDisplayName(', 'Locale)', 'String'),
  \ javaapi#method(0,1,'getAbbreviation(', ')', 'String'),
  \ javaapi#method(0,1,'getDiaplayAbbreviation(', 'Locale)', 'String'),
  \ javaapi#method(0,1,'getSince(', 'TimeZone)', 'long'),
  \ javaapi#method(0,1,'getSinceDate(', ')', 'CalendarDate'),
  \ javaapi#method(0,1,'isLocalTime(', ')', 'boolean'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('ImmutableGregorianDate', 'Date', [
  \ javaapi#method(0,1,'getEra(', ')', 'Era'),
  \ javaapi#method(0,1,'setEra(', 'Era)', 'CalendarDate'),
  \ javaapi#method(0,1,'getYear(', ')', 'int'),
  \ javaapi#method(0,1,'setYear(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addYear(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'isLeapYear(', ')', 'boolean'),
  \ javaapi#method(0,1,'getMonth(', ')', 'int'),
  \ javaapi#method(0,1,'setMonth(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addMonth(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getDayOfMonth(', ')', 'int'),
  \ javaapi#method(0,1,'setDayOfMonth(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addDayOfMonth(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getDayOfWeek(', ')', 'int'),
  \ javaapi#method(0,1,'getHours(', ')', 'int'),
  \ javaapi#method(0,1,'setHours(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addHours(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getMinutes(', ')', 'int'),
  \ javaapi#method(0,1,'setMinutes(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addMinutes(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getSeconds(', ')', 'int'),
  \ javaapi#method(0,1,'setSeconds(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addSeconds(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getMillis(', ')', 'int'),
  \ javaapi#method(0,1,'setMillis(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addMillis(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getTimeOfDay(', ')', 'long'),
  \ javaapi#method(0,1,'setDate(', 'int, int, int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addDate(', 'int, int, int)', 'CalendarDate'),
  \ javaapi#method(0,1,'setTimeOfDay(', 'int, int, int, int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addTimeOfDay(', 'int, int, int, int)', 'CalendarDate'),
  \ javaapi#method(0,0,'setTimeOfDay(', 'long)', 'void'),
  \ javaapi#method(0,1,'isNormalized(', ')', 'boolean'),
  \ javaapi#method(0,1,'isStandardTime(', ')', 'boolean'),
  \ javaapi#method(0,1,'setStandardTime(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'isDaylightTime(', ')', 'boolean'),
  \ javaapi#method(0,0,'setLocale(', 'Locale)', 'void'),
  \ javaapi#method(0,1,'getZone(', ')', 'TimeZone'),
  \ javaapi#method(0,1,'setZone(', 'TimeZone)', 'CalendarDate'),
  \ javaapi#method(0,1,'isSameDate(', 'CalendarDate)', 'boolean'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'clone(', ')', 'Object'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,0,'setDayOfWeek(', 'int)', 'void'),
  \ javaapi#method(0,0,'setNormalized(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getZoneOffset(', ')', 'int'),
  \ javaapi#method(0,0,'setZoneOffset(', 'int)', 'void'),
  \ javaapi#method(0,1,'getDaylightSaving(', ')', 'int'),
  \ javaapi#method(0,0,'setDaylightSaving(', 'int)', 'void'),
  \ javaapi#method(0,1,'getNormalizedYear(', ')', 'int'),
  \ javaapi#method(0,1,'setNormalizedYear(', 'int)', 'void'),
  \ ])

call javaapi#class('JulianCalendar', 'BaseCalendar', [
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getCalendarDate(', ')', 'Date'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long)', 'Date'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, CalendarDate)', 'Date'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, TimeZone)', 'Date'),
  \ javaapi#method(0,1,'newCalendarDate(', ')', 'Date'),
  \ javaapi#method(0,1,'newCalendarDate(', 'TimeZone)', 'Date'),
  \ javaapi#method(0,1,'getFixedDate(', 'int, int, int, Date)', 'long'),
  \ javaapi#method(0,1,'getCalendarDateFromFixedDate(', 'CalendarDate, long)', 'void'),
  \ javaapi#method(0,1,'getYearFromFixedDate(', 'long)', 'int'),
  \ javaapi#method(0,1,'getDayOfWeek(', 'CalendarDate)', 'int'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, CalendarDate)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, TimeZone)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', ')', 'CalendarDate'),
  \ javaapi#method(0,1,'newCalendarDate(', 'TimeZone)', 'CalendarDate'),
  \ javaapi#method(0,1,'newCalendarDate(', ')', 'CalendarDate'),
  \ ])

call javaapi#class('LocalGregorianCalendar', 'BaseCalendar', [
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getCalendarDate(', ')', 'Date'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long)', 'Date'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, TimeZone)', 'Date'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, CalendarDate)', 'Date'),
  \ javaapi#method(0,1,'newCalendarDate(', ')', 'Date'),
  \ javaapi#method(0,1,'newCalendarDate(', 'TimeZone)', 'Date'),
  \ javaapi#method(0,1,'validate(', 'CalendarDate)', 'boolean'),
  \ javaapi#method(0,1,'normalize(', 'CalendarDate)', 'boolean'),
  \ javaapi#method(0,1,'isLeapYear(', 'int)', 'boolean'),
  \ javaapi#method(0,1,'isLeapYear(', 'Era, int)', 'boolean'),
  \ javaapi#method(0,1,'getCalendarDateFromFixedDate(', 'CalendarDate, long)', 'void'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, CalendarDate)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, TimeZone)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', ')', 'CalendarDate'),
  \ javaapi#method(0,1,'newCalendarDate(', 'TimeZone)', 'CalendarDate'),
  \ javaapi#method(0,1,'newCalendarDate(', ')', 'CalendarDate'),
  \ ])

call javaapi#class('TzIDOldMapping', '', [
  \ ])

call javaapi#namespace('sun.util.calendar')

call javaapi#class('CalendarUtils', '', [
  \ javaapi#method(0,1,'CalendarUtils(', ')', ''),
  \ javaapi#method(1,1,'isGregorianLeapYear(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'isJulianLeapYear(', 'int)', 'boolean'),
  \ javaapi#method(1,1,'floorDivide(', 'long, long)', 'long'),
  \ javaapi#method(1,1,'floorDivide(', 'int, int)', 'int'),
  \ javaapi#method(1,1,'floorDivide(', 'int, int, int[])', 'int'),
  \ javaapi#method(1,1,'floorDivide(', 'long, int, int[])', 'int'),
  \ javaapi#method(1,1,'mod(', 'long, long)', 'long'),
  \ javaapi#method(1,1,'mod(', 'int, int)', 'int'),
  \ javaapi#method(1,1,'amod(', 'int, int)', 'int'),
  \ javaapi#method(1,1,'amod(', 'long, long)', 'long'),
  \ javaapi#method(1,1,'sprintf0d(', 'StringBuilder, int, int)', 'StringBuilder'),
  \ javaapi#method(1,1,'sprintf0d(', 'StringBuffer, int, int)', 'StringBuffer'),
  \ ])

call javaapi#class('CalendarDate', 'Cloneable', [
  \ javaapi#field(1,1,'FIELD_UNDEFINED', 'int'),
  \ javaapi#field(1,1,'TIME_UNDEFINED', 'long'),
  \ javaapi#method(0,0,'CalendarDate(', ')', ''),
  \ javaapi#method(0,0,'CalendarDate(', 'TimeZone)', ''),
  \ javaapi#method(0,1,'getEra(', ')', 'Era'),
  \ javaapi#method(0,1,'setEra(', 'Era)', 'CalendarDate'),
  \ javaapi#method(0,1,'getYear(', ')', 'int'),
  \ javaapi#method(0,1,'setYear(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addYear(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'isLeapYear(', ')', 'boolean'),
  \ javaapi#method(0,1,'getMonth(', ')', 'int'),
  \ javaapi#method(0,1,'setMonth(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addMonth(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getDayOfMonth(', ')', 'int'),
  \ javaapi#method(0,1,'setDayOfMonth(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addDayOfMonth(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getDayOfWeek(', ')', 'int'),
  \ javaapi#method(0,1,'getHours(', ')', 'int'),
  \ javaapi#method(0,1,'setHours(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addHours(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getMinutes(', ')', 'int'),
  \ javaapi#method(0,1,'setMinutes(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addMinutes(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getSeconds(', ')', 'int'),
  \ javaapi#method(0,1,'setSeconds(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addSeconds(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getMillis(', ')', 'int'),
  \ javaapi#method(0,1,'setMillis(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addMillis(', 'int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getTimeOfDay(', ')', 'long'),
  \ javaapi#method(0,1,'setDate(', 'int, int, int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addDate(', 'int, int, int)', 'CalendarDate'),
  \ javaapi#method(0,1,'setTimeOfDay(', 'int, int, int, int)', 'CalendarDate'),
  \ javaapi#method(0,1,'addTimeOfDay(', 'int, int, int, int)', 'CalendarDate'),
  \ javaapi#method(0,0,'setTimeOfDay(', 'long)', 'void'),
  \ javaapi#method(0,1,'isNormalized(', ')', 'boolean'),
  \ javaapi#method(0,1,'isStandardTime(', ')', 'boolean'),
  \ javaapi#method(0,1,'setStandardTime(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'isDaylightTime(', ')', 'boolean'),
  \ javaapi#method(0,0,'setLocale(', 'Locale)', 'void'),
  \ javaapi#method(0,1,'getZone(', ')', 'TimeZone'),
  \ javaapi#method(0,1,'setZone(', 'TimeZone)', 'CalendarDate'),
  \ javaapi#method(0,1,'isSameDate(', 'CalendarDate)', 'boolean'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'clone(', ')', 'Object'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,0,'setDayOfWeek(', 'int)', 'void'),
  \ javaapi#method(0,0,'setNormalized(', 'boolean)', 'void'),
  \ javaapi#method(0,1,'getZoneOffset(', ')', 'int'),
  \ javaapi#method(0,0,'setZoneOffset(', 'int)', 'void'),
  \ javaapi#method(0,1,'getDaylightSaving(', ')', 'int'),
  \ javaapi#method(0,0,'setDaylightSaving(', 'int)', 'void'),
  \ ])

call javaapi#namespace('sun.util.calendar')

call javaapi#class('ZoneInfoFile', '', [
  \ javaapi#field(1,1,'JAVAZI_LABEL', 'byte[]'),
  \ javaapi#field(1,1,'JAVAZI_VERSION', 'byte'),
  \ javaapi#field(1,1,'TAG_RawOffset', 'byte'),
  \ javaapi#field(1,1,'TAG_LastDSTSaving', 'byte'),
  \ javaapi#field(1,1,'TAG_CRC32', 'byte'),
  \ javaapi#field(1,1,'TAG_Transition', 'byte'),
  \ javaapi#field(1,1,'TAG_Offset', 'byte'),
  \ javaapi#field(1,1,'TAG_SimpleTimeZone', 'byte'),
  \ javaapi#field(1,1,'TAG_GMTOffsetWillChange', 'byte'),
  \ javaapi#field(1,1,'JAVAZM_FILE_NAME', 'String'),
  \ javaapi#field(1,1,'JAVAZM_LABEL', 'byte[]'),
  \ javaapi#field(1,1,'JAVAZM_VERSION', 'byte'),
  \ javaapi#field(1,1,'TAG_ZoneIDs', 'byte'),
  \ javaapi#field(1,1,'TAG_RawOffsets', 'byte'),
  \ javaapi#field(1,1,'TAG_RawOffsetIndices', 'byte'),
  \ javaapi#field(1,1,'TAG_ZoneAliases', 'byte'),
  \ javaapi#field(1,1,'TAG_TZDataVersion', 'byte'),
  \ javaapi#field(1,1,'TAG_ExcludedZones', 'byte'),
  \ javaapi#method(0,1,'ZoneInfoFile(', ')', ''),
  \ javaapi#method(1,1,'getFileName(', 'String)', 'String'),
  \ javaapi#method(1,1,'getCustomTimeZone(', 'String, int)', 'ZoneInfo'),
  \ javaapi#method(1,1,'toCustomID(', 'int)', 'String'),
  \ javaapi#method(1,1,'getZoneInfo(', 'String)', 'ZoneInfo'),
  \ ])

call javaapi#class('ZoneInfo', 'TimeZone', [
  \ javaapi#method(0,1,'ZoneInfo(', ')', ''),
  \ javaapi#method(0,1,'ZoneInfo(', 'String, int)', ''),
  \ javaapi#method(0,1,'getOffset(', 'long)', 'int'),
  \ javaapi#method(0,1,'getOffsets(', 'long, int[])', 'int'),
  \ javaapi#method(0,1,'getOffsetsByStandard(', 'long, int[])', 'int'),
  \ javaapi#method(0,1,'getOffsetsByWall(', 'long, int[])', 'int'),
  \ javaapi#method(0,1,'getOffset(', 'int, int, int, int, int, int)', 'int'),
  \ javaapi#method(0,1,'setRawOffset(', 'int)', 'void'),
  \ javaapi#method(0,1,'getRawOffset(', ')', 'int'),
  \ javaapi#method(0,1,'isDirty(', ')', 'boolean'),
  \ javaapi#method(0,1,'useDaylightTime(', ')', 'boolean'),
  \ javaapi#method(0,1,'observesDaylightTime(', ')', 'boolean'),
  \ javaapi#method(0,1,'inDaylightTime(', 'Date)', 'boolean'),
  \ javaapi#method(0,1,'getDSTSavings(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(1,1,'getAvailableIDs(', ')', 'String[]'),
  \ javaapi#method(1,1,'getAvailableIDs(', 'int)', 'String[]'),
  \ javaapi#method(1,1,'getTimeZone(', 'String)', 'TimeZone'),
  \ javaapi#method(0,1,'getLastRuleInstance(', ')', 'SimpleTimeZone'),
  \ javaapi#method(0,1,'clone(', ')', 'Object'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hasSameRules(', 'TimeZone)', 'boolean'),
  \ javaapi#method(1,1,'getAliasTable(', ')', 'String>'),
  \ ])

call javaapi#namespace('sun.util.calendar')

call javaapi#class('AbstractCalendar', 'CalendarSystem', [
  \ javaapi#method(0,0,'AbstractCalendar(', ')', ''),
  \ javaapi#method(0,1,'getEra(', 'String)', 'Era'),
  \ javaapi#method(0,1,'getEras(', ')', 'Era[]'),
  \ javaapi#method(0,1,'setEra(', 'CalendarDate, String)', 'void'),
  \ javaapi#method(0,0,'setEras(', 'Era[])', 'void'),
  \ javaapi#method(0,1,'getCalendarDate(', ')', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, TimeZone)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, CalendarDate)', 'CalendarDate'),
  \ javaapi#method(0,1,'getTime(', 'CalendarDate)', 'long'),
  \ javaapi#method(0,0,'getTimeOfDay(', 'CalendarDate)', 'long'),
  \ javaapi#method(0,1,'getTimeOfDayValue(', 'CalendarDate)', 'long'),
  \ javaapi#method(0,1,'setTimeOfDay(', 'CalendarDate, int)', 'CalendarDate'),
  \ javaapi#method(0,1,'getWeekLength(', ')', 'int'),
  \ javaapi#method(0,0,'isLeapYear(', 'CalendarDate)', 'boolean'),
  \ javaapi#method(0,1,'getNthDayOfWeek(', 'int, int, CalendarDate)', 'CalendarDate'),
  \ javaapi#method(1,1,'getDayOfWeekDateOnOrBefore(', 'long, int)', 'long'),
  \ javaapi#method(0,0,'getFixedDate(', 'CalendarDate)', 'long'),
  \ javaapi#method(0,0,'getCalendarDateFromFixedDate(', 'CalendarDate, long)', 'void'),
  \ javaapi#method(0,1,'validateTime(', 'CalendarDate)', 'boolean'),
  \ ])

call javaapi#class('BaseCalendar', 'AbstractCalendar', [
  \ javaapi#field(1,1,'JANUARY', 'int'),
  \ javaapi#field(1,1,'FEBRUARY', 'int'),
  \ javaapi#field(1,1,'MARCH', 'int'),
  \ javaapi#field(1,1,'APRIL', 'int'),
  \ javaapi#field(1,1,'MAY', 'int'),
  \ javaapi#field(1,1,'JUNE', 'int'),
  \ javaapi#field(1,1,'JULY', 'int'),
  \ javaapi#field(1,1,'AUGUST', 'int'),
  \ javaapi#field(1,1,'SEPTEMBER', 'int'),
  \ javaapi#field(1,1,'OCTOBER', 'int'),
  \ javaapi#field(1,1,'NOVEMBER', 'int'),
  \ javaapi#field(1,1,'DECEMBER', 'int'),
  \ javaapi#field(1,1,'SUNDAY', 'int'),
  \ javaapi#field(1,1,'MONDAY', 'int'),
  \ javaapi#field(1,1,'TUESDAY', 'int'),
  \ javaapi#field(1,1,'WEDNESDAY', 'int'),
  \ javaapi#field(1,1,'THURSDAY', 'int'),
  \ javaapi#field(1,1,'FRIDAY', 'int'),
  \ javaapi#field(1,1,'SATURDAY', 'int'),
  \ javaapi#method(0,1,'BaseCalendar(', ')', ''),
  \ javaapi#method(0,1,'validate(', 'CalendarDate)', 'boolean'),
  \ javaapi#method(0,1,'normalize(', 'CalendarDate)', 'boolean'),
  \ javaapi#method(0,1,'getYearLength(', 'CalendarDate)', 'int'),
  \ javaapi#method(0,1,'getYearLengthInMonths(', 'CalendarDate)', 'int'),
  \ javaapi#method(0,1,'getMonthLength(', 'CalendarDate)', 'int'),
  \ javaapi#method(0,1,'getDayOfYear(', 'CalendarDate)', 'long'),
  \ javaapi#method(0,1,'getFixedDate(', 'CalendarDate)', 'long'),
  \ javaapi#method(0,1,'getFixedDate(', 'int, int, int, Date)', 'long'),
  \ javaapi#method(0,1,'getCalendarDateFromFixedDate(', 'CalendarDate, long)', 'void'),
  \ javaapi#method(0,1,'getDayOfWeek(', 'CalendarDate)', 'int'),
  \ javaapi#method(1,1,'getDayOfWeekFromFixedDate(', 'long)', 'int'),
  \ javaapi#method(0,1,'getYearFromFixedDate(', 'long)', 'int'),
  \ javaapi#method(0,0,'isLeapYear(', 'CalendarDate)', 'boolean'),
  \ ])

call javaapi#class('Gregorian', 'BaseCalendar', [
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getCalendarDate(', ')', 'Date'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long)', 'Date'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, CalendarDate)', 'Date'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, TimeZone)', 'Date'),
  \ javaapi#method(0,1,'newCalendarDate(', ')', 'Date'),
  \ javaapi#method(0,1,'newCalendarDate(', 'TimeZone)', 'Date'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, CalendarDate)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, TimeZone)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', ')', 'CalendarDate'),
  \ javaapi#method(0,1,'newCalendarDate(', 'TimeZone)', 'CalendarDate'),
  \ javaapi#method(0,1,'newCalendarDate(', ')', 'CalendarDate'),
  \ ])

call javaapi#namespace('sun.util.calendar')

call javaapi#class('CalendarSystem', '', [
  \ javaapi#method(0,1,'CalendarSystem(', ')', ''),
  \ javaapi#method(1,1,'getGregorianCalendar(', ')', 'Gregorian'),
  \ javaapi#method(1,1,'forName(', 'String)', 'CalendarSystem'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getCalendarDate(', ')', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, CalendarDate)', 'CalendarDate'),
  \ javaapi#method(0,1,'getCalendarDate(', 'long, TimeZone)', 'CalendarDate'),
  \ javaapi#method(0,1,'newCalendarDate(', ')', 'CalendarDate'),
  \ javaapi#method(0,1,'newCalendarDate(', 'TimeZone)', 'CalendarDate'),
  \ javaapi#method(0,1,'getTime(', 'CalendarDate)', 'long'),
  \ javaapi#method(0,1,'getYearLength(', 'CalendarDate)', 'int'),
  \ javaapi#method(0,1,'getYearLengthInMonths(', 'CalendarDate)', 'int'),
  \ javaapi#method(0,1,'getMonthLength(', 'CalendarDate)', 'int'),
  \ javaapi#method(0,1,'getWeekLength(', ')', 'int'),
  \ javaapi#method(0,1,'getEra(', 'String)', 'Era'),
  \ javaapi#method(0,1,'getEras(', ')', 'Era[]'),
  \ javaapi#method(0,1,'setEra(', 'CalendarDate, String)', 'void'),
  \ javaapi#method(0,1,'getNthDayOfWeek(', 'int, int, CalendarDate)', 'CalendarDate'),
  \ javaapi#method(0,1,'setTimeOfDay(', 'CalendarDate, int)', 'CalendarDate'),
  \ javaapi#method(0,1,'validate(', 'CalendarDate)', 'boolean'),
  \ javaapi#method(0,1,'normalize(', 'CalendarDate)', 'boolean'),
  \ ])

