call javaapi#namespace('sun.security.x509')

call javaapi#class('AVA', 'DerEncoder', [
  \ javaapi#method(0,1,'AVA(', 'ObjectIdentifier, DerValue)', ''),
  \ javaapi#method(0,1,'getObjectIdentifier(', ')', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'getDerValue(', ')', 'DerValue'),
  \ javaapi#method(0,1,'getValueString(', ')', 'String'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'derEncode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'toRFC1779String(', ')', 'String'),
  \ javaapi#method(0,1,'toRFC1779String(', 'Map<String, String>)', 'String'),
  \ javaapi#method(0,1,'toRFC2253String(', ')', 'String'),
  \ javaapi#method(0,1,'toRFC2253String(', 'Map<String, String>)', 'String'),
  \ javaapi#method(0,1,'toRFC2253CanonicalString(', ')', 'String'),
  \ ])

call javaapi#class('AVAComparator', 'Comparator', [
  \ javaapi#method(0,1,'compare(', 'AVA, AVA)', 'int'),
  \ javaapi#method(0,1,'compare(', 'Object, Object)', 'int'),
  \ ])

call javaapi#class('AVAKeyword', '', [
  \ ])

call javaapi#class('AccessDescription', '', [
  \ javaapi#field(1,1,'Ad_OCSP_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'Ad_CAISSUERS_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'Ad_TIMESTAMPING_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'Ad_CAREPOSITORY_Id', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'AccessDescription(', 'ObjectIdentifier, GeneralName)', ''),
  \ javaapi#method(0,1,'AccessDescription(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'getAccessMethod(', ')', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'getAccessLocation(', ')', 'GeneralName'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('AlgIdDSA', 'AlgorithmId', [
  \ javaapi#method(0,1,'getP(', ')', 'BigInteger'),
  \ javaapi#method(0,1,'getQ(', ')', 'BigInteger'),
  \ javaapi#method(0,1,'getG(', ')', 'BigInteger'),
  \ javaapi#method(0,1,'AlgIdDSA(', ')', ''),
  \ javaapi#method(0,1,'AlgIdDSA(', 'byte[]) throws IOException', ''),
  \ javaapi#method(0,1,'AlgIdDSA(', 'byte[], byte[], byte[]) throws IOException', ''),
  \ javaapi#method(0,1,'AlgIdDSA(', 'BigInteger, BigInteger, BigInteger)', ''),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,0,'decodeParams(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,0,'paramsToString(', ')', 'String'),
  \ ])

call javaapi#class('AttributeNameEnumeration', 'Vector', [
  \ javaapi#method(0,1,'AttributeNameEnumeration(', ')', ''),
  \ ])

call javaapi#class('AuthorityInfoAccessExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'DESCRIPTIONS', 'String'),
  \ javaapi#method(0,1,'AuthorityInfoAccessExtension(', 'List<AccessDescription>) throws IOException', ''),
  \ javaapi#method(0,1,'AuthorityInfoAccessExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'getAccessDescriptions(', ')', 'List'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('AuthorityKeyIdentifierExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'KEY_ID', 'String'),
  \ javaapi#field(1,1,'AUTH_NAME', 'String'),
  \ javaapi#field(1,1,'SERIAL_NUMBER', 'String'),
  \ javaapi#method(0,1,'AuthorityKeyIdentifierExtension(', 'KeyIdentifier, GeneralNames, SerialNumber) throws IOException', ''),
  \ javaapi#method(0,1,'AuthorityKeyIdentifierExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('BasicConstraintsExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'IS_CA', 'String'),
  \ javaapi#field(1,1,'PATH_LEN', 'String'),
  \ javaapi#method(0,1,'BasicConstraintsExtension(', 'boolean, int) throws IOException', ''),
  \ javaapi#method(0,1,'BasicConstraintsExtension(', 'Boolean, boolean, int) throws IOException', ''),
  \ javaapi#method(0,1,'BasicConstraintsExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('CRLDistributionPointsExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'POINTS', 'String'),
  \ javaapi#method(0,1,'CRLDistributionPointsExtension(', 'List<DistributionPoint>) throws IOException', ''),
  \ javaapi#method(0,1,'CRLDistributionPointsExtension(', 'boolean, List<DistributionPoint>) throws IOException', ''),
  \ javaapi#method(0,0,'CRLDistributionPointsExtension(', 'ObjectIdentifier, boolean, List<DistributionPoint>, String) throws IOException', ''),
  \ javaapi#method(0,1,'CRLDistributionPointsExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,0,'CRLDistributionPointsExtension(', 'ObjectIdentifier, Boolean, Object, String) throws IOException', ''),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,0,'encode(', 'OutputStream, ObjectIdentifier, boolean) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('CRLExtensions', '', [
  \ javaapi#method(0,1,'CRLExtensions(', ')', ''),
  \ javaapi#method(0,1,'CRLExtensions(', 'DerInputStream) throws CRLException', ''),
  \ javaapi#method(0,1,'encode(', 'OutputStream, boolean) throws CRLException', 'void'),
  \ javaapi#method(0,1,'get(', 'String)', 'Extension'),
  \ javaapi#method(0,1,'set(', 'String, Object)', 'void'),
  \ javaapi#method(0,1,'delete(', 'String)', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getAllExtensions(', ')', 'Collection'),
  \ javaapi#method(0,1,'hasUnsupportedCriticalExtension(', ')', 'boolean'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('CRLNumberExtension', 'Extension', [
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'NUMBER', 'String'),
  \ javaapi#method(0,1,'CRLNumberExtension(', 'int) throws IOException', ''),
  \ javaapi#method(0,1,'CRLNumberExtension(', 'BigInteger) throws IOException', ''),
  \ javaapi#method(0,0,'CRLNumberExtension(', 'ObjectIdentifier, boolean, BigInteger, String, String) throws IOException', ''),
  \ javaapi#method(0,1,'CRLNumberExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,0,'CRLNumberExtension(', 'ObjectIdentifier, Boolean, Object, String, String) throws IOException', ''),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,0,'encode(', 'OutputStream, ObjectIdentifier, boolean) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('CRLReasonCodeExtension', 'Extension', [
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'REASON', 'String'),
  \ javaapi#field(1,1,'UNSPECIFIED', 'int'),
  \ javaapi#field(1,1,'KEY_COMPROMISE', 'int'),
  \ javaapi#field(1,1,'CA_COMPROMISE', 'int'),
  \ javaapi#field(1,1,'AFFLIATION_CHANGED', 'int'),
  \ javaapi#field(1,1,'SUPERSEDED', 'int'),
  \ javaapi#field(1,1,'CESSATION_OF_OPERATION', 'int'),
  \ javaapi#field(1,1,'CERTIFICATE_HOLD', 'int'),
  \ javaapi#field(1,1,'REMOVE_FROM_CRL', 'int'),
  \ javaapi#field(1,1,'PRIVILEGE_WITHDRAWN', 'int'),
  \ javaapi#field(1,1,'AA_COMPROMISE', 'int'),
  \ javaapi#method(0,1,'CRLReasonCodeExtension(', 'int) throws IOException', ''),
  \ javaapi#method(0,1,'CRLReasonCodeExtension(', 'boolean, int) throws IOException', ''),
  \ javaapi#method(0,1,'CRLReasonCodeExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getReasonCode(', ')', 'CRLReason'),
  \ ])

call javaapi#class('CertAndKeyGen', '', [
  \ javaapi#method(0,1,'CertAndKeyGen(', 'String, String) throws NoSuchAlgorithmException', ''),
  \ javaapi#method(0,1,'CertAndKeyGen(', 'String, String, String) throws NoSuchAlgorithmException, NoSuchProviderException', ''),
  \ javaapi#method(0,1,'setRandom(', 'SecureRandom)', 'void'),
  \ javaapi#method(0,1,'generate(', 'int) throws InvalidKeyException', 'void'),
  \ javaapi#method(0,1,'getPublicKey(', ')', 'X509Key'),
  \ javaapi#method(0,1,'getPrivateKey(', ')', 'PrivateKey'),
  \ javaapi#method(0,1,'getSelfCertificate(', 'X500Name, Date, long) throws CertificateException, InvalidKeyException, SignatureException, NoSuchAlgorithmException, NoSuchProviderException', 'X509Certificate'),
  \ javaapi#method(0,1,'getSelfCertificate(', 'X500Name, long) throws CertificateException, InvalidKeyException, SignatureException, NoSuchAlgorithmException, NoSuchProviderException', 'X509Certificate'),
  \ javaapi#method(0,1,'getCertRequest(', 'X500Name) throws InvalidKeyException, SignatureException', 'PKCS10'),
  \ ])

call javaapi#interface('CertAttrSet', '', [
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws CertificateException, IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('CertException', 'SecurityException', [
  \ javaapi#field(1,1,'verf_INVALID_SIG', 'int'),
  \ javaapi#field(1,1,'verf_INVALID_REVOKED', 'int'),
  \ javaapi#field(1,1,'verf_INVALID_NOTBEFORE', 'int'),
  \ javaapi#field(1,1,'verf_INVALID_EXPIRED', 'int'),
  \ javaapi#field(1,1,'verf_CA_UNTRUSTED', 'int'),
  \ javaapi#field(1,1,'verf_CHAIN_LENGTH', 'int'),
  \ javaapi#field(1,1,'verf_PARSE_ERROR', 'int'),
  \ javaapi#field(1,1,'err_CONSTRUCTION', 'int'),
  \ javaapi#field(1,1,'err_INVALID_PUBLIC_KEY', 'int'),
  \ javaapi#field(1,1,'err_INVALID_VERSION', 'int'),
  \ javaapi#field(1,1,'err_INVALID_FORMAT', 'int'),
  \ javaapi#field(1,1,'err_ENCODING', 'int'),
  \ javaapi#method(0,1,'CertException(', 'int, String)', ''),
  \ javaapi#method(0,1,'CertException(', 'int)', ''),
  \ javaapi#method(0,1,'getVerfCode(', ')', 'int'),
  \ javaapi#method(0,1,'getMoreData(', ')', 'String'),
  \ javaapi#method(0,1,'getVerfDescription(', ')', 'String'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'getMessage(', ')', 'String'),
  \ ])

call javaapi#class('CertParseError', 'CertException', [
  \ ])

call javaapi#class('CertificateAlgorithmId', 'CertAttrSet', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'ALGORITHM', 'String'),
  \ javaapi#method(0,1,'CertificateAlgorithmId(', 'AlgorithmId)', ''),
  \ javaapi#method(0,1,'CertificateAlgorithmId(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateAlgorithmId(', 'InputStream) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('CertificateExtensions', 'CertAttrSet', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#method(0,1,'CertificateExtensions(', ')', ''),
  \ javaapi#method(0,1,'CertificateExtensions(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'encode(', 'OutputStream, boolean) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getNameByOid(', 'ObjectIdentifier) throws IOException', 'String'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getAllExtensions(', ')', 'Collection'),
  \ javaapi#method(0,1,'getUnparseableExtensions(', ')', 'Extension>'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'hasUnsupportedCriticalExtension(', ')', 'boolean'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('CertificateIssuerExtension', 'Extension', [
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'ISSUER', 'String'),
  \ javaapi#method(0,1,'CertificateIssuerExtension(', 'GeneralNames) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateIssuerExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('CertificateIssuerName', 'CertAttrSet', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'DN_NAME', 'String'),
  \ javaapi#field(1,1,'DN_PRINCIPAL', 'String'),
  \ javaapi#method(0,1,'CertificateIssuerName(', 'X500Name)', ''),
  \ javaapi#method(0,1,'CertificateIssuerName(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateIssuerName(', 'InputStream) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('CertificateIssuerUniqueIdentity', 'CertAttrSet', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'ID', 'String'),
  \ javaapi#method(0,1,'CertificateIssuerUniqueIdentity(', 'UniqueIdentity)', ''),
  \ javaapi#method(0,1,'CertificateIssuerUniqueIdentity(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateIssuerUniqueIdentity(', 'InputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateIssuerUniqueIdentity(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('CertificatePoliciesExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'POLICIES', 'String'),
  \ javaapi#method(0,1,'CertificatePoliciesExtension(', 'List<PolicyInformation>) throws IOException', ''),
  \ javaapi#method(0,1,'CertificatePoliciesExtension(', 'Boolean, List<PolicyInformation>) throws IOException', ''),
  \ javaapi#method(0,1,'CertificatePoliciesExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('CertificatePolicyId', '', [
  \ javaapi#method(0,1,'CertificatePolicyId(', 'ObjectIdentifier)', ''),
  \ javaapi#method(0,1,'CertificatePolicyId(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'getIdentifier(', ')', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ ])

call javaapi#class('CertificatePolicyMap', '', [
  \ javaapi#method(0,1,'CertificatePolicyMap(', 'CertificatePolicyId, CertificatePolicyId)', ''),
  \ javaapi#method(0,1,'CertificatePolicyMap(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'getIssuerIdentifier(', ')', 'CertificatePolicyId'),
  \ javaapi#method(0,1,'getSubjectIdentifier(', ')', 'CertificatePolicyId'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ ])

call javaapi#class('CertificatePolicySet', '', [
  \ javaapi#method(0,1,'CertificatePolicySet(', 'Vector<CertificatePolicyId>)', ''),
  \ javaapi#method(0,1,'CertificatePolicySet(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getCertPolicyIds(', ')', 'List'),
  \ ])

call javaapi#class('CertificateSerialNumber', 'CertAttrSet', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'NUMBER', 'String'),
  \ javaapi#method(0,1,'CertificateSerialNumber(', 'BigInteger)', ''),
  \ javaapi#method(0,1,'CertificateSerialNumber(', 'int)', ''),
  \ javaapi#method(0,1,'CertificateSerialNumber(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateSerialNumber(', 'InputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateSerialNumber(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('CertificateSubjectName', 'CertAttrSet', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'DN_NAME', 'String'),
  \ javaapi#field(1,1,'DN_PRINCIPAL', 'String'),
  \ javaapi#method(0,1,'CertificateSubjectName(', 'X500Name)', ''),
  \ javaapi#method(0,1,'CertificateSubjectName(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateSubjectName(', 'InputStream) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('CertificateSubjectUniqueIdentity', 'CertAttrSet', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'ID', 'String'),
  \ javaapi#method(0,1,'CertificateSubjectUniqueIdentity(', 'UniqueIdentity)', ''),
  \ javaapi#method(0,1,'CertificateSubjectUniqueIdentity(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateSubjectUniqueIdentity(', 'InputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateSubjectUniqueIdentity(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('CertificateValidity', 'CertAttrSet', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'NOT_BEFORE', 'String'),
  \ javaapi#field(1,1,'NOT_AFTER', 'String'),
  \ javaapi#method(0,1,'CertificateValidity(', ')', ''),
  \ javaapi#method(0,1,'CertificateValidity(', 'Date, Date)', ''),
  \ javaapi#method(0,1,'CertificateValidity(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'valid(', ') throws CertificateNotYetValidException, CertificateExpiredException', 'void'),
  \ javaapi#method(0,1,'valid(', 'Date) throws CertificateNotYetValidException, CertificateExpiredException', 'void'),
  \ ])

call javaapi#class('CertificateVersion', 'CertAttrSet', [
  \ javaapi#field(1,1,'V1', 'int'),
  \ javaapi#field(1,1,'V2', 'int'),
  \ javaapi#field(1,1,'V3', 'int'),
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'VERSION', 'String'),
  \ javaapi#method(0,1,'CertificateVersion(', ')', ''),
  \ javaapi#method(0,1,'CertificateVersion(', 'int) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateVersion(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateVersion(', 'InputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateVersion(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'compare(', 'int)', 'int'),
  \ ])

call javaapi#class('CertificateX509Key', 'CertAttrSet', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'KEY', 'String'),
  \ javaapi#method(0,1,'CertificateX509Key(', 'PublicKey)', ''),
  \ javaapi#method(0,1,'CertificateX509Key(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'CertificateX509Key(', 'InputStream) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('DNSName', 'GeneralNameInterface', [
  \ javaapi#method(0,1,'DNSName(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'DNSName(', 'String) throws IOException', ''),
  \ javaapi#method(0,1,'getType(', ')', 'int'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'constrains(', 'GeneralNameInterface) throws UnsupportedOperationException', 'int'),
  \ javaapi#method(0,1,'subtreeDepth(', ') throws UnsupportedOperationException', 'int'),
  \ ])

call javaapi#class('DeltaCRLIndicatorExtension', 'CRLNumberExtension', [
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#method(0,1,'DeltaCRLIndicatorExtension(', 'int) throws IOException', ''),
  \ javaapi#method(0,1,'DeltaCRLIndicatorExtension(', 'BigInteger) throws IOException', ''),
  \ javaapi#method(0,1,'DeltaCRLIndicatorExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ ])

call javaapi#class('DistributionPoint', '', [
  \ javaapi#field(1,1,'KEY_COMPROMISE', 'int'),
  \ javaapi#field(1,1,'CA_COMPROMISE', 'int'),
  \ javaapi#field(1,1,'AFFILIATION_CHANGED', 'int'),
  \ javaapi#field(1,1,'SUPERSEDED', 'int'),
  \ javaapi#field(1,1,'CESSATION_OF_OPERATION', 'int'),
  \ javaapi#field(1,1,'CERTIFICATE_HOLD', 'int'),
  \ javaapi#field(1,1,'PRIVILEGE_WITHDRAWN', 'int'),
  \ javaapi#field(1,1,'AA_COMPROMISE', 'int'),
  \ javaapi#method(0,1,'DistributionPoint(', 'GeneralNames, boolean[], GeneralNames)', ''),
  \ javaapi#method(0,1,'DistributionPoint(', 'RDN, boolean[], GeneralNames)', ''),
  \ javaapi#method(0,1,'DistributionPoint(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'getFullName(', ')', 'GeneralNames'),
  \ javaapi#method(0,1,'getRelativeName(', ')', 'RDN'),
  \ javaapi#method(0,1,'getReasonFlags(', ')', 'boolean'),
  \ javaapi#method(0,1,'getCRLIssuer(', ')', 'GeneralNames'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('DistributionPointName', '', [
  \ javaapi#method(0,1,'DistributionPointName(', 'GeneralNames)', ''),
  \ javaapi#method(0,1,'DistributionPointName(', 'RDN)', ''),
  \ javaapi#method(0,1,'DistributionPointName(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'getFullName(', ')', 'GeneralNames'),
  \ javaapi#method(0,1,'getRelativeName(', ')', 'RDN'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('EDIPartyName', 'GeneralNameInterface', [
  \ javaapi#method(0,1,'EDIPartyName(', 'String, String)', ''),
  \ javaapi#method(0,1,'EDIPartyName(', 'String)', ''),
  \ javaapi#method(0,1,'EDIPartyName(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'getType(', ')', 'int'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getAssignerName(', ')', 'String'),
  \ javaapi#method(0,1,'getPartyName(', ')', 'String'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'constrains(', 'GeneralNameInterface) throws UnsupportedOperationException', 'int'),
  \ javaapi#method(0,1,'subtreeDepth(', ') throws UnsupportedOperationException', 'int'),
  \ ])

call javaapi#class('ExtendedKeyUsageExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'USAGES', 'String'),
  \ javaapi#method(0,1,'ExtendedKeyUsageExtension(', 'Vector<ObjectIdentifier>) throws IOException', ''),
  \ javaapi#method(0,1,'ExtendedKeyUsageExtension(', 'Boolean, Vector<ObjectIdentifier>) throws IOException', ''),
  \ javaapi#method(0,1,'ExtendedKeyUsageExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getExtendedKeyUsage(', ')', 'List'),
  \ ])

call javaapi#class('Extension', 'Extension', [
  \ javaapi#field(0,0,'extensionId', 'ObjectIdentifier'),
  \ javaapi#field(0,0,'critical', 'boolean'),
  \ javaapi#field(0,0,'extensionValue', 'byte'),
  \ javaapi#method(0,1,'Extension(', ')', ''),
  \ javaapi#method(0,1,'Extension(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'Extension(', 'ObjectIdentifier, boolean, byte[]) throws IOException', ''),
  \ javaapi#method(0,1,'Extension(', 'Extension)', ''),
  \ javaapi#method(1,1,'newExtension(', 'ObjectIdentifier, boolean, byte[]) throws IOException', 'Extension'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'isCritical(', ')', 'boolean'),
  \ javaapi#method(0,1,'getExtensionId(', ')', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'getValue(', ')', 'byte'),
  \ javaapi#method(0,1,'getExtensionValue(', ')', 'byte'),
  \ javaapi#method(0,1,'getId(', ')', 'String'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ ])

call javaapi#class('FreshestCRLExtension', 'CRLDistributionPointsExtension', [
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#method(0,1,'FreshestCRLExtension(', 'List<DistributionPoint>) throws IOException', ''),
  \ javaapi#method(0,1,'FreshestCRLExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ ])

call javaapi#class('GeneralName', '', [
  \ javaapi#method(0,1,'GeneralName(', 'GeneralNameInterface)', ''),
  \ javaapi#method(0,1,'GeneralName(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'GeneralName(', 'DerValue, boolean) throws IOException', ''),
  \ javaapi#method(0,1,'getType(', ')', 'int'),
  \ javaapi#method(0,1,'getName(', ')', 'GeneralNameInterface'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ ])

call javaapi#interface('GeneralNameInterface', '', [
  \ javaapi#field(1,1,'NAME_ANY', 'int'),
  \ javaapi#field(1,1,'NAME_RFC822', 'int'),
  \ javaapi#field(1,1,'NAME_DNS', 'int'),
  \ javaapi#field(1,1,'NAME_X400', 'int'),
  \ javaapi#field(1,1,'NAME_DIRECTORY', 'int'),
  \ javaapi#field(1,1,'NAME_EDI', 'int'),
  \ javaapi#field(1,1,'NAME_URI', 'int'),
  \ javaapi#field(1,1,'NAME_IP', 'int'),
  \ javaapi#field(1,1,'NAME_OID', 'int'),
  \ javaapi#field(1,1,'NAME_DIFF_TYPE', 'int'),
  \ javaapi#field(1,1,'NAME_MATCH', 'int'),
  \ javaapi#field(1,1,'NAME_NARROWS', 'int'),
  \ javaapi#field(1,1,'NAME_WIDENS', 'int'),
  \ javaapi#field(1,1,'NAME_SAME_TYPE', 'int'),
  \ javaapi#method(0,1,'getType(', ')', 'int'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'constrains(', 'GeneralNameInterface) throws UnsupportedOperationException', 'int'),
  \ javaapi#method(0,1,'subtreeDepth(', ') throws UnsupportedOperationException', 'int'),
  \ ])

call javaapi#class('GeneralNames', '', [
  \ javaapi#method(0,1,'GeneralNames(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'GeneralNames(', ')', ''),
  \ javaapi#method(0,1,'add(', 'GeneralName)', 'GeneralNames'),
  \ javaapi#method(0,1,'get(', 'int)', 'GeneralName'),
  \ javaapi#method(0,1,'isEmpty(', ')', 'boolean'),
  \ javaapi#method(0,1,'size(', ')', 'int'),
  \ javaapi#method(0,1,'iterator(', ')', 'Iterator'),
  \ javaapi#method(0,1,'names(', ')', 'List'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('GeneralSubtree', '', [
  \ javaapi#method(0,1,'GeneralSubtree(', 'GeneralName, int, int)', ''),
  \ javaapi#method(0,1,'GeneralSubtree(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'getName(', ')', 'GeneralName'),
  \ javaapi#method(0,1,'getMinimum(', ')', 'int'),
  \ javaapi#method(0,1,'getMaximum(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ ])

call javaapi#class('GeneralSubtrees', 'Cloneable', [
  \ javaapi#method(0,1,'GeneralSubtrees(', ')', ''),
  \ javaapi#method(0,1,'GeneralSubtrees(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'get(', 'int)', 'GeneralSubtree'),
  \ javaapi#method(0,1,'remove(', 'int)', 'void'),
  \ javaapi#method(0,1,'add(', 'GeneralSubtree)', 'void'),
  \ javaapi#method(0,1,'contains(', 'GeneralSubtree)', 'boolean'),
  \ javaapi#method(0,1,'size(', ')', 'int'),
  \ javaapi#method(0,1,'iterator(', ')', 'Iterator'),
  \ javaapi#method(0,1,'trees(', ')', 'List'),
  \ javaapi#method(0,1,'clone(', ')', 'Object'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'intersect(', 'GeneralSubtrees)', 'GeneralSubtrees'),
  \ javaapi#method(0,1,'union(', 'GeneralSubtrees)', 'void'),
  \ javaapi#method(0,1,'reduce(', 'GeneralSubtrees)', 'void'),
  \ ])

call javaapi#class('IPAddressName', 'GeneralNameInterface', [
  \ javaapi#method(0,1,'IPAddressName(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'IPAddressName(', 'byte[]) throws IOException', ''),
  \ javaapi#method(0,1,'IPAddressName(', 'String) throws IOException', ''),
  \ javaapi#method(0,1,'getType(', ')', 'int'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'getName(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getBytes(', ')', 'byte'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'constrains(', 'GeneralNameInterface) throws UnsupportedOperationException', 'int'),
  \ javaapi#method(0,1,'subtreeDepth(', ') throws UnsupportedOperationException', 'int'),
  \ ])

call javaapi#class('InhibitAnyPolicyExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'AnyPolicy_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'SKIP_CERTS', 'String'),
  \ javaapi#method(0,1,'InhibitAnyPolicyExtension(', 'int) throws IOException', ''),
  \ javaapi#method(0,1,'InhibitAnyPolicyExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('InvalidityDateExtension', 'Extension', [
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'DATE', 'String'),
  \ javaapi#method(0,1,'InvalidityDateExtension(', 'Date) throws IOException', ''),
  \ javaapi#method(0,1,'InvalidityDateExtension(', 'boolean, Date) throws IOException', ''),
  \ javaapi#method(0,1,'InvalidityDateExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(1,1,'toImpl(', 'Extension) throws IOException', 'InvalidityDateExtension'),
  \ ])

call javaapi#class('IssuerAlternativeNameExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'ISSUER_NAME', 'String'),
  \ javaapi#method(0,1,'IssuerAlternativeNameExtension(', 'GeneralNames) throws IOException', ''),
  \ javaapi#method(0,1,'IssuerAlternativeNameExtension(', 'Boolean, GeneralNames) throws IOException', ''),
  \ javaapi#method(0,1,'IssuerAlternativeNameExtension(', ')', ''),
  \ javaapi#method(0,1,'IssuerAlternativeNameExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('IssuingDistributionPointExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'POINT', 'String'),
  \ javaapi#field(1,1,'REASONS', 'String'),
  \ javaapi#field(1,1,'ONLY_USER_CERTS', 'String'),
  \ javaapi#field(1,1,'ONLY_CA_CERTS', 'String'),
  \ javaapi#field(1,1,'ONLY_ATTRIBUTE_CERTS', 'String'),
  \ javaapi#field(1,1,'INDIRECT_CRL', 'String'),
  \ javaapi#method(0,1,'IssuingDistributionPointExtension(', 'DistributionPointName, ReasonFlags, boolean, boolean, boolean, boolean) throws IOException', ''),
  \ javaapi#method(0,1,'IssuingDistributionPointExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('KeyIdentifier', '', [
  \ javaapi#method(0,1,'KeyIdentifier(', 'byte[])', ''),
  \ javaapi#method(0,1,'KeyIdentifier(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'KeyIdentifier(', 'PublicKey) throws IOException', ''),
  \ javaapi#method(0,1,'getIdentifier(', ')', 'byte'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ ])

call javaapi#class('KeyUsageExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'DIGITAL_SIGNATURE', 'String'),
  \ javaapi#field(1,1,'NON_REPUDIATION', 'String'),
  \ javaapi#field(1,1,'KEY_ENCIPHERMENT', 'String'),
  \ javaapi#field(1,1,'DATA_ENCIPHERMENT', 'String'),
  \ javaapi#field(1,1,'KEY_AGREEMENT', 'String'),
  \ javaapi#field(1,1,'KEY_CERTSIGN', 'String'),
  \ javaapi#field(1,1,'CRL_SIGN', 'String'),
  \ javaapi#field(1,1,'ENCIPHER_ONLY', 'String'),
  \ javaapi#field(1,1,'DECIPHER_ONLY', 'String'),
  \ javaapi#method(0,1,'KeyUsageExtension(', 'byte[]) throws IOException', ''),
  \ javaapi#method(0,1,'KeyUsageExtension(', 'boolean[]) throws IOException', ''),
  \ javaapi#method(0,1,'KeyUsageExtension(', 'BitArray) throws IOException', ''),
  \ javaapi#method(0,1,'KeyUsageExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'KeyUsageExtension(', ')', ''),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getBits(', ')', 'boolean'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('NameConstraintsExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'PERMITTED_SUBTREES', 'String'),
  \ javaapi#field(1,1,'EXCLUDED_SUBTREES', 'String'),
  \ javaapi#method(0,1,'NameConstraintsExtension(', 'GeneralSubtrees, GeneralSubtrees) throws IOException', ''),
  \ javaapi#method(0,1,'NameConstraintsExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'merge(', 'NameConstraintsExtension) throws IOException', 'void'),
  \ javaapi#method(0,1,'verify(', 'X509Certificate) throws IOException', 'boolean'),
  \ javaapi#method(0,1,'verify(', 'GeneralNameInterface) throws IOException', 'boolean'),
  \ javaapi#method(0,1,'verifyRFC822SpecialCase(', 'X500Name) throws IOException', 'boolean'),
  \ javaapi#method(0,1,'clone(', ')', 'Object'),
  \ ])

call javaapi#class('NetscapeCertTypeExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'SSL_CLIENT', 'String'),
  \ javaapi#field(1,1,'SSL_SERVER', 'String'),
  \ javaapi#field(1,1,'S_MIME', 'String'),
  \ javaapi#field(1,1,'OBJECT_SIGNING', 'String'),
  \ javaapi#field(1,1,'SSL_CA', 'String'),
  \ javaapi#field(1,1,'S_MIME_CA', 'String'),
  \ javaapi#field(1,1,'OBJECT_SIGNING_CA', 'String'),
  \ javaapi#field(1,1,'NetscapeCertType_Id', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'NetscapeCertTypeExtension(', 'byte[]) throws IOException', ''),
  \ javaapi#method(0,1,'NetscapeCertTypeExtension(', 'boolean[]) throws IOException', ''),
  \ javaapi#method(0,1,'NetscapeCertTypeExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'NetscapeCertTypeExtension(', ')', ''),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getKeyUsageMappedBits(', ')', 'boolean'),
  \ ])

call javaapi#class('OCSPNoCheckExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#method(0,1,'OCSPNoCheckExtension(', ') throws IOException', ''),
  \ javaapi#method(0,1,'OCSPNoCheckExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('OIDMap', '', [
  \ javaapi#method(1,1,'addAttribute(', 'String, String, Class) throws CertificateException', 'void'),
  \ javaapi#method(1,1,'getName(', 'ObjectIdentifier)', 'String'),
  \ javaapi#method(1,1,'getOID(', 'String)', 'ObjectIdentifier'),
  \ javaapi#method(1,1,'getClass(', 'String) throws CertificateException', 'Class'),
  \ javaapi#method(1,1,'getClass(', 'ObjectIdentifier) throws CertificateException', 'Class'),
  \ ])

call javaapi#class('OIDName', 'GeneralNameInterface', [
  \ javaapi#method(0,1,'OIDName(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'OIDName(', 'ObjectIdentifier)', ''),
  \ javaapi#method(0,1,'OIDName(', 'String) throws IOException', ''),
  \ javaapi#method(0,1,'getType(', ')', 'int'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'getOID(', ')', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'constrains(', 'GeneralNameInterface) throws UnsupportedOperationException', 'int'),
  \ javaapi#method(0,1,'subtreeDepth(', ') throws UnsupportedOperationException', 'int'),
  \ ])

call javaapi#class('OtherName', 'GeneralNameInterface', [
  \ javaapi#method(0,1,'OtherName(', 'ObjectIdentifier, byte[]) throws IOException', ''),
  \ javaapi#method(0,1,'OtherName(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'getOID(', ')', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'getNameValue(', ')', 'byte'),
  \ javaapi#method(0,1,'getType(', ')', 'int'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'constrains(', 'GeneralNameInterface)', 'int'),
  \ javaapi#method(0,1,'subtreeDepth(', ')', 'int'),
  \ ])

call javaapi#class('PKIXExtensions', '', [
  \ javaapi#field(1,1,'AuthorityKey_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'SubjectKey_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'KeyUsage_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'PrivateKeyUsage_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'CertificatePolicies_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'PolicyMappings_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'SubjectAlternativeName_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'IssuerAlternativeName_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'SubjectDirectoryAttributes_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'BasicConstraints_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'NameConstraints_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'PolicyConstraints_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'CRLDistributionPoints_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'CRLNumber_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'IssuingDistributionPoint_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'DeltaCRLIndicator_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'ReasonCode_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'HoldInstructionCode_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'InvalidityDate_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'ExtendedKeyUsage_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'InhibitAnyPolicy_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'CertificateIssuer_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'AuthInfoAccess_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'SubjectInfoAccess_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'FreshestCRL_Id', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'OCSPNoCheck_Id', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'PKIXExtensions(', ')', ''),
  \ ])

call javaapi#class('PolicyConstraintsExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'REQUIRE', 'String'),
  \ javaapi#field(1,1,'INHIBIT', 'String'),
  \ javaapi#method(0,1,'PolicyConstraintsExtension(', 'int, int) throws IOException', ''),
  \ javaapi#method(0,1,'PolicyConstraintsExtension(', 'Boolean, int, int) throws IOException', ''),
  \ javaapi#method(0,1,'PolicyConstraintsExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('PolicyInformation', '', [
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'ID', 'String'),
  \ javaapi#field(1,1,'QUALIFIERS', 'String'),
  \ javaapi#method(0,1,'PolicyInformation(', 'CertificatePolicyId, Set<PolicyQualifierInfo>) throws IOException', ''),
  \ javaapi#method(0,1,'PolicyInformation(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'getPolicyIdentifier(', ')', 'CertificatePolicyId'),
  \ javaapi#method(0,1,'getPolicyQualifiers(', ')', 'Set'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ ])

call javaapi#class('PolicyMappingsExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'MAP', 'String'),
  \ javaapi#method(0,1,'PolicyMappingsExtension(', 'List<CertificatePolicyMap>) throws IOException', ''),
  \ javaapi#method(0,1,'PolicyMappingsExtension(', ')', ''),
  \ javaapi#method(0,1,'PolicyMappingsExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('PrivateKeyUsageExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'NOT_BEFORE', 'String'),
  \ javaapi#field(1,1,'NOT_AFTER', 'String'),
  \ javaapi#method(0,1,'PrivateKeyUsageExtension(', 'Date, Date) throws IOException', ''),
  \ javaapi#method(0,1,'PrivateKeyUsageExtension(', 'Boolean, Object) throws CertificateException, IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'valid(', ') throws CertificateNotYetValidException, CertificateExpiredException', 'void'),
  \ javaapi#method(0,1,'valid(', 'Date) throws CertificateNotYetValidException, CertificateExpiredException', 'void'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws CertificateException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('RDN', '', [
  \ javaapi#method(0,1,'RDN(', 'String) throws IOException', ''),
  \ javaapi#method(0,1,'RDN(', 'String, Map<String, String>) throws IOException', ''),
  \ javaapi#method(0,1,'RDN(', 'AVA)', ''),
  \ javaapi#method(0,1,'RDN(', 'AVA[])', ''),
  \ javaapi#method(0,1,'avas(', ')', 'List'),
  \ javaapi#method(0,1,'size(', ')', 'int'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'toRFC1779String(', ')', 'String'),
  \ javaapi#method(0,1,'toRFC1779String(', 'Map<String, String>)', 'String'),
  \ javaapi#method(0,1,'toRFC2253String(', ')', 'String'),
  \ javaapi#method(0,1,'toRFC2253String(', 'Map<String, String>)', 'String'),
  \ javaapi#method(0,1,'toRFC2253String(', 'boolean)', 'String'),
  \ ])

call javaapi#class('RFC822Name', 'GeneralNameInterface', [
  \ javaapi#method(0,1,'RFC822Name(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'RFC822Name(', 'String) throws IOException', ''),
  \ javaapi#method(0,1,'parseName(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getType(', ')', 'int'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'constrains(', 'GeneralNameInterface) throws UnsupportedOperationException', 'int'),
  \ javaapi#method(0,1,'subtreeDepth(', ') throws UnsupportedOperationException', 'int'),
  \ ])

call javaapi#class('ReasonFlags', '', [
  \ javaapi#field(1,1,'UNUSED', 'String'),
  \ javaapi#field(1,1,'KEY_COMPROMISE', 'String'),
  \ javaapi#field(1,1,'CA_COMPROMISE', 'String'),
  \ javaapi#field(1,1,'AFFILIATION_CHANGED', 'String'),
  \ javaapi#field(1,1,'SUPERSEDED', 'String'),
  \ javaapi#field(1,1,'CESSATION_OF_OPERATION', 'String'),
  \ javaapi#field(1,1,'CERTIFICATE_HOLD', 'String'),
  \ javaapi#field(1,1,'PRIVILEGE_WITHDRAWN', 'String'),
  \ javaapi#field(1,1,'AA_COMPROMISE', 'String'),
  \ javaapi#method(0,1,'ReasonFlags(', 'byte[])', ''),
  \ javaapi#method(0,1,'ReasonFlags(', 'boolean[])', ''),
  \ javaapi#method(0,1,'ReasonFlags(', 'BitArray)', ''),
  \ javaapi#method(0,1,'ReasonFlags(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'ReasonFlags(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'getFlags(', ')', 'boolean'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ ])

call javaapi#class('SerialNumber', '', [
  \ javaapi#method(0,1,'SerialNumber(', 'BigInteger)', ''),
  \ javaapi#method(0,1,'SerialNumber(', 'int)', ''),
  \ javaapi#method(0,1,'SerialNumber(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'SerialNumber(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'SerialNumber(', 'InputStream) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getNumber(', ')', 'BigInteger'),
  \ ])

call javaapi#class('SubjectAlternativeNameExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'SUBJECT_NAME', 'String'),
  \ javaapi#method(0,1,'SubjectAlternativeNameExtension(', 'GeneralNames) throws IOException', ''),
  \ javaapi#method(0,1,'SubjectAlternativeNameExtension(', 'Boolean, GeneralNames) throws IOException', ''),
  \ javaapi#method(0,1,'SubjectAlternativeNameExtension(', ')', ''),
  \ javaapi#method(0,1,'SubjectAlternativeNameExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('SubjectInfoAccessExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'DESCRIPTIONS', 'String'),
  \ javaapi#method(0,1,'SubjectInfoAccessExtension(', 'List<AccessDescription>) throws IOException', ''),
  \ javaapi#method(0,1,'SubjectInfoAccessExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'getAccessDescriptions(', ')', 'List'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('SubjectKeyIdentifierExtension', 'Extension', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'KEY_ID', 'String'),
  \ javaapi#method(0,1,'SubjectKeyIdentifierExtension(', 'byte[]) throws IOException', ''),
  \ javaapi#method(0,1,'SubjectKeyIdentifierExtension(', 'Boolean, Object) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws IOException', 'Object'),
  \ javaapi#method(0,1,'delete(', 'String) throws IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ ])

call javaapi#class('URIName', 'GeneralNameInterface', [
  \ javaapi#method(0,1,'URIName(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'URIName(', 'String) throws IOException', ''),
  \ javaapi#method(1,1,'nameConstraint(', 'DerValue) throws IOException', 'URIName'),
  \ javaapi#method(0,1,'getType(', ')', 'int'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'getURI(', ')', 'URI'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getScheme(', ')', 'String'),
  \ javaapi#method(0,1,'getHost(', ')', 'String'),
  \ javaapi#method(0,1,'getHostObject(', ')', 'Object'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'constrains(', 'GeneralNameInterface) throws UnsupportedOperationException', 'int'),
  \ javaapi#method(0,1,'subtreeDepth(', ') throws UnsupportedOperationException', 'int'),
  \ ])

call javaapi#class('UniqueIdentity', '', [
  \ javaapi#method(0,1,'UniqueIdentity(', 'BitArray)', ''),
  \ javaapi#method(0,1,'UniqueIdentity(', 'byte[])', ''),
  \ javaapi#method(0,1,'UniqueIdentity(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'UniqueIdentity(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream, byte) throws IOException', 'void'),
  \ javaapi#method(0,1,'getId(', ')', 'boolean'),
  \ ])

call javaapi#class('UnparseableExtension', 'Extension', [
  \ javaapi#method(0,1,'UnparseableExtension(', 'Extension, Throwable)', ''),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ ])

call javaapi#class('X400Address', 'GeneralNameInterface', [
  \ javaapi#method(0,1,'X400Address(', 'byte[])', ''),
  \ javaapi#method(0,1,'X400Address(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'getType(', ')', 'int'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'constrains(', 'GeneralNameInterface) throws UnsupportedOperationException', 'int'),
  \ javaapi#method(0,1,'subtreeDepth(', ') throws UnsupportedOperationException', 'int'),
  \ ])

call javaapi#class('X500Name', 'Principal', [
  \ javaapi#field(1,1,'commonName_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'countryName_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'localityName_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'orgName_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'orgUnitName_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'stateName_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'streetAddress_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'title_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'DNQUALIFIER_OID', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'SURNAME_OID', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'GIVENNAME_OID', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'INITIALS_OID', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'GENERATIONQUALIFIER_OID', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'ipAddress_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'DOMAIN_COMPONENT_OID', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'userid_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'SERIALNUMBER_OID', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'X500Name(', 'String) throws IOException', ''),
  \ javaapi#method(0,1,'X500Name(', 'String, Map<String, String>) throws IOException', ''),
  \ javaapi#method(0,1,'X500Name(', 'String, String) throws IOException', ''),
  \ javaapi#method(0,1,'X500Name(', 'String, String, String, String) throws IOException', ''),
  \ javaapi#method(0,1,'X500Name(', 'String, String, String, String, String, String) throws IOException', ''),
  \ javaapi#method(0,1,'X500Name(', 'RDN[]) throws IOException', ''),
  \ javaapi#method(0,1,'X500Name(', 'DerValue) throws IOException', ''),
  \ javaapi#method(0,1,'X500Name(', 'DerInputStream) throws IOException', ''),
  \ javaapi#method(0,1,'X500Name(', 'byte[]) throws IOException', ''),
  \ javaapi#method(0,1,'rdns(', ')', 'List'),
  \ javaapi#method(0,1,'size(', ')', 'int'),
  \ javaapi#method(0,1,'allAvas(', ')', 'List'),
  \ javaapi#method(0,1,'avaSize(', ')', 'int'),
  \ javaapi#method(0,1,'isEmpty(', ')', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'getType(', ')', 'int'),
  \ javaapi#method(0,1,'getCountry(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getOrganization(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getOrganizationalUnit(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getCommonName(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getLocality(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getState(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getDomain(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getDNQualifier(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getSurname(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getGivenName(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getInitials(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getGeneration(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'getIP(', ') throws IOException', 'String'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'getRFC1779Name(', ')', 'String'),
  \ javaapi#method(0,1,'getRFC1779Name(', 'Map<String, String>) throws IllegalArgumentException', 'String'),
  \ javaapi#method(0,1,'getRFC2253Name(', ')', 'String'),
  \ javaapi#method(0,1,'getRFC2253Name(', 'Map<String, String>)', 'String'),
  \ javaapi#method(0,1,'getRFC2253CanonicalName(', ')', 'String'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'findMostSpecificAttribute(', 'ObjectIdentifier)', 'DerValue'),
  \ javaapi#method(0,1,'emit(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getEncodedInternal(', ') throws IOException', 'byte'),
  \ javaapi#method(0,1,'getEncoded(', ') throws IOException', 'byte'),
  \ javaapi#method(0,1,'constrains(', 'GeneralNameInterface) throws UnsupportedOperationException', 'int'),
  \ javaapi#method(0,1,'subtreeDepth(', ') throws UnsupportedOperationException', 'int'),
  \ javaapi#method(0,1,'commonAncestor(', 'X500Name)', 'X500Name'),
  \ javaapi#method(0,1,'asX500Principal(', ')', 'X500Principal'),
  \ javaapi#method(1,1,'asX500Name(', 'X500Principal)', 'X500Name'),
  \ ])

call javaapi#class('X509AttributeName', '', [
  \ javaapi#method(0,1,'X509AttributeName(', 'String)', ''),
  \ javaapi#method(0,1,'getPrefix(', ')', 'String'),
  \ javaapi#method(0,1,'getSuffix(', ')', 'String'),
  \ ])

call javaapi#class('X509CRLEntryImpl', 'X509CRLEntry', [
  \ javaapi#method(0,1,'X509CRLEntryImpl(', 'BigInteger, Date)', ''),
  \ javaapi#method(0,1,'X509CRLEntryImpl(', 'BigInteger, Date, CRLExtensions)', ''),
  \ javaapi#method(0,1,'X509CRLEntryImpl(', 'byte[]) throws CRLException', ''),
  \ javaapi#method(0,1,'X509CRLEntryImpl(', 'DerValue) throws CRLException', ''),
  \ javaapi#method(0,1,'hasExtensions(', ')', 'boolean'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws CRLException', 'void'),
  \ javaapi#method(0,1,'getEncoded(', ') throws CRLException', 'byte'),
  \ javaapi#method(0,1,'getCertificateIssuer(', ')', 'X500Principal'),
  \ javaapi#method(0,1,'getSerialNumber(', ')', 'BigInteger'),
  \ javaapi#method(0,1,'getRevocationDate(', ')', 'Date'),
  \ javaapi#method(0,1,'getRevocationReason(', ')', 'CRLReason'),
  \ javaapi#method(1,1,'getRevocationReason(', 'X509CRLEntry)', 'CRLReason'),
  \ javaapi#method(0,1,'getReasonCode(', ') throws IOException', 'Integer'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'hasUnsupportedCriticalExtension(', ')', 'boolean'),
  \ javaapi#method(0,1,'getCriticalExtensionOIDs(', ')', 'Set'),
  \ javaapi#method(0,1,'getNonCriticalExtensionOIDs(', ')', 'Set'),
  \ javaapi#method(0,1,'getExtensionValue(', 'String)', 'byte'),
  \ javaapi#method(0,1,'getExtension(', 'ObjectIdentifier)', 'Extension'),
  \ javaapi#method(1,1,'toImpl(', 'X509CRLEntry) throws CRLException', 'X509CRLEntryImpl'),
  \ javaapi#method(0,1,'getExtensions(', ')', 'Extension>'),
  \ ])

call javaapi#class('X509CRLImpl', 'X509CRL', [
  \ javaapi#method(0,1,'X509CRLImpl(', 'byte[]) throws CRLException', ''),
  \ javaapi#method(0,1,'X509CRLImpl(', 'DerValue) throws CRLException', ''),
  \ javaapi#method(0,1,'X509CRLImpl(', 'InputStream) throws CRLException', ''),
  \ javaapi#method(0,1,'X509CRLImpl(', 'X500Name, Date, Date)', ''),
  \ javaapi#method(0,1,'X509CRLImpl(', 'X500Name, Date, Date, X509CRLEntry[]) throws CRLException', ''),
  \ javaapi#method(0,1,'X509CRLImpl(', 'X500Name, Date, Date, X509CRLEntry[], CRLExtensions) throws CRLException', ''),
  \ javaapi#method(0,1,'getEncodedInternal(', ') throws CRLException', 'byte'),
  \ javaapi#method(0,1,'getEncoded(', ') throws CRLException', 'byte'),
  \ javaapi#method(0,1,'encodeInfo(', 'OutputStream) throws CRLException', 'void'),
  \ javaapi#method(0,1,'verify(', 'PublicKey) throws CRLException, NoSuchAlgorithmException, InvalidKeyException, NoSuchProviderException, SignatureException', 'void'),
  \ javaapi#method(0,1,'verify(', 'PublicKey, String) throws CRLException, NoSuchAlgorithmException, InvalidKeyException, NoSuchProviderException, SignatureException', 'void'),
  \ javaapi#method(0,1,'sign(', 'PrivateKey, String) throws CRLException, NoSuchAlgorithmException, InvalidKeyException, NoSuchProviderException, SignatureException', 'void'),
  \ javaapi#method(0,1,'sign(', 'PrivateKey, String, String) throws CRLException, NoSuchAlgorithmException, InvalidKeyException, NoSuchProviderException, SignatureException', 'void'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'isRevoked(', 'Certificate)', 'boolean'),
  \ javaapi#method(0,1,'getVersion(', ')', 'int'),
  \ javaapi#method(0,1,'getIssuerDN(', ')', 'Principal'),
  \ javaapi#method(0,1,'getIssuerX500Principal(', ')', 'X500Principal'),
  \ javaapi#method(0,1,'getThisUpdate(', ')', 'Date'),
  \ javaapi#method(0,1,'getNextUpdate(', ')', 'Date'),
  \ javaapi#method(0,1,'getRevokedCertificate(', 'BigInteger)', 'X509CRLEntry'),
  \ javaapi#method(0,1,'getRevokedCertificate(', 'X509Certificate)', 'X509CRLEntry'),
  \ javaapi#method(0,1,'getRevokedCertificates(', ')', 'Set'),
  \ javaapi#method(0,1,'getTBSCertList(', ') throws CRLException', 'byte'),
  \ javaapi#method(0,1,'getSignature(', ')', 'byte'),
  \ javaapi#method(0,1,'getSigAlgName(', ')', 'String'),
  \ javaapi#method(0,1,'getSigAlgOID(', ')', 'String'),
  \ javaapi#method(0,1,'getSigAlgParams(', ')', 'byte'),
  \ javaapi#method(0,1,'getSigAlgId(', ')', 'AlgorithmId'),
  \ javaapi#method(0,1,'getAuthKeyId(', ') throws IOException', 'KeyIdentifier'),
  \ javaapi#method(0,1,'getAuthKeyIdExtension(', ') throws IOException', 'AuthorityKeyIdentifierExtension'),
  \ javaapi#method(0,1,'getCRLNumberExtension(', ') throws IOException', 'CRLNumberExtension'),
  \ javaapi#method(0,1,'getCRLNumber(', ') throws IOException', 'BigInteger'),
  \ javaapi#method(0,1,'getDeltaCRLIndicatorExtension(', ') throws IOException', 'DeltaCRLIndicatorExtension'),
  \ javaapi#method(0,1,'getBaseCRLNumber(', ') throws IOException', 'BigInteger'),
  \ javaapi#method(0,1,'getIssuerAltNameExtension(', ') throws IOException', 'IssuerAlternativeNameExtension'),
  \ javaapi#method(0,1,'getIssuingDistributionPointExtension(', ') throws IOException', 'IssuingDistributionPointExtension'),
  \ javaapi#method(0,1,'hasUnsupportedCriticalExtension(', ')', 'boolean'),
  \ javaapi#method(0,1,'getCriticalExtensionOIDs(', ')', 'Set'),
  \ javaapi#method(0,1,'getNonCriticalExtensionOIDs(', ')', 'Set'),
  \ javaapi#method(0,1,'getExtensionValue(', 'String)', 'byte'),
  \ javaapi#method(0,1,'getExtension(', 'ObjectIdentifier)', 'Object'),
  \ javaapi#method(1,1,'getIssuerX500Principal(', 'X509CRL)', 'X500Principal'),
  \ javaapi#method(1,1,'getEncodedInternal(', 'X509CRL) throws CRLException', 'byte'),
  \ javaapi#method(1,1,'toImpl(', 'X509CRL) throws CRLException', 'X509CRLImpl'),
  \ javaapi#method(0,1,'derEncode(', 'OutputStream) throws IOException', 'void'),
  \ ])

call javaapi#class('X509CertImpl', 'X509Certificate', [
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'INFO', 'String'),
  \ javaapi#field(1,1,'ALG_ID', 'String'),
  \ javaapi#field(1,1,'SIGNATURE', 'String'),
  \ javaapi#field(1,1,'SIGNED_CERT', 'String'),
  \ javaapi#field(1,1,'SUBJECT_DN', 'String'),
  \ javaapi#field(1,1,'ISSUER_DN', 'String'),
  \ javaapi#field(1,1,'SERIAL_ID', 'String'),
  \ javaapi#field(1,1,'PUBLIC_KEY', 'String'),
  \ javaapi#field(1,1,'VERSION', 'String'),
  \ javaapi#field(1,1,'SIG_ALG', 'String'),
  \ javaapi#field(1,1,'SIG', 'String'),
  \ javaapi#field(0,0,'info', 'X509CertInfo'),
  \ javaapi#field(0,0,'algId', 'AlgorithmId'),
  \ javaapi#field(0,0,'signature', 'byte'),
  \ javaapi#method(0,1,'X509CertImpl(', ')', ''),
  \ javaapi#method(0,1,'X509CertImpl(', 'byte[]) throws CertificateException', ''),
  \ javaapi#method(0,1,'X509CertImpl(', 'InputStream) throws CertificateException', ''),
  \ javaapi#method(0,1,'X509CertImpl(', 'X509CertInfo)', ''),
  \ javaapi#method(0,1,'X509CertImpl(', 'DerValue) throws CertificateException', ''),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws CertificateEncodingException', 'void'),
  \ javaapi#method(0,1,'derEncode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getEncoded(', ') throws CertificateEncodingException', 'byte'),
  \ javaapi#method(0,1,'getEncodedInternal(', ') throws CertificateEncodingException', 'byte'),
  \ javaapi#method(0,1,'verify(', 'PublicKey) throws CertificateException, NoSuchAlgorithmException, InvalidKeyException, NoSuchProviderException, SignatureException', 'void'),
  \ javaapi#method(0,1,'verify(', 'PublicKey, String) throws CertificateException, NoSuchAlgorithmException, InvalidKeyException, NoSuchProviderException, SignatureException', 'void'),
  \ javaapi#method(0,1,'sign(', 'PrivateKey, String) throws CertificateException, NoSuchAlgorithmException, InvalidKeyException, NoSuchProviderException, SignatureException', 'void'),
  \ javaapi#method(0,1,'sign(', 'PrivateKey, String, String) throws CertificateException, NoSuchAlgorithmException, InvalidKeyException, NoSuchProviderException, SignatureException', 'void'),
  \ javaapi#method(0,1,'checkValidity(', ') throws CertificateExpiredException, CertificateNotYetValidException', 'void'),
  \ javaapi#method(0,1,'checkValidity(', 'Date) throws CertificateExpiredException, CertificateNotYetValidException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws CertificateParsingException', 'Object'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'delete(', 'String) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'getPublicKey(', ')', 'PublicKey'),
  \ javaapi#method(0,1,'getVersion(', ')', 'int'),
  \ javaapi#method(0,1,'getSerialNumber(', ')', 'BigInteger'),
  \ javaapi#method(0,1,'getSerialNumberObject(', ')', 'SerialNumber'),
  \ javaapi#method(0,1,'getSubjectDN(', ')', 'Principal'),
  \ javaapi#method(0,1,'getSubjectX500Principal(', ')', 'X500Principal'),
  \ javaapi#method(0,1,'getIssuerDN(', ')', 'Principal'),
  \ javaapi#method(0,1,'getIssuerX500Principal(', ')', 'X500Principal'),
  \ javaapi#method(0,1,'getNotBefore(', ')', 'Date'),
  \ javaapi#method(0,1,'getNotAfter(', ')', 'Date'),
  \ javaapi#method(0,1,'getTBSCertificate(', ') throws CertificateEncodingException', 'byte'),
  \ javaapi#method(0,1,'getSignature(', ')', 'byte'),
  \ javaapi#method(0,1,'getSigAlgName(', ')', 'String'),
  \ javaapi#method(0,1,'getSigAlgOID(', ')', 'String'),
  \ javaapi#method(0,1,'getSigAlgParams(', ')', 'byte'),
  \ javaapi#method(0,1,'getIssuerUniqueID(', ')', 'boolean'),
  \ javaapi#method(0,1,'getSubjectUniqueID(', ')', 'boolean'),
  \ javaapi#method(0,1,'getAuthorityKeyIdentifierExtension(', ')', 'AuthorityKeyIdentifierExtension'),
  \ javaapi#method(0,1,'getBasicConstraintsExtension(', ')', 'BasicConstraintsExtension'),
  \ javaapi#method(0,1,'getCertificatePoliciesExtension(', ')', 'CertificatePoliciesExtension'),
  \ javaapi#method(0,1,'getExtendedKeyUsageExtension(', ')', 'ExtendedKeyUsageExtension'),
  \ javaapi#method(0,1,'getIssuerAlternativeNameExtension(', ')', 'IssuerAlternativeNameExtension'),
  \ javaapi#method(0,1,'getNameConstraintsExtension(', ')', 'NameConstraintsExtension'),
  \ javaapi#method(0,1,'getPolicyConstraintsExtension(', ')', 'PolicyConstraintsExtension'),
  \ javaapi#method(0,1,'getPolicyMappingsExtension(', ')', 'PolicyMappingsExtension'),
  \ javaapi#method(0,1,'getPrivateKeyUsageExtension(', ')', 'PrivateKeyUsageExtension'),
  \ javaapi#method(0,1,'getSubjectAlternativeNameExtension(', ')', 'SubjectAlternativeNameExtension'),
  \ javaapi#method(0,1,'getSubjectKeyIdentifierExtension(', ')', 'SubjectKeyIdentifierExtension'),
  \ javaapi#method(0,1,'getCRLDistributionPointsExtension(', ')', 'CRLDistributionPointsExtension'),
  \ javaapi#method(0,1,'hasUnsupportedCriticalExtension(', ')', 'boolean'),
  \ javaapi#method(0,1,'getCriticalExtensionOIDs(', ')', 'Set'),
  \ javaapi#method(0,1,'getNonCriticalExtensionOIDs(', ')', 'Set'),
  \ javaapi#method(0,1,'getExtension(', 'ObjectIdentifier)', 'Extension'),
  \ javaapi#method(0,1,'getUnparseableExtension(', 'ObjectIdentifier)', 'Extension'),
  \ javaapi#method(0,1,'getExtensionValue(', 'String)', 'byte'),
  \ javaapi#method(0,1,'getKeyUsage(', ')', 'boolean'),
  \ javaapi#method(0,1,'getExtendedKeyUsage(', ') throws CertificateParsingException', 'List'),
  \ javaapi#method(1,1,'getExtendedKeyUsage(', 'X509Certificate) throws CertificateParsingException', 'List'),
  \ javaapi#method(0,1,'getBasicConstraints(', ')', 'int'),
  \ javaapi#method(0,1,'getSubjectAlternativeNames(', ') throws CertificateParsingException', 'List'),
  \ javaapi#method(1,1,'getSubjectAlternativeNames(', 'X509Certificate) throws CertificateParsingException', 'List'),
  \ javaapi#method(0,1,'getIssuerAlternativeNames(', ') throws CertificateParsingException', 'List'),
  \ javaapi#method(1,1,'getIssuerAlternativeNames(', 'X509Certificate) throws CertificateParsingException', 'List'),
  \ javaapi#method(0,1,'getAuthorityInfoAccessExtension(', ')', 'AuthorityInfoAccessExtension'),
  \ javaapi#method(1,1,'getSubjectX500Principal(', 'X509Certificate)', 'X500Principal'),
  \ javaapi#method(1,1,'getIssuerX500Principal(', 'X509Certificate)', 'X500Principal'),
  \ javaapi#method(1,1,'getEncodedInternal(', 'Certificate) throws CertificateEncodingException', 'byte'),
  \ javaapi#method(1,1,'toImpl(', 'X509Certificate) throws CertificateException', 'X509CertImpl'),
  \ javaapi#method(1,1,'isSelfIssued(', 'X509Certificate)', 'boolean'),
  \ javaapi#method(1,1,'isSelfSigned(', 'X509Certificate, String)', 'boolean'),
  \ ])

call javaapi#class('X509CertInfo', 'CertAttrSet', [
  \ javaapi#field(1,1,'IDENT', 'String'),
  \ javaapi#field(1,1,'NAME', 'String'),
  \ javaapi#field(1,1,'VERSION', 'String'),
  \ javaapi#field(1,1,'SERIAL_NUMBER', 'String'),
  \ javaapi#field(1,1,'ALGORITHM_ID', 'String'),
  \ javaapi#field(1,1,'ISSUER', 'String'),
  \ javaapi#field(1,1,'VALIDITY', 'String'),
  \ javaapi#field(1,1,'SUBJECT', 'String'),
  \ javaapi#field(1,1,'KEY', 'String'),
  \ javaapi#field(1,1,'ISSUER_ID', 'String'),
  \ javaapi#field(1,1,'SUBJECT_ID', 'String'),
  \ javaapi#field(1,1,'EXTENSIONS', 'String'),
  \ javaapi#field(0,0,'version', 'CertificateVersion'),
  \ javaapi#field(0,0,'serialNum', 'CertificateSerialNumber'),
  \ javaapi#field(0,0,'algId', 'CertificateAlgorithmId'),
  \ javaapi#field(0,0,'issuer', 'CertificateIssuerName'),
  \ javaapi#field(0,0,'interval', 'CertificateValidity'),
  \ javaapi#field(0,0,'subject', 'CertificateSubjectName'),
  \ javaapi#field(0,0,'pubKey', 'CertificateX509Key'),
  \ javaapi#field(0,0,'issuerUniqueId', 'CertificateIssuerUniqueIdentity'),
  \ javaapi#field(0,0,'subjectUniqueId', 'CertificateSubjectUniqueIdentity'),
  \ javaapi#field(0,0,'extensions', 'CertificateExtensions'),
  \ javaapi#method(0,1,'X509CertInfo(', ')', ''),
  \ javaapi#method(0,1,'X509CertInfo(', 'byte[]) throws CertificateParsingException', ''),
  \ javaapi#method(0,1,'X509CertInfo(', 'DerValue) throws CertificateParsingException', ''),
  \ javaapi#method(0,1,'encode(', 'OutputStream) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'getElements(', ')', 'Enumeration'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getEncodedInfo(', ') throws CertificateEncodingException', 'byte'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'equals(', 'X509CertInfo)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'set(', 'String, Object) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'delete(', 'String) throws CertificateException, IOException', 'void'),
  \ javaapi#method(0,1,'get(', 'String) throws CertificateException, IOException', 'Object'),
  \ ])

call javaapi#namespace('sun.security.x509')

call javaapi#class('AlgorithmId', 'DerEncoder', [
  \ javaapi#field(0,0,'params', 'DerValue'),
  \ javaapi#field(1,1,'MD2_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'MD5_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'SHA_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'SHA256_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'SHA384_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'SHA512_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'DH_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'DH_PKIX_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'DSA_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'DSA_OIW_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'EC_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'RSA_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'RSAEncryption_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'md2WithRSAEncryption_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'md5WithRSAEncryption_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha1WithRSAEncryption_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha1WithRSAEncryption_OIW_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha256WithRSAEncryption_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha384WithRSAEncryption_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha512WithRSAEncryption_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'shaWithDSA_OIW_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha1WithDSA_OIW_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha1WithDSA_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha1WithECDSA_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha224WithECDSA_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha256WithECDSA_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha384WithECDSA_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'sha512WithECDSA_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'specifiedWithECDSA_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'pbeWithMD5AndDES_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'pbeWithMD5AndRC2_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'pbeWithSHA1AndDES_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'pbeWithSHA1AndRC2_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'pbeWithSHA1AndDESede_oid', 'ObjectIdentifier'),
  \ javaapi#field(1,1,'pbeWithSHA1AndRC2_40_oid', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'AlgorithmId(', ')', ''),
  \ javaapi#method(0,1,'AlgorithmId(', 'ObjectIdentifier)', ''),
  \ javaapi#method(0,1,'AlgorithmId(', 'ObjectIdentifier, AlgorithmParameters)', ''),
  \ javaapi#method(0,0,'decodeParams(', ') throws IOException', 'void'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'derEncode(', 'OutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'encode(', ') throws IOException', 'byte'),
  \ javaapi#method(0,1,'getOID(', ')', 'ObjectIdentifier'),
  \ javaapi#method(0,1,'getName(', ')', 'String'),
  \ javaapi#method(0,1,'getParameters(', ')', 'AlgorithmParameters'),
  \ javaapi#method(0,1,'getEncodedParams(', ') throws IOException', 'byte'),
  \ javaapi#method(0,1,'equals(', 'AlgorithmId)', 'boolean'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'equals(', 'ObjectIdentifier)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ javaapi#method(0,0,'paramsToString(', ')', 'String'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(1,1,'parse(', 'DerValue) throws IOException', 'AlgorithmId'),
  \ javaapi#method(1,1,'getAlgorithmId(', 'String) throws NoSuchAlgorithmException', 'AlgorithmId'),
  \ javaapi#method(1,1,'get(', 'String) throws NoSuchAlgorithmException', 'AlgorithmId'),
  \ javaapi#method(1,1,'get(', 'AlgorithmParameters) throws NoSuchAlgorithmException', 'AlgorithmId'),
  \ javaapi#method(1,1,'makeSigAlg(', 'String, String)', 'String'),
  \ javaapi#method(1,1,'getEncAlgFromSigAlg(', 'String)', 'String'),
  \ javaapi#method(1,1,'getDigAlgFromSigAlg(', 'String)', 'String'),
  \ ])

call javaapi#class('X509Key', 'PublicKey', [
  \ javaapi#field(0,0,'algid', 'AlgorithmId'),
  \ javaapi#field(0,0,'key', 'byte'),
  \ javaapi#field(0,0,'encodedKey', 'byte'),
  \ javaapi#method(0,1,'X509Key(', ')', ''),
  \ javaapi#method(0,0,'setKey(', 'BitArray)', 'void'),
  \ javaapi#method(0,0,'getKey(', ')', 'BitArray'),
  \ javaapi#method(1,1,'parse(', 'DerValue) throws IOException', 'PublicKey'),
  \ javaapi#method(0,0,'parseKeyBits(', ') throws IOException, InvalidKeyException', 'void'),
  \ javaapi#method(0,1,'getAlgorithm(', ')', 'String'),
  \ javaapi#method(0,1,'getAlgorithmId(', ')', 'AlgorithmId'),
  \ javaapi#method(0,1,'encode(', 'DerOutputStream) throws IOException', 'void'),
  \ javaapi#method(0,1,'getEncoded(', ')', 'byte'),
  \ javaapi#method(0,1,'getEncodedInternal(', ') throws InvalidKeyException', 'byte'),
  \ javaapi#method(0,1,'getFormat(', ')', 'String'),
  \ javaapi#method(0,1,'encode(', ') throws InvalidKeyException', 'byte'),
  \ javaapi#method(0,1,'toString(', ')', 'String'),
  \ javaapi#method(0,1,'decode(', 'InputStream) throws InvalidKeyException', 'void'),
  \ javaapi#method(0,1,'decode(', 'byte[]) throws InvalidKeyException', 'void'),
  \ javaapi#method(0,1,'equals(', 'Object)', 'boolean'),
  \ javaapi#method(0,1,'hashCode(', ')', 'int'),
  \ ])

